/**
 * App Schema Registry - CRM & Business Apps
 * 
 * Schema definitions for CRM systems, e-commerce, and business tools
 */

import type { AppSchema } from '../types';

// ============================================
// HUBSPOT SCHEMA
// ============================================

export const hubspotSchema: AppSchema = {
  id: 'hubspot',
  name: 'HubSpot',
  description: 'Manage contacts, deals, and CRM data in HubSpot',
  icon: '🧡',
  color: '#FF7A59',
  category: 'CRM',
  tags: ['crm', 'hubspot', 'contacts', 'deals', 'marketing'],
  apiBaseUrl: 'https://api.hubapi.com',
  apiDocsUrl: 'https://developers.hubspot.com/docs/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'hubspot_api',
    name: 'HubSpot API',
    type: 'bearer',
    helpUrl: 'https://app.hubspot.com/settings/account/private-apps',
    fields: [{
      id: 'accessToken',
      name: 'Private App Access Token',
      type: 'secret',
      validation: { required: true, pattern: '^pat-' },
    }],
  }],
  
  triggers: [
    {
      id: 'hubspot_new_contact',
      appId: 'hubspot',
      name: 'New Contact',
      description: 'Triggers when a contact is created',
      category: 'Contacts',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        {
          id: 'properties',
          name: 'Properties to Fetch',
          description: 'Contact properties to include',
          type: 'array',
          itemSchema: { id: 'prop', name: 'Property', type: 'text' },
        },
      ],
    },
    {
      id: 'hubspot_new_deal',
      appId: 'hubspot',
      name: 'New Deal',
      description: 'Triggers when a deal is created',
      category: 'Deals',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        {
          id: 'pipeline',
          name: 'Pipeline',
          type: 'resource',
          dynamicOptions: { type: 'api', endpoint: '/crm/v3/pipelines/deals' },
        },
      ],
    },
    {
      id: 'hubspot_deal_stage_changed',
      appId: 'hubspot',
      name: 'Deal Stage Changed',
      description: 'Triggers when a deal moves to a new stage',
      category: 'Deals',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        { id: 'pipeline', name: 'Pipeline', type: 'resource' },
        {
          id: 'stage',
          name: 'Stage',
          type: 'resource',
          dynamicOptions: { type: 'dependent', dependsOn: ['pipeline'] },
        },
      ],
    },
    {
      id: 'hubspot_form_submitted',
      appId: 'hubspot',
      name: 'Form Submitted',
      description: 'Triggers when a form is submitted',
      category: 'Forms',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        {
          id: 'formId',
          name: 'Form',
          type: 'resource',
          dynamicOptions: { type: 'api', endpoint: '/marketing/v3/forms' },
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'hubspot_create_contact',
      appId: 'hubspot',
      name: 'Create Contact',
      description: 'Create a new contact in HubSpot',
      category: 'Contacts',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fieldGroups: [
        { id: 'basic', name: 'Basic Info' },
        { id: 'details', name: 'Contact Details', collapsed: true },
        { id: 'custom', name: 'Custom Properties', collapsed: true },
      ],
      fields: [
        { id: 'email', name: 'Email', type: 'email', group: 'basic', validation: { required: true } },
        { id: 'firstname', name: 'First Name', type: 'expression', group: 'basic' },
        { id: 'lastname', name: 'Last Name', type: 'expression', group: 'basic' },
        { id: 'phone', name: 'Phone', type: 'text', group: 'basic' },
        { id: 'company', name: 'Company', type: 'expression', group: 'details' },
        { id: 'jobtitle', name: 'Job Title', type: 'expression', group: 'details' },
        { id: 'website', name: 'Website', type: 'url', group: 'details' },
        { id: 'city', name: 'City', type: 'text', group: 'details' },
        { id: 'state', name: 'State/Region', type: 'text', group: 'details' },
        { id: 'country', name: 'Country', type: 'text', group: 'details' },
        {
          id: 'lifecyclestage',
          name: 'Lifecycle Stage',
          type: 'select',
          group: 'details',
          options: [
            { value: 'subscriber', label: 'Subscriber' },
            { value: 'lead', label: 'Lead' },
            { value: 'marketingqualifiedlead', label: 'Marketing Qualified Lead' },
            { value: 'salesqualifiedlead', label: 'Sales Qualified Lead' },
            { value: 'opportunity', label: 'Opportunity' },
            { value: 'customer', label: 'Customer' },
            { value: 'evangelist', label: 'Evangelist' },
          ],
        },
        {
          id: 'customProperties',
          name: 'Custom Properties',
          type: 'key-value',
          group: 'custom',
          aiAutoFill: true,
        },
      ],
    },
    {
      id: 'hubspot_update_contact',
      appId: 'hubspot',
      name: 'Update Contact',
      description: 'Update an existing contact',
      category: 'Contacts',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        {
          id: 'contactId',
          name: 'Contact ID',
          type: 'expression',
          validation: { required: true },
        },
        { id: 'email', name: 'Email', type: 'email' },
        { id: 'firstname', name: 'First Name', type: 'expression' },
        { id: 'lastname', name: 'Last Name', type: 'expression' },
        { id: 'phone', name: 'Phone', type: 'text' },
        { id: 'customProperties', name: 'Custom Properties', type: 'key-value' },
      ],
    },
    {
      id: 'hubspot_get_contact',
      appId: 'hubspot',
      name: 'Get Contact',
      description: 'Get contact details',
      category: 'Contacts',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        {
          id: 'idType',
          name: 'Lookup By',
          type: 'select',
          defaultValue: 'id',
          options: [
            { value: 'id', label: 'Contact ID' },
            { value: 'email', label: 'Email' },
          ],
        },
        { id: 'contactId', name: 'Contact ID', type: 'expression', showWhen: [{ field: 'idType', condition: 'equals', value: 'id' }], validation: { required: true } },
        { id: 'email', name: 'Email', type: 'email', showWhen: [{ field: 'idType', condition: 'equals', value: 'email' }], validation: { required: true } },
        {
          id: 'properties',
          name: 'Properties to Fetch',
          type: 'array',
          itemSchema: { id: 'prop', name: 'Property', type: 'text' },
        },
      ],
    },
    {
      id: 'hubspot_search_contacts',
      appId: 'hubspot',
      name: 'Search Contacts',
      description: 'Search for contacts',
      category: 'Contacts',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        {
          id: 'filters',
          name: 'Filters',
          type: 'array',
          itemSchema: {
            id: 'filter',
            name: 'Filter',
            type: 'object',
            fields: [
              { id: 'property', name: 'Property', type: 'text', validation: { required: true } },
              {
                id: 'operator',
                name: 'Operator',
                type: 'select',
                options: [
                  { value: 'EQ', label: 'Equals' },
                  { value: 'NEQ', label: 'Not Equals' },
                  { value: 'CONTAINS', label: 'Contains' },
                  { value: 'GT', label: 'Greater Than' },
                  { value: 'LT', label: 'Less Than' },
                  { value: 'HAS_PROPERTY', label: 'Has Property' },
                ],
              },
              { id: 'value', name: 'Value', type: 'expression' },
            ],
          },
        },
        { id: 'limit', name: 'Limit', type: 'number', defaultValue: 10, validation: { min: 1, max: 100 } },
      ],
    },
    {
      id: 'hubspot_create_deal',
      appId: 'hubspot',
      name: 'Create Deal',
      description: 'Create a new deal',
      category: 'Deals',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        { id: 'dealname', name: 'Deal Name', type: 'expression', validation: { required: true }, aiSuggestions: true },
        { id: 'amount', name: 'Amount', type: 'number' },
        { id: 'pipeline', name: 'Pipeline', type: 'resource', validation: { required: true } },
        { id: 'dealstage', name: 'Deal Stage', type: 'resource', validation: { required: true }, dynamicOptions: { type: 'dependent', dependsOn: ['pipeline'] } },
        { id: 'closedate', name: 'Close Date', type: 'date' },
        { id: 'hubspot_owner_id', name: 'Owner', type: 'resource', dynamicOptions: { type: 'api', endpoint: '/crm/v3/owners' } },
        { id: 'customProperties', name: 'Custom Properties', type: 'key-value' },
      ],
    },
    {
      id: 'hubspot_update_deal',
      appId: 'hubspot',
      name: 'Update Deal',
      description: 'Update an existing deal',
      category: 'Deals',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        { id: 'dealId', name: 'Deal ID', type: 'expression', validation: { required: true } },
        { id: 'dealname', name: 'Deal Name', type: 'expression' },
        { id: 'amount', name: 'Amount', type: 'number' },
        { id: 'dealstage', name: 'Deal Stage', type: 'resource' },
        { id: 'closedate', name: 'Close Date', type: 'date' },
        { id: 'customProperties', name: 'Custom Properties', type: 'key-value' },
      ],
    },
    {
      id: 'hubspot_create_company',
      appId: 'hubspot',
      name: 'Create Company',
      description: 'Create a new company',
      category: 'Companies',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        { id: 'name', name: 'Company Name', type: 'expression', validation: { required: true } },
        { id: 'domain', name: 'Website Domain', type: 'text' },
        { id: 'industry', name: 'Industry', type: 'text' },
        { id: 'numberofemployees', name: 'Employees', type: 'number' },
        { id: 'annualrevenue', name: 'Annual Revenue', type: 'number' },
        { id: 'city', name: 'City', type: 'text' },
        { id: 'country', name: 'Country', type: 'text' },
      ],
    },
    {
      id: 'hubspot_add_note',
      appId: 'hubspot',
      name: 'Add Note',
      description: 'Add a note to a record',
      category: 'Engagement',
      requiresCredential: true,
      credentialType: 'hubspot_api',
      fields: [
        {
          id: 'objectType',
          name: 'Object Type',
          type: 'select',
          validation: { required: true },
          options: [
            { value: 'contacts', label: 'Contact' },
            { value: 'deals', label: 'Deal' },
            { value: 'companies', label: 'Company' },
          ],
        },
        { id: 'objectId', name: 'Object ID', type: 'expression', validation: { required: true } },
        { id: 'body', name: 'Note Content', type: 'textarea', rows: 4, validation: { required: true }, aiSuggestions: true },
      ],
    },
  ],
};

// ============================================
// SALESFORCE SCHEMA
// ============================================

export const salesforceSchema: AppSchema = {
  id: 'salesforce',
  name: 'Salesforce',
  description: 'Manage leads, contacts, opportunities, and more',
  icon: '☁️',
  color: '#00A1E0',
  category: 'CRM',
  tags: ['crm', 'salesforce', 'leads', 'opportunities', 'sales'],
  apiDocsUrl: 'https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'salesforce_oauth',
    name: 'Salesforce OAuth',
    type: 'oauth2',
    helpUrl: 'https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_web_server_flow.htm',
    fields: [
      { id: 'instanceUrl', name: 'Instance URL', type: 'text', validation: { required: true }, placeholder: 'https://yourcompany.salesforce.com' },
      { id: 'clientId', name: 'Consumer Key', type: 'text', validation: { required: true } },
      { id: 'clientSecret', name: 'Consumer Secret', type: 'secret', validation: { required: true } },
      { id: 'refreshToken', name: 'Refresh Token', type: 'secret' },
    ],
  }],
  
  triggers: [
    {
      id: 'salesforce_new_record',
      appId: 'salesforce',
      name: 'New Record',
      description: 'Triggers when a record is created',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'salesforce_oauth',
      fields: [
        {
          id: 'objectType',
          name: 'Object Type',
          type: 'select',
          validation: { required: true },
          options: [
            { value: 'Lead', label: 'Lead' },
            { value: 'Contact', label: 'Contact' },
            { value: 'Account', label: 'Account' },
            { value: 'Opportunity', label: 'Opportunity' },
            { value: 'Case', label: 'Case' },
            { value: 'Task', label: 'Task' },
          ],
          allowCustom: true,
        },
      ],
    },
    {
      id: 'salesforce_updated_record',
      appId: 'salesforce',
      name: 'Updated Record',
      description: 'Triggers when a record is modified',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'salesforce_oauth',
      fields: [
        {
          id: 'objectType',
          name: 'Object Type',
          type: 'select',
          validation: { required: true },
          options: [
            { value: 'Lead', label: 'Lead' },
            { value: 'Contact', label: 'Contact' },
            { value: 'Account', label: 'Account' },
            { value: 'Opportunity', label: 'Opportunity' },
          ],
          allowCustom: true,
        },
        {
          id: 'fields',
          name: 'Watch Fields',
          description: 'Only trigger when these fields change',
          type: 'array',
          itemSchema: { id: 'field', name: 'Field', type: 'text' },
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'salesforce_create_record',
      appId: 'salesforce',
      name: 'Create Record',
      description: 'Create a new Salesforce record',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'salesforce_oauth',
      fields: [
        {
          id: 'objectType',
          name: 'Object Type',
          type: 'select',
          validation: { required: true },
          options: [
            { value: 'Lead', label: 'Lead' },
            { value: 'Contact', label: 'Contact' },
            { value: 'Account', label: 'Account' },
            { value: 'Opportunity', label: 'Opportunity' },
            { value: 'Case', label: 'Case' },
            { value: 'Task', label: 'Task' },
          ],
          allowCustom: true,
        },
        {
          id: 'fields',
          name: 'Fields',
          description: 'Record field values',
          type: 'key-value',
          validation: { required: true },
          aiAutoFill: true,
        },
      ],
    },
    {
      id: 'salesforce_update_record',
      appId: 'salesforce',
      name: 'Update Record',
      description: 'Update an existing record',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'salesforce_oauth',
      fields: [
        {
          id: 'objectType',
          name: 'Object Type',
          type: 'select',
          validation: { required: true },
          options: [
            { value: 'Lead', label: 'Lead' },
            { value: 'Contact', label: 'Contact' },
            { value: 'Account', label: 'Account' },
            { value: 'Opportunity', label: 'Opportunity' },
          ],
          allowCustom: true,
        },
        { id: 'recordId', name: 'Record ID', type: 'expression', validation: { required: true } },
        { id: 'fields', name: 'Fields', type: 'key-value', validation: { required: true } },
      ],
    },
    {
      id: 'salesforce_get_record',
      appId: 'salesforce',
      name: 'Get Record',
      description: 'Retrieve a single record',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'salesforce_oauth',
      fields: [
        { id: 'objectType', name: 'Object Type', type: 'select', validation: { required: true }, options: [
          { value: 'Lead', label: 'Lead' },
          { value: 'Contact', label: 'Contact' },
          { value: 'Account', label: 'Account' },
          { value: 'Opportunity', label: 'Opportunity' },
        ], allowCustom: true },
        { id: 'recordId', name: 'Record ID', type: 'expression', validation: { required: true } },
        { id: 'fields', name: 'Fields', description: 'Fields to retrieve', type: 'array', itemSchema: { id: 'field', name: 'Field', type: 'text' } },
      ],
    },
    {
      id: 'salesforce_query',
      appId: 'salesforce',
      name: 'SOQL Query',
      description: 'Execute a SOQL query',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'salesforce_oauth',
      fields: [
        {
          id: 'query',
          name: 'SOQL Query',
          description: 'Salesforce Object Query Language',
          type: 'code',
          language: 'sql',
          validation: { required: true },
          placeholder: 'SELECT Id, Name FROM Contact WHERE Email != null',
          aiSuggestions: true,
        },
      ],
    },
    {
      id: 'salesforce_delete_record',
      appId: 'salesforce',
      name: 'Delete Record',
      description: 'Delete a record',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'salesforce_oauth',
      fields: [
        { id: 'objectType', name: 'Object Type', type: 'select', validation: { required: true }, options: [
          { value: 'Lead', label: 'Lead' },
          { value: 'Contact', label: 'Contact' },
          { value: 'Account', label: 'Account' },
          { value: 'Opportunity', label: 'Opportunity' },
        ], allowCustom: true },
        { id: 'recordId', name: 'Record ID', type: 'expression', validation: { required: true } },
      ],
    },
  ],
};

// ============================================
// STRIPE SCHEMA
// ============================================

export const stripeSchema: AppSchema = {
  id: 'stripe',
  name: 'Stripe',
  description: 'Process payments, manage subscriptions, and handle billing',
  icon: '💳',
  color: '#6772E5',
  category: 'E-commerce',
  tags: ['payments', 'stripe', 'billing', 'subscriptions'],
  apiBaseUrl: 'https://api.stripe.com/v1',
  apiDocsUrl: 'https://stripe.com/docs/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'stripe_api',
    name: 'Stripe API',
    type: 'bearer',
    helpUrl: 'https://dashboard.stripe.com/apikeys',
    fields: [{
      id: 'secretKey',
      name: 'Secret Key',
      description: 'Use test key for development, live key for production',
      type: 'secret',
      validation: { required: true, pattern: '^sk_(test|live)_' },
    }],
  }],
  
  triggers: [
    {
      id: 'stripe_payment_succeeded',
      appId: 'stripe',
      name: 'Payment Succeeded',
      description: 'Triggers when a payment succeeds',
      category: 'Payments',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [],
    },
    {
      id: 'stripe_payment_failed',
      appId: 'stripe',
      name: 'Payment Failed',
      description: 'Triggers when a payment fails',
      category: 'Payments',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [],
    },
    {
      id: 'stripe_subscription_created',
      appId: 'stripe',
      name: 'Subscription Created',
      description: 'Triggers when a subscription is created',
      category: 'Subscriptions',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [],
    },
    {
      id: 'stripe_subscription_canceled',
      appId: 'stripe',
      name: 'Subscription Canceled',
      description: 'Triggers when a subscription is canceled',
      category: 'Subscriptions',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [],
    },
    {
      id: 'stripe_invoice_paid',
      appId: 'stripe',
      name: 'Invoice Paid',
      description: 'Triggers when an invoice is paid',
      category: 'Invoices',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [],
    },
    {
      id: 'stripe_customer_created',
      appId: 'stripe',
      name: 'Customer Created',
      description: 'Triggers when a customer is created',
      category: 'Customers',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [],
    },
  ],
  
  actions: [
    {
      id: 'stripe_create_customer',
      appId: 'stripe',
      name: 'Create Customer',
      description: 'Create a new Stripe customer',
      category: 'Customers',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [
        { id: 'email', name: 'Email', type: 'email', validation: { required: true } },
        { id: 'name', name: 'Name', type: 'expression' },
        { id: 'phone', name: 'Phone', type: 'text' },
        { id: 'description', name: 'Description', type: 'text' },
        {
          id: 'metadata',
          name: 'Metadata',
          description: 'Custom key-value pairs',
          type: 'key-value',
        },
      ],
    },
    {
      id: 'stripe_update_customer',
      appId: 'stripe',
      name: 'Update Customer',
      description: 'Update a customer',
      category: 'Customers',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [
        { id: 'customerId', name: 'Customer ID', type: 'expression', validation: { required: true } },
        { id: 'email', name: 'Email', type: 'email' },
        { id: 'name', name: 'Name', type: 'expression' },
        { id: 'metadata', name: 'Metadata', type: 'key-value' },
      ],
    },
    {
      id: 'stripe_get_customer',
      appId: 'stripe',
      name: 'Get Customer',
      description: 'Retrieve customer details',
      category: 'Customers',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [
        { id: 'customerId', name: 'Customer ID', type: 'expression', validation: { required: true } },
      ],
    },
    {
      id: 'stripe_create_payment_intent',
      appId: 'stripe',
      name: 'Create Payment Intent',
      description: 'Create a payment intent',
      category: 'Payments',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fieldGroups: [
        { id: 'payment', name: 'Payment Details' },
        { id: 'options', name: 'Options', collapsed: true },
      ],
      fields: [
        {
          id: 'amount',
          name: 'Amount',
          description: 'Amount in smallest currency unit (e.g., cents)',
          type: 'number',
          group: 'payment',
          validation: { required: true, min: 1 },
        },
        {
          id: 'currency',
          name: 'Currency',
          type: 'select',
          group: 'payment',
          validation: { required: true },
          defaultValue: 'usd',
          options: [
            { value: 'usd', label: 'USD' },
            { value: 'eur', label: 'EUR' },
            { value: 'gbp', label: 'GBP' },
            { value: 'inr', label: 'INR' },
            { value: 'cad', label: 'CAD' },
            { value: 'aud', label: 'AUD' },
          ],
          allowCustom: true,
        },
        { id: 'customerId', name: 'Customer ID', type: 'expression', group: 'payment' },
        { id: 'description', name: 'Description', type: 'text', group: 'payment' },
        {
          id: 'paymentMethodTypes',
          name: 'Payment Methods',
          type: 'multi-select',
          group: 'options',
          defaultValue: ['card'],
          options: [
            { value: 'card', label: 'Card' },
            { value: 'bank_transfer', label: 'Bank Transfer' },
            { value: 'sepa_debit', label: 'SEPA Direct Debit' },
            { value: 'ideal', label: 'iDEAL' },
          ],
        },
        { id: 'receiptEmail', name: 'Receipt Email', type: 'email', group: 'options' },
        { id: 'metadata', name: 'Metadata', type: 'key-value', group: 'options' },
      ],
    },
    {
      id: 'stripe_create_subscription',
      appId: 'stripe',
      name: 'Create Subscription',
      description: 'Create a new subscription',
      category: 'Subscriptions',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [
        { id: 'customerId', name: 'Customer ID', type: 'expression', validation: { required: true } },
        { id: 'priceId', name: 'Price ID', type: 'expression', validation: { required: true } },
        {
          id: 'quantity',
          name: 'Quantity',
          type: 'number',
          defaultValue: 1,
          validation: { min: 1 },
        },
        {
          id: 'trialDays',
          name: 'Trial Period Days',
          type: 'number',
          validation: { min: 0 },
        },
        { id: 'metadata', name: 'Metadata', type: 'key-value' },
      ],
    },
    {
      id: 'stripe_cancel_subscription',
      appId: 'stripe',
      name: 'Cancel Subscription',
      description: 'Cancel a subscription',
      category: 'Subscriptions',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [
        { id: 'subscriptionId', name: 'Subscription ID', type: 'expression', validation: { required: true } },
        {
          id: 'cancelAt',
          name: 'Cancel At',
          type: 'select',
          defaultValue: 'now',
          options: [
            { value: 'now', label: 'Immediately' },
            { value: 'period_end', label: 'At Period End' },
          ],
        },
      ],
    },
    {
      id: 'stripe_create_invoice',
      appId: 'stripe',
      name: 'Create Invoice',
      description: 'Create an invoice',
      category: 'Invoices',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [
        { id: 'customerId', name: 'Customer ID', type: 'expression', validation: { required: true } },
        { id: 'description', name: 'Description', type: 'text' },
        {
          id: 'items',
          name: 'Line Items',
          type: 'array',
          itemSchema: {
            id: 'item',
            name: 'Item',
            type: 'object',
            fields: [
              { id: 'description', name: 'Description', type: 'text', validation: { required: true } },
              { id: 'amount', name: 'Amount (cents)', type: 'number', validation: { required: true } },
              { id: 'quantity', name: 'Quantity', type: 'number', defaultValue: 1 },
            ],
          },
        },
        { id: 'dueDate', name: 'Due Date', type: 'date' },
        { id: 'autoAdvance', name: 'Auto Finalize', type: 'boolean', defaultValue: true },
      ],
    },
    {
      id: 'stripe_create_refund',
      appId: 'stripe',
      name: 'Create Refund',
      description: 'Refund a payment',
      category: 'Payments',
      requiresCredential: true,
      credentialType: 'stripe_api',
      fields: [
        { id: 'paymentIntentId', name: 'Payment Intent ID', type: 'expression', validation: { required: true } },
        { id: 'amount', name: 'Amount (cents)', description: 'Leave empty for full refund', type: 'number' },
        {
          id: 'reason',
          name: 'Reason',
          type: 'select',
          options: [
            { value: 'duplicate', label: 'Duplicate' },
            { value: 'fraudulent', label: 'Fraudulent' },
            { value: 'requested_by_customer', label: 'Customer Request' },
          ],
        },
      ],
    },
  ],
};

// ============================================
// SHOPIFY SCHEMA
// ============================================

export const shopifySchema: AppSchema = {
  id: 'shopify',
  name: 'Shopify',
  description: 'Manage orders, products, and customers in Shopify',
  icon: '🛒',
  color: '#96BF48',
  category: 'E-commerce',
  tags: ['ecommerce', 'shopify', 'orders', 'products'],
  apiDocsUrl: 'https://shopify.dev/docs/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'shopify_api',
    name: 'Shopify API',
    type: 'custom',
    helpUrl: 'https://shopify.dev/docs/apps/auth/admin-app-access-tokens',
    fields: [
      { id: 'shopDomain', name: 'Shop Domain', type: 'text', validation: { required: true }, placeholder: 'your-store.myshopify.com' },
      { id: 'accessToken', name: 'Access Token', type: 'secret', validation: { required: true } },
    ],
  }],
  
  triggers: [
    {
      id: 'shopify_new_order',
      appId: 'shopify',
      name: 'New Order',
      description: 'Triggers when an order is placed',
      category: 'Orders',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [],
    },
    {
      id: 'shopify_order_paid',
      appId: 'shopify',
      name: 'Order Paid',
      description: 'Triggers when an order is paid',
      category: 'Orders',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [],
    },
    {
      id: 'shopify_order_fulfilled',
      appId: 'shopify',
      name: 'Order Fulfilled',
      description: 'Triggers when an order is fulfilled',
      category: 'Orders',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [],
    },
    {
      id: 'shopify_new_customer',
      appId: 'shopify',
      name: 'New Customer',
      description: 'Triggers when a customer is created',
      category: 'Customers',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [],
    },
    {
      id: 'shopify_new_product',
      appId: 'shopify',
      name: 'New Product',
      description: 'Triggers when a product is created',
      category: 'Products',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [],
    },
  ],
  
  actions: [
    {
      id: 'shopify_get_order',
      appId: 'shopify',
      name: 'Get Order',
      description: 'Get order details',
      category: 'Orders',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [
        { id: 'orderId', name: 'Order ID', type: 'expression', validation: { required: true } },
      ],
    },
    {
      id: 'shopify_get_orders',
      appId: 'shopify',
      name: 'Get Orders',
      description: 'List orders with filters',
      category: 'Orders',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [
        {
          id: 'status',
          name: 'Status',
          type: 'select',
          options: [
            { value: 'any', label: 'Any' },
            { value: 'open', label: 'Open' },
            { value: 'closed', label: 'Closed' },
            { value: 'cancelled', label: 'Cancelled' },
          ],
        },
        {
          id: 'financialStatus',
          name: 'Financial Status',
          type: 'select',
          options: [
            { value: 'any', label: 'Any' },
            { value: 'pending', label: 'Pending' },
            { value: 'paid', label: 'Paid' },
            { value: 'refunded', label: 'Refunded' },
          ],
        },
        { id: 'createdAfter', name: 'Created After', type: 'datetime' },
        { id: 'limit', name: 'Limit', type: 'number', defaultValue: 50, validation: { min: 1, max: 250 } },
      ],
    },
    {
      id: 'shopify_update_order',
      appId: 'shopify',
      name: 'Update Order',
      description: 'Update order details',
      category: 'Orders',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [
        { id: 'orderId', name: 'Order ID', type: 'expression', validation: { required: true } },
        { id: 'note', name: 'Note', type: 'textarea', rows: 3 },
        { id: 'tags', name: 'Tags', type: 'text', placeholder: 'tag1, tag2, tag3' },
      ],
    },
    {
      id: 'shopify_cancel_order',
      appId: 'shopify',
      name: 'Cancel Order',
      description: 'Cancel an order',
      category: 'Orders',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [
        { id: 'orderId', name: 'Order ID', type: 'expression', validation: { required: true } },
        {
          id: 'reason',
          name: 'Reason',
          type: 'select',
          options: [
            { value: 'customer', label: 'Customer Request' },
            { value: 'fraud', label: 'Fraud' },
            { value: 'inventory', label: 'Out of Stock' },
            { value: 'other', label: 'Other' },
          ],
        },
        { id: 'email', name: 'Send Notification Email', type: 'boolean', defaultValue: true },
        { id: 'refund', name: 'Issue Refund', type: 'boolean', defaultValue: false },
      ],
    },
    {
      id: 'shopify_create_product',
      appId: 'shopify',
      name: 'Create Product',
      description: 'Create a new product',
      category: 'Products',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fieldGroups: [
        { id: 'basic', name: 'Product Details' },
        { id: 'pricing', name: 'Pricing & Inventory' },
        { id: 'options', name: 'Options', collapsed: true },
      ],
      fields: [
        { id: 'title', name: 'Title', type: 'expression', group: 'basic', validation: { required: true }, aiSuggestions: true },
        { id: 'bodyHtml', name: 'Description (HTML)', type: 'textarea', rows: 4, group: 'basic', aiSuggestions: true },
        { id: 'vendor', name: 'Vendor', type: 'text', group: 'basic' },
        { id: 'productType', name: 'Product Type', type: 'text', group: 'basic' },
        { id: 'tags', name: 'Tags', type: 'text', group: 'basic', placeholder: 'tag1, tag2' },
        { id: 'price', name: 'Price', type: 'number', group: 'pricing' },
        { id: 'compareAtPrice', name: 'Compare at Price', type: 'number', group: 'pricing' },
        { id: 'sku', name: 'SKU', type: 'text', group: 'pricing' },
        { id: 'barcode', name: 'Barcode', type: 'text', group: 'pricing' },
        { id: 'inventoryQuantity', name: 'Inventory Quantity', type: 'number', group: 'pricing' },
        {
          id: 'status',
          name: 'Status',
          type: 'select',
          group: 'options',
          defaultValue: 'draft',
          options: [
            { value: 'active', label: 'Active' },
            { value: 'draft', label: 'Draft' },
            { value: 'archived', label: 'Archived' },
          ],
        },
        { id: 'images', name: 'Image URLs', type: 'array', group: 'options', itemSchema: { id: 'image', name: 'URL', type: 'url' } },
      ],
    },
    {
      id: 'shopify_update_product',
      appId: 'shopify',
      name: 'Update Product',
      description: 'Update a product',
      category: 'Products',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [
        { id: 'productId', name: 'Product ID', type: 'expression', validation: { required: true } },
        { id: 'title', name: 'Title', type: 'expression' },
        { id: 'bodyHtml', name: 'Description (HTML)', type: 'textarea', rows: 4 },
        { id: 'tags', name: 'Tags', type: 'text' },
        { id: 'status', name: 'Status', type: 'select', options: [
          { value: 'active', label: 'Active' },
          { value: 'draft', label: 'Draft' },
          { value: 'archived', label: 'Archived' },
        ]},
      ],
    },
    {
      id: 'shopify_create_customer',
      appId: 'shopify',
      name: 'Create Customer',
      description: 'Create a new customer',
      category: 'Customers',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [
        { id: 'email', name: 'Email', type: 'email', validation: { required: true } },
        { id: 'firstName', name: 'First Name', type: 'expression' },
        { id: 'lastName', name: 'Last Name', type: 'expression' },
        { id: 'phone', name: 'Phone', type: 'text' },
        { id: 'tags', name: 'Tags', type: 'text' },
        { id: 'note', name: 'Note', type: 'textarea', rows: 2 },
        { id: 'acceptsMarketing', name: 'Accepts Marketing', type: 'boolean', defaultValue: false },
      ],
    },
    {
      id: 'shopify_update_inventory',
      appId: 'shopify',
      name: 'Update Inventory',
      description: 'Update inventory levels',
      category: 'Inventory',
      requiresCredential: true,
      credentialType: 'shopify_api',
      fields: [
        { id: 'inventoryItemId', name: 'Inventory Item ID', type: 'expression', validation: { required: true } },
        { id: 'locationId', name: 'Location ID', type: 'expression', validation: { required: true } },
        { id: 'available', name: 'Available Quantity', type: 'number', validation: { required: true } },
      ],
    },
  ],
};

// Export all CRM & business schemas
export const businessAppSchemas: AppSchema[] = [
  hubspotSchema,
  salesforceSchema,
  stripeSchema,
  shopifySchema,
];
