/**
 * App Schema Registry - Productivity Apps
 * 
 * Schema definitions for email, calendar, storage, and productivity tools
 */

import type { AppSchema, FieldSchema } from '../types';

// ============================================
// GMAIL SCHEMA
// ============================================

export const gmailSchema: AppSchema = {
  id: 'gmail',
  name: 'Gmail',
  description: 'Send, read, and manage emails with Gmail',
  icon: '📧',
  color: '#EA4335',
  category: 'Email',
  tags: ['email', 'gmail', 'google', 'communication'],
  apiBaseUrl: 'https://gmail.googleapis.com/gmail/v1',
  apiDocsUrl: 'https://developers.google.com/gmail/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'google_oauth',
    name: 'Google OAuth',
    type: 'oauth2',
    helpUrl: 'https://console.cloud.google.com/apis/credentials',
    fields: [
      { id: 'clientId', name: 'Client ID', type: 'text', validation: { required: true } },
      { id: 'clientSecret', name: 'Client Secret', type: 'secret', validation: { required: true } },
      { id: 'refreshToken', name: 'Refresh Token', type: 'secret' },
    ],
  }],
  
  triggers: [
    {
      id: 'gmail_new_email',
      appId: 'gmail',
      name: 'New Email',
      description: 'Triggers when a new email is received',
      category: 'Emails',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'labelIds',
          name: 'Labels',
          description: 'Filter by Gmail labels',
          type: 'multi-select',
          defaultValue: ['INBOX'],
          options: [
            { value: 'INBOX', label: 'Inbox' },
            { value: 'SENT', label: 'Sent' },
            { value: 'IMPORTANT', label: 'Important' },
            { value: 'STARRED', label: 'Starred' },
            { value: 'UNREAD', label: 'Unread' },
          ],
        },
        {
          id: 'from',
          name: 'From',
          description: 'Filter by sender email address',
          type: 'text',
          placeholder: 'sender@example.com',
        },
        {
          id: 'subject',
          name: 'Subject Contains',
          description: 'Filter by subject keywords',
          type: 'text',
        },
        {
          id: 'hasAttachment',
          name: 'Has Attachment',
          description: 'Only trigger for emails with attachments',
          type: 'boolean',
          defaultValue: false,
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'gmail_send_email',
      appId: 'gmail',
      name: 'Send Email',
      description: 'Send an email via Gmail',
      category: 'Emails',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fieldGroups: [
        { id: 'recipients', name: 'Recipients' },
        { id: 'content', name: 'Email Content' },
        { id: 'attachments', name: 'Attachments', collapsed: true },
        { id: 'options', name: 'Options', collapsed: true },
      ],
      fields: [
        {
          id: 'to',
          name: 'To',
          description: 'Recipient email addresses',
          type: 'expression',
          group: 'recipients',
          validation: { required: true },
          placeholder: 'recipient@example.com, another@example.com',
        },
        {
          id: 'cc',
          name: 'CC',
          description: 'Carbon copy recipients',
          type: 'expression',
          group: 'recipients',
        },
        {
          id: 'bcc',
          name: 'BCC',
          description: 'Blind carbon copy recipients',
          type: 'expression',
          group: 'recipients',
        },
        {
          id: 'subject',
          name: 'Subject',
          description: 'Email subject line',
          type: 'expression',
          group: 'content',
          validation: { required: true },
          aiSuggestions: true,
        },
        {
          id: 'body',
          name: 'Body',
          description: 'Email body content',
          type: 'expression',
          group: 'content',
          validation: { required: true },
          aiSuggestions: true,
          aiAutoFill: true,
        },
        {
          id: 'contentType',
          name: 'Content Type',
          description: 'Format of the email body',
          type: 'select',
          group: 'content',
          defaultValue: 'html',
          options: [
            { value: 'text', label: 'Plain Text' },
            { value: 'html', label: 'HTML' },
          ],
        },
        {
          id: 'attachments',
          name: 'Attachments',
          description: 'Files to attach',
          type: 'array',
          group: 'attachments',
          itemSchema: {
            id: 'attachment',
            name: 'Attachment',
            type: 'object',
            fields: [
              { id: 'filename', name: 'Filename', type: 'text', validation: { required: true } },
              { id: 'content', name: 'Content (Base64)', type: 'text', validation: { required: true } },
              { id: 'mimeType', name: 'MIME Type', type: 'text', defaultValue: 'application/octet-stream' },
            ],
          },
        },
        {
          id: 'replyTo',
          name: 'Reply-To',
          description: 'Reply-to email address',
          type: 'email',
          group: 'options',
        },
        {
          id: 'threadId',
          name: 'Thread ID',
          description: 'Reply to existing thread',
          type: 'text',
          group: 'options',
        },
      ],
    },
    {
      id: 'gmail_get_emails',
      appId: 'gmail',
      name: 'Get Emails',
      description: 'Retrieve emails from Gmail',
      category: 'Emails',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'query',
          name: 'Search Query',
          description: 'Gmail search query (e.g., "from:someone@example.com is:unread")',
          type: 'text',
          aiHelp: 'Use Gmail search operators: from:, to:, subject:, is:unread, has:attachment, etc.',
        },
        {
          id: 'maxResults',
          name: 'Max Results',
          description: 'Maximum number of emails to return',
          type: 'number',
          defaultValue: 10,
          validation: { min: 1, max: 500 },
        },
        {
          id: 'includeBody',
          name: 'Include Body',
          description: 'Include full email body (slower)',
          type: 'boolean',
          defaultValue: false,
        },
      ],
    },
    {
      id: 'gmail_create_draft',
      appId: 'gmail',
      name: 'Create Draft',
      description: 'Create an email draft',
      category: 'Emails',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        { id: 'to', name: 'To', type: 'expression', validation: { required: true } },
        { id: 'subject', name: 'Subject', type: 'expression', validation: { required: true } },
        { id: 'body', name: 'Body', type: 'expression', validation: { required: true } },
      ],
    },
    {
      id: 'gmail_add_label',
      appId: 'gmail',
      name: 'Add Label',
      description: 'Add a label to an email',
      category: 'Labels',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        { id: 'messageId', name: 'Message ID', type: 'text', validation: { required: true } },
        {
          id: 'labelIds',
          name: 'Labels',
          type: 'multi-select',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/users/me/labels' },
        },
      ],
    },
  ],
};

// ============================================
// GOOGLE SHEETS SCHEMA
// ============================================

export const googleSheetsSchema: AppSchema = {
  id: 'google_sheets',
  name: 'Google Sheets',
  description: 'Read, write, and manage Google Sheets spreadsheets',
  icon: '📊',
  color: '#0F9D58',
  category: 'Productivity',
  tags: ['spreadsheet', 'sheets', 'google', 'data'],
  apiBaseUrl: 'https://sheets.googleapis.com/v4',
  apiDocsUrl: 'https://developers.google.com/sheets/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'google_oauth',
    name: 'Google OAuth',
    type: 'oauth2',
    helpUrl: 'https://console.cloud.google.com/apis/credentials',
    fields: [
      { id: 'clientId', name: 'Client ID', type: 'text', validation: { required: true } },
      { id: 'clientSecret', name: 'Client Secret', type: 'secret', validation: { required: true } },
    ],
  }],
  
  triggers: [
    {
      id: 'sheets_new_row',
      appId: 'google_sheets',
      name: 'New Row',
      description: 'Triggers when a new row is added',
      category: 'Rows',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'spreadsheetId',
          name: 'Spreadsheet',
          description: 'Select or enter spreadsheet ID',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: {
            type: 'api',
            endpoint: '/drive/v3/files?q=mimeType="application/vnd.google-apps.spreadsheet"',
          },
        },
        {
          id: 'sheetName',
          name: 'Sheet',
          description: 'Sheet/tab name',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: {
            type: 'dependent',
            dependsOn: ['spreadsheetId'],
          },
        },
      ],
    },
    {
      id: 'sheets_row_updated',
      appId: 'google_sheets',
      name: 'Row Updated',
      description: 'Triggers when a row is modified',
      category: 'Rows',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'spreadsheetId',
          name: 'Spreadsheet',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/drive/v3/files' },
        },
        {
          id: 'sheetName',
          name: 'Sheet',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'dependent', dependsOn: ['spreadsheetId'] },
        },
        {
          id: 'columns',
          name: 'Watch Columns',
          description: 'Only trigger when these columns change',
          type: 'array',
          itemSchema: { id: 'column', name: 'Column', type: 'text' },
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'sheets_append_row',
      appId: 'google_sheets',
      name: 'Append Row',
      description: 'Add a new row to the end of the sheet',
      category: 'Rows',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'spreadsheetId',
          name: 'Spreadsheet',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/drive/v3/files' },
        },
        {
          id: 'sheetName',
          name: 'Sheet',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'dependent', dependsOn: ['spreadsheetId'] },
        },
        {
          id: 'values',
          name: 'Values',
          description: 'Row values to append',
          type: 'key-value',
          validation: { required: true },
          aiAutoFill: true,
        },
        {
          id: 'valueInputOption',
          name: 'Value Input Option',
          description: 'How to interpret input data',
          type: 'select',
          defaultValue: 'USER_ENTERED',
          options: [
            { value: 'RAW', label: 'Raw', description: 'Values are stored as-is' },
            { value: 'USER_ENTERED', label: 'User Entered', description: 'Values are parsed as if typed by user' },
          ],
        },
      ],
    },
    {
      id: 'sheets_update_row',
      appId: 'google_sheets',
      name: 'Update Row',
      description: 'Update an existing row',
      category: 'Rows',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'spreadsheetId',
          name: 'Spreadsheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'sheetName',
          name: 'Sheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'rowNumber',
          name: 'Row Number',
          description: 'Row to update (1-indexed)',
          type: 'number',
          validation: { required: true, min: 1 },
        },
        {
          id: 'values',
          name: 'Values',
          description: 'New row values',
          type: 'key-value',
          validation: { required: true },
        },
      ],
    },
    {
      id: 'sheets_get_rows',
      appId: 'google_sheets',
      name: 'Get Rows',
      description: 'Read rows from a sheet',
      category: 'Rows',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'spreadsheetId',
          name: 'Spreadsheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'sheetName',
          name: 'Sheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'range',
          name: 'Range',
          description: 'Cell range (e.g., A1:D10 or leave empty for all)',
          type: 'text',
          placeholder: 'A1:Z1000',
        },
        {
          id: 'firstRowHeaders',
          name: 'First Row is Headers',
          description: 'Use first row as column names',
          type: 'boolean',
          defaultValue: true,
        },
      ],
    },
    {
      id: 'sheets_find_row',
      appId: 'google_sheets',
      name: 'Find Row',
      description: 'Find rows matching criteria',
      category: 'Rows',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'spreadsheetId',
          name: 'Spreadsheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'sheetName',
          name: 'Sheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'column',
          name: 'Search Column',
          description: 'Column to search in',
          type: 'text',
          validation: { required: true },
          placeholder: 'A or Email',
        },
        {
          id: 'value',
          name: 'Search Value',
          description: 'Value to find',
          type: 'expression',
          validation: { required: true },
        },
        {
          id: 'matchType',
          name: 'Match Type',
          type: 'select',
          defaultValue: 'exact',
          options: [
            { value: 'exact', label: 'Exact Match' },
            { value: 'contains', label: 'Contains' },
            { value: 'starts', label: 'Starts With' },
            { value: 'ends', label: 'Ends With' },
          ],
        },
      ],
    },
    {
      id: 'sheets_delete_row',
      appId: 'google_sheets',
      name: 'Delete Row',
      description: 'Delete a row from the sheet',
      category: 'Rows',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'spreadsheetId',
          name: 'Spreadsheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'sheetName',
          name: 'Sheet',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'rowNumber',
          name: 'Row Number',
          type: 'number',
          validation: { required: true, min: 1 },
        },
      ],
    },
  ],
};

// ============================================
// GOOGLE CALENDAR SCHEMA
// ============================================

export const googleCalendarSchema: AppSchema = {
  id: 'google_calendar',
  name: 'Google Calendar',
  description: 'Create, update, and manage calendar events',
  icon: '📅',
  color: '#4285F4',
  category: 'Productivity',
  tags: ['calendar', 'events', 'google', 'scheduling'],
  apiBaseUrl: 'https://www.googleapis.com/calendar/v3',
  apiDocsUrl: 'https://developers.google.com/calendar/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'google_oauth',
    name: 'Google OAuth',
    type: 'oauth2',
    fields: [
      { id: 'clientId', name: 'Client ID', type: 'text', validation: { required: true } },
      { id: 'clientSecret', name: 'Client Secret', type: 'secret', validation: { required: true } },
    ],
  }],
  
  triggers: [
    {
      id: 'calendar_event_created',
      appId: 'google_calendar',
      name: 'Event Created',
      description: 'Triggers when a new event is created',
      category: 'Events',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'calendarId',
          name: 'Calendar',
          type: 'resource',
          defaultValue: 'primary',
          dynamicOptions: { type: 'api', endpoint: '/users/me/calendarList' },
        },
      ],
    },
    {
      id: 'calendar_event_starting',
      appId: 'google_calendar',
      name: 'Event Starting',
      description: 'Triggers before an event starts',
      category: 'Events',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'calendarId',
          name: 'Calendar',
          type: 'resource',
          defaultValue: 'primary',
        },
        {
          id: 'minutesBefore',
          name: 'Minutes Before',
          description: 'How many minutes before the event to trigger',
          type: 'number',
          defaultValue: 15,
          validation: { min: 0, max: 60 },
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'calendar_create_event',
      appId: 'google_calendar',
      name: 'Create Event',
      description: 'Create a new calendar event',
      category: 'Events',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fieldGroups: [
        { id: 'basic', name: 'Event Details' },
        { id: 'time', name: 'Date & Time' },
        { id: 'attendees', name: 'Attendees', collapsed: true },
        { id: 'options', name: 'Options', collapsed: true },
      ],
      fields: [
        {
          id: 'calendarId',
          name: 'Calendar',
          type: 'resource',
          group: 'basic',
          defaultValue: 'primary',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/users/me/calendarList' },
        },
        {
          id: 'summary',
          name: 'Title',
          description: 'Event title',
          type: 'expression',
          group: 'basic',
          validation: { required: true },
          aiSuggestions: true,
        },
        {
          id: 'description',
          name: 'Description',
          type: 'expression',
          group: 'basic',
          aiSuggestions: true,
        },
        {
          id: 'location',
          name: 'Location',
          type: 'text',
          group: 'basic',
        },
        {
          id: 'startDateTime',
          name: 'Start',
          type: 'datetime',
          group: 'time',
          validation: { required: true },
        },
        {
          id: 'endDateTime',
          name: 'End',
          type: 'datetime',
          group: 'time',
          validation: { required: true },
        },
        {
          id: 'allDay',
          name: 'All Day Event',
          type: 'boolean',
          group: 'time',
          defaultValue: false,
        },
        {
          id: 'timeZone',
          name: 'Time Zone',
          type: 'select',
          group: 'time',
          defaultValue: 'UTC',
          options: [
            { value: 'UTC', label: 'UTC' },
            { value: 'America/New_York', label: 'Eastern Time' },
            { value: 'America/Los_Angeles', label: 'Pacific Time' },
            { value: 'Europe/London', label: 'London' },
            { value: 'Asia/Tokyo', label: 'Tokyo' },
            { value: 'Asia/Kolkata', label: 'India' },
          ],
          allowCustom: true,
        },
        {
          id: 'attendees',
          name: 'Attendees',
          description: 'Email addresses of attendees',
          type: 'array',
          group: 'attendees',
          itemSchema: {
            id: 'attendee',
            name: 'Attendee',
            type: 'object',
            fields: [
              { id: 'email', name: 'Email', type: 'email', validation: { required: true } },
              {
                id: 'optional',
                name: 'Optional',
                type: 'boolean',
                defaultValue: false,
              },
            ],
          },
        },
        {
          id: 'sendUpdates',
          name: 'Send Invites',
          type: 'select',
          group: 'attendees',
          defaultValue: 'all',
          options: [
            { value: 'all', label: 'Send to all' },
            { value: 'externalOnly', label: 'External only' },
            { value: 'none', label: 'Don\'t send' },
          ],
        },
        {
          id: 'reminders',
          name: 'Reminders',
          type: 'array',
          group: 'options',
          itemSchema: {
            id: 'reminder',
            name: 'Reminder',
            type: 'object',
            fields: [
              {
                id: 'method',
                name: 'Method',
                type: 'select',
                options: [
                  { value: 'email', label: 'Email' },
                  { value: 'popup', label: 'Popup' },
                ],
              },
              {
                id: 'minutes',
                name: 'Minutes Before',
                type: 'number',
                defaultValue: 30,
              },
            ],
          },
        },
        {
          id: 'colorId',
          name: 'Color',
          type: 'select',
          group: 'options',
          options: [
            { value: '1', label: 'Lavender' },
            { value: '2', label: 'Sage' },
            { value: '3', label: 'Grape' },
            { value: '4', label: 'Flamingo' },
            { value: '5', label: 'Banana' },
            { value: '6', label: 'Tangerine' },
            { value: '7', label: 'Peacock' },
            { value: '8', label: 'Graphite' },
            { value: '9', label: 'Blueberry' },
            { value: '10', label: 'Basil' },
            { value: '11', label: 'Tomato' },
          ],
        },
        {
          id: 'recurrence',
          name: 'Recurrence',
          description: 'Repeat pattern',
          type: 'select',
          group: 'options',
          options: [
            { value: '', label: 'Does not repeat' },
            { value: 'RRULE:FREQ=DAILY', label: 'Daily' },
            { value: 'RRULE:FREQ=WEEKLY', label: 'Weekly' },
            { value: 'RRULE:FREQ=MONTHLY', label: 'Monthly' },
            { value: 'RRULE:FREQ=YEARLY', label: 'Yearly' },
          ],
          allowCustom: true,
        },
        {
          id: 'conferenceData',
          name: 'Add Google Meet',
          type: 'boolean',
          group: 'options',
          defaultValue: false,
        },
      ],
    },
    {
      id: 'calendar_get_events',
      appId: 'google_calendar',
      name: 'Get Events',
      description: 'Retrieve calendar events',
      category: 'Events',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'calendarId',
          name: 'Calendar',
          type: 'resource',
          defaultValue: 'primary',
        },
        {
          id: 'timeMin',
          name: 'From',
          description: 'Start of time range',
          type: 'datetime',
        },
        {
          id: 'timeMax',
          name: 'To',
          description: 'End of time range',
          type: 'datetime',
        },
        {
          id: 'maxResults',
          name: 'Max Results',
          type: 'number',
          defaultValue: 10,
          validation: { min: 1, max: 2500 },
        },
        {
          id: 'q',
          name: 'Search',
          description: 'Free text search',
          type: 'text',
        },
      ],
    },
    {
      id: 'calendar_update_event',
      appId: 'google_calendar',
      name: 'Update Event',
      description: 'Update an existing event',
      category: 'Events',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        { id: 'calendarId', name: 'Calendar', type: 'resource', defaultValue: 'primary', validation: { required: true } },
        { id: 'eventId', name: 'Event ID', type: 'text', validation: { required: true } },
        { id: 'summary', name: 'Title', type: 'expression' },
        { id: 'description', name: 'Description', type: 'expression' },
        { id: 'startDateTime', name: 'Start', type: 'datetime' },
        { id: 'endDateTime', name: 'End', type: 'datetime' },
      ],
    },
    {
      id: 'calendar_delete_event',
      appId: 'google_calendar',
      name: 'Delete Event',
      description: 'Delete a calendar event',
      category: 'Events',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        { id: 'calendarId', name: 'Calendar', type: 'resource', defaultValue: 'primary', validation: { required: true } },
        { id: 'eventId', name: 'Event ID', type: 'text', validation: { required: true } },
        { id: 'sendUpdates', name: 'Send Cancellation', type: 'select', defaultValue: 'all', options: [
          { value: 'all', label: 'Send to all' },
          { value: 'none', label: 'Don\'t send' },
        ]},
      ],
    },
  ],
};

// ============================================
// GOOGLE DRIVE SCHEMA
// ============================================

export const googleDriveSchema: AppSchema = {
  id: 'google_drive',
  name: 'Google Drive',
  description: 'Manage files and folders in Google Drive',
  icon: '📁',
  color: '#4285F4',
  category: 'Storage',
  tags: ['storage', 'files', 'google', 'drive'],
  apiBaseUrl: 'https://www.googleapis.com/drive/v3',
  apiDocsUrl: 'https://developers.google.com/drive/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'google_oauth',
    name: 'Google OAuth',
    type: 'oauth2',
    fields: [
      { id: 'clientId', name: 'Client ID', type: 'text', validation: { required: true } },
      { id: 'clientSecret', name: 'Client Secret', type: 'secret', validation: { required: true } },
    ],
  }],
  
  triggers: [
    {
      id: 'drive_new_file',
      appId: 'google_drive',
      name: 'New File',
      description: 'Triggers when a file is added',
      category: 'Files',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'folderId',
          name: 'Folder',
          description: 'Watch specific folder (leave empty for root)',
          type: 'resource',
          dynamicOptions: { type: 'api', endpoint: '/files?q=mimeType="application/vnd.google-apps.folder"' },
        },
        {
          id: 'mimeTypes',
          name: 'File Types',
          description: 'Filter by file type',
          type: 'multi-select',
          options: [
            { value: 'application/pdf', label: 'PDF' },
            { value: 'image/*', label: 'Images' },
            { value: 'video/*', label: 'Videos' },
            { value: 'application/vnd.google-apps.spreadsheet', label: 'Google Sheets' },
            { value: 'application/vnd.google-apps.document', label: 'Google Docs' },
          ],
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'drive_upload_file',
      appId: 'google_drive',
      name: 'Upload File',
      description: 'Upload a file to Google Drive',
      category: 'Files',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'name',
          name: 'File Name',
          type: 'expression',
          validation: { required: true },
        },
        {
          id: 'content',
          name: 'File Content',
          description: 'File content (base64 or text)',
          type: 'expression',
          validation: { required: true },
        },
        {
          id: 'mimeType',
          name: 'MIME Type',
          type: 'select',
          defaultValue: 'text/plain',
          options: [
            { value: 'text/plain', label: 'Plain Text' },
            { value: 'application/pdf', label: 'PDF' },
            { value: 'image/png', label: 'PNG Image' },
            { value: 'image/jpeg', label: 'JPEG Image' },
            { value: 'application/json', label: 'JSON' },
          ],
          allowCustom: true,
        },
        {
          id: 'folderId',
          name: 'Folder',
          description: 'Destination folder',
          type: 'resource',
          dynamicOptions: { type: 'api', endpoint: '/files' },
        },
      ],
    },
    {
      id: 'drive_get_file',
      appId: 'google_drive',
      name: 'Get File',
      description: 'Download or get file metadata',
      category: 'Files',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'fileId',
          name: 'File ID',
          type: 'expression',
          validation: { required: true },
        },
        {
          id: 'downloadContent',
          name: 'Download Content',
          description: 'Include file content in response',
          type: 'boolean',
          defaultValue: false,
        },
      ],
    },
    {
      id: 'drive_create_folder',
      appId: 'google_drive',
      name: 'Create Folder',
      description: 'Create a new folder',
      category: 'Folders',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'name',
          name: 'Folder Name',
          type: 'expression',
          validation: { required: true },
        },
        {
          id: 'parentId',
          name: 'Parent Folder',
          description: 'Create inside this folder',
          type: 'resource',
          dynamicOptions: { type: 'api', endpoint: '/files' },
        },
      ],
    },
    {
      id: 'drive_list_files',
      appId: 'google_drive',
      name: 'List Files',
      description: 'List files in a folder',
      category: 'Files',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        {
          id: 'folderId',
          name: 'Folder',
          type: 'resource',
          dynamicOptions: { type: 'api', endpoint: '/files' },
        },
        {
          id: 'query',
          name: 'Search Query',
          description: 'Drive search query',
          type: 'text',
          placeholder: 'name contains "report"',
        },
        {
          id: 'maxResults',
          name: 'Max Results',
          type: 'number',
          defaultValue: 100,
          validation: { min: 1, max: 1000 },
        },
      ],
    },
    {
      id: 'drive_share_file',
      appId: 'google_drive',
      name: 'Share File',
      description: 'Share a file or folder',
      category: 'Sharing',
      requiresCredential: true,
      credentialType: 'google_oauth',
      fields: [
        { id: 'fileId', name: 'File ID', type: 'expression', validation: { required: true } },
        {
          id: 'type',
          name: 'Share With',
          type: 'select',
          validation: { required: true },
          options: [
            { value: 'user', label: 'Specific User' },
            { value: 'group', label: 'Group' },
            { value: 'domain', label: 'Domain' },
            { value: 'anyone', label: 'Anyone with link' },
          ],
        },
        {
          id: 'email',
          name: 'Email',
          type: 'email',
          showWhen: [{ field: 'type', condition: 'in', values: ['user', 'group'] }],
        },
        {
          id: 'role',
          name: 'Permission',
          type: 'select',
          defaultValue: 'reader',
          options: [
            { value: 'reader', label: 'Viewer' },
            { value: 'commenter', label: 'Commenter' },
            { value: 'writer', label: 'Editor' },
          ],
        },
      ],
    },
  ],
};

// ============================================
// NOTION SCHEMA
// ============================================

export const notionSchema: AppSchema = {
  id: 'notion',
  name: 'Notion',
  description: 'Create pages, databases, and manage Notion workspace',
  icon: '📝',
  color: '#000000',
  category: 'Productivity',
  tags: ['notes', 'notion', 'wiki', 'database'],
  apiBaseUrl: 'https://api.notion.com/v1',
  apiDocsUrl: 'https://developers.notion.com',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'notion_api',
    name: 'Notion Integration',
    type: 'bearer',
    helpUrl: 'https://www.notion.so/my-integrations',
    fields: [{
      id: 'apiKey',
      name: 'Integration Token',
      description: 'Internal integration token from notion.so/my-integrations',
      type: 'secret',
      validation: { required: true, pattern: '^(secret_|ntn_)' },
    }],
  }],
  
  triggers: [
    {
      id: 'notion_page_created',
      appId: 'notion',
      name: 'Page Created',
      description: 'Triggers when a page is created in a database',
      category: 'Pages',
      requiresCredential: true,
      credentialType: 'notion_api',
      fields: [
        {
          id: 'databaseId',
          name: 'Database',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/search' },
        },
      ],
    },
    {
      id: 'notion_page_updated',
      appId: 'notion',
      name: 'Page Updated',
      description: 'Triggers when a page is modified',
      category: 'Pages',
      requiresCredential: true,
      credentialType: 'notion_api',
      fields: [
        {
          id: 'databaseId',
          name: 'Database',
          type: 'resource',
          validation: { required: true },
        },
        {
          id: 'properties',
          name: 'Watch Properties',
          description: 'Only trigger when these properties change',
          type: 'array',
          itemSchema: { id: 'property', name: 'Property', type: 'text' },
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'notion_create_page',
      appId: 'notion',
      name: 'Create Page',
      description: 'Create a new page in a database',
      category: 'Pages',
      requiresCredential: true,
      credentialType: 'notion_api',
      fields: [
        {
          id: 'databaseId',
          name: 'Database',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/search' },
        },
        {
          id: 'properties',
          name: 'Properties',
          description: 'Page properties',
          type: 'key-value',
          validation: { required: true },
          aiAutoFill: true,
        },
        {
          id: 'content',
          name: 'Page Content',
          description: 'Initial page content (Markdown)',
          type: 'textarea',
          rows: 6,
          aiSuggestions: true,
        },
        {
          id: 'icon',
          name: 'Icon',
          description: 'Page icon (emoji or URL)',
          type: 'text',
          placeholder: '📄 or https://...',
        },
        {
          id: 'cover',
          name: 'Cover Image URL',
          type: 'url',
        },
      ],
    },
    {
      id: 'notion_update_page',
      appId: 'notion',
      name: 'Update Page',
      description: 'Update page properties',
      category: 'Pages',
      requiresCredential: true,
      credentialType: 'notion_api',
      fields: [
        { id: 'pageId', name: 'Page ID', type: 'text', validation: { required: true } },
        { id: 'properties', name: 'Properties', type: 'key-value', validation: { required: true } },
      ],
    },
    {
      id: 'notion_query_database',
      appId: 'notion',
      name: 'Query Database',
      description: 'Search and filter database entries',
      category: 'Databases',
      requiresCredential: true,
      credentialType: 'notion_api',
      fields: [
        { id: 'databaseId', name: 'Database', type: 'resource', validation: { required: true } },
        {
          id: 'filter',
          name: 'Filter',
          description: 'Filter criteria (JSON)',
          type: 'json',
          aiHelp: 'Notion filter format: https://developers.notion.com/reference/post-database-query-filter',
        },
        {
          id: 'sorts',
          name: 'Sort',
          description: 'Sort order',
          type: 'array',
          itemSchema: {
            id: 'sort',
            name: 'Sort',
            type: 'object',
            fields: [
              { id: 'property', name: 'Property', type: 'text' },
              {
                id: 'direction',
                name: 'Direction',
                type: 'select',
                options: [
                  { value: 'ascending', label: 'Ascending' },
                  { value: 'descending', label: 'Descending' },
                ],
              },
            ],
          },
        },
        { id: 'pageSize', name: 'Max Results', type: 'number', defaultValue: 100, validation: { min: 1, max: 100 } },
      ],
    },
    {
      id: 'notion_append_block',
      appId: 'notion',
      name: 'Append Content',
      description: 'Add content to a page',
      category: 'Blocks',
      requiresCredential: true,
      credentialType: 'notion_api',
      fields: [
        { id: 'pageId', name: 'Page ID', type: 'text', validation: { required: true } },
        {
          id: 'content',
          name: 'Content',
          description: 'Content to append (Markdown supported)',
          type: 'textarea',
          rows: 6,
          validation: { required: true },
          aiSuggestions: true,
        },
      ],
    },
  ],
};

// ============================================
// AIRTABLE SCHEMA
// ============================================

export const airtableSchema: AppSchema = {
  id: 'airtable',
  name: 'Airtable',
  description: 'Create, update, and manage Airtable bases and records',
  icon: '🗃️',
  color: '#18BFFF',
  category: 'Productivity',
  tags: ['database', 'airtable', 'spreadsheet', 'records'],
  apiBaseUrl: 'https://api.airtable.com/v0',
  apiDocsUrl: 'https://airtable.com/developers/web/api',
  version: '1.0.0',
  status: 'stable',
  
  credentials: [{
    id: 'airtable_api',
    name: 'Airtable API',
    type: 'bearer',
    helpUrl: 'https://airtable.com/create/tokens',
    fields: [{
      id: 'apiKey',
      name: 'Personal Access Token',
      type: 'secret',
      validation: { required: true, pattern: '^pat[a-zA-Z0-9]+\\.[a-f0-9]+' },
    }],
  }],
  
  triggers: [
    {
      id: 'airtable_new_record',
      appId: 'airtable',
      name: 'New Record',
      description: 'Triggers when a record is created',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'airtable_api',
      fields: [
        {
          id: 'baseId',
          name: 'Base',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/meta/bases' },
        },
        {
          id: 'tableId',
          name: 'Table',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'dependent', dependsOn: ['baseId'] },
        },
      ],
    },
  ],
  
  actions: [
    {
      id: 'airtable_create_record',
      appId: 'airtable',
      name: 'Create Record',
      description: 'Add a new record to a table',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'airtable_api',
      fields: [
        {
          id: 'baseId',
          name: 'Base',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'api', endpoint: '/meta/bases' },
        },
        {
          id: 'tableId',
          name: 'Table',
          type: 'resource',
          validation: { required: true },
          dynamicOptions: { type: 'dependent', dependsOn: ['baseId'] },
        },
        {
          id: 'fields',
          name: 'Fields',
          description: 'Record field values',
          type: 'key-value',
          validation: { required: true },
          aiAutoFill: true,
        },
        {
          id: 'typecast',
          name: 'Typecast',
          description: 'Auto-convert field values',
          type: 'boolean',
          defaultValue: true,
        },
      ],
    },
    {
      id: 'airtable_update_record',
      appId: 'airtable',
      name: 'Update Record',
      description: 'Update an existing record',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'airtable_api',
      fields: [
        { id: 'baseId', name: 'Base', type: 'resource', validation: { required: true } },
        { id: 'tableId', name: 'Table', type: 'resource', validation: { required: true } },
        { id: 'recordId', name: 'Record ID', type: 'expression', validation: { required: true } },
        { id: 'fields', name: 'Fields', type: 'key-value', validation: { required: true } },
      ],
    },
    {
      id: 'airtable_find_records',
      appId: 'airtable',
      name: 'Find Records',
      description: 'Search for records in a table',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'airtable_api',
      fields: [
        { id: 'baseId', name: 'Base', type: 'resource', validation: { required: true } },
        { id: 'tableId', name: 'Table', type: 'resource', validation: { required: true } },
        {
          id: 'filterFormula',
          name: 'Filter Formula',
          description: 'Airtable formula to filter records',
          type: 'text',
          placeholder: '{Status} = "Active"',
          aiHelp: 'Airtable formula reference: https://support.airtable.com/docs/formula-field-reference',
        },
        { id: 'maxRecords', name: 'Max Records', type: 'number', defaultValue: 100 },
        {
          id: 'sort',
          name: 'Sort By',
          type: 'array',
          itemSchema: {
            id: 'sortField',
            name: 'Sort',
            type: 'object',
            fields: [
              { id: 'field', name: 'Field', type: 'text' },
              {
                id: 'direction',
                name: 'Direction',
                type: 'select',
                options: [
                  { value: 'asc', label: 'Ascending' },
                  { value: 'desc', label: 'Descending' },
                ],
              },
            ],
          },
        },
      ],
    },
    {
      id: 'airtable_delete_record',
      appId: 'airtable',
      name: 'Delete Record',
      description: 'Delete a record from a table',
      category: 'Records',
      requiresCredential: true,
      credentialType: 'airtable_api',
      fields: [
        { id: 'baseId', name: 'Base', type: 'resource', validation: { required: true } },
        { id: 'tableId', name: 'Table', type: 'resource', validation: { required: true } },
        { id: 'recordId', name: 'Record ID', type: 'expression', validation: { required: true } },
      ],
    },
  ],
};

// Export all productivity schemas
export const productivityAppSchemas: AppSchema[] = [
  gmailSchema,
  googleSheetsSchema,
  googleCalendarSchema,
  googleDriveSchema,
  notionSchema,
  airtableSchema,
];
