/**
 * Bitbucket n8n-style Schema
 * 
 * Comprehensive Bitbucket API operations
 */

import { N8nAppSchema } from './types';

export const bitbucketSchema: N8nAppSchema = {
  id: 'bitbucket',
  name: 'Bitbucket',
  description: 'Bitbucket version control and collaboration',
  version: '1.0.0',
  color: '#0052CC',
  icon: 'bitbucket',
  group: ['developer'],
  
  credentials: [
    {
      name: 'bitbucketAppPassword',
      displayName: 'Bitbucket App Password',
      required: true,
      type: 'basicAuth',
      properties: [
        {
          name: 'username',
          displayName: 'Username',
          type: 'string',
          required: true,
        },
        {
          name: 'appPassword',
          displayName: 'App Password',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
    {
      name: 'bitbucketOAuth2',
      displayName: 'Bitbucket OAuth2',
      required: true,
      type: 'oauth2',
      properties: [
        {
          name: 'accessToken',
          displayName: 'Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // REPOSITORY RESOURCE
    // ============================================
    {
      id: 'repository',
      name: 'Repository',
      value: 'repository',
      description: 'Repository operations',
      operations: [
        {
          id: 'create_repo',
          name: 'Create Repository',
          value: 'create',
          description: 'Create a new repository',
          action: 'Create repository',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'is_private',
              name: 'isPrivate',
              displayName: 'Private',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'fork_policy',
              name: 'forkPolicy',
              displayName: 'Fork Policy',
              type: 'options',
              required: false,
              default: 'allow_forks',
              options: [
                { name: 'Allow Forks', value: 'allow_forks' },
                { name: 'No Public Forks', value: 'no_public_forks' },
                { name: 'No Forks', value: 'no_forks' },
              ],
            },
            {
              id: 'project',
              name: 'project',
              displayName: 'Project Key',
              type: 'string',
              required: false,
            },
            {
              id: 'language',
              name: 'language',
              displayName: 'Language',
              type: 'string',
              required: false,
            },
            {
              id: 'has_wiki',
              name: 'hasWiki',
              displayName: 'Enable Wiki',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'has_issues',
              name: 'hasIssues',
              displayName: 'Enable Issues',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_repo',
          name: 'Get Repository',
          value: 'get',
          description: 'Get repository information',
          action: 'Get repository',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_repos',
          name: 'List Repositories',
          value: 'getMany',
          description: 'List repositories',
          action: 'List repositories',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'role',
              name: 'role',
              displayName: 'Role',
              type: 'options',
              required: false,
              options: [
                { name: 'Admin', value: 'admin' },
                { name: 'Contributor', value: 'contributor' },
                { name: 'Member', value: 'member' },
                { name: 'Owner', value: 'owner' },
              ],
            },
            {
              id: 'q',
              name: 'q',
              displayName: 'Query',
              type: 'string',
              required: false,
              description: 'Filter query string',
            },
            {
              id: 'sort',
              name: 'sort',
              displayName: 'Sort',
              type: 'options',
              required: false,
              options: [
                { name: 'Full Name', value: 'full_name' },
                { name: 'Name', value: 'name' },
                { name: 'Updated On', value: '-updated_on' },
                { name: 'Created On', value: '-created_on' },
              ],
            },
            {
              id: 'pagelen',
              name: 'pagelen',
              displayName: 'Page Length',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'fork_repo',
          name: 'Fork Repository',
          value: 'fork',
          description: 'Fork a repository',
          action: 'Fork repository',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Source Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'target_workspace',
              name: 'targetWorkspace',
              displayName: 'Target Workspace',
              type: 'string',
              required: false,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Fork Name',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_repo',
          name: 'Delete Repository',
          value: 'delete',
          description: 'Delete a repository',
          action: 'Delete repository',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // PULL REQUEST RESOURCE
    // ============================================
    {
      id: 'pullRequest',
      name: 'Pull Request',
      value: 'pullRequest',
      description: 'Pull request operations',
      operations: [
        {
          id: 'create_pr',
          name: 'Create Pull Request',
          value: 'create',
          description: 'Create a pull request',
          action: 'Create pull request',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
            {
              id: 'source_branch',
              name: 'sourceBranch',
              displayName: 'Source Branch',
              type: 'string',
              required: true,
            },
            {
              id: 'destination_branch',
              name: 'destinationBranch',
              displayName: 'Destination Branch',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'close_source_branch',
              name: 'closeSourceBranch',
              displayName: 'Close Source Branch',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'reviewers',
              name: 'reviewers',
              displayName: 'Reviewers',
              type: 'string',
              required: false,
              description: 'Comma-separated UUIDs',
            },
          ],
        },
        {
          id: 'get_pr',
          name: 'Get Pull Request',
          value: 'get',
          description: 'Get a pull request',
          action: 'Get pull request',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_request_id',
              name: 'pullRequestId',
              displayName: 'Pull Request ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_prs',
          name: 'List Pull Requests',
          value: 'getMany',
          description: 'List pull requests',
          action: 'List pull requests',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              default: 'OPEN',
              options: [
                { name: 'Open', value: 'OPEN' },
                { name: 'Merged', value: 'MERGED' },
                { name: 'Declined', value: 'DECLINED' },
                { name: 'Superseded', value: 'SUPERSEDED' },
              ],
            },
            {
              id: 'pagelen',
              name: 'pagelen',
              displayName: 'Page Length',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_pr',
          name: 'Update Pull Request',
          value: 'update',
          description: 'Update a pull request',
          action: 'Update pull request',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_request_id',
              name: 'pullRequestId',
              displayName: 'Pull Request ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'reviewers',
              name: 'reviewers',
              displayName: 'Reviewers',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'merge_pr',
          name: 'Merge Pull Request',
          value: 'merge',
          description: 'Merge a pull request',
          action: 'Merge pull request',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_request_id',
              name: 'pullRequestId',
              displayName: 'Pull Request ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'merge_strategy',
              name: 'mergeStrategy',
              displayName: 'Merge Strategy',
              type: 'options',
              required: false,
              default: 'merge_commit',
              options: [
                { name: 'Merge Commit', value: 'merge_commit' },
                { name: 'Squash', value: 'squash' },
                { name: 'Fast Forward', value: 'fast_forward' },
              ],
            },
            {
              id: 'message',
              name: 'message',
              displayName: 'Commit Message',
              type: 'string',
              required: false,
            },
            {
              id: 'close_source_branch',
              name: 'closeSourceBranch',
              displayName: 'Close Source Branch',
              type: 'boolean',
              required: false,
            },
          ],
        },
        {
          id: 'decline_pr',
          name: 'Decline Pull Request',
          value: 'decline',
          description: 'Decline a pull request',
          action: 'Decline pull request',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_request_id',
              name: 'pullRequestId',
              displayName: 'Pull Request ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'approve_pr',
          name: 'Approve Pull Request',
          value: 'approve',
          description: 'Approve a pull request',
          action: 'Approve pull request',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_request_id',
              name: 'pullRequestId',
              displayName: 'Pull Request ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ISSUE RESOURCE
    // ============================================
    {
      id: 'issue',
      name: 'Issue',
      value: 'issue',
      description: 'Issue operations',
      operations: [
        {
          id: 'create_issue',
          name: 'Create Issue',
          value: 'create',
          description: 'Create an issue',
          action: 'Create issue',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'content',
              name: 'content',
              displayName: 'Content',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'kind',
              name: 'kind',
              displayName: 'Kind',
              type: 'options',
              required: false,
              default: 'bug',
              options: [
                { name: 'Bug', value: 'bug' },
                { name: 'Enhancement', value: 'enhancement' },
                { name: 'Proposal', value: 'proposal' },
                { name: 'Task', value: 'task' },
              ],
            },
            {
              id: 'priority',
              name: 'priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              default: 'major',
              options: [
                { name: 'Trivial', value: 'trivial' },
                { name: 'Minor', value: 'minor' },
                { name: 'Major', value: 'major' },
                { name: 'Critical', value: 'critical' },
                { name: 'Blocker', value: 'blocker' },
              ],
            },
            {
              id: 'assignee',
              name: 'assignee',
              displayName: 'Assignee UUID',
              type: 'string',
              required: false,
            },
            {
              id: 'component',
              name: 'component',
              displayName: 'Component',
              type: 'string',
              required: false,
            },
            {
              id: 'milestone',
              name: 'milestone',
              displayName: 'Milestone',
              type: 'string',
              required: false,
            },
            {
              id: 'version',
              name: 'version',
              displayName: 'Version',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_issue',
          name: 'Get Issue',
          value: 'get',
          description: 'Get an issue',
          action: 'Get issue',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_id',
              name: 'issueId',
              displayName: 'Issue ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_issues',
          name: 'List Issues',
          value: 'getMany',
          description: 'List issues',
          action: 'List issues',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              options: [
                { name: 'New', value: 'new' },
                { name: 'Open', value: 'open' },
                { name: 'Resolved', value: 'resolved' },
                { name: 'On Hold', value: 'on hold' },
                { name: 'Invalid', value: 'invalid' },
                { name: 'Duplicate', value: 'duplicate' },
                { name: 'Wontfix', value: 'wontfix' },
                { name: 'Closed', value: 'closed' },
              ],
            },
            {
              id: 'priority',
              name: 'priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              options: [
                { name: 'Trivial', value: 'trivial' },
                { name: 'Minor', value: 'minor' },
                { name: 'Major', value: 'major' },
                { name: 'Critical', value: 'critical' },
                { name: 'Blocker', value: 'blocker' },
              ],
            },
            {
              id: 'q',
              name: 'q',
              displayName: 'Query',
              type: 'string',
              required: false,
            },
            {
              id: 'pagelen',
              name: 'pagelen',
              displayName: 'Page Length',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_issue',
          name: 'Update Issue',
          value: 'update',
          description: 'Update an issue',
          action: 'Update issue',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_id',
              name: 'issueId',
              displayName: 'Issue ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'content',
              name: 'content',
              displayName: 'Content',
              type: 'string',
              required: false,
            },
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              options: [
                { name: 'New', value: 'new' },
                { name: 'Open', value: 'open' },
                { name: 'Resolved', value: 'resolved' },
                { name: 'On Hold', value: 'on hold' },
                { name: 'Invalid', value: 'invalid' },
                { name: 'Duplicate', value: 'duplicate' },
                { name: 'Wontfix', value: 'wontfix' },
                { name: 'Closed', value: 'closed' },
              ],
            },
            {
              id: 'priority',
              name: 'priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              options: [
                { name: 'Trivial', value: 'trivial' },
                { name: 'Minor', value: 'minor' },
                { name: 'Major', value: 'major' },
                { name: 'Critical', value: 'critical' },
                { name: 'Blocker', value: 'blocker' },
              ],
            },
            {
              id: 'assignee',
              name: 'assignee',
              displayName: 'Assignee UUID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_issue',
          name: 'Delete Issue',
          value: 'delete',
          description: 'Delete an issue',
          action: 'Delete issue',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_id',
              name: 'issueId',
              displayName: 'Issue ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // BRANCH RESOURCE
    // ============================================
    {
      id: 'branch',
      name: 'Branch',
      value: 'branch',
      description: 'Branch operations',
      operations: [
        {
          id: 'create_branch',
          name: 'Create Branch',
          value: 'create',
          description: 'Create a branch',
          action: 'Create branch',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Branch Name',
              type: 'string',
              required: true,
            },
            {
              id: 'target',
              name: 'target',
              displayName: 'Target Hash',
              type: 'string',
              required: true,
              description: 'Commit hash to branch from',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_branch',
          name: 'Get Branch',
          value: 'get',
          description: 'Get branch information',
          action: 'Get branch',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Branch Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_branches',
          name: 'List Branches',
          value: 'getMany',
          description: 'List branches',
          action: 'List branches',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'q',
              name: 'q',
              displayName: 'Query',
              type: 'string',
              required: false,
            },
            {
              id: 'sort',
              name: 'sort',
              displayName: 'Sort',
              type: 'string',
              required: false,
            },
            {
              id: 'pagelen',
              name: 'pagelen',
              displayName: 'Page Length',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'delete_branch',
          name: 'Delete Branch',
          value: 'delete',
          description: 'Delete a branch',
          action: 'Delete branch',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Branch Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // COMMIT RESOURCE
    // ============================================
    {
      id: 'commit',
      name: 'Commit',
      value: 'commit',
      description: 'Commit operations',
      operations: [
        {
          id: 'get_commit',
          name: 'Get Commit',
          value: 'get',
          description: 'Get a commit',
          action: 'Get commit',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'commit',
              name: 'commit',
              displayName: 'Commit SHA',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_commits',
          name: 'List Commits',
          value: 'getMany',
          description: 'List commits',
          action: 'List commits',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch',
              type: 'string',
              required: false,
            },
            {
              id: 'include',
              name: 'include',
              displayName: 'Include',
              type: 'string',
              required: false,
              description: 'Commit hash to include',
            },
            {
              id: 'exclude',
              name: 'exclude',
              displayName: 'Exclude',
              type: 'string',
              required: false,
              description: 'Commit hash to exclude',
            },
            {
              id: 'pagelen',
              name: 'pagelen',
              displayName: 'Page Length',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'create_comment',
          name: 'Create Commit Comment',
          value: 'createComment',
          description: 'Create a comment on a commit',
          action: 'Create commit comment',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'commit',
              name: 'commit',
              displayName: 'Commit SHA',
              type: 'string',
              required: true,
            },
            {
              id: 'content',
              name: 'content',
              displayName: 'Comment Content',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: false,
            },
            {
              id: 'line',
              name: 'line',
              displayName: 'Line Number',
              type: 'number',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // PIPELINE RESOURCE
    // ============================================
    {
      id: 'pipeline',
      name: 'Pipeline',
      value: 'pipeline',
      description: 'Pipeline operations',
      operations: [
        {
          id: 'trigger_pipeline',
          name: 'Trigger Pipeline',
          value: 'create',
          description: 'Trigger a pipeline',
          action: 'Trigger pipeline',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'target_type',
              name: 'targetType',
              displayName: 'Target Type',
              type: 'options',
              required: true,
              options: [
                { name: 'Branch', value: 'pipeline_ref_target' },
                { name: 'Commit', value: 'pipeline_commit_target' },
              ],
            },
            {
              id: 'target_ref',
              name: 'targetRef',
              displayName: 'Target Reference',
              type: 'string',
              required: true,
              description: 'Branch name or commit hash',
            },
          ],
          optionalFields: [
            {
              id: 'variables',
              name: 'variables',
              displayName: 'Variables',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_pipeline',
          name: 'Get Pipeline',
          value: 'get',
          description: 'Get a pipeline',
          action: 'Get pipeline',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'pipeline_uuid',
              name: 'pipelineUuid',
              displayName: 'Pipeline UUID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_pipelines',
          name: 'List Pipelines',
          value: 'getMany',
          description: 'List pipelines',
          action: 'List pipelines',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Pending', value: 'PENDING' },
                { name: 'Building', value: 'BUILDING' },
                { name: 'Successful', value: 'SUCCESSFUL' },
                { name: 'Failed', value: 'FAILED' },
                { name: 'Stopped', value: 'STOPPED' },
              ],
            },
            {
              id: 'pagelen',
              name: 'pagelen',
              displayName: 'Page Length',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'stop_pipeline',
          name: 'Stop Pipeline',
          value: 'stop',
          description: 'Stop a pipeline',
          action: 'Stop pipeline',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'pipeline_uuid',
              name: 'pipelineUuid',
              displayName: 'Pipeline UUID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // FILE RESOURCE
    // ============================================
    {
      id: 'file',
      name: 'File',
      value: 'file',
      description: 'File operations',
      operations: [
        {
          id: 'get_file',
          name: 'Get File Content',
          value: 'get',
          description: 'Get file from repository',
          action: 'Get file',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'commit',
              name: 'commit',
              displayName: 'Commit/Branch/Tag',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'list_files',
          name: 'List Files',
          value: 'getMany',
          description: 'List files in directory',
          action: 'List files',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Directory Path',
              type: 'string',
              required: false,
              default: '',
            },
            {
              id: 'commit',
              name: 'commit',
              displayName: 'Commit/Branch/Tag',
              type: 'string',
              required: false,
            },
            {
              id: 'max_depth',
              name: 'maxDepth',
              displayName: 'Max Depth',
              type: 'number',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // WEBHOOK RESOURCE
    // ============================================
    {
      id: 'webhook',
      name: 'Webhook',
      value: 'webhook',
      description: 'Webhook operations',
      operations: [
        {
          id: 'create_webhook',
          name: 'Create Webhook',
          value: 'create',
          description: 'Create a webhook',
          action: 'Create webhook',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
            {
              id: 'events',
              name: 'events',
              displayName: 'Events',
              type: 'multiOptions',
              required: true,
              options: [
                { name: 'Push', value: 'repo:push' },
                { name: 'Pull Request Created', value: 'pullrequest:created' },
                { name: 'Pull Request Updated', value: 'pullrequest:updated' },
                { name: 'Pull Request Approved', value: 'pullrequest:approved' },
                { name: 'Pull Request Fulfilled', value: 'pullrequest:fulfilled' },
                { name: 'Pull Request Rejected', value: 'pullrequest:rejected' },
                { name: 'Issue Created', value: 'issue:created' },
                { name: 'Issue Updated', value: 'issue:updated' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'active',
              name: 'active',
              displayName: 'Active',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'list_webhooks',
          name: 'List Webhooks',
          value: 'getMany',
          description: 'List webhooks',
          action: 'List webhooks',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_webhook',
          name: 'Delete Webhook',
          value: 'delete',
          description: 'Delete a webhook',
          action: 'Delete webhook',
          fields: [
            {
              id: 'workspace',
              name: 'workspace',
              displayName: 'Workspace',
              type: 'string',
              required: true,
            },
            {
              id: 'repo_slug',
              name: 'repoSlug',
              displayName: 'Repository Slug',
              type: 'string',
              required: true,
            },
            {
              id: 'webhook_uuid',
              name: 'webhookUuid',
              displayName: 'Webhook UUID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
