/**
 * Amazon DynamoDB n8n-style Schema
 * 
 * Comprehensive DynamoDB NoSQL database operations
 */

import { N8nAppSchema } from './types';

export const dynamodbSchema: N8nAppSchema = {
  id: 'dynamodb',
  name: 'Amazon DynamoDB',
  description: 'AWS DynamoDB NoSQL database',
  version: '1.0.0',
  color: '#4053D6',
  icon: 'dynamodb',
  group: ['database'],
  
  credentials: [
    {
      name: 'awsCredentials',
      displayName: 'AWS Credentials',
      required: true,
      type: 'custom',
      properties: [
        {
          name: 'accessKeyId',
          displayName: 'Access Key ID',
          type: 'string',
          required: true,
        },
        {
          name: 'secretAccessKey',
          displayName: 'Secret Access Key',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'region',
          displayName: 'Region',
          type: 'options',
          required: true,
          default: 'us-east-1',
          options: [
            { name: 'US East (N. Virginia)', value: 'us-east-1' },
            { name: 'US East (Ohio)', value: 'us-east-2' },
            { name: 'US West (N. California)', value: 'us-west-1' },
            { name: 'US West (Oregon)', value: 'us-west-2' },
            { name: 'EU (Ireland)', value: 'eu-west-1' },
            { name: 'EU (London)', value: 'eu-west-2' },
            { name: 'EU (Frankfurt)', value: 'eu-central-1' },
            { name: 'Asia Pacific (Tokyo)', value: 'ap-northeast-1' },
            { name: 'Asia Pacific (Seoul)', value: 'ap-northeast-2' },
            { name: 'Asia Pacific (Singapore)', value: 'ap-southeast-1' },
            { name: 'Asia Pacific (Sydney)', value: 'ap-southeast-2' },
            { name: 'Asia Pacific (Mumbai)', value: 'ap-south-1' },
            { name: 'South America (São Paulo)', value: 'sa-east-1' },
          ],
        },
        {
          name: 'endpoint',
          displayName: 'Endpoint URL',
          type: 'string',
          required: false,
          description: 'Custom endpoint (e.g., local DynamoDB)',
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // ITEM RESOURCE
    // ============================================
    {
      id: 'item',
      name: 'Item',
      value: 'item',
      description: 'DynamoDB items',
      operations: [
        {
          id: 'put_item',
          name: 'Put Item',
          value: 'put',
          description: 'Put an item into a table',
          action: 'Put item',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'item',
              name: 'item',
              displayName: 'Item',
              type: 'json',
              required: true,
              description: 'Item as JSON object',
            },
          ],
          optionalFields: [
            {
              id: 'condition_expression',
              name: 'conditionExpression',
              displayName: 'Condition Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'expression_attribute_names',
              name: 'expressionAttributeNames',
              displayName: 'Expression Attribute Names',
              type: 'json',
              required: false,
            },
            {
              id: 'expression_attribute_values',
              name: 'expressionAttributeValues',
              displayName: 'Expression Attribute Values',
              type: 'json',
              required: false,
            },
            {
              id: 'return_values',
              name: 'returnValues',
              displayName: 'Return Values',
              type: 'options',
              required: false,
              options: [
                { name: 'None', value: 'NONE' },
                { name: 'All Old', value: 'ALL_OLD' },
              ],
            },
          ],
        },
        {
          id: 'get_item',
          name: 'Get Item',
          value: 'get',
          description: 'Get an item by key',
          action: 'Get item',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'json',
              required: true,
              description: 'Primary key as JSON',
            },
          ],
          optionalFields: [
            {
              id: 'projection_expression',
              name: 'projectionExpression',
              displayName: 'Projection Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'consistent_read',
              name: 'consistentRead',
              displayName: 'Consistent Read',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'expression_attribute_names',
              name: 'expressionAttributeNames',
              displayName: 'Expression Attribute Names',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'update_item',
          name: 'Update Item',
          value: 'update',
          description: 'Update an item',
          action: 'Update item',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'json',
              required: true,
            },
            {
              id: 'update_expression',
              name: 'updateExpression',
              displayName: 'Update Expression',
              type: 'string',
              required: true,
              placeholder: 'SET #name = :name, #count = #count + :inc',
            },
          ],
          optionalFields: [
            {
              id: 'condition_expression',
              name: 'conditionExpression',
              displayName: 'Condition Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'expression_attribute_names',
              name: 'expressionAttributeNames',
              displayName: 'Expression Attribute Names',
              type: 'json',
              required: false,
            },
            {
              id: 'expression_attribute_values',
              name: 'expressionAttributeValues',
              displayName: 'Expression Attribute Values',
              type: 'json',
              required: false,
            },
            {
              id: 'return_values',
              name: 'returnValues',
              displayName: 'Return Values',
              type: 'options',
              required: false,
              options: [
                { name: 'None', value: 'NONE' },
                { name: 'All Old', value: 'ALL_OLD' },
                { name: 'Updated Old', value: 'UPDATED_OLD' },
                { name: 'All New', value: 'ALL_NEW' },
                { name: 'Updated New', value: 'UPDATED_NEW' },
              ],
            },
          ],
        },
        {
          id: 'delete_item',
          name: 'Delete Item',
          value: 'delete',
          description: 'Delete an item',
          action: 'Delete item',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'condition_expression',
              name: 'conditionExpression',
              displayName: 'Condition Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'expression_attribute_names',
              name: 'expressionAttributeNames',
              displayName: 'Expression Attribute Names',
              type: 'json',
              required: false,
            },
            {
              id: 'expression_attribute_values',
              name: 'expressionAttributeValues',
              displayName: 'Expression Attribute Values',
              type: 'json',
              required: false,
            },
            {
              id: 'return_values',
              name: 'returnValues',
              displayName: 'Return Values',
              type: 'options',
              required: false,
              options: [
                { name: 'None', value: 'NONE' },
                { name: 'All Old', value: 'ALL_OLD' },
              ],
            },
          ],
        },
        {
          id: 'batch_get',
          name: 'Batch Get',
          value: 'batchGet',
          description: 'Get multiple items',
          action: 'Batch get items',
          fields: [
            {
              id: 'request_items',
              name: 'requestItems',
              displayName: 'Request Items',
              type: 'json',
              required: true,
              description: 'Table-keyed map of items to retrieve',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'batch_write',
          name: 'Batch Write',
          value: 'batchWrite',
          description: 'Write/delete multiple items',
          action: 'Batch write items',
          fields: [
            {
              id: 'request_items',
              name: 'requestItems',
              displayName: 'Request Items',
              type: 'json',
              required: true,
              description: 'Table-keyed map of put/delete requests',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'transact_get',
          name: 'Transact Get',
          value: 'transactGet',
          description: 'Transactional get items',
          action: 'Transaction get',
          fields: [
            {
              id: 'transact_items',
              name: 'transactItems',
              displayName: 'Transact Items',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'transact_write',
          name: 'Transact Write',
          value: 'transactWrite',
          description: 'Transactional write items',
          action: 'Transaction write',
          fields: [
            {
              id: 'transact_items',
              name: 'transactItems',
              displayName: 'Transact Items',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'client_request_token',
              name: 'clientRequestToken',
              displayName: 'Client Request Token',
              type: 'string',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // QUERY RESOURCE
    // ============================================
    {
      id: 'query',
      name: 'Query',
      value: 'query',
      description: 'Query operations',
      operations: [
        {
          id: 'query',
          name: 'Query',
          value: 'query',
          description: 'Query items by key',
          action: 'Query items',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'key_condition_expression',
              name: 'keyConditionExpression',
              displayName: 'Key Condition Expression',
              type: 'string',
              required: true,
              placeholder: '#pk = :pk AND #sk BEGINS_WITH :prefix',
            },
          ],
          optionalFields: [
            {
              id: 'index_name',
              name: 'indexName',
              displayName: 'Index Name',
              type: 'string',
              required: false,
            },
            {
              id: 'filter_expression',
              name: 'filterExpression',
              displayName: 'Filter Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'projection_expression',
              name: 'projectionExpression',
              displayName: 'Projection Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'expression_attribute_names',
              name: 'expressionAttributeNames',
              displayName: 'Expression Attribute Names',
              type: 'json',
              required: false,
            },
            {
              id: 'expression_attribute_values',
              name: 'expressionAttributeValues',
              displayName: 'Expression Attribute Values',
              type: 'json',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
            },
            {
              id: 'scan_index_forward',
              name: 'scanIndexForward',
              displayName: 'Scan Index Forward',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'consistent_read',
              name: 'consistentRead',
              displayName: 'Consistent Read',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'exclusive_start_key',
              name: 'exclusiveStartKey',
              displayName: 'Exclusive Start Key',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'scan',
          name: 'Scan',
          value: 'scan',
          description: 'Scan all items',
          action: 'Scan table',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'index_name',
              name: 'indexName',
              displayName: 'Index Name',
              type: 'string',
              required: false,
            },
            {
              id: 'filter_expression',
              name: 'filterExpression',
              displayName: 'Filter Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'projection_expression',
              name: 'projectionExpression',
              displayName: 'Projection Expression',
              type: 'string',
              required: false,
            },
            {
              id: 'expression_attribute_names',
              name: 'expressionAttributeNames',
              displayName: 'Expression Attribute Names',
              type: 'json',
              required: false,
            },
            {
              id: 'expression_attribute_values',
              name: 'expressionAttributeValues',
              displayName: 'Expression Attribute Values',
              type: 'json',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
            },
            {
              id: 'consistent_read',
              name: 'consistentRead',
              displayName: 'Consistent Read',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'exclusive_start_key',
              name: 'exclusiveStartKey',
              displayName: 'Exclusive Start Key',
              type: 'json',
              required: false,
            },
            {
              id: 'segment',
              name: 'segment',
              displayName: 'Segment',
              type: 'number',
              required: false,
            },
            {
              id: 'total_segments',
              name: 'totalSegments',
              displayName: 'Total Segments',
              type: 'number',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // TABLE RESOURCE
    // ============================================
    {
      id: 'table',
      name: 'Table',
      value: 'table',
      description: 'Table management',
      operations: [
        {
          id: 'create_table',
          name: 'Create Table',
          value: 'create',
          description: 'Create a table',
          action: 'Create table',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'attribute_definitions',
              name: 'attributeDefinitions',
              displayName: 'Attribute Definitions',
              type: 'json',
              required: true,
              description: '[{"AttributeName": "pk", "AttributeType": "S"}]',
            },
            {
              id: 'key_schema',
              name: 'keySchema',
              displayName: 'Key Schema',
              type: 'json',
              required: true,
              description: '[{"AttributeName": "pk", "KeyType": "HASH"}]',
            },
          ],
          optionalFields: [
            {
              id: 'billing_mode',
              name: 'billingMode',
              displayName: 'Billing Mode',
              type: 'options',
              required: false,
              default: 'PAY_PER_REQUEST',
              options: [
                { name: 'Pay Per Request', value: 'PAY_PER_REQUEST' },
                { name: 'Provisioned', value: 'PROVISIONED' },
              ],
            },
            {
              id: 'read_capacity_units',
              name: 'readCapacityUnits',
              displayName: 'Read Capacity Units',
              type: 'number',
              required: false,
            },
            {
              id: 'write_capacity_units',
              name: 'writeCapacityUnits',
              displayName: 'Write Capacity Units',
              type: 'number',
              required: false,
            },
            {
              id: 'global_secondary_indexes',
              name: 'globalSecondaryIndexes',
              displayName: 'Global Secondary Indexes',
              type: 'json',
              required: false,
            },
            {
              id: 'local_secondary_indexes',
              name: 'localSecondaryIndexes',
              displayName: 'Local Secondary Indexes',
              type: 'json',
              required: false,
            },
            {
              id: 'stream_specification',
              name: 'streamSpecification',
              displayName: 'Stream Specification',
              type: 'json',
              required: false,
            },
            {
              id: 'tags',
              name: 'tags',
              displayName: 'Tags',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'describe_table',
          name: 'Describe Table',
          value: 'describe',
          description: 'Describe a table',
          action: 'Describe table',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_tables',
          name: 'List Tables',
          value: 'getMany',
          description: 'List all tables',
          action: 'List tables',
          fields: [],
          optionalFields: [
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
            },
            {
              id: 'exclusive_start_table_name',
              name: 'exclusiveStartTableName',
              displayName: 'Exclusive Start Table Name',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'update_table',
          name: 'Update Table',
          value: 'update',
          description: 'Update table settings',
          action: 'Update table',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'billing_mode',
              name: 'billingMode',
              displayName: 'Billing Mode',
              type: 'options',
              required: false,
              options: [
                { name: 'Pay Per Request', value: 'PAY_PER_REQUEST' },
                { name: 'Provisioned', value: 'PROVISIONED' },
              ],
            },
            {
              id: 'read_capacity_units',
              name: 'readCapacityUnits',
              displayName: 'Read Capacity Units',
              type: 'number',
              required: false,
            },
            {
              id: 'write_capacity_units',
              name: 'writeCapacityUnits',
              displayName: 'Write Capacity Units',
              type: 'number',
              required: false,
            },
            {
              id: 'global_secondary_index_updates',
              name: 'globalSecondaryIndexUpdates',
              displayName: 'GSI Updates',
              type: 'json',
              required: false,
            },
            {
              id: 'stream_specification',
              name: 'streamSpecification',
              displayName: 'Stream Specification',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'delete_table',
          name: 'Delete Table',
          value: 'delete',
          description: 'Delete a table',
          action: 'Delete table',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // TTL RESOURCE
    // ============================================
    {
      id: 'ttl',
      name: 'Time To Live',
      value: 'ttl',
      description: 'TTL settings',
      operations: [
        {
          id: 'describe_ttl',
          name: 'Describe TTL',
          value: 'describe',
          description: 'Describe TTL settings',
          action: 'Describe TTL',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_ttl',
          name: 'Update TTL',
          value: 'update',
          description: 'Update TTL settings',
          action: 'Update TTL',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'attribute_name',
              name: 'attributeName',
              displayName: 'Attribute Name',
              type: 'string',
              required: true,
            },
            {
              id: 'enabled',
              name: 'enabled',
              displayName: 'Enabled',
              type: 'boolean',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // BACKUP RESOURCE
    // ============================================
    {
      id: 'backup',
      name: 'Backup',
      value: 'backup',
      description: 'Backup operations',
      operations: [
        {
          id: 'create_backup',
          name: 'Create Backup',
          value: 'create',
          description: 'Create a backup',
          action: 'Create backup',
          fields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'backup_name',
              name: 'backupName',
              displayName: 'Backup Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_backups',
          name: 'List Backups',
          value: 'getMany',
          description: 'List backups',
          action: 'List backups',
          fields: [],
          optionalFields: [
            {
              id: 'table_name',
              name: 'tableName',
              displayName: 'Table Name',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'describe_backup',
          name: 'Describe Backup',
          value: 'describe',
          description: 'Describe a backup',
          action: 'Describe backup',
          fields: [
            {
              id: 'backup_arn',
              name: 'backupArn',
              displayName: 'Backup ARN',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_backup',
          name: 'Delete Backup',
          value: 'delete',
          description: 'Delete a backup',
          action: 'Delete backup',
          fields: [
            {
              id: 'backup_arn',
              name: 'backupArn',
              displayName: 'Backup ARN',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'restore_table',
          name: 'Restore Table',
          value: 'restore',
          description: 'Restore table from backup',
          action: 'Restore from backup',
          fields: [
            {
              id: 'target_table_name',
              name: 'targetTableName',
              displayName: 'Target Table Name',
              type: 'string',
              required: true,
            },
            {
              id: 'backup_arn',
              name: 'backupArn',
              displayName: 'Backup ARN',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
