/**
 * Elasticsearch n8n-style Schema
 * 
 * Comprehensive Elasticsearch search and analytics operations
 */

import { N8nAppSchema } from './types';

export const elasticsearchSchema: N8nAppSchema = {
  id: 'elasticsearch',
  name: 'Elasticsearch',
  description: 'Elasticsearch search and analytics engine',
  version: '1.0.0',
  color: '#00BFB3',
  icon: 'elasticsearch',
  group: ['database'],
  
  credentials: [
    {
      name: 'elasticsearchConnection',
      displayName: 'Elasticsearch Connection',
      required: true,
      type: 'custom',
      properties: [
        {
          name: 'baseUrl',
          displayName: 'Base URL',
          type: 'string',
          required: true,
          default: 'http://localhost:9200',
        },
        {
          name: 'username',
          displayName: 'Username',
          type: 'string',
          required: false,
        },
        {
          name: 'password',
          displayName: 'Password',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'apiKey',
          displayName: 'API Key',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
          description: 'Alternative to username/password',
        },
        {
          name: 'cloudId',
          displayName: 'Cloud ID',
          type: 'string',
          required: false,
          description: 'Elastic Cloud deployment ID',
        },
        {
          name: 'ssl',
          displayName: 'Verify SSL',
          type: 'boolean',
          required: false,
          default: true,
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // DOCUMENT RESOURCE
    // ============================================
    {
      id: 'document',
      name: 'Document',
      value: 'document',
      description: 'Document operations',
      operations: [
        {
          id: 'index_document',
          name: 'Index Document',
          value: 'index',
          description: 'Index a new document',
          action: 'Index document',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
            {
              id: 'document',
              name: 'document',
              displayName: 'Document',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'id',
              name: 'id',
              displayName: 'Document ID',
              type: 'string',
              required: false,
              description: 'Auto-generated if not provided',
            },
            {
              id: 'routing',
              name: 'routing',
              displayName: 'Routing',
              type: 'string',
              required: false,
            },
            {
              id: 'refresh',
              name: 'refresh',
              displayName: 'Refresh',
              type: 'options',
              required: false,
              options: [
                { name: 'False', value: 'false' },
                { name: 'True', value: 'true' },
                { name: 'Wait For', value: 'wait_for' },
              ],
            },
            {
              id: 'pipeline',
              name: 'pipeline',
              displayName: 'Pipeline',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_document',
          name: 'Get Document',
          value: 'get',
          description: 'Get a document by ID',
          action: 'Get document',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
            {
              id: 'id',
              name: 'id',
              displayName: 'Document ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'source_includes',
              name: 'sourceIncludes',
              displayName: 'Source Includes',
              type: 'string',
              required: false,
              description: 'Comma-separated fields to include',
            },
            {
              id: 'source_excludes',
              name: 'sourceExcludes',
              displayName: 'Source Excludes',
              type: 'string',
              required: false,
              description: 'Comma-separated fields to exclude',
            },
            {
              id: 'routing',
              name: 'routing',
              displayName: 'Routing',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'update_document',
          name: 'Update Document',
          value: 'update',
          description: 'Update a document',
          action: 'Update document',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
            {
              id: 'id',
              name: 'id',
              displayName: 'Document ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'doc',
              name: 'doc',
              displayName: 'Partial Document',
              type: 'json',
              required: false,
              description: 'Fields to update',
            },
            {
              id: 'script',
              name: 'script',
              displayName: 'Script',
              type: 'json',
              required: false,
              description: 'Script for update',
            },
            {
              id: 'upsert',
              name: 'upsert',
              displayName: 'Upsert Document',
              type: 'json',
              required: false,
              description: 'Document to insert if not exists',
            },
            {
              id: 'doc_as_upsert',
              name: 'docAsUpsert',
              displayName: 'Doc as Upsert',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'refresh',
              name: 'refresh',
              displayName: 'Refresh',
              type: 'options',
              required: false,
              options: [
                { name: 'False', value: 'false' },
                { name: 'True', value: 'true' },
                { name: 'Wait For', value: 'wait_for' },
              ],
            },
            {
              id: 'retry_on_conflict',
              name: 'retryOnConflict',
              displayName: 'Retry on Conflict',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'delete_document',
          name: 'Delete Document',
          value: 'delete',
          description: 'Delete a document',
          action: 'Delete document',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
            {
              id: 'id',
              name: 'id',
              displayName: 'Document ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'routing',
              name: 'routing',
              displayName: 'Routing',
              type: 'string',
              required: false,
            },
            {
              id: 'refresh',
              name: 'refresh',
              displayName: 'Refresh',
              type: 'options',
              required: false,
              options: [
                { name: 'False', value: 'false' },
                { name: 'True', value: 'true' },
                { name: 'Wait For', value: 'wait_for' },
              ],
            },
          ],
        },
        {
          id: 'bulk_operations',
          name: 'Bulk Operations',
          value: 'bulk',
          description: 'Perform bulk operations',
          action: 'Bulk operations',
          fields: [
            {
              id: 'operations',
              name: 'operations',
              displayName: 'Operations',
              type: 'json',
              required: true,
              description: 'Array of bulk operations',
            },
          ],
          optionalFields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Default Index',
              type: 'string',
              required: false,
            },
            {
              id: 'refresh',
              name: 'refresh',
              displayName: 'Refresh',
              type: 'options',
              required: false,
              options: [
                { name: 'False', value: 'false' },
                { name: 'True', value: 'true' },
                { name: 'Wait For', value: 'wait_for' },
              ],
            },
            {
              id: 'pipeline',
              name: 'pipeline',
              displayName: 'Pipeline',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'multi_get',
          name: 'Multi Get',
          value: 'mget',
          description: 'Get multiple documents',
          action: 'Multi get documents',
          fields: [
            {
              id: 'docs',
              name: 'docs',
              displayName: 'Documents',
              type: 'json',
              required: true,
              description: 'Array of {_index, _id} objects',
            },
          ],
          optionalFields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Default Index',
              type: 'string',
              required: false,
            },
            {
              id: 'source_includes',
              name: 'sourceIncludes',
              displayName: 'Source Includes',
              type: 'string',
              required: false,
            },
            {
              id: 'source_excludes',
              name: 'sourceExcludes',
              displayName: 'Source Excludes',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'reindex',
          name: 'Reindex',
          value: 'reindex',
          description: 'Reindex documents',
          action: 'Reindex',
          fields: [
            {
              id: 'source_index',
              name: 'sourceIndex',
              displayName: 'Source Index',
              type: 'string',
              required: true,
            },
            {
              id: 'dest_index',
              name: 'destIndex',
              displayName: 'Destination Index',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'json',
              required: false,
            },
            {
              id: 'script',
              name: 'script',
              displayName: 'Script',
              type: 'json',
              required: false,
            },
            {
              id: 'max_docs',
              name: 'maxDocs',
              displayName: 'Max Documents',
              type: 'number',
              required: false,
            },
            {
              id: 'wait_for_completion',
              name: 'waitForCompletion',
              displayName: 'Wait for Completion',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // SEARCH RESOURCE
    // ============================================
    {
      id: 'search',
      name: 'Search',
      value: 'search',
      description: 'Search operations',
      operations: [
        {
          id: 'search',
          name: 'Search',
          value: 'search',
          description: 'Search documents',
          action: 'Search documents',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
              description: 'Index name or pattern (e.g., logs-*)',
            },
          ],
          optionalFields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'json',
              required: false,
              description: 'Elasticsearch query DSL',
            },
            {
              id: 'simple_query',
              name: 'simpleQuery',
              displayName: 'Simple Query String',
              type: 'string',
              required: false,
            },
            {
              id: 'sort',
              name: 'sort',
              displayName: 'Sort',
              type: 'json',
              required: false,
              description: 'Sort criteria',
            },
            {
              id: 'size',
              name: 'size',
              displayName: 'Size',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'from',
              name: 'from',
              displayName: 'From',
              type: 'number',
              required: false,
              default: 0,
            },
            {
              id: 'source_includes',
              name: 'sourceIncludes',
              displayName: 'Source Includes',
              type: 'string',
              required: false,
            },
            {
              id: 'source_excludes',
              name: 'sourceExcludes',
              displayName: 'Source Excludes',
              type: 'string',
              required: false,
            },
            {
              id: 'aggs',
              name: 'aggs',
              displayName: 'Aggregations',
              type: 'json',
              required: false,
            },
            {
              id: 'highlight',
              name: 'highlight',
              displayName: 'Highlight',
              type: 'json',
              required: false,
            },
            {
              id: 'track_total_hits',
              name: 'trackTotalHits',
              displayName: 'Track Total Hits',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'count',
          name: 'Count',
          value: 'count',
          description: 'Count documents',
          action: 'Count documents',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'delete_by_query',
          name: 'Delete by Query',
          value: 'deleteByQuery',
          description: 'Delete documents matching query',
          action: 'Delete by query',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'refresh',
              name: 'refresh',
              displayName: 'Refresh',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'wait_for_completion',
              name: 'waitForCompletion',
              displayName: 'Wait for Completion',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'conflicts',
              name: 'conflicts',
              displayName: 'Conflicts',
              type: 'options',
              required: false,
              options: [
                { name: 'Abort', value: 'abort' },
                { name: 'Proceed', value: 'proceed' },
              ],
            },
          ],
        },
        {
          id: 'update_by_query',
          name: 'Update by Query',
          value: 'updateByQuery',
          description: 'Update documents matching query',
          action: 'Update by query',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'json',
              required: false,
            },
            {
              id: 'script',
              name: 'script',
              displayName: 'Script',
              type: 'json',
              required: false,
            },
            {
              id: 'refresh',
              name: 'refresh',
              displayName: 'Refresh',
              type: 'boolean',
              required: false,
            },
            {
              id: 'wait_for_completion',
              name: 'waitForCompletion',
              displayName: 'Wait for Completion',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'scroll',
          name: 'Scroll',
          value: 'scroll',
          description: 'Scroll through results',
          action: 'Scroll search',
          fields: [
            {
              id: 'scroll_id',
              name: 'scrollId',
              displayName: 'Scroll ID',
              type: 'string',
              required: true,
            },
            {
              id: 'scroll',
              name: 'scroll',
              displayName: 'Scroll Timeout',
              type: 'string',
              required: true,
              default: '1m',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'clear_scroll',
          name: 'Clear Scroll',
          value: 'clearScroll',
          description: 'Clear scroll context',
          action: 'Clear scroll',
          fields: [
            {
              id: 'scroll_id',
              name: 'scrollId',
              displayName: 'Scroll ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // INDEX RESOURCE
    // ============================================
    {
      id: 'index',
      name: 'Index',
      value: 'index',
      description: 'Index management',
      operations: [
        {
          id: 'create_index',
          name: 'Create Index',
          value: 'create',
          description: 'Create an index',
          action: 'Create index',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'settings',
              name: 'settings',
              displayName: 'Settings',
              type: 'json',
              required: false,
            },
            {
              id: 'mappings',
              name: 'mappings',
              displayName: 'Mappings',
              type: 'json',
              required: false,
            },
            {
              id: 'aliases',
              name: 'aliases',
              displayName: 'Aliases',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_index',
          name: 'Get Index',
          value: 'get',
          description: 'Get index information',
          action: 'Get index',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_indices',
          name: 'List Indices',
          value: 'getMany',
          description: 'List all indices',
          action: 'List indices',
          fields: [],
          optionalFields: [
            {
              id: 'pattern',
              name: 'pattern',
              displayName: 'Index Pattern',
              type: 'string',
              required: false,
              default: '*',
            },
          ],
        },
        {
          id: 'delete_index',
          name: 'Delete Index',
          value: 'delete',
          description: 'Delete an index',
          action: 'Delete index',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'index_exists',
          name: 'Index Exists',
          value: 'exists',
          description: 'Check if index exists',
          action: 'Check index exists',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'open_index',
          name: 'Open Index',
          value: 'open',
          description: 'Open a closed index',
          action: 'Open index',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'close_index',
          name: 'Close Index',
          value: 'close',
          description: 'Close an index',
          action: 'Close index',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'refresh_index',
          name: 'Refresh Index',
          value: 'refresh',
          description: 'Refresh an index',
          action: 'Refresh index',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_settings',
          name: 'Update Settings',
          value: 'updateSettings',
          description: 'Update index settings',
          action: 'Update settings',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
            {
              id: 'settings',
              name: 'settings',
              displayName: 'Settings',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'put_mapping',
          name: 'Put Mapping',
          value: 'putMapping',
          description: 'Update index mapping',
          action: 'Put mapping',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index Name',
              type: 'string',
              required: true,
            },
            {
              id: 'mappings',
              name: 'mappings',
              displayName: 'Mappings',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ALIAS RESOURCE
    // ============================================
    {
      id: 'alias',
      name: 'Alias',
      value: 'alias',
      description: 'Alias management',
      operations: [
        {
          id: 'create_alias',
          name: 'Create Alias',
          value: 'create',
          description: 'Create an alias',
          action: 'Create alias',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
            {
              id: 'alias',
              name: 'alias',
              displayName: 'Alias Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'filter',
              name: 'filter',
              displayName: 'Filter',
              type: 'json',
              required: false,
            },
            {
              id: 'routing',
              name: 'routing',
              displayName: 'Routing',
              type: 'string',
              required: false,
            },
            {
              id: 'is_write_index',
              name: 'isWriteIndex',
              displayName: 'Is Write Index',
              type: 'boolean',
              required: false,
            },
          ],
        },
        {
          id: 'get_alias',
          name: 'Get Alias',
          value: 'get',
          description: 'Get alias information',
          action: 'Get alias',
          fields: [
            {
              id: 'alias',
              name: 'alias',
              displayName: 'Alias Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_alias',
          name: 'Delete Alias',
          value: 'delete',
          description: 'Delete an alias',
          action: 'Delete alias',
          fields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: true,
            },
            {
              id: 'alias',
              name: 'alias',
              displayName: 'Alias Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_aliases',
          name: 'Update Aliases',
          value: 'updateAliases',
          description: 'Atomic alias updates',
          action: 'Update aliases',
          fields: [
            {
              id: 'actions',
              name: 'actions',
              displayName: 'Actions',
              type: 'json',
              required: true,
              description: 'Array of add/remove actions',
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // TEMPLATE RESOURCE
    // ============================================
    {
      id: 'template',
      name: 'Template',
      value: 'template',
      description: 'Index template management',
      operations: [
        {
          id: 'create_template',
          name: 'Create Template',
          value: 'create',
          description: 'Create an index template',
          action: 'Create template',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Template Name',
              type: 'string',
              required: true,
            },
            {
              id: 'index_patterns',
              name: 'indexPatterns',
              displayName: 'Index Patterns',
              type: 'string',
              required: true,
              description: 'Comma-separated patterns',
            },
          ],
          optionalFields: [
            {
              id: 'settings',
              name: 'settings',
              displayName: 'Settings',
              type: 'json',
              required: false,
            },
            {
              id: 'mappings',
              name: 'mappings',
              displayName: 'Mappings',
              type: 'json',
              required: false,
            },
            {
              id: 'aliases',
              name: 'aliases',
              displayName: 'Aliases',
              type: 'json',
              required: false,
            },
            {
              id: 'priority',
              name: 'priority',
              displayName: 'Priority',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_template',
          name: 'Get Template',
          value: 'get',
          description: 'Get a template',
          action: 'Get template',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Template Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_template',
          name: 'Delete Template',
          value: 'delete',
          description: 'Delete a template',
          action: 'Delete template',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Template Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CLUSTER RESOURCE
    // ============================================
    {
      id: 'cluster',
      name: 'Cluster',
      value: 'cluster',
      description: 'Cluster operations',
      operations: [
        {
          id: 'health',
          name: 'Cluster Health',
          value: 'health',
          description: 'Get cluster health',
          action: 'Get cluster health',
          fields: [],
          optionalFields: [
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'string',
              required: false,
            },
            {
              id: 'wait_for_status',
              name: 'waitForStatus',
              displayName: 'Wait for Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Green', value: 'green' },
                { name: 'Yellow', value: 'yellow' },
                { name: 'Red', value: 'red' },
              ],
            },
            {
              id: 'timeout',
              name: 'timeout',
              displayName: 'Timeout',
              type: 'string',
              required: false,
              default: '30s',
            },
          ],
        },
        {
          id: 'stats',
          name: 'Cluster Stats',
          value: 'stats',
          description: 'Get cluster statistics',
          action: 'Get cluster stats',
          fields: [],
          optionalFields: [],
        },
        {
          id: 'settings',
          name: 'Cluster Settings',
          value: 'getSettings',
          description: 'Get cluster settings',
          action: 'Get cluster settings',
          fields: [],
          optionalFields: [
            {
              id: 'include_defaults',
              name: 'includeDefaults',
              displayName: 'Include Defaults',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'update_settings',
          name: 'Update Settings',
          value: 'updateSettings',
          description: 'Update cluster settings',
          action: 'Update cluster settings',
          fields: [
            {
              id: 'settings',
              name: 'settings',
              displayName: 'Settings',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'persistent',
              name: 'persistent',
              displayName: 'Persistent',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
      ],
    },
  ],
};
