/**
 * ElevenLabs n8n-style Schema
 * 
 * Comprehensive ElevenLabs AI Voice API operations
 */

import { N8nAppSchema } from './types';

export const elevenLabsSchema: N8nAppSchema = {
  id: 'elevenLabs',
  name: 'ElevenLabs',
  description: 'ElevenLabs AI voice synthesis',
  version: '1.0.0',
  color: '#000000',
  icon: 'elevenlabs',
  group: ['ai', 'audio', 'voice'],
  
  credentials: [
    {
      name: 'elevenLabsApi',
      displayName: 'ElevenLabs API',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'apiKey',
          displayName: 'API Key',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // TEXT TO SPEECH RESOURCE
    // ============================================
    {
      id: 'textToSpeech',
      name: 'Text to Speech',
      value: 'textToSpeech',
      description: 'Text to speech conversion',
      operations: [
        {
          id: 'convert',
          name: 'Convert Text to Speech',
          value: 'convert',
          description: 'Convert text to speech audio',
          action: 'Convert text to speech',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
              description: 'ID of the voice to use',
            },
            {
              id: 'text',
              name: 'text',
              displayName: 'Text',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 4,
              },
            },
          ],
          optionalFields: [
            {
              id: 'model_id',
              name: 'modelId',
              displayName: 'Model',
              type: 'options',
              required: false,
              options: [
                { name: 'Eleven Multilingual v2', value: 'eleven_multilingual_v2' },
                { name: 'Eleven Flash v2.5', value: 'eleven_flash_v2_5' },
                { name: 'Eleven Turbo v2.5', value: 'eleven_turbo_v2_5' },
                { name: 'Eleven Turbo v2', value: 'eleven_turbo_v2' },
                { name: 'Eleven Monolingual v1', value: 'eleven_monolingual_v1' },
                { name: 'Eleven English v1', value: 'eleven_english_sts_v2' },
              ],
              default: 'eleven_multilingual_v2',
            },
            {
              id: 'output_format',
              name: 'outputFormat',
              displayName: 'Output Format',
              type: 'options',
              required: false,
              options: [
                { name: 'MP3 44.1kHz 128kbps', value: 'mp3_44100_128' },
                { name: 'MP3 44.1kHz 64kbps', value: 'mp3_44100_64' },
                { name: 'MP3 44.1kHz 32kbps', value: 'mp3_44100_32' },
                { name: 'MP3 22.05kHz 32kbps', value: 'mp3_22050_32' },
                { name: 'PCM 16kHz', value: 'pcm_16000' },
                { name: 'PCM 22.05kHz', value: 'pcm_22050' },
                { name: 'PCM 24kHz', value: 'pcm_24000' },
                { name: 'PCM 44.1kHz', value: 'pcm_44100' },
                { name: 'μ-law 8kHz', value: 'ulaw_8000' },
              ],
              default: 'mp3_44100_128',
            },
            {
              id: 'stability',
              name: 'stability',
              displayName: 'Stability',
              type: 'number',
              required: false,
              default: 0.5,
              description: 'Voice stability (0-1)',
            },
            {
              id: 'similarity_boost',
              name: 'similarityBoost',
              displayName: 'Similarity Boost',
              type: 'number',
              required: false,
              default: 0.75,
              description: 'Similarity boost (0-1)',
            },
            {
              id: 'style',
              name: 'style',
              displayName: 'Style',
              type: 'number',
              required: false,
              default: 0,
              description: 'Style exaggeration (0-1)',
            },
            {
              id: 'use_speaker_boost',
              name: 'useSpeakerBoost',
              displayName: 'Use Speaker Boost',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'seed',
              name: 'seed',
              displayName: 'Seed',
              type: 'number',
              required: false,
              description: 'Random seed for reproducibility',
            },
            {
              id: 'previous_text',
              name: 'previousText',
              displayName: 'Previous Text',
              type: 'string',
              required: false,
              description: 'Text before for context',
            },
            {
              id: 'next_text',
              name: 'nextText',
              displayName: 'Next Text',
              type: 'string',
              required: false,
              description: 'Text after for context',
            },
            {
              id: 'language_code',
              name: 'languageCode',
              displayName: 'Language Code',
              type: 'string',
              required: false,
              description: 'ISO language code (e.g., en, es, fr)',
            },
          ],
        },
        {
          id: 'stream',
          name: 'Stream Text to Speech',
          value: 'stream',
          description: 'Stream text to speech audio',
          action: 'Stream text to speech',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
            {
              id: 'text',
              name: 'text',
              displayName: 'Text',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 4,
              },
            },
          ],
          optionalFields: [
            {
              id: 'model_id',
              name: 'modelId',
              displayName: 'Model',
              type: 'options',
              required: false,
              options: [
                { name: 'Eleven Multilingual v2', value: 'eleven_multilingual_v2' },
                { name: 'Eleven Flash v2.5', value: 'eleven_flash_v2_5' },
                { name: 'Eleven Turbo v2.5', value: 'eleven_turbo_v2_5' },
                { name: 'Eleven Turbo v2', value: 'eleven_turbo_v2' },
              ],
              default: 'eleven_multilingual_v2',
            },
            {
              id: 'output_format',
              name: 'outputFormat',
              displayName: 'Output Format',
              type: 'options',
              required: false,
              options: [
                { name: 'MP3 44.1kHz 128kbps', value: 'mp3_44100_128' },
                { name: 'MP3 44.1kHz 64kbps', value: 'mp3_44100_64' },
                { name: 'PCM 16kHz', value: 'pcm_16000' },
                { name: 'PCM 22.05kHz', value: 'pcm_22050' },
                { name: 'PCM 24kHz', value: 'pcm_24000' },
              ],
              default: 'mp3_44100_128',
            },
            {
              id: 'stability',
              name: 'stability',
              displayName: 'Stability',
              type: 'number',
              required: false,
              default: 0.5,
            },
            {
              id: 'similarity_boost',
              name: 'similarityBoost',
              displayName: 'Similarity Boost',
              type: 'number',
              required: false,
              default: 0.75,
            },
          ],
        },
        {
          id: 'convert_with_timestamps',
          name: 'Convert with Timestamps',
          value: 'convertWithTimestamps',
          description: 'Convert text to speech with word timestamps',
          action: 'Convert with timestamps',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
            {
              id: 'text',
              name: 'text',
              displayName: 'Text',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 4,
              },
            },
          ],
          optionalFields: [
            {
              id: 'model_id',
              name: 'modelId',
              displayName: 'Model',
              type: 'options',
              required: false,
              options: [
                { name: 'Eleven Multilingual v2', value: 'eleven_multilingual_v2' },
                { name: 'Eleven Flash v2.5', value: 'eleven_flash_v2_5' },
                { name: 'Eleven Turbo v2.5', value: 'eleven_turbo_v2_5' },
              ],
              default: 'eleven_multilingual_v2',
            },
            {
              id: 'output_format',
              name: 'outputFormat',
              displayName: 'Output Format',
              type: 'options',
              required: false,
              options: [
                { name: 'MP3 44.1kHz 128kbps', value: 'mp3_44100_128' },
                { name: 'MP3 44.1kHz 64kbps', value: 'mp3_44100_64' },
              ],
              default: 'mp3_44100_128',
            },
            {
              id: 'stability',
              name: 'stability',
              displayName: 'Stability',
              type: 'number',
              required: false,
              default: 0.5,
            },
            {
              id: 'similarity_boost',
              name: 'similarityBoost',
              displayName: 'Similarity Boost',
              type: 'number',
              required: false,
              default: 0.75,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // SPEECH TO SPEECH RESOURCE
    // ============================================
    {
      id: 'speechToSpeech',
      name: 'Speech to Speech',
      value: 'speechToSpeech',
      description: 'Voice conversion operations',
      operations: [
        {
          id: 'convert_speech',
          name: 'Convert Speech',
          value: 'convert',
          description: 'Convert voice in audio to another voice',
          action: 'Convert speech',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Target Voice ID',
              type: 'string',
              required: true,
            },
            {
              id: 'audio',
              name: 'audio',
              displayName: 'Audio (Base64)',
              type: 'string',
              required: true,
              description: 'Base64 encoded audio',
            },
          ],
          optionalFields: [
            {
              id: 'model_id',
              name: 'modelId',
              displayName: 'Model',
              type: 'options',
              required: false,
              options: [
                { name: 'Eleven English v2', value: 'eleven_english_sts_v2' },
                { name: 'Eleven Multilingual v2', value: 'eleven_multilingual_sts_v2' },
              ],
              default: 'eleven_english_sts_v2',
            },
            {
              id: 'output_format',
              name: 'outputFormat',
              displayName: 'Output Format',
              type: 'options',
              required: false,
              options: [
                { name: 'MP3 44.1kHz 128kbps', value: 'mp3_44100_128' },
                { name: 'MP3 44.1kHz 64kbps', value: 'mp3_44100_64' },
                { name: 'PCM 16kHz', value: 'pcm_16000' },
                { name: 'PCM 22.05kHz', value: 'pcm_22050' },
              ],
              default: 'mp3_44100_128',
            },
            {
              id: 'stability',
              name: 'stability',
              displayName: 'Stability',
              type: 'number',
              required: false,
              default: 0.5,
            },
            {
              id: 'similarity_boost',
              name: 'similarityBoost',
              displayName: 'Similarity Boost',
              type: 'number',
              required: false,
              default: 0.75,
            },
            {
              id: 'remove_background_noise',
              name: 'removeBackgroundNoise',
              displayName: 'Remove Background Noise',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'stream_speech',
          name: 'Stream Speech Conversion',
          value: 'stream',
          description: 'Stream voice conversion',
          action: 'Stream speech conversion',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Target Voice ID',
              type: 'string',
              required: true,
            },
            {
              id: 'audio',
              name: 'audio',
              displayName: 'Audio (Base64)',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'model_id',
              name: 'modelId',
              displayName: 'Model',
              type: 'options',
              required: false,
              options: [
                { name: 'Eleven English v2', value: 'eleven_english_sts_v2' },
                { name: 'Eleven Multilingual v2', value: 'eleven_multilingual_sts_v2' },
              ],
              default: 'eleven_english_sts_v2',
            },
            {
              id: 'stability',
              name: 'stability',
              displayName: 'Stability',
              type: 'number',
              required: false,
              default: 0.5,
            },
            {
              id: 'similarity_boost',
              name: 'similarityBoost',
              displayName: 'Similarity Boost',
              type: 'number',
              required: false,
              default: 0.75,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // VOICES RESOURCE
    // ============================================
    {
      id: 'voices',
      name: 'Voices',
      value: 'voices',
      description: 'Voice management operations',
      operations: [
        {
          id: 'get_voice',
          name: 'Get Voice',
          value: 'get',
          description: 'Get voice details',
          action: 'Get voice',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'with_settings',
              name: 'withSettings',
              displayName: 'Include Settings',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'list_voices',
          name: 'List Voices',
          value: 'getMany',
          description: 'List all available voices',
          action: 'List voices',
          fields: [],
          optionalFields: [
            {
              id: 'show_legacy',
              name: 'showLegacy',
              displayName: 'Show Legacy Voices',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'add_voice',
          name: 'Add Voice',
          value: 'create',
          description: 'Add a new voice from samples',
          action: 'Add voice',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Voice Name',
              type: 'string',
              required: true,
            },
            {
              id: 'files',
              name: 'files',
              displayName: 'Audio Files (Base64 Array)',
              type: 'json',
              required: true,
              description: 'Array of base64 encoded audio samples',
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels (JSON)',
              type: 'json',
              required: false,
              description: 'Key-value pairs for categorization',
            },
            {
              id: 'remove_background_noise',
              name: 'removeBackgroundNoise',
              displayName: 'Remove Background Noise',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'edit_voice',
          name: 'Edit Voice',
          value: 'update',
          description: 'Edit a voice',
          action: 'Edit voice',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Voice Name',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'delete_voice',
          name: 'Delete Voice',
          value: 'delete',
          description: 'Delete a voice',
          action: 'Delete voice',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_default_settings',
          name: 'Get Default Settings',
          value: 'getDefaultSettings',
          description: 'Get default voice settings',
          action: 'Get default settings',
          fields: [],
          optionalFields: [],
        },
        {
          id: 'get_voice_settings',
          name: 'Get Voice Settings',
          value: 'getSettings',
          description: 'Get voice-specific settings',
          action: 'Get voice settings',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'edit_voice_settings',
          name: 'Edit Voice Settings',
          value: 'updateSettings',
          description: 'Update voice settings',
          action: 'Edit voice settings',
          fields: [
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
            {
              id: 'stability',
              name: 'stability',
              displayName: 'Stability',
              type: 'number',
              required: true,
              default: 0.5,
            },
            {
              id: 'similarity_boost',
              name: 'similarityBoost',
              displayName: 'Similarity Boost',
              type: 'number',
              required: true,
              default: 0.75,
            },
          ],
          optionalFields: [
            {
              id: 'style',
              name: 'style',
              displayName: 'Style',
              type: 'number',
              required: false,
              default: 0,
            },
            {
              id: 'use_speaker_boost',
              name: 'useSpeakerBoost',
              displayName: 'Use Speaker Boost',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // VOICE LIBRARY RESOURCE
    // ============================================
    {
      id: 'voiceLibrary',
      name: 'Voice Library',
      value: 'voiceLibrary',
      description: 'Voice library operations',
      operations: [
        {
          id: 'get_shared_voices',
          name: 'Get Shared Voices',
          value: 'getShared',
          description: 'Browse shared voices in the library',
          action: 'Get shared voices',
          fields: [],
          optionalFields: [
            {
              id: 'page_size',
              name: 'pageSize',
              displayName: 'Page Size',
              type: 'number',
              required: false,
              default: 30,
            },
            {
              id: 'category',
              name: 'category',
              displayName: 'Category',
              type: 'options',
              required: false,
              options: [
                { name: 'Generated', value: 'generated' },
                { name: 'Professional', value: 'professional' },
                { name: 'Cloned', value: 'cloned' },
                { name: 'High Quality', value: 'high_quality' },
              ],
            },
            {
              id: 'gender',
              name: 'gender',
              displayName: 'Gender',
              type: 'options',
              required: false,
              options: [
                { name: 'Male', value: 'male' },
                { name: 'Female', value: 'female' },
                { name: 'Neutral', value: 'neutral' },
              ],
            },
            {
              id: 'age',
              name: 'age',
              displayName: 'Age',
              type: 'options',
              required: false,
              options: [
                { name: 'Young', value: 'young' },
                { name: 'Middle Aged', value: 'middle_aged' },
                { name: 'Old', value: 'old' },
              ],
            },
            {
              id: 'language',
              name: 'language',
              displayName: 'Language',
              type: 'string',
              required: false,
            },
            {
              id: 'search',
              name: 'search',
              displayName: 'Search Query',
              type: 'string',
              required: false,
            },
            {
              id: 'use_cases',
              name: 'useCases',
              displayName: 'Use Cases',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Narration', value: 'narration' },
                { name: 'News', value: 'news' },
                { name: 'Video Games', value: 'video_games' },
                { name: 'Meditation', value: 'meditation' },
                { name: 'Conversational', value: 'conversational' },
                { name: 'Characters', value: 'characters' },
                { name: 'ASMR', value: 'asmr' },
                { name: 'Audiobook', value: 'audiobook' },
              ],
            },
            {
              id: 'sort',
              name: 'sort',
              displayName: 'Sort By',
              type: 'options',
              required: false,
              options: [
                { name: 'Trending', value: 'trending' },
                { name: 'Latest', value: 'latest' },
                { name: 'Most Users', value: 'usage_count' },
                { name: 'Most Likes', value: 'total_character_count' },
              ],
            },
          ],
        },
        {
          id: 'add_shared_voice',
          name: 'Add Shared Voice',
          value: 'addShared',
          description: 'Add a shared voice to your library',
          action: 'Add shared voice',
          fields: [
            {
              id: 'public_user_id',
              name: 'publicUserId',
              displayName: 'Public User ID',
              type: 'string',
              required: true,
            },
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID',
              type: 'string',
              required: true,
            },
            {
              id: 'new_name',
              name: 'newName',
              displayName: 'New Voice Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // SOUND EFFECTS RESOURCE
    // ============================================
    {
      id: 'soundEffects',
      name: 'Sound Effects',
      value: 'soundEffects',
      description: 'Sound effects generation',
      operations: [
        {
          id: 'generate_sound_effect',
          name: 'Generate Sound Effect',
          value: 'generate',
          description: 'Generate a sound effect from text',
          action: 'Generate sound effect',
          fields: [
            {
              id: 'text',
              name: 'text',
              displayName: 'Description',
              type: 'string',
              required: true,
              description: 'Description of the sound effect',
              typeOptions: {
                rows: 2,
              },
            },
          ],
          optionalFields: [
            {
              id: 'duration_seconds',
              name: 'durationSeconds',
              displayName: 'Duration (seconds)',
              type: 'number',
              required: false,
              description: '0.5 to 22 seconds',
            },
            {
              id: 'prompt_influence',
              name: 'promptInfluence',
              displayName: 'Prompt Influence',
              type: 'number',
              required: false,
              default: 0.3,
              description: 'How closely to follow the prompt (0-1)',
            },
          ],
        },
      ],
    },
    
    // ============================================
    // AUDIO ISOLATION RESOURCE
    // ============================================
    {
      id: 'audioIsolation',
      name: 'Audio Isolation',
      value: 'audioIsolation',
      description: 'Audio isolation and enhancement',
      operations: [
        {
          id: 'isolate_audio',
          name: 'Isolate Audio',
          value: 'isolate',
          description: 'Isolate voice from background noise',
          action: 'Isolate audio',
          fields: [
            {
              id: 'audio',
              name: 'audio',
              displayName: 'Audio (Base64)',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // DUBBING RESOURCE
    // ============================================
    {
      id: 'dubbing',
      name: 'Dubbing',
      value: 'dubbing',
      description: 'Video/audio dubbing operations',
      operations: [
        {
          id: 'create_dubbing',
          name: 'Create Dubbing',
          value: 'create',
          description: 'Create a dubbing project',
          action: 'Create dubbing',
          fields: [
            {
              id: 'target_lang',
              name: 'targetLang',
              displayName: 'Target Language',
              type: 'string',
              required: true,
              description: 'ISO language code (e.g., es, fr, de)',
            },
          ],
          optionalFields: [
            {
              id: 'source_url',
              name: 'sourceUrl',
              displayName: 'Source URL',
              type: 'string',
              required: false,
              description: 'URL of video/audio to dub',
            },
            {
              id: 'source_file',
              name: 'sourceFile',
              displayName: 'Source File (Base64)',
              type: 'string',
              required: false,
            },
            {
              id: 'source_lang',
              name: 'sourceLang',
              displayName: 'Source Language',
              type: 'string',
              required: false,
              description: 'Auto-detected if not specified',
            },
            {
              id: 'num_speakers',
              name: 'numSpeakers',
              displayName: 'Number of Speakers',
              type: 'number',
              required: false,
              default: 0,
              description: '0 for auto-detection',
            },
            {
              id: 'watermark',
              name: 'watermark',
              displayName: 'Add Watermark',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'start_time',
              name: 'startTime',
              displayName: 'Start Time (seconds)',
              type: 'number',
              required: false,
            },
            {
              id: 'end_time',
              name: 'endTime',
              displayName: 'End Time (seconds)',
              type: 'number',
              required: false,
            },
            {
              id: 'highest_resolution',
              name: 'highestResolution',
              displayName: 'Highest Resolution',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'drop_background_audio',
              name: 'dropBackgroundAudio',
              displayName: 'Drop Background Audio',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'use_profanity_filter',
              name: 'useProfanityFilter',
              displayName: 'Use Profanity Filter',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_dubbing',
          name: 'Get Dubbing',
          value: 'get',
          description: 'Get dubbing project status',
          action: 'Get dubbing',
          fields: [
            {
              id: 'dubbing_id',
              name: 'dubbingId',
              displayName: 'Dubbing ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_dubbed_file',
          name: 'Get Dubbed File',
          value: 'getFile',
          description: 'Download dubbed audio/video',
          action: 'Get dubbed file',
          fields: [
            {
              id: 'dubbing_id',
              name: 'dubbingId',
              displayName: 'Dubbing ID',
              type: 'string',
              required: true,
            },
            {
              id: 'language_code',
              name: 'languageCode',
              displayName: 'Language Code',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_dubbing',
          name: 'Delete Dubbing',
          value: 'delete',
          description: 'Delete a dubbing project',
          action: 'Delete dubbing',
          fields: [
            {
              id: 'dubbing_id',
              name: 'dubbingId',
              displayName: 'Dubbing ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // PROJECTS RESOURCE
    // ============================================
    {
      id: 'projects',
      name: 'Projects',
      value: 'projects',
      description: 'Long-form project operations',
      operations: [
        {
          id: 'create_project',
          name: 'Create Project',
          value: 'create',
          description: 'Create a new project',
          action: 'Create project',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Project Name',
              type: 'string',
              required: true,
            },
            {
              id: 'default_title_voice_id',
              name: 'defaultTitleVoiceId',
              displayName: 'Default Title Voice ID',
              type: 'string',
              required: true,
            },
            {
              id: 'default_paragraph_voice_id',
              name: 'defaultParagraphVoiceId',
              displayName: 'Default Paragraph Voice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'default_model_id',
              name: 'defaultModelId',
              displayName: 'Default Model',
              type: 'options',
              required: false,
              options: [
                { name: 'Eleven Multilingual v2', value: 'eleven_multilingual_v2' },
                { name: 'Eleven Turbo v2', value: 'eleven_turbo_v2' },
              ],
            },
            {
              id: 'from_url',
              name: 'fromUrl',
              displayName: 'From URL',
              type: 'string',
              required: false,
              description: 'URL to scrape content from',
            },
            {
              id: 'from_document',
              name: 'fromDocument',
              displayName: 'From Document (Base64)',
              type: 'string',
              required: false,
            },
            {
              id: 'quality_preset',
              name: 'qualityPreset',
              displayName: 'Quality Preset',
              type: 'options',
              required: false,
              options: [
                { name: 'Standard', value: 'standard' },
                { name: 'High', value: 'high' },
                { name: 'Ultra', value: 'ultra' },
              ],
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'author',
              name: 'author',
              displayName: 'Author',
              type: 'string',
              required: false,
            },
            {
              id: 'isbn_number',
              name: 'isbnNumber',
              displayName: 'ISBN',
              type: 'string',
              required: false,
            },
            {
              id: 'acx_volume_normalization',
              name: 'acxVolumeNormalization',
              displayName: 'ACX Volume Normalization',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_project',
          name: 'Get Project',
          value: 'get',
          description: 'Get project details',
          action: 'Get project',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_projects',
          name: 'List Projects',
          value: 'getMany',
          description: 'List all projects',
          action: 'List projects',
          fields: [],
          optionalFields: [],
        },
        {
          id: 'delete_project',
          name: 'Delete Project',
          value: 'delete',
          description: 'Delete a project',
          action: 'Delete project',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'convert_project',
          name: 'Convert Project',
          value: 'convert',
          description: 'Convert project to audio',
          action: 'Convert project',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_project_snapshots',
          name: 'Get Snapshots',
          value: 'getSnapshots',
          description: 'Get project audio snapshots',
          action: 'Get snapshots',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'stream_snapshot_audio',
          name: 'Stream Snapshot Audio',
          value: 'streamSnapshot',
          description: 'Stream audio from a snapshot',
          action: 'Stream snapshot audio',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID',
              type: 'string',
              required: true,
            },
            {
              id: 'project_snapshot_id',
              name: 'projectSnapshotId',
              displayName: 'Snapshot ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // HISTORY RESOURCE
    // ============================================
    {
      id: 'history',
      name: 'History',
      value: 'history',
      description: 'Generation history operations',
      operations: [
        {
          id: 'get_history',
          name: 'Get History',
          value: 'getMany',
          description: 'Get generation history',
          action: 'Get history',
          fields: [],
          optionalFields: [
            {
              id: 'page_size',
              name: 'pageSize',
              displayName: 'Page Size',
              type: 'number',
              required: false,
              default: 100,
            },
            {
              id: 'voice_id',
              name: 'voiceId',
              displayName: 'Voice ID Filter',
              type: 'string',
              required: false,
            },
            {
              id: 'start_after_history_item_id',
              name: 'startAfterHistoryItemId',
              displayName: 'Start After Item ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_history_item',
          name: 'Get History Item',
          value: 'get',
          description: 'Get specific history item',
          action: 'Get history item',
          fields: [
            {
              id: 'history_item_id',
              name: 'historyItemId',
              displayName: 'History Item ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_history_audio',
          name: 'Get History Audio',
          value: 'getAudio',
          description: 'Download audio from history',
          action: 'Get history audio',
          fields: [
            {
              id: 'history_item_id',
              name: 'historyItemId',
              displayName: 'History Item ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_history_item',
          name: 'Delete History Item',
          value: 'delete',
          description: 'Delete history item',
          action: 'Delete history item',
          fields: [
            {
              id: 'history_item_id',
              name: 'historyItemId',
              displayName: 'History Item ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'download_history',
          name: 'Download History',
          value: 'download',
          description: 'Download multiple history items',
          action: 'Download history',
          fields: [
            {
              id: 'history_item_ids',
              name: 'historyItemIds',
              displayName: 'History Item IDs',
              type: 'string',
              required: true,
              description: 'Comma-separated IDs',
            },
          ],
          optionalFields: [
            {
              id: 'output_format',
              name: 'outputFormat',
              displayName: 'Output Format',
              type: 'options',
              required: false,
              options: [
                { name: 'MP3 ZIP', value: 'mp3_44100_128' },
                { name: 'PCM ZIP', value: 'pcm_44100' },
              ],
            },
          ],
        },
      ],
    },
    
    // ============================================
    // USER RESOURCE
    // ============================================
    {
      id: 'user',
      name: 'User',
      value: 'user',
      description: 'User account operations',
      operations: [
        {
          id: 'get_user_info',
          name: 'Get User Info',
          value: 'getInfo',
          description: 'Get user account information',
          action: 'Get user info',
          fields: [],
          optionalFields: [],
        },
        {
          id: 'get_subscription',
          name: 'Get Subscription',
          value: 'getSubscription',
          description: 'Get subscription details',
          action: 'Get subscription',
          fields: [],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // MODELS RESOURCE
    // ============================================
    {
      id: 'models',
      name: 'Models',
      value: 'models',
      description: 'Model information',
      operations: [
        {
          id: 'list_models',
          name: 'List Models',
          value: 'getMany',
          description: 'List available models',
          action: 'List models',
          fields: [],
          optionalFields: [],
        },
      ],
    },
  ],
};
