/**
 * Firebase n8n-style Schema
 * 
 * Comprehensive Firebase operations (Firestore, Auth, Realtime DB, Storage)
 */

import { N8nAppSchema } from './types';

export const firebaseSchema: N8nAppSchema = {
  id: 'firebase',
  name: 'Firebase',
  description: 'Firebase platform services',
  version: '1.0.0',
  color: '#FFCA28',
  icon: 'firebase',
  group: ['database'],
  
  credentials: [
    {
      name: 'firebaseApi',
      displayName: 'Firebase Admin',
      required: true,
      type: 'serviceAccount',
      properties: [
        {
          name: 'projectId',
          displayName: 'Project ID',
          type: 'string',
          required: true,
        },
        {
          name: 'serviceAccountJson',
          displayName: 'Service Account JSON',
          type: 'json',
          required: true,
          typeOptions: {
            rows: 10,
          },
        },
        {
          name: 'databaseURL',
          displayName: 'Database URL',
          type: 'string',
          required: false,
          description: 'Required for Realtime Database',
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // FIRESTORE DOCUMENT RESOURCE
    // ============================================
    {
      id: 'firestoreDocument',
      name: 'Firestore Document',
      value: 'firestoreDocument',
      description: 'Firestore documents',
      operations: [
        {
          id: 'create_document',
          name: 'Create Document',
          value: 'create',
          description: 'Create a new document',
          action: 'Create a document',
          fields: [
            {
              id: 'collection',
              name: 'collection',
              displayName: 'Collection Path',
              type: 'string',
              required: true,
              placeholder: 'users',
            },
            {
              id: 'data',
              name: 'data',
              displayName: 'Document Data',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'document_id',
              name: 'documentId',
              displayName: 'Document ID',
              type: 'string',
              required: false,
              description: 'Leave empty for auto-generated ID',
            },
          ],
        },
        {
          id: 'get_document',
          name: 'Get Document',
          value: 'get',
          description: 'Get a document by ID',
          action: 'Retrieve a document',
          fields: [
            {
              id: 'collection',
              name: 'collection',
              displayName: 'Collection Path',
              type: 'string',
              required: true,
            },
            {
              id: 'document_id',
              name: 'documentId',
              displayName: 'Document ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_documents',
          name: 'Get Documents',
          value: 'getMany',
          description: 'Get documents from a collection',
          action: 'List documents',
          fields: [
            {
              id: 'collection',
              name: 'collection',
              displayName: 'Collection Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'where',
              name: 'where',
              displayName: 'Where Conditions',
              type: 'json',
              required: false,
              description: 'Array of conditions: [{"field": "status", "operator": "==", "value": "active"}]',
            },
            {
              id: 'order_by',
              name: 'orderBy',
              displayName: 'Order By',
              type: 'string',
              required: false,
            },
            {
              id: 'order_direction',
              name: 'orderDirection',
              displayName: 'Order Direction',
              type: 'options',
              required: false,
              default: 'asc',
              options: [
                { name: 'Ascending', value: 'asc' },
                { name: 'Descending', value: 'desc' },
              ],
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
            },
            {
              id: 'start_after',
              name: 'startAfter',
              displayName: 'Start After',
              type: 'string',
              required: false,
              description: 'Document ID for pagination',
            },
          ],
        },
        {
          id: 'update_document',
          name: 'Update Document',
          value: 'update',
          description: 'Update a document',
          action: 'Update a document',
          fields: [
            {
              id: 'collection',
              name: 'collection',
              displayName: 'Collection Path',
              type: 'string',
              required: true,
            },
            {
              id: 'document_id',
              name: 'documentId',
              displayName: 'Document ID',
              type: 'string',
              required: true,
            },
            {
              id: 'data',
              name: 'data',
              displayName: 'Update Data',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'merge',
              name: 'merge',
              displayName: 'Merge',
              type: 'boolean',
              required: false,
              default: true,
              description: 'Merge with existing data instead of replacing',
            },
          ],
        },
        {
          id: 'delete_document',
          name: 'Delete Document',
          value: 'delete',
          description: 'Delete a document',
          action: 'Delete a document',
          fields: [
            {
              id: 'collection',
              name: 'collection',
              displayName: 'Collection Path',
              type: 'string',
              required: true,
            },
            {
              id: 'document_id',
              name: 'documentId',
              displayName: 'Document ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'query_documents',
          name: 'Query Documents',
          value: 'query',
          description: 'Query documents with advanced filters',
          action: 'Query documents',
          fields: [
            {
              id: 'collection',
              name: 'collection',
              displayName: 'Collection Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'where_conditions',
              name: 'whereConditions',
              displayName: 'Where Conditions',
              type: 'json',
              required: false,
              description: 'Array: [{"field": "name", "operator": "==", "value": "John"}]',
            },
            {
              id: 'order_by',
              name: 'orderBy',
              displayName: 'Order By',
              type: 'json',
              required: false,
              description: 'Array: [{"field": "createdAt", "direction": "desc"}]',
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
            },
            {
              id: 'offset',
              name: 'offset',
              displayName: 'Offset',
              type: 'number',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // FIRESTORE COLLECTION RESOURCE
    // ============================================
    {
      id: 'firestoreCollection',
      name: 'Firestore Collection',
      value: 'firestoreCollection',
      description: 'Firestore collections',
      operations: [
        {
          id: 'get_collections',
          name: 'Get Collections',
          value: 'getMany',
          description: 'List all collections',
          action: 'List collections',
          fields: [],
          optionalFields: [
            {
              id: 'parent_path',
              name: 'parentPath',
              displayName: 'Parent Document Path',
              type: 'string',
              required: false,
              description: 'For subcollections, e.g., users/userId',
            },
          ],
        },
        {
          id: 'delete_collection',
          name: 'Delete Collection',
          value: 'delete',
          description: 'Delete a collection and all documents',
          action: 'Delete a collection',
          fields: [
            {
              id: 'collection',
              name: 'collection',
              displayName: 'Collection Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'batch_size',
              name: 'batchSize',
              displayName: 'Batch Size',
              type: 'number',
              required: false,
              default: 500,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // REALTIME DATABASE RESOURCE
    // ============================================
    {
      id: 'realtimeDb',
      name: 'Realtime Database',
      value: 'realtimeDb',
      description: 'Firebase Realtime Database',
      operations: [
        {
          id: 'set_data',
          name: 'Set Data',
          value: 'set',
          description: 'Set data at a path',
          action: 'Set data',
          fields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: true,
              placeholder: '/users/user123',
            },
            {
              id: 'data',
              name: 'data',
              displayName: 'Data',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_data',
          name: 'Get Data',
          value: 'get',
          description: 'Get data from a path',
          action: 'Get data',
          fields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'shallow',
              name: 'shallow',
              displayName: 'Shallow',
              type: 'boolean',
              required: false,
              default: false,
              description: 'Return only keys, not values',
            },
          ],
        },
        {
          id: 'push_data',
          name: 'Push Data',
          value: 'push',
          description: 'Push data to a list',
          action: 'Push data',
          fields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: true,
            },
            {
              id: 'data',
              name: 'data',
              displayName: 'Data',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_data',
          name: 'Update Data',
          value: 'update',
          description: 'Update data at a path',
          action: 'Update data',
          fields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: true,
            },
            {
              id: 'data',
              name: 'data',
              displayName: 'Data',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'remove_data',
          name: 'Remove Data',
          value: 'remove',
          description: 'Remove data at a path',
          action: 'Remove data',
          fields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'query_data',
          name: 'Query Data',
          value: 'query',
          description: 'Query data with filters',
          action: 'Query data',
          fields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'order_by_child',
              name: 'orderByChild',
              displayName: 'Order By Child',
              type: 'string',
              required: false,
            },
            {
              id: 'order_by_key',
              name: 'orderByKey',
              displayName: 'Order By Key',
              type: 'boolean',
              required: false,
            },
            {
              id: 'order_by_value',
              name: 'orderByValue',
              displayName: 'Order By Value',
              type: 'boolean',
              required: false,
            },
            {
              id: 'equal_to',
              name: 'equalTo',
              displayName: 'Equal To',
              type: 'string',
              required: false,
            },
            {
              id: 'start_at',
              name: 'startAt',
              displayName: 'Start At',
              type: 'string',
              required: false,
            },
            {
              id: 'end_at',
              name: 'endAt',
              displayName: 'End At',
              type: 'string',
              required: false,
            },
            {
              id: 'limit_to_first',
              name: 'limitToFirst',
              displayName: 'Limit to First',
              type: 'number',
              required: false,
            },
            {
              id: 'limit_to_last',
              name: 'limitToLast',
              displayName: 'Limit to Last',
              type: 'number',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // AUTH RESOURCE
    // ============================================
    {
      id: 'auth',
      name: 'Authentication',
      value: 'auth',
      description: 'Firebase Authentication',
      operations: [
        {
          id: 'create_user',
          name: 'Create User',
          value: 'createUser',
          description: 'Create a new user',
          action: 'Create a user',
          fields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: true,
            },
            {
              id: 'password',
              name: 'password',
              displayName: 'Password',
              type: 'string',
              required: true,
              typeOptions: {
                password: true,
              },
            },
          ],
          optionalFields: [
            {
              id: 'display_name',
              name: 'displayName',
              displayName: 'Display Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone_number',
              name: 'phoneNumber',
              displayName: 'Phone Number',
              type: 'string',
              required: false,
            },
            {
              id: 'photo_url',
              name: 'photoURL',
              displayName: 'Photo URL',
              type: 'string',
              required: false,
            },
            {
              id: 'email_verified',
              name: 'emailVerified',
              displayName: 'Email Verified',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'disabled',
              name: 'disabled',
              displayName: 'Disabled',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_user',
          name: 'Get User',
          value: 'getUser',
          description: 'Get a user by UID',
          action: 'Retrieve a user',
          fields: [
            {
              id: 'uid',
              name: 'uid',
              displayName: 'User UID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_user_by_email',
          name: 'Get User by Email',
          value: 'getUserByEmail',
          description: 'Get a user by email',
          action: 'Get user by email',
          fields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_users',
          name: 'Get Users',
          value: 'getUsers',
          description: 'List all users',
          action: 'List users',
          fields: [],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 1000,
            },
            {
              id: 'page_token',
              name: 'pageToken',
              displayName: 'Page Token',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'update_user',
          name: 'Update User',
          value: 'updateUser',
          description: 'Update a user',
          action: 'Update a user',
          fields: [
            {
              id: 'uid',
              name: 'uid',
              displayName: 'User UID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'password',
              name: 'password',
              displayName: 'New Password',
              type: 'string',
              required: false,
              typeOptions: {
                password: true,
              },
            },
            {
              id: 'display_name',
              name: 'displayName',
              displayName: 'Display Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone_number',
              name: 'phoneNumber',
              displayName: 'Phone Number',
              type: 'string',
              required: false,
            },
            {
              id: 'photo_url',
              name: 'photoURL',
              displayName: 'Photo URL',
              type: 'string',
              required: false,
            },
            {
              id: 'email_verified',
              name: 'emailVerified',
              displayName: 'Email Verified',
              type: 'boolean',
              required: false,
            },
            {
              id: 'disabled',
              name: 'disabled',
              displayName: 'Disabled',
              type: 'boolean',
              required: false,
            },
          ],
        },
        {
          id: 'delete_user',
          name: 'Delete User',
          value: 'deleteUser',
          description: 'Delete a user',
          action: 'Delete a user',
          fields: [
            {
              id: 'uid',
              name: 'uid',
              displayName: 'User UID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'set_custom_claims',
          name: 'Set Custom Claims',
          value: 'setCustomClaims',
          description: 'Set custom claims for a user',
          action: 'Set custom claims',
          fields: [
            {
              id: 'uid',
              name: 'uid',
              displayName: 'User UID',
              type: 'string',
              required: true,
            },
            {
              id: 'custom_claims',
              name: 'customClaims',
              displayName: 'Custom Claims',
              type: 'json',
              required: true,
              description: 'JSON object with custom claims',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'generate_email_verification_link',
          name: 'Generate Email Verification Link',
          value: 'generateEmailVerificationLink',
          description: 'Generate email verification link',
          action: 'Generate verification link',
          fields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'action_code_settings',
              name: 'actionCodeSettings',
              displayName: 'Action Code Settings',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'generate_password_reset_link',
          name: 'Generate Password Reset Link',
          value: 'generatePasswordResetLink',
          description: 'Generate password reset link',
          action: 'Generate password reset link',
          fields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'action_code_settings',
              name: 'actionCodeSettings',
              displayName: 'Action Code Settings',
              type: 'json',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // STORAGE RESOURCE
    // ============================================
    {
      id: 'storage',
      name: 'Cloud Storage',
      value: 'storage',
      description: 'Firebase Cloud Storage',
      operations: [
        {
          id: 'upload_file',
          name: 'Upload File',
          value: 'upload',
          description: 'Upload a file to storage',
          action: 'Upload a file',
          fields: [
            {
              id: 'bucket',
              name: 'bucket',
              displayName: 'Bucket Name',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
              placeholder: 'uploads/file.png',
            },
            {
              id: 'data',
              name: 'data',
              displayName: 'File Data',
              type: 'string',
              required: true,
              description: 'Base64 encoded file data',
            },
          ],
          optionalFields: [
            {
              id: 'content_type',
              name: 'contentType',
              displayName: 'Content Type',
              type: 'string',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata',
              type: 'json',
              required: false,
            },
            {
              id: 'make_public',
              name: 'makePublic',
              displayName: 'Make Public',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'download_file',
          name: 'Download File',
          value: 'download',
          description: 'Download a file from storage',
          action: 'Download a file',
          fields: [
            {
              id: 'bucket',
              name: 'bucket',
              displayName: 'Bucket Name',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_download_url',
          name: 'Get Download URL',
          value: 'getDownloadUrl',
          description: 'Get a signed download URL',
          action: 'Get download URL',
          fields: [
            {
              id: 'bucket',
              name: 'bucket',
              displayName: 'Bucket Name',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'expires',
              name: 'expires',
              displayName: 'Expires In (ms)',
              type: 'number',
              required: false,
              default: 3600000,
            },
          ],
        },
        {
          id: 'delete_file',
          name: 'Delete File',
          value: 'delete',
          description: 'Delete a file from storage',
          action: 'Delete a file',
          fields: [
            {
              id: 'bucket',
              name: 'bucket',
              displayName: 'Bucket Name',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_files',
          name: 'List Files',
          value: 'list',
          description: 'List files in a directory',
          action: 'List files',
          fields: [
            {
              id: 'bucket',
              name: 'bucket',
              displayName: 'Bucket Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'prefix',
              name: 'prefix',
              displayName: 'Prefix',
              type: 'string',
              required: false,
              description: 'Directory path prefix',
            },
            {
              id: 'delimiter',
              name: 'delimiter',
              displayName: 'Delimiter',
              type: 'string',
              required: false,
              default: '/',
            },
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_metadata',
          name: 'Get File Metadata',
          value: 'getMetadata',
          description: 'Get file metadata',
          action: 'Get file metadata',
          fields: [
            {
              id: 'bucket',
              name: 'bucket',
              displayName: 'Bucket Name',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CLOUD MESSAGING (FCM) RESOURCE
    // ============================================
    {
      id: 'messaging',
      name: 'Cloud Messaging',
      value: 'messaging',
      description: 'Firebase Cloud Messaging (FCM)',
      operations: [
        {
          id: 'send_message',
          name: 'Send Message',
          value: 'send',
          description: 'Send a push notification',
          action: 'Send message',
          fields: [
            {
              id: 'token',
              name: 'token',
              displayName: 'Device Token',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'image',
              name: 'image',
              displayName: 'Image URL',
              type: 'string',
              required: false,
            },
            {
              id: 'data',
              name: 'data',
              displayName: 'Data Payload',
              type: 'json',
              required: false,
            },
            {
              id: 'click_action',
              name: 'clickAction',
              displayName: 'Click Action',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'send_to_topic',
          name: 'Send to Topic',
          value: 'sendToTopic',
          description: 'Send a message to a topic',
          action: 'Send to topic',
          fields: [
            {
              id: 'topic',
              name: 'topic',
              displayName: 'Topic',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'data',
              name: 'data',
              displayName: 'Data Payload',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'subscribe_to_topic',
          name: 'Subscribe to Topic',
          value: 'subscribeToTopic',
          description: 'Subscribe tokens to a topic',
          action: 'Subscribe to topic',
          fields: [
            {
              id: 'tokens',
              name: 'tokens',
              displayName: 'Device Tokens',
              type: 'string',
              required: true,
              description: 'Comma-separated device tokens',
            },
            {
              id: 'topic',
              name: 'topic',
              displayName: 'Topic',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'unsubscribe_from_topic',
          name: 'Unsubscribe from Topic',
          value: 'unsubscribeFromTopic',
          description: 'Unsubscribe tokens from a topic',
          action: 'Unsubscribe from topic',
          fields: [
            {
              id: 'tokens',
              name: 'tokens',
              displayName: 'Device Tokens',
              type: 'string',
              required: true,
              description: 'Comma-separated device tokens',
            },
            {
              id: 'topic',
              name: 'topic',
              displayName: 'Topic',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
