/**
 * Freshsales n8n-style Schema
 * 
 * Comprehensive Freshsales CRM API operations
 */

import { N8nAppSchema } from './types';

export const freshsalesSchema: N8nAppSchema = {
  id: 'freshsales',
  name: 'Freshsales',
  description: 'Freshsales CRM automation',
  version: '1.0.0',
  color: '#13C26B',
  icon: 'freshsales',
  group: ['crm'],
  
  credentials: [
    {
      name: 'freshsalesApi',
      displayName: 'Freshsales API Key',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'apiKey',
          displayName: 'API Key',
          type: 'string',
          required: true,
        },
        {
          name: 'domain',
          displayName: 'Domain',
          type: 'string',
          required: true,
          placeholder: 'yourcompany.freshsales.io',
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // LEAD RESOURCE
    // ============================================
    {
      id: 'lead',
      name: 'Lead',
      value: 'lead',
      description: 'Sales leads',
      operations: [
        {
          id: 'create_lead',
          name: 'Create Lead',
          value: 'create',
          description: 'Create a new lead',
          action: 'Create a new lead',
          fields: [
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'work_number',
              name: 'work_number',
              displayName: 'Work Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'mobile_number',
              name: 'mobile_number',
              displayName: 'Mobile',
              type: 'string',
              required: false,
            },
            {
              id: 'job_title',
              name: 'job_title',
              displayName: 'Job Title',
              type: 'string',
              required: false,
            },
            {
              id: 'company',
              name: 'company',
              displayName: 'Company Name',
              type: 'string',
              required: false,
            },
            {
              id: 'lead_source_id',
              name: 'lead_source_id',
              displayName: 'Lead Source ID',
              type: 'number',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner ID',
              type: 'number',
              required: false,
            },
            {
              id: 'lead_stage_id',
              name: 'lead_stage_id',
              displayName: 'Lead Stage ID',
              type: 'number',
              required: false,
            },
            {
              id: 'city',
              name: 'city',
              displayName: 'City',
              type: 'string',
              required: false,
            },
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'string',
              required: false,
            },
            {
              id: 'zipcode',
              name: 'zipcode',
              displayName: 'Zip Code',
              type: 'string',
              required: false,
            },
            {
              id: 'country',
              name: 'country',
              displayName: 'Country',
              type: 'string',
              required: false,
            },
            {
              id: 'medium',
              name: 'medium',
              displayName: 'Medium',
              type: 'string',
              required: false,
            },
            {
              id: 'campaign_id',
              name: 'campaign_id',
              displayName: 'Campaign ID',
              type: 'number',
              required: false,
            },
            {
              id: 'custom_fields',
              name: 'custom_field',
              displayName: 'Custom Fields (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_lead',
          name: 'Get Lead',
          value: 'get',
          description: 'Get a lead by ID',
          action: 'Retrieve a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_leads',
          name: 'Get Leads',
          value: 'getMany',
          description: 'Get all leads',
          action: 'List all leads',
          fields: [],
          optionalFields: [
            {
              id: 'view_id',
              name: 'view_id',
              displayName: 'View ID',
              type: 'number',
              required: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 25,
            },
          ],
        },
        {
          id: 'update_lead',
          name: 'Update Lead',
          value: 'update',
          description: 'Update a lead',
          action: 'Update a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'lead_stage_id',
              name: 'lead_stage_id',
              displayName: 'Lead Stage ID',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'delete_lead',
          name: 'Delete Lead',
          value: 'delete',
          description: 'Delete a lead',
          action: 'Delete a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'convert_lead',
          name: 'Convert Lead',
          value: 'convert',
          description: 'Convert lead to contact',
          action: 'Convert a lead to contact',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CONTACT RESOURCE
    // ============================================
    {
      id: 'contact',
      name: 'Contact',
      value: 'contact',
      description: 'Contacts',
      operations: [
        {
          id: 'create_contact',
          name: 'Create Contact',
          value: 'create',
          description: 'Create a new contact',
          action: 'Create a new contact',
          fields: [
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'work_number',
              name: 'work_number',
              displayName: 'Work Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'mobile_number',
              name: 'mobile_number',
              displayName: 'Mobile',
              type: 'string',
              required: false,
            },
            {
              id: 'job_title',
              name: 'job_title',
              displayName: 'Job Title',
              type: 'string',
              required: false,
            },
            {
              id: 'sales_account_id',
              name: 'sales_account_id',
              displayName: 'Account ID',
              type: 'number',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner ID',
              type: 'number',
              required: false,
            },
            {
              id: 'lifecycle_stage_id',
              name: 'lifecycle_stage_id',
              displayName: 'Lifecycle Stage ID',
              type: 'number',
              required: false,
            },
            {
              id: 'contact_status_id',
              name: 'contact_status_id',
              displayName: 'Contact Status ID',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_contact',
          name: 'Get Contact',
          value: 'get',
          description: 'Get a contact by ID',
          action: 'Retrieve a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_contacts',
          name: 'Get Contacts',
          value: 'getMany',
          description: 'Get all contacts',
          action: 'List all contacts',
          fields: [],
          optionalFields: [
            {
              id: 'view_id',
              name: 'view_id',
              displayName: 'View ID',
              type: 'number',
              required: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 25,
            },
          ],
        },
        {
          id: 'update_contact',
          name: 'Update Contact',
          value: 'update',
          description: 'Update a contact',
          action: 'Update a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_contact',
          name: 'Delete Contact',
          value: 'delete',
          description: 'Delete a contact',
          action: 'Delete a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ACCOUNT RESOURCE
    // ============================================
    {
      id: 'account',
      name: 'Account',
      value: 'account',
      description: 'Sales accounts/companies',
      operations: [
        {
          id: 'create_account',
          name: 'Create Account',
          value: 'create',
          description: 'Create a new account',
          action: 'Create a new sales account',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Account Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'website',
              name: 'website',
              displayName: 'Website',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'industry_type_id',
              name: 'industry_type_id',
              displayName: 'Industry Type ID',
              type: 'number',
              required: false,
            },
            {
              id: 'business_type_id',
              name: 'business_type_id',
              displayName: 'Business Type ID',
              type: 'number',
              required: false,
            },
            {
              id: 'number_of_employees',
              name: 'number_of_employees',
              displayName: 'Number of Employees',
              type: 'number',
              required: false,
            },
            {
              id: 'annual_revenue',
              name: 'annual_revenue',
              displayName: 'Annual Revenue',
              type: 'number',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner ID',
              type: 'number',
              required: false,
            },
            {
              id: 'city',
              name: 'city',
              displayName: 'City',
              type: 'string',
              required: false,
            },
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'string',
              required: false,
            },
            {
              id: 'country',
              name: 'country',
              displayName: 'Country',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_account',
          name: 'Get Account',
          value: 'get',
          description: 'Get an account by ID',
          action: 'Retrieve an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_accounts',
          name: 'Get Accounts',
          value: 'getMany',
          description: 'Get all accounts',
          action: 'List all accounts',
          fields: [],
          optionalFields: [
            {
              id: 'view_id',
              name: 'view_id',
              displayName: 'View ID',
              type: 'number',
              required: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 25,
            },
          ],
        },
        {
          id: 'update_account',
          name: 'Update Account',
          value: 'update',
          description: 'Update an account',
          action: 'Update an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Account Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_account',
          name: 'Delete Account',
          value: 'delete',
          description: 'Delete an account',
          action: 'Delete an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // DEAL RESOURCE
    // ============================================
    {
      id: 'deal',
      name: 'Deal',
      value: 'deal',
      description: 'Sales deals/opportunities',
      operations: [
        {
          id: 'create_deal',
          name: 'Create Deal',
          value: 'create',
          description: 'Create a new deal',
          action: 'Create a new deal',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Deal Name',
              type: 'string',
              required: true,
            },
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'deal_stage_id',
              name: 'deal_stage_id',
              displayName: 'Deal Stage ID',
              type: 'number',
              required: false,
            },
            {
              id: 'deal_pipeline_id',
              name: 'deal_pipeline_id',
              displayName: 'Deal Pipeline ID',
              type: 'number',
              required: false,
            },
            {
              id: 'expected_close',
              name: 'expected_close',
              displayName: 'Expected Close Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'probability',
              name: 'deal_probability',
              displayName: 'Probability (%)',
              type: 'number',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner ID',
              type: 'number',
              required: false,
            },
            {
              id: 'sales_account_id',
              name: 'sales_account_id',
              displayName: 'Account ID',
              type: 'number',
              required: false,
            },
            {
              id: 'contacts',
              name: 'contacts',
              displayName: 'Contact IDs (JSON array)',
              type: 'json',
              required: false,
            },
            {
              id: 'currency',
              name: 'base_currency_amount',
              displayName: 'Currency Amount',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_deal',
          name: 'Get Deal',
          value: 'get',
          description: 'Get a deal by ID',
          action: 'Retrieve a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_deals',
          name: 'Get Deals',
          value: 'getMany',
          description: 'Get all deals',
          action: 'List all deals',
          fields: [],
          optionalFields: [
            {
              id: 'view_id',
              name: 'view_id',
              displayName: 'View ID',
              type: 'number',
              required: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 25,
            },
          ],
        },
        {
          id: 'update_deal',
          name: 'Update Deal',
          value: 'update',
          description: 'Update a deal',
          action: 'Update a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Deal Name',
              type: 'string',
              required: false,
            },
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount',
              type: 'number',
              required: false,
            },
            {
              id: 'deal_stage_id',
              name: 'deal_stage_id',
              displayName: 'Deal Stage ID',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'delete_deal',
          name: 'Delete Deal',
          value: 'delete',
          description: 'Delete a deal',
          action: 'Delete a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // TASK RESOURCE
    // ============================================
    {
      id: 'task',
      name: 'Task',
      value: 'task',
      description: 'Tasks and activities',
      operations: [
        {
          id: 'create_task',
          name: 'Create Task',
          value: 'create',
          description: 'Create a new task',
          action: 'Create a new task',
          fields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'due_date',
              name: 'due_date',
              displayName: 'Due Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner ID',
              type: 'number',
              required: false,
            },
            {
              id: 'targetable_id',
              name: 'targetable_id',
              displayName: 'Related Record ID',
              type: 'number',
              required: false,
            },
            {
              id: 'targetable_type',
              name: 'targetable_type',
              displayName: 'Related Record Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Contact', value: 'Contact' },
                { name: 'Lead', value: 'Lead' },
                { name: 'Sales Account', value: 'SalesAccount' },
                { name: 'Deal', value: 'Deal' },
              ],
            },
            {
              id: 'task_type_id',
              name: 'task_type_id',
              displayName: 'Task Type ID',
              type: 'number',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 0,
              options: [
                { name: 'Open', value: 0 },
                { name: 'Completed', value: 1 },
              ],
            },
          ],
        },
        {
          id: 'get_tasks',
          name: 'Get Tasks',
          value: 'getMany',
          description: 'Get all tasks',
          action: 'List all tasks',
          fields: [],
          optionalFields: [
            {
              id: 'filter',
              name: 'filter',
              displayName: 'Filter',
              type: 'options',
              required: false,
              options: [
                { name: 'Open', value: 'open' },
                { name: 'Due Today', value: 'due_today' },
                { name: 'Due Tomorrow', value: 'due_tomorrow' },
                { name: 'Overdue', value: 'overdue' },
                { name: 'Completed', value: 'completed' },
              ],
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 25,
            },
          ],
        },
        {
          id: 'update_task',
          name: 'Update Task',
          value: 'update',
          description: 'Update a task',
          action: 'Update a task',
          fields: [
            {
              id: 'task_id',
              name: 'taskId',
              displayName: 'Task ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Open', value: 0 },
                { name: 'Completed', value: 1 },
              ],
            },
          ],
        },
        {
          id: 'delete_task',
          name: 'Delete Task',
          value: 'delete',
          description: 'Delete a task',
          action: 'Delete a task',
          fields: [
            {
              id: 'task_id',
              name: 'taskId',
              displayName: 'Task ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // NOTE RESOURCE
    // ============================================
    {
      id: 'note',
      name: 'Note',
      value: 'note',
      description: 'Notes attached to records',
      operations: [
        {
          id: 'create_note',
          name: 'Create Note',
          value: 'create',
          description: 'Create a new note',
          action: 'Create a new note',
          fields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Note Content',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'targetable_id',
              name: 'targetable_id',
              displayName: 'Related Record ID',
              type: 'number',
              required: true,
            },
            {
              id: 'targetable_type',
              name: 'targetable_type',
              displayName: 'Related Record Type',
              type: 'options',
              required: true,
              options: [
                { name: 'Contact', value: 'Contact' },
                { name: 'Lead', value: 'Lead' },
                { name: 'Sales Account', value: 'SalesAccount' },
                { name: 'Deal', value: 'Deal' },
              ],
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_note',
          name: 'Delete Note',
          value: 'delete',
          description: 'Delete a note',
          action: 'Delete a note',
          fields: [
            {
              id: 'note_id',
              name: 'noteId',
              displayName: 'Note ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
