/**
 * GitHub n8n-style Schema
 * 
 * Comprehensive GitHub API operations
 */

import { N8nAppSchema } from './types';

export const githubSchema: N8nAppSchema = {
  id: 'github',
  name: 'GitHub',
  description: 'GitHub version control and collaboration',
  version: '1.0.0',
  color: '#24292F',
  icon: 'github',
  group: ['developer'],
  
  credentials: [
    {
      name: 'githubOAuth2',
      displayName: 'GitHub OAuth2',
      required: true,
      type: 'oauth2',
      properties: [
        {
          name: 'accessToken',
          displayName: 'Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
    {
      name: 'githubToken',
      displayName: 'GitHub Personal Access Token',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'token',
          displayName: 'Personal Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // REPOSITORY RESOURCE
    // ============================================
    {
      id: 'repository',
      name: 'Repository',
      value: 'repository',
      description: 'Repository operations',
      operations: [
        {
          id: 'create_repo',
          name: 'Create Repository',
          value: 'create',
          description: 'Create a new repository',
          action: 'Create repository',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Repository Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'private',
              name: 'private',
              displayName: 'Private',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'auto_init',
              name: 'autoInit',
              displayName: 'Auto Initialize',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'gitignore_template',
              name: 'gitignoreTemplate',
              displayName: 'Gitignore Template',
              type: 'string',
              required: false,
            },
            {
              id: 'license_template',
              name: 'licenseTemplate',
              displayName: 'License Template',
              type: 'string',
              required: false,
            },
            {
              id: 'organization',
              name: 'organization',
              displayName: 'Organization',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_repo',
          name: 'Get Repository',
          value: 'get',
          description: 'Get repository information',
          action: 'Get repository',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_repos',
          name: 'List Repositories',
          value: 'getMany',
          description: 'List repositories',
          action: 'List repositories',
          fields: [],
          optionalFields: [
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: false,
              default: 'all',
              options: [
                { name: 'All', value: 'all' },
                { name: 'Owner', value: 'owner' },
                { name: 'Public', value: 'public' },
                { name: 'Private', value: 'private' },
                { name: 'Member', value: 'member' },
              ],
            },
            {
              id: 'sort',
              name: 'sort',
              displayName: 'Sort',
              type: 'options',
              required: false,
              options: [
                { name: 'Created', value: 'created' },
                { name: 'Updated', value: 'updated' },
                { name: 'Pushed', value: 'pushed' },
                { name: 'Full Name', value: 'full_name' },
              ],
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 30,
            },
          ],
        },
        {
          id: 'fork_repo',
          name: 'Fork Repository',
          value: 'fork',
          description: 'Fork a repository',
          action: 'Fork repository',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'organization',
              name: 'organization',
              displayName: 'Organization',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_repo',
          name: 'Delete Repository',
          value: 'delete',
          description: 'Delete a repository',
          action: 'Delete repository',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ISSUE RESOURCE
    // ============================================
    {
      id: 'issue',
      name: 'Issue',
      value: 'issue',
      description: 'Issue operations',
      operations: [
        {
          id: 'create_issue',
          name: 'Create Issue',
          value: 'create',
          description: 'Create a new issue',
          action: 'Create issue',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels',
              type: 'string',
              required: false,
              description: 'Comma-separated label names',
            },
            {
              id: 'assignees',
              name: 'assignees',
              displayName: 'Assignees',
              type: 'string',
              required: false,
              description: 'Comma-separated usernames',
            },
            {
              id: 'milestone',
              name: 'milestone',
              displayName: 'Milestone Number',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_issue',
          name: 'Get Issue',
          value: 'get',
          description: 'Get an issue',
          action: 'Get issue',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_number',
              name: 'issueNumber',
              displayName: 'Issue Number',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_issues',
          name: 'List Issues',
          value: 'getMany',
          description: 'List issues',
          action: 'List issues',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              default: 'open',
              options: [
                { name: 'Open', value: 'open' },
                { name: 'Closed', value: 'closed' },
                { name: 'All', value: 'all' },
              ],
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels',
              type: 'string',
              required: false,
            },
            {
              id: 'assignee',
              name: 'assignee',
              displayName: 'Assignee',
              type: 'string',
              required: false,
            },
            {
              id: 'sort',
              name: 'sort',
              displayName: 'Sort',
              type: 'options',
              required: false,
              options: [
                { name: 'Created', value: 'created' },
                { name: 'Updated', value: 'updated' },
                { name: 'Comments', value: 'comments' },
              ],
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 30,
            },
          ],
        },
        {
          id: 'update_issue',
          name: 'Update Issue',
          value: 'update',
          description: 'Update an issue',
          action: 'Update issue',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_number',
              name: 'issueNumber',
              displayName: 'Issue Number',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'string',
              required: false,
            },
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              options: [
                { name: 'Open', value: 'open' },
                { name: 'Closed', value: 'closed' },
              ],
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels',
              type: 'string',
              required: false,
            },
            {
              id: 'assignees',
              name: 'assignees',
              displayName: 'Assignees',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'lock_issue',
          name: 'Lock Issue',
          value: 'lock',
          description: 'Lock an issue',
          action: 'Lock issue',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_number',
              name: 'issueNumber',
              displayName: 'Issue Number',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'lock_reason',
              name: 'lockReason',
              displayName: 'Lock Reason',
              type: 'options',
              required: false,
              options: [
                { name: 'Off Topic', value: 'off-topic' },
                { name: 'Too Heated', value: 'too heated' },
                { name: 'Resolved', value: 'resolved' },
                { name: 'Spam', value: 'spam' },
              ],
            },
          ],
        },
      ],
    },
    
    // ============================================
    // PULL REQUEST RESOURCE
    // ============================================
    {
      id: 'pullRequest',
      name: 'Pull Request',
      value: 'pullRequest',
      description: 'Pull request operations',
      operations: [
        {
          id: 'create_pr',
          name: 'Create Pull Request',
          value: 'create',
          description: 'Create a pull request',
          action: 'Create pull request',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
            {
              id: 'head',
              name: 'head',
              displayName: 'Head Branch',
              type: 'string',
              required: true,
            },
            {
              id: 'base',
              name: 'base',
              displayName: 'Base Branch',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'draft',
              name: 'draft',
              displayName: 'Draft',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'maintainer_can_modify',
              name: 'maintainerCanModify',
              displayName: 'Allow Maintainer Edits',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'get_pr',
          name: 'Get Pull Request',
          value: 'get',
          description: 'Get a pull request',
          action: 'Get pull request',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_number',
              name: 'pullNumber',
              displayName: 'Pull Request Number',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_prs',
          name: 'List Pull Requests',
          value: 'getMany',
          description: 'List pull requests',
          action: 'List pull requests',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              default: 'open',
              options: [
                { name: 'Open', value: 'open' },
                { name: 'Closed', value: 'closed' },
                { name: 'All', value: 'all' },
              ],
            },
            {
              id: 'base',
              name: 'base',
              displayName: 'Base Branch',
              type: 'string',
              required: false,
            },
            {
              id: 'sort',
              name: 'sort',
              displayName: 'Sort',
              type: 'options',
              required: false,
              options: [
                { name: 'Created', value: 'created' },
                { name: 'Updated', value: 'updated' },
                { name: 'Popularity', value: 'popularity' },
                { name: 'Long Running', value: 'long-running' },
              ],
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 30,
            },
          ],
        },
        {
          id: 'merge_pr',
          name: 'Merge Pull Request',
          value: 'merge',
          description: 'Merge a pull request',
          action: 'Merge pull request',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_number',
              name: 'pullNumber',
              displayName: 'Pull Request Number',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'commit_title',
              name: 'commitTitle',
              displayName: 'Commit Title',
              type: 'string',
              required: false,
            },
            {
              id: 'commit_message',
              name: 'commitMessage',
              displayName: 'Commit Message',
              type: 'string',
              required: false,
            },
            {
              id: 'merge_method',
              name: 'mergeMethod',
              displayName: 'Merge Method',
              type: 'options',
              required: false,
              default: 'merge',
              options: [
                { name: 'Merge', value: 'merge' },
                { name: 'Squash', value: 'squash' },
                { name: 'Rebase', value: 'rebase' },
              ],
            },
          ],
        },
        {
          id: 'review_pr',
          name: 'Create Review',
          value: 'createReview',
          description: 'Create a pull request review',
          action: 'Create review',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'pull_number',
              name: 'pullNumber',
              displayName: 'Pull Request Number',
              type: 'number',
              required: true,
            },
            {
              id: 'event',
              name: 'event',
              displayName: 'Review Event',
              type: 'options',
              required: true,
              options: [
                { name: 'Approve', value: 'APPROVE' },
                { name: 'Request Changes', value: 'REQUEST_CHANGES' },
                { name: 'Comment', value: 'COMMENT' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'body',
              name: 'body',
              displayName: 'Review Body',
              type: 'string',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // FILE RESOURCE
    // ============================================
    {
      id: 'file',
      name: 'File',
      value: 'file',
      description: 'File operations',
      operations: [
        {
          id: 'get_content',
          name: 'Get File Content',
          value: 'get',
          description: 'Get file contents',
          action: 'Get file content',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'ref',
              name: 'ref',
              displayName: 'Branch/Tag/SHA',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'create_file',
          name: 'Create File',
          value: 'create',
          description: 'Create or update a file',
          action: 'Create file',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
            {
              id: 'content',
              name: 'content',
              displayName: 'Content',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 10,
              },
            },
            {
              id: 'message',
              name: 'message',
              displayName: 'Commit Message',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch',
              type: 'string',
              required: false,
            },
            {
              id: 'sha',
              name: 'sha',
              displayName: 'File SHA (for update)',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_file',
          name: 'Delete File',
          value: 'delete',
          description: 'Delete a file',
          action: 'Delete file',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
            {
              id: 'sha',
              name: 'sha',
              displayName: 'File SHA',
              type: 'string',
              required: true,
            },
            {
              id: 'message',
              name: 'message',
              displayName: 'Commit Message',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch',
              type: 'string',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // RELEASE RESOURCE
    // ============================================
    {
      id: 'release',
      name: 'Release',
      value: 'release',
      description: 'Release operations',
      operations: [
        {
          id: 'create_release',
          name: 'Create Release',
          value: 'create',
          description: 'Create a release',
          action: 'Create release',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'tag_name',
              name: 'tagName',
              displayName: 'Tag Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Release Name',
              type: 'string',
              required: false,
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'string',
              required: false,
            },
            {
              id: 'draft',
              name: 'draft',
              displayName: 'Draft',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'prerelease',
              name: 'prerelease',
              displayName: 'Pre-release',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'target_commitish',
              name: 'targetCommitish',
              displayName: 'Target Commitish',
              type: 'string',
              required: false,
            },
            {
              id: 'generate_release_notes',
              name: 'generateReleaseNotes',
              displayName: 'Generate Release Notes',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'list_releases',
          name: 'List Releases',
          value: 'getMany',
          description: 'List releases',
          action: 'List releases',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 30,
            },
          ],
        },
        {
          id: 'get_latest',
          name: 'Get Latest Release',
          value: 'getLatest',
          description: 'Get latest release',
          action: 'Get latest release',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // WORKFLOW RESOURCE
    // ============================================
    {
      id: 'workflow',
      name: 'Actions Workflow',
      value: 'workflow',
      description: 'GitHub Actions workflows',
      operations: [
        {
          id: 'list_workflows',
          name: 'List Workflows',
          value: 'getMany',
          description: 'List workflows',
          action: 'List workflows',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'dispatch_workflow',
          name: 'Dispatch Workflow',
          value: 'dispatch',
          description: 'Trigger a workflow dispatch',
          action: 'Dispatch workflow',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'workflow_id',
              name: 'workflowId',
              displayName: 'Workflow ID or File',
              type: 'string',
              required: true,
            },
            {
              id: 'ref',
              name: 'ref',
              displayName: 'Branch/Tag',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'inputs',
              name: 'inputs',
              displayName: 'Inputs',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'list_runs',
          name: 'List Workflow Runs',
          value: 'listRuns',
          description: 'List workflow runs',
          action: 'List workflow runs',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'workflow_id',
              name: 'workflowId',
              displayName: 'Workflow ID',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Completed', value: 'completed' },
                { name: 'In Progress', value: 'in_progress' },
                { name: 'Queued', value: 'queued' },
              ],
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 30,
            },
          ],
        },
        {
          id: 'rerun_workflow',
          name: 'Re-run Workflow',
          value: 'rerun',
          description: 'Re-run a workflow',
          action: 'Re-run workflow',
          fields: [
            {
              id: 'owner',
              name: 'owner',
              displayName: 'Owner',
              type: 'string',
              required: true,
            },
            {
              id: 'repo',
              name: 'repo',
              displayName: 'Repository',
              type: 'string',
              required: true,
            },
            {
              id: 'run_id',
              name: 'runId',
              displayName: 'Run ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
