/**
 * GitLab n8n-style Schema
 * 
 * Comprehensive GitLab API operations
 */

import { N8nAppSchema } from './types';

export const gitlabSchema: N8nAppSchema = {
  id: 'gitlab',
  name: 'GitLab',
  description: 'GitLab DevOps and version control',
  version: '1.0.0',
  color: '#FC6D26',
  icon: 'gitlab',
  group: ['developer'],
  
  credentials: [
    {
      name: 'gitlabToken',
      displayName: 'GitLab Personal Access Token',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'host',
          displayName: 'GitLab Host',
          type: 'string',
          required: true,
          default: 'https://gitlab.com',
        },
        {
          name: 'token',
          displayName: 'Personal Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
    {
      name: 'gitlabOAuth2',
      displayName: 'GitLab OAuth2',
      required: true,
      type: 'oauth2',
      properties: [
        {
          name: 'host',
          displayName: 'GitLab Host',
          type: 'string',
          required: true,
          default: 'https://gitlab.com',
        },
        {
          name: 'accessToken',
          displayName: 'Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // PROJECT RESOURCE
    // ============================================
    {
      id: 'project',
      name: 'Project',
      value: 'project',
      description: 'GitLab project operations',
      operations: [
        {
          id: 'create_project',
          name: 'Create Project',
          value: 'create',
          description: 'Create a new project',
          action: 'Create project',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Project Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: false,
            },
            {
              id: 'namespace_id',
              name: 'namespaceId',
              displayName: 'Namespace ID',
              type: 'number',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'visibility',
              name: 'visibility',
              displayName: 'Visibility',
              type: 'options',
              required: false,
              default: 'private',
              options: [
                { name: 'Private', value: 'private' },
                { name: 'Internal', value: 'internal' },
                { name: 'Public', value: 'public' },
              ],
            },
            {
              id: 'initialize_with_readme',
              name: 'initializeWithReadme',
              displayName: 'Initialize with README',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'default_branch',
              name: 'defaultBranch',
              displayName: 'Default Branch',
              type: 'string',
              required: false,
              default: 'main',
            },
          ],
        },
        {
          id: 'get_project',
          name: 'Get Project',
          value: 'get',
          description: 'Get project information',
          action: 'Get project',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_projects',
          name: 'List Projects',
          value: 'getMany',
          description: 'List projects',
          action: 'List projects',
          fields: [],
          optionalFields: [
            {
              id: 'visibility',
              name: 'visibility',
              displayName: 'Visibility',
              type: 'options',
              required: false,
              options: [
                { name: 'Private', value: 'private' },
                { name: 'Internal', value: 'internal' },
                { name: 'Public', value: 'public' },
              ],
            },
            {
              id: 'membership',
              name: 'membership',
              displayName: 'Membership',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'search',
              name: 'search',
              displayName: 'Search',
              type: 'string',
              required: false,
            },
            {
              id: 'order_by',
              name: 'orderBy',
              displayName: 'Order By',
              type: 'options',
              required: false,
              options: [
                { name: 'ID', value: 'id' },
                { name: 'Name', value: 'name' },
                { name: 'Path', value: 'path' },
                { name: 'Created At', value: 'created_at' },
                { name: 'Updated At', value: 'updated_at' },
                { name: 'Last Activity At', value: 'last_activity_at' },
              ],
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 20,
            },
          ],
        },
        {
          id: 'fork_project',
          name: 'Fork Project',
          value: 'fork',
          description: 'Fork a project',
          action: 'Fork project',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'namespace_id',
              name: 'namespaceId',
              displayName: 'Target Namespace ID',
              type: 'number',
              required: false,
            },
            {
              id: 'path',
              name: 'path',
              displayName: 'Path',
              type: 'string',
              required: false,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_project',
          name: 'Delete Project',
          value: 'delete',
          description: 'Delete a project',
          action: 'Delete project',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ISSUE RESOURCE
    // ============================================
    {
      id: 'issue',
      name: 'Issue',
      value: 'issue',
      description: 'Issue operations',
      operations: [
        {
          id: 'create_issue',
          name: 'Create Issue',
          value: 'create',
          description: 'Create a new issue',
          action: 'Create issue',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'issue_type',
              name: 'issueType',
              displayName: 'Issue Type',
              type: 'options',
              required: false,
              default: 'issue',
              options: [
                { name: 'Issue', value: 'issue' },
                { name: 'Incident', value: 'incident' },
                { name: 'Test Case', value: 'test_case' },
              ],
            },
            {
              id: 'confidential',
              name: 'confidential',
              displayName: 'Confidential',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'assignee_ids',
              name: 'assigneeIds',
              displayName: 'Assignee IDs',
              type: 'string',
              required: false,
              description: 'Comma-separated user IDs',
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels',
              type: 'string',
              required: false,
              description: 'Comma-separated labels',
            },
            {
              id: 'milestone_id',
              name: 'milestoneId',
              displayName: 'Milestone ID',
              type: 'number',
              required: false,
            },
            {
              id: 'due_date',
              name: 'dueDate',
              displayName: 'Due Date',
              type: 'string',
              required: false,
            },
            {
              id: 'weight',
              name: 'weight',
              displayName: 'Weight',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_issue',
          name: 'Get Issue',
          value: 'get',
          description: 'Get an issue',
          action: 'Get issue',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_iid',
              name: 'issueIid',
              displayName: 'Issue IID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_issues',
          name: 'List Issues',
          value: 'getMany',
          description: 'List issues',
          action: 'List issues',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              default: 'opened',
              options: [
                { name: 'Opened', value: 'opened' },
                { name: 'Closed', value: 'closed' },
                { name: 'All', value: 'all' },
              ],
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels',
              type: 'string',
              required: false,
            },
            {
              id: 'assignee_id',
              name: 'assigneeId',
              displayName: 'Assignee ID',
              type: 'number',
              required: false,
            },
            {
              id: 'search',
              name: 'search',
              displayName: 'Search',
              type: 'string',
              required: false,
            },
            {
              id: 'order_by',
              name: 'orderBy',
              displayName: 'Order By',
              type: 'options',
              required: false,
              options: [
                { name: 'Created At', value: 'created_at' },
                { name: 'Updated At', value: 'updated_at' },
                { name: 'Priority', value: 'priority' },
                { name: 'Due Date', value: 'due_date' },
              ],
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 20,
            },
          ],
        },
        {
          id: 'update_issue',
          name: 'Update Issue',
          value: 'update',
          description: 'Update an issue',
          action: 'Update issue',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_iid',
              name: 'issueIid',
              displayName: 'Issue IID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'state_event',
              name: 'stateEvent',
              displayName: 'State Event',
              type: 'options',
              required: false,
              options: [
                { name: 'Close', value: 'close' },
                { name: 'Reopen', value: 'reopen' },
              ],
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels',
              type: 'string',
              required: false,
            },
            {
              id: 'assignee_ids',
              name: 'assigneeIds',
              displayName: 'Assignee IDs',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_issue',
          name: 'Delete Issue',
          value: 'delete',
          description: 'Delete an issue',
          action: 'Delete issue',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'issue_iid',
              name: 'issueIid',
              displayName: 'Issue IID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // MERGE REQUEST RESOURCE
    // ============================================
    {
      id: 'mergeRequest',
      name: 'Merge Request',
      value: 'mergeRequest',
      description: 'Merge request operations',
      operations: [
        {
          id: 'create_mr',
          name: 'Create Merge Request',
          value: 'create',
          description: 'Create a merge request',
          action: 'Create merge request',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
            {
              id: 'source_branch',
              name: 'sourceBranch',
              displayName: 'Source Branch',
              type: 'string',
              required: true,
            },
            {
              id: 'target_branch',
              name: 'targetBranch',
              displayName: 'Target Branch',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'assignee_id',
              name: 'assigneeId',
              displayName: 'Assignee ID',
              type: 'number',
              required: false,
            },
            {
              id: 'reviewer_ids',
              name: 'reviewerIds',
              displayName: 'Reviewer IDs',
              type: 'string',
              required: false,
              description: 'Comma-separated user IDs',
            },
            {
              id: 'labels',
              name: 'labels',
              displayName: 'Labels',
              type: 'string',
              required: false,
            },
            {
              id: 'milestone_id',
              name: 'milestoneId',
              displayName: 'Milestone ID',
              type: 'number',
              required: false,
            },
            {
              id: 'remove_source_branch',
              name: 'removeSourceBranch',
              displayName: 'Remove Source Branch',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'squash',
              name: 'squash',
              displayName: 'Squash Commits',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'draft',
              name: 'draft',
              displayName: 'Draft',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_mr',
          name: 'Get Merge Request',
          value: 'get',
          description: 'Get a merge request',
          action: 'Get merge request',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'merge_request_iid',
              name: 'mergeRequestIid',
              displayName: 'Merge Request IID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_mrs',
          name: 'List Merge Requests',
          value: 'getMany',
          description: 'List merge requests',
          action: 'List merge requests',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              default: 'opened',
              options: [
                { name: 'Opened', value: 'opened' },
                { name: 'Closed', value: 'closed' },
                { name: 'Merged', value: 'merged' },
                { name: 'All', value: 'all' },
              ],
            },
            {
              id: 'scope',
              name: 'scope',
              displayName: 'Scope',
              type: 'options',
              required: false,
              options: [
                { name: 'Created by Me', value: 'created_by_me' },
                { name: 'Assigned to Me', value: 'assigned_to_me' },
                { name: 'All', value: 'all' },
              ],
            },
            {
              id: 'target_branch',
              name: 'targetBranch',
              displayName: 'Target Branch',
              type: 'string',
              required: false,
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 20,
            },
          ],
        },
        {
          id: 'merge_mr',
          name: 'Merge Merge Request',
          value: 'merge',
          description: 'Merge a merge request',
          action: 'Merge merge request',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'merge_request_iid',
              name: 'mergeRequestIid',
              displayName: 'Merge Request IID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'merge_commit_message',
              name: 'mergeCommitMessage',
              displayName: 'Merge Commit Message',
              type: 'string',
              required: false,
            },
            {
              id: 'squash_commit_message',
              name: 'squashCommitMessage',
              displayName: 'Squash Commit Message',
              type: 'string',
              required: false,
            },
            {
              id: 'squash',
              name: 'squash',
              displayName: 'Squash Commits',
              type: 'boolean',
              required: false,
            },
            {
              id: 'should_remove_source_branch',
              name: 'shouldRemoveSourceBranch',
              displayName: 'Remove Source Branch',
              type: 'boolean',
              required: false,
            },
          ],
        },
        {
          id: 'approve_mr',
          name: 'Approve Merge Request',
          value: 'approve',
          description: 'Approve a merge request',
          action: 'Approve merge request',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'merge_request_iid',
              name: 'mergeRequestIid',
              displayName: 'Merge Request IID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // PIPELINE RESOURCE
    // ============================================
    {
      id: 'pipeline',
      name: 'Pipeline',
      value: 'pipeline',
      description: 'CI/CD pipeline operations',
      operations: [
        {
          id: 'create_pipeline',
          name: 'Create Pipeline',
          value: 'create',
          description: 'Create a new pipeline',
          action: 'Create pipeline',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'ref',
              name: 'ref',
              displayName: 'Branch/Tag',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'variables',
              name: 'variables',
              displayName: 'Variables',
              type: 'json',
              required: false,
              description: 'Array of {key, value} objects',
            },
          ],
        },
        {
          id: 'get_pipeline',
          name: 'Get Pipeline',
          value: 'get',
          description: 'Get a pipeline',
          action: 'Get pipeline',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'pipeline_id',
              name: 'pipelineId',
              displayName: 'Pipeline ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_pipelines',
          name: 'List Pipelines',
          value: 'getMany',
          description: 'List pipelines',
          action: 'List pipelines',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Running', value: 'running' },
                { name: 'Pending', value: 'pending' },
                { name: 'Success', value: 'success' },
                { name: 'Failed', value: 'failed' },
                { name: 'Canceled', value: 'canceled' },
                { name: 'Skipped', value: 'skipped' },
                { name: 'Manual', value: 'manual' },
              ],
            },
            {
              id: 'ref',
              name: 'ref',
              displayName: 'Ref',
              type: 'string',
              required: false,
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 20,
            },
          ],
        },
        {
          id: 'retry_pipeline',
          name: 'Retry Pipeline',
          value: 'retry',
          description: 'Retry a pipeline',
          action: 'Retry pipeline',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'pipeline_id',
              name: 'pipelineId',
              displayName: 'Pipeline ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'cancel_pipeline',
          name: 'Cancel Pipeline',
          value: 'cancel',
          description: 'Cancel a pipeline',
          action: 'Cancel pipeline',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'pipeline_id',
              name: 'pipelineId',
              displayName: 'Pipeline ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // BRANCH RESOURCE
    // ============================================
    {
      id: 'branch',
      name: 'Branch',
      value: 'branch',
      description: 'Branch operations',
      operations: [
        {
          id: 'create_branch',
          name: 'Create Branch',
          value: 'create',
          description: 'Create a branch',
          action: 'Create branch',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch Name',
              type: 'string',
              required: true,
            },
            {
              id: 'ref',
              name: 'ref',
              displayName: 'Reference (SHA/Branch)',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_branch',
          name: 'Get Branch',
          value: 'get',
          description: 'Get branch information',
          action: 'Get branch',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_branches',
          name: 'List Branches',
          value: 'getMany',
          description: 'List branches',
          action: 'List branches',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'search',
              name: 'search',
              displayName: 'Search',
              type: 'string',
              required: false,
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 20,
            },
          ],
        },
        {
          id: 'delete_branch',
          name: 'Delete Branch',
          value: 'delete',
          description: 'Delete a branch',
          action: 'Delete branch',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'protect_branch',
          name: 'Protect Branch',
          value: 'protect',
          description: 'Protect a branch',
          action: 'Protect branch',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Branch Name Pattern',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'push_access_level',
              name: 'pushAccessLevel',
              displayName: 'Push Access Level',
              type: 'options',
              required: false,
              default: '40',
              options: [
                { name: 'No Access', value: '0' },
                { name: 'Developers + Maintainers', value: '30' },
                { name: 'Maintainers', value: '40' },
                { name: 'Admins', value: '60' },
              ],
            },
            {
              id: 'merge_access_level',
              name: 'mergeAccessLevel',
              displayName: 'Merge Access Level',
              type: 'options',
              required: false,
              default: '40',
              options: [
                { name: 'No Access', value: '0' },
                { name: 'Developers + Maintainers', value: '30' },
                { name: 'Maintainers', value: '40' },
                { name: 'Admins', value: '60' },
              ],
            },
            {
              id: 'allow_force_push',
              name: 'allowForcePush',
              displayName: 'Allow Force Push',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // FILE RESOURCE
    // ============================================
    {
      id: 'file',
      name: 'File',
      value: 'file',
      description: 'Repository file operations',
      operations: [
        {
          id: 'get_file',
          name: 'Get File Content',
          value: 'get',
          description: 'Get file from repository',
          action: 'Get file',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'file_path',
              name: 'filePath',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
            {
              id: 'ref',
              name: 'ref',
              displayName: 'Branch/Tag/SHA',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'create_file',
          name: 'Create File',
          value: 'create',
          description: 'Create a new file',
          action: 'Create file',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'file_path',
              name: 'filePath',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch',
              type: 'string',
              required: true,
            },
            {
              id: 'content',
              name: 'content',
              displayName: 'Content',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 10,
              },
            },
            {
              id: 'commit_message',
              name: 'commitMessage',
              displayName: 'Commit Message',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'author_email',
              name: 'authorEmail',
              displayName: 'Author Email',
              type: 'string',
              required: false,
            },
            {
              id: 'author_name',
              name: 'authorName',
              displayName: 'Author Name',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'update_file',
          name: 'Update File',
          value: 'update',
          description: 'Update an existing file',
          action: 'Update file',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'file_path',
              name: 'filePath',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch',
              type: 'string',
              required: true,
            },
            {
              id: 'content',
              name: 'content',
              displayName: 'Content',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 10,
              },
            },
            {
              id: 'commit_message',
              name: 'commitMessage',
              displayName: 'Commit Message',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'last_commit_id',
              name: 'lastCommitId',
              displayName: 'Last Commit ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_file',
          name: 'Delete File',
          value: 'delete',
          description: 'Delete a file',
          action: 'Delete file',
          fields: [
            {
              id: 'project_id',
              name: 'projectId',
              displayName: 'Project ID or Path',
              type: 'string',
              required: true,
            },
            {
              id: 'file_path',
              name: 'filePath',
              displayName: 'File Path',
              type: 'string',
              required: true,
            },
            {
              id: 'branch',
              name: 'branch',
              displayName: 'Branch',
              type: 'string',
              required: true,
            },
            {
              id: 'commit_message',
              name: 'commitMessage',
              displayName: 'Commit Message',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // USER RESOURCE
    // ============================================
    {
      id: 'user',
      name: 'User',
      value: 'user',
      description: 'User operations',
      operations: [
        {
          id: 'get_current_user',
          name: 'Get Current User',
          value: 'getCurrent',
          description: 'Get authenticated user',
          action: 'Get current user',
          fields: [],
          optionalFields: [],
        },
        {
          id: 'get_user',
          name: 'Get User',
          value: 'get',
          description: 'Get a user by ID',
          action: 'Get user',
          fields: [
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_users',
          name: 'List Users',
          value: 'getMany',
          description: 'List users',
          action: 'List users',
          fields: [],
          optionalFields: [
            {
              id: 'search',
              name: 'search',
              displayName: 'Search',
              type: 'string',
              required: false,
            },
            {
              id: 'username',
              name: 'username',
              displayName: 'Username',
              type: 'string',
              required: false,
            },
            {
              id: 'active',
              name: 'active',
              displayName: 'Active Only',
              type: 'boolean',
              required: false,
            },
            {
              id: 'per_page',
              name: 'perPage',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 20,
            },
          ],
        },
      ],
    },
  ],
};
