/**
 * Google Forms n8n-style Schema
 * 
 * Comprehensive Google Forms API operations
 */

import { N8nAppSchema } from './types';

export const googleFormsSchema: N8nAppSchema = {
  id: 'googleForms',
  name: 'Google Forms',
  description: 'Google Forms surveys and quizzes',
  version: '1.0.0',
  color: '#673AB7',
  icon: 'google-forms',
  group: ['google', 'productivity'],
  
  credentials: [
    {
      name: 'googleFormsOAuth2',
      displayName: 'Google Forms OAuth2',
      required: true,
      type: 'oauth2',
      properties: [
        {
          name: 'accessToken',
          displayName: 'Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'refreshToken',
          displayName: 'Refresh Token',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
    {
      name: 'googleFormsServiceAccount',
      displayName: 'Google Forms Service Account',
      required: true,
      type: 'serviceAccount',
      properties: [
        {
          name: 'serviceAccountKey',
          displayName: 'Service Account JSON',
          type: 'json',
          required: true,
        },
        {
          name: 'impersonateUser',
          displayName: 'Impersonate User Email',
          type: 'string',
          required: false,
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // FORM RESOURCE
    // ============================================
    {
      id: 'form',
      name: 'Form',
      value: 'form',
      description: 'Form operations',
      operations: [
        {
          id: 'create_form',
          name: 'Create Form',
          value: 'create',
          description: 'Create a new form',
          action: 'Create form',
          fields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'document_title',
              name: 'documentTitle',
              displayName: 'Document Title',
              type: 'string',
              required: false,
              description: 'Title shown in Drive',
            },
          ],
        },
        {
          id: 'get_form',
          name: 'Get Form',
          value: 'get',
          description: 'Get form details',
          action: 'Get form',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_form',
          name: 'Update Form',
          value: 'update',
          description: 'Update form settings',
          action: 'Update form',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'is_quiz',
              name: 'isQuiz',
              displayName: 'Enable Quiz Mode',
              type: 'boolean',
              required: false,
            },
            {
              id: 'collect_email',
              name: 'collectEmail',
              displayName: 'Collect Email Addresses',
              type: 'boolean',
              required: false,
            },
            {
              id: 'allow_response_edits',
              name: 'allowResponseEdits',
              displayName: 'Allow Response Edits',
              type: 'boolean',
              required: false,
            },
            {
              id: 'limit_one_response_per_user',
              name: 'limitOneResponsePerUser',
              displayName: 'Limit to One Response',
              type: 'boolean',
              required: false,
            },
            {
              id: 'confirmation_message',
              name: 'confirmationMessage',
              displayName: 'Confirmation Message',
              type: 'string',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // ITEM RESOURCE (Questions)
    // ============================================
    {
      id: 'item',
      name: 'Question',
      value: 'item',
      description: 'Form question operations',
      operations: [
        {
          id: 'add_text_question',
          name: 'Add Text Question',
          value: 'addText',
          description: 'Add a short/long text question',
          action: 'Add text question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: true,
            },
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: true,
              options: [
                { name: 'Short Answer', value: 'TEXT' },
                { name: 'Paragraph', value: 'PARAGRAPH' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_choice_question',
          name: 'Add Choice Question',
          value: 'addChoice',
          description: 'Add a multiple choice or checkbox question',
          action: 'Add choice question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: true,
            },
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: true,
              options: [
                { name: 'Multiple Choice', value: 'RADIO' },
                { name: 'Checkboxes', value: 'CHECKBOX' },
                { name: 'Dropdown', value: 'DROP_DOWN' },
              ],
            },
            {
              id: 'options',
              name: 'options',
              displayName: 'Options',
              type: 'string',
              required: true,
              description: 'Comma-separated options',
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'shuffle',
              name: 'shuffle',
              displayName: 'Shuffle Options',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'other_option',
              name: 'otherOption',
              displayName: 'Include Other Option',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_scale_question',
          name: 'Add Scale Question',
          value: 'addScale',
          description: 'Add a linear scale question',
          action: 'Add scale question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: true,
            },
            {
              id: 'low',
              name: 'low',
              displayName: 'Low Value',
              type: 'number',
              required: true,
              default: 1,
            },
            {
              id: 'high',
              name: 'high',
              displayName: 'High Value',
              type: 'number',
              required: true,
              default: 5,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'low_label',
              name: 'lowLabel',
              displayName: 'Low Label',
              type: 'string',
              required: false,
            },
            {
              id: 'high_label',
              name: 'highLabel',
              displayName: 'High Label',
              type: 'string',
              required: false,
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_date_question',
          name: 'Add Date Question',
          value: 'addDate',
          description: 'Add a date question',
          action: 'Add date question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'include_time',
              name: 'includeTime',
              displayName: 'Include Time',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'include_year',
              name: 'includeYear',
              displayName: 'Include Year',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_time_question',
          name: 'Add Time Question',
          value: 'addTime',
          description: 'Add a time question',
          action: 'Add time question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'duration',
              name: 'duration',
              displayName: 'Duration Mode',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_grid_question',
          name: 'Add Grid Question',
          value: 'addGrid',
          description: 'Add a multiple choice or checkbox grid question',
          action: 'Add grid question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: true,
            },
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: true,
              options: [
                { name: 'Multiple Choice Grid', value: 'RADIO' },
                { name: 'Checkbox Grid', value: 'CHECKBOX' },
              ],
            },
            {
              id: 'rows',
              name: 'rows',
              displayName: 'Rows',
              type: 'string',
              required: true,
              description: 'Comma-separated row labels',
            },
            {
              id: 'columns',
              name: 'columns',
              displayName: 'Columns',
              type: 'string',
              required: true,
              description: 'Comma-separated column labels',
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'shuffle_rows',
              name: 'shuffleRows',
              displayName: 'Shuffle Rows',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_file_upload',
          name: 'Add File Upload',
          value: 'addFileUpload',
          description: 'Add a file upload question',
          action: 'Add file upload question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: true,
            },
            {
              id: 'folder_id',
              name: 'folderId',
              displayName: 'Drive Folder ID',
              type: 'string',
              required: true,
              description: 'Folder to store uploads',
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'max_files',
              name: 'maxFiles',
              displayName: 'Max Files',
              type: 'number',
              required: false,
              default: 1,
            },
            {
              id: 'max_file_size',
              name: 'maxFileSize',
              displayName: 'Max File Size (MB)',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'allowed_mime_types',
              name: 'allowedMimeTypes',
              displayName: 'Allowed File Types',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Documents', value: 'DOCUMENT' },
                { name: 'Spreadsheets', value: 'SPREADSHEET' },
                { name: 'Presentations', value: 'PRESENTATION' },
                { name: 'Drawings', value: 'DRAWING' },
                { name: 'PDFs', value: 'PDF' },
                { name: 'Images', value: 'IMAGE' },
                { name: 'Videos', value: 'VIDEO' },
                { name: 'Audio', value: 'AUDIO' },
              ],
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'update_item',
          name: 'Update Question',
          value: 'update',
          description: 'Update a question',
          action: 'Update question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'item_id',
              name: 'itemId',
              displayName: 'Item ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Question Title',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'required',
              name: 'required',
              displayName: 'Required',
              type: 'boolean',
              required: false,
            },
          ],
        },
        {
          id: 'delete_item',
          name: 'Delete Question',
          value: 'delete',
          description: 'Delete a question',
          action: 'Delete question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'item_index',
              name: 'itemIndex',
              displayName: 'Item Index',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'move_item',
          name: 'Move Question',
          value: 'move',
          description: 'Move a question to a new position',
          action: 'Move question',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'original_index',
              name: 'originalIndex',
              displayName: 'Original Index',
              type: 'number',
              required: true,
            },
            {
              id: 'new_index',
              name: 'newIndex',
              displayName: 'New Index',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // SECTION RESOURCE
    // ============================================
    {
      id: 'section',
      name: 'Section',
      value: 'section',
      description: 'Form section operations',
      operations: [
        {
          id: 'add_section',
          name: 'Add Section',
          value: 'create',
          description: 'Add a section header',
          action: 'Add section',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'title',
              name: 'title',
              displayName: 'Section Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_page_break',
          name: 'Add Page Break',
          value: 'addPageBreak',
          description: 'Add a page break',
          action: 'Add page break',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Page Title',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // RESPONSE RESOURCE
    // ============================================
    {
      id: 'response',
      name: 'Response',
      value: 'response',
      description: 'Form response operations',
      operations: [
        {
          id: 'get_response',
          name: 'Get Response',
          value: 'get',
          description: 'Get a specific response',
          action: 'Get response',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'response_id',
              name: 'responseId',
              displayName: 'Response ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_responses',
          name: 'List Responses',
          value: 'getMany',
          description: 'List all responses',
          action: 'List responses',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'filter',
              name: 'filter',
              displayName: 'Filter',
              type: 'string',
              required: false,
              description: 'Filter expression',
            },
            {
              id: 'page_size',
              name: 'pageSize',
              displayName: 'Page Size',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // WATCH RESOURCE
    // ============================================
    {
      id: 'watch',
      name: 'Watch',
      value: 'watch',
      description: 'Form watch (webhook) operations',
      operations: [
        {
          id: 'create_watch',
          name: 'Create Watch',
          value: 'create',
          description: 'Create a watch for form submissions',
          action: 'Create watch',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'event_type',
              name: 'eventType',
              displayName: 'Event Type',
              type: 'options',
              required: true,
              options: [
                { name: 'New Responses', value: 'RESPONSES' },
                { name: 'Schema Changes', value: 'SCHEMA' },
              ],
            },
            {
              id: 'target_uri',
              name: 'targetUri',
              displayName: 'Target URI',
              type: 'string',
              required: true,
              description: 'Pub/Sub topic or Cloud Function URL',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_watches',
          name: 'List Watches',
          value: 'getMany',
          description: 'List active watches',
          action: 'List watches',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_watch',
          name: 'Delete Watch',
          value: 'delete',
          description: 'Delete a watch',
          action: 'Delete watch',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'watch_id',
              name: 'watchId',
              displayName: 'Watch ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'renew_watch',
          name: 'Renew Watch',
          value: 'renew',
          description: 'Renew a watch before expiration',
          action: 'Renew watch',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'watch_id',
              name: 'watchId',
              displayName: 'Watch ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // IMAGE/VIDEO RESOURCE
    // ============================================
    {
      id: 'media',
      name: 'Media',
      value: 'media',
      description: 'Image and video operations',
      operations: [
        {
          id: 'add_image',
          name: 'Add Image',
          value: 'addImage',
          description: 'Add an image to the form',
          action: 'Add image',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'source_uri',
              name: 'sourceUri',
              displayName: 'Image URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'width',
              name: 'width',
              displayName: 'Width',
              type: 'number',
              required: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'add_video',
          name: 'Add Video',
          value: 'addVideo',
          description: 'Add a YouTube video to the form',
          action: 'Add video',
          fields: [
            {
              id: 'form_id',
              name: 'formId',
              displayName: 'Form ID',
              type: 'string',
              required: true,
            },
            {
              id: 'youtube_uri',
              name: 'youtubeUri',
              displayName: 'YouTube URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'width',
              name: 'width',
              displayName: 'Width',
              type: 'number',
              required: false,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Position Index',
              type: 'number',
              required: false,
            },
          ],
        },
      ],
    },
  ],
};
