/**
 * Google Calendar n8n-style Schema
 * 
 * Comprehensive Google Calendar API operations
 */

import { N8nAppSchema } from './types';

export const googleCalendarSchema: N8nAppSchema = {
  id: 'googleCalendar',
  name: 'Google Calendar',
  description: 'Google Calendar scheduling',
  version: '1.0.0',
  color: '#4285F4',
  icon: 'google-calendar',
  group: ['google', 'productivity'],
  
  credentials: [
    {
      name: 'googleCalendarOAuth2',
      displayName: 'Google Calendar OAuth2',
      required: true,
      type: 'oauth2',
      properties: [
        {
          name: 'accessToken',
          displayName: 'Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'refreshToken',
          displayName: 'Refresh Token',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
    {
      name: 'googleCalendarServiceAccount',
      displayName: 'Google Calendar Service Account',
      required: true,
      type: 'serviceAccount',
      properties: [
        {
          name: 'serviceAccountKey',
          displayName: 'Service Account JSON',
          type: 'json',
          required: true,
        },
        {
          name: 'impersonateUser',
          displayName: 'Impersonate User Email',
          type: 'string',
          required: false,
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // EVENT RESOURCE
    // ============================================
    {
      id: 'event',
      name: 'Event',
      value: 'event',
      description: 'Calendar event operations',
      operations: [
        {
          id: 'create_event',
          name: 'Create Event',
          value: 'create',
          description: 'Create a calendar event',
          action: 'Create event',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar',
              type: 'string',
              required: true,
              default: 'primary',
            },
            {
              id: 'summary',
              name: 'summary',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
            {
              id: 'start',
              name: 'start',
              displayName: 'Start Time',
              type: 'string',
              required: true,
              description: 'ISO 8601 datetime or date',
            },
            {
              id: 'end',
              name: 'end',
              displayName: 'End Time',
              type: 'string',
              required: true,
              description: 'ISO 8601 datetime or date',
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'location',
              name: 'location',
              displayName: 'Location',
              type: 'string',
              required: false,
            },
            {
              id: 'all_day',
              name: 'allDay',
              displayName: 'All Day Event',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'timezone',
              name: 'timezone',
              displayName: 'Timezone',
              type: 'string',
              required: false,
              description: 'e.g., America/New_York',
            },
            {
              id: 'attendees',
              name: 'attendees',
              displayName: 'Attendees',
              type: 'string',
              required: false,
              description: 'Comma-separated email addresses',
            },
            {
              id: 'send_updates',
              name: 'sendUpdates',
              displayName: 'Send Notifications',
              type: 'options',
              required: false,
              default: 'all',
              options: [
                { name: 'All', value: 'all' },
                { name: 'External Only', value: 'externalOnly' },
                { name: 'None', value: 'none' },
              ],
            },
            {
              id: 'color_id',
              name: 'colorId',
              displayName: 'Color',
              type: 'options',
              required: false,
              options: [
                { name: 'Lavender', value: '1' },
                { name: 'Sage', value: '2' },
                { name: 'Grape', value: '3' },
                { name: 'Flamingo', value: '4' },
                { name: 'Banana', value: '5' },
                { name: 'Tangerine', value: '6' },
                { name: 'Peacock', value: '7' },
                { name: 'Graphite', value: '8' },
                { name: 'Blueberry', value: '9' },
                { name: 'Basil', value: '10' },
                { name: 'Tomato', value: '11' },
              ],
            },
            {
              id: 'visibility',
              name: 'visibility',
              displayName: 'Visibility',
              type: 'options',
              required: false,
              options: [
                { name: 'Default', value: 'default' },
                { name: 'Public', value: 'public' },
                { name: 'Private', value: 'private' },
                { name: 'Confidential', value: 'confidential' },
              ],
            },
            {
              id: 'recurrence',
              name: 'recurrence',
              displayName: 'Recurrence Rule',
              type: 'string',
              required: false,
              description: 'RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR',
            },
            {
              id: 'reminders',
              name: 'reminders',
              displayName: 'Reminders',
              type: 'json',
              required: false,
              description: 'Array of {method, minutes}',
            },
            {
              id: 'conference_data_type',
              name: 'conferenceDataType',
              displayName: 'Add Video Conference',
              type: 'options',
              required: false,
              options: [
                { name: 'None', value: 'none' },
                { name: 'Google Meet', value: 'hangoutsMeet' },
              ],
            },
          ],
        },
        {
          id: 'get_event',
          name: 'Get Event',
          value: 'get',
          description: 'Get an event',
          action: 'Get event',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar',
              type: 'string',
              required: true,
              default: 'primary',
            },
            {
              id: 'event_id',
              name: 'eventId',
              displayName: 'Event ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_events',
          name: 'List Events',
          value: 'getMany',
          description: 'List calendar events',
          action: 'List events',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar',
              type: 'string',
              required: true,
              default: 'primary',
            },
          ],
          optionalFields: [
            {
              id: 'time_min',
              name: 'timeMin',
              displayName: 'Start Time',
              type: 'string',
              required: false,
              description: 'ISO 8601 datetime',
            },
            {
              id: 'time_max',
              name: 'timeMax',
              displayName: 'End Time',
              type: 'string',
              required: false,
            },
            {
              id: 'q',
              name: 'q',
              displayName: 'Search Query',
              type: 'string',
              required: false,
            },
            {
              id: 'single_events',
              name: 'singleEvents',
              displayName: 'Expand Recurring',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'order_by',
              name: 'orderBy',
              displayName: 'Order By',
              type: 'options',
              required: false,
              options: [
                { name: 'Start Time', value: 'startTime' },
                { name: 'Updated', value: 'updated' },
              ],
            },
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 250,
            },
            {
              id: 'show_deleted',
              name: 'showDeleted',
              displayName: 'Show Deleted',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'update_event',
          name: 'Update Event',
          value: 'update',
          description: 'Update an event',
          action: 'Update event',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar',
              type: 'string',
              required: true,
              default: 'primary',
            },
            {
              id: 'event_id',
              name: 'eventId',
              displayName: 'Event ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'summary',
              name: 'summary',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'start',
              name: 'start',
              displayName: 'Start Time',
              type: 'string',
              required: false,
            },
            {
              id: 'end',
              name: 'end',
              displayName: 'End Time',
              type: 'string',
              required: false,
            },
            {
              id: 'location',
              name: 'location',
              displayName: 'Location',
              type: 'string',
              required: false,
            },
            {
              id: 'attendees',
              name: 'attendees',
              displayName: 'Attendees',
              type: 'string',
              required: false,
            },
            {
              id: 'color_id',
              name: 'colorId',
              displayName: 'Color',
              type: 'options',
              required: false,
              options: [
                { name: 'Lavender', value: '1' },
                { name: 'Sage', value: '2' },
                { name: 'Grape', value: '3' },
                { name: 'Flamingo', value: '4' },
                { name: 'Banana', value: '5' },
                { name: 'Tangerine', value: '6' },
                { name: 'Peacock', value: '7' },
                { name: 'Graphite', value: '8' },
                { name: 'Blueberry', value: '9' },
                { name: 'Basil', value: '10' },
                { name: 'Tomato', value: '11' },
              ],
            },
            {
              id: 'send_updates',
              name: 'sendUpdates',
              displayName: 'Send Notifications',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: 'all' },
                { name: 'External Only', value: 'externalOnly' },
                { name: 'None', value: 'none' },
              ],
            },
          ],
        },
        {
          id: 'delete_event',
          name: 'Delete Event',
          value: 'delete',
          description: 'Delete an event',
          action: 'Delete event',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar',
              type: 'string',
              required: true,
              default: 'primary',
            },
            {
              id: 'event_id',
              name: 'eventId',
              displayName: 'Event ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'send_updates',
              name: 'sendUpdates',
              displayName: 'Send Notifications',
              type: 'options',
              required: false,
              default: 'all',
              options: [
                { name: 'All', value: 'all' },
                { name: 'External Only', value: 'externalOnly' },
                { name: 'None', value: 'none' },
              ],
            },
          ],
        },
        {
          id: 'move_event',
          name: 'Move Event',
          value: 'move',
          description: 'Move event to another calendar',
          action: 'Move event',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Source Calendar',
              type: 'string',
              required: true,
            },
            {
              id: 'event_id',
              name: 'eventId',
              displayName: 'Event ID',
              type: 'string',
              required: true,
            },
            {
              id: 'destination',
              name: 'destination',
              displayName: 'Destination Calendar',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'send_updates',
              name: 'sendUpdates',
              displayName: 'Send Notifications',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: 'all' },
                { name: 'External Only', value: 'externalOnly' },
                { name: 'None', value: 'none' },
              ],
            },
          ],
        },
        {
          id: 'quick_add',
          name: 'Quick Add Event',
          value: 'quickAdd',
          description: 'Create event from text',
          action: 'Quick add event',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar',
              type: 'string',
              required: true,
              default: 'primary',
            },
            {
              id: 'text',
              name: 'text',
              displayName: 'Text',
              type: 'string',
              required: true,
              description: 'e.g., Meeting tomorrow at 3pm',
            },
          ],
          optionalFields: [
            {
              id: 'send_updates',
              name: 'sendUpdates',
              displayName: 'Send Notifications',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: 'all' },
                { name: 'External Only', value: 'externalOnly' },
                { name: 'None', value: 'none' },
              ],
            },
          ],
        },
      ],
    },
    
    // ============================================
    // CALENDAR RESOURCE
    // ============================================
    {
      id: 'calendar',
      name: 'Calendar',
      value: 'calendar',
      description: 'Calendar operations',
      operations: [
        {
          id: 'create_calendar',
          name: 'Create Calendar',
          value: 'create',
          description: 'Create a calendar',
          action: 'Create calendar',
          fields: [
            {
              id: 'summary',
              name: 'summary',
              displayName: 'Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'timezone',
              name: 'timezone',
              displayName: 'Timezone',
              type: 'string',
              required: false,
            },
            {
              id: 'location',
              name: 'location',
              displayName: 'Location',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_calendar',
          name: 'Get Calendar',
          value: 'get',
          description: 'Get a calendar',
          action: 'Get calendar',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_calendars',
          name: 'List Calendars',
          value: 'getMany',
          description: 'List all calendars',
          action: 'List calendars',
          fields: [],
          optionalFields: [
            {
              id: 'show_hidden',
              name: 'showHidden',
              displayName: 'Show Hidden',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'show_deleted',
              name: 'showDeleted',
              displayName: 'Show Deleted',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'min_access_role',
              name: 'minAccessRole',
              displayName: 'Minimum Access Role',
              type: 'options',
              required: false,
              options: [
                { name: 'Free/Busy Reader', value: 'freeBusyReader' },
                { name: 'Reader', value: 'reader' },
                { name: 'Writer', value: 'writer' },
                { name: 'Owner', value: 'owner' },
              ],
            },
          ],
        },
        {
          id: 'update_calendar',
          name: 'Update Calendar',
          value: 'update',
          description: 'Update a calendar',
          action: 'Update calendar',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'summary',
              name: 'summary',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'timezone',
              name: 'timezone',
              displayName: 'Timezone',
              type: 'string',
              required: false,
            },
            {
              id: 'color_id',
              name: 'colorId',
              displayName: 'Color',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_calendar',
          name: 'Delete Calendar',
          value: 'delete',
          description: 'Delete a calendar',
          action: 'Delete calendar',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'clear_calendar',
          name: 'Clear Calendar',
          value: 'clear',
          description: 'Clear all events from primary calendar',
          action: 'Clear calendar',
          fields: [],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // FREE/BUSY RESOURCE
    // ============================================
    {
      id: 'freeBusy',
      name: 'Free/Busy',
      value: 'freeBusy',
      description: 'Free/Busy queries',
      operations: [
        {
          id: 'query_freebusy',
          name: 'Query Free/Busy',
          value: 'query',
          description: 'Query free/busy information',
          action: 'Query free/busy',
          fields: [
            {
              id: 'time_min',
              name: 'timeMin',
              displayName: 'Start Time',
              type: 'string',
              required: true,
              description: 'ISO 8601 datetime',
            },
            {
              id: 'time_max',
              name: 'timeMax',
              displayName: 'End Time',
              type: 'string',
              required: true,
            },
            {
              id: 'items',
              name: 'items',
              displayName: 'Calendars',
              type: 'string',
              required: true,
              description: 'Comma-separated calendar IDs or emails',
            },
          ],
          optionalFields: [
            {
              id: 'timezone',
              name: 'timezone',
              displayName: 'Timezone',
              type: 'string',
              required: false,
            },
            {
              id: 'group_expansion_max',
              name: 'groupExpansionMax',
              displayName: 'Group Expansion Max',
              type: 'number',
              required: false,
              default: 100,
            },
            {
              id: 'calendar_expansion_max',
              name: 'calendarExpansionMax',
              displayName: 'Calendar Expansion Max',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // ACL RESOURCE
    // ============================================
    {
      id: 'acl',
      name: 'Access Control',
      value: 'acl',
      description: 'Calendar sharing and access control',
      operations: [
        {
          id: 'share_calendar',
          name: 'Share Calendar',
          value: 'create',
          description: 'Share a calendar',
          action: 'Share calendar',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar ID',
              type: 'string',
              required: true,
            },
            {
              id: 'role',
              name: 'role',
              displayName: 'Role',
              type: 'options',
              required: true,
              options: [
                { name: 'Free/Busy Reader', value: 'freeBusyReader' },
                { name: 'Reader', value: 'reader' },
                { name: 'Writer', value: 'writer' },
                { name: 'Owner', value: 'owner' },
              ],
            },
            {
              id: 'scope_type',
              name: 'scopeType',
              displayName: 'Scope Type',
              type: 'options',
              required: true,
              options: [
                { name: 'User', value: 'user' },
                { name: 'Group', value: 'group' },
                { name: 'Domain', value: 'domain' },
                { name: 'Default (public)', value: 'default' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'scope_value',
              name: 'scopeValue',
              displayName: 'Email/Domain',
              type: 'string',
              required: false,
              description: 'Email address or domain',
            },
            {
              id: 'send_notifications',
              name: 'sendNotifications',
              displayName: 'Send Notification',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'list_acl',
          name: 'List Access Rules',
          value: 'getMany',
          description: 'List calendar access rules',
          action: 'List access rules',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_acl',
          name: 'Remove Access',
          value: 'delete',
          description: 'Remove calendar access',
          action: 'Remove access',
          fields: [
            {
              id: 'calendar_id',
              name: 'calendarId',
              displayName: 'Calendar ID',
              type: 'string',
              required: true,
            },
            {
              id: 'rule_id',
              name: 'ruleId',
              displayName: 'Rule ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // SETTINGS RESOURCE
    // ============================================
    {
      id: 'settings',
      name: 'Settings',
      value: 'settings',
      description: 'Calendar settings',
      operations: [
        {
          id: 'get_setting',
          name: 'Get Setting',
          value: 'get',
          description: 'Get a calendar setting',
          action: 'Get setting',
          fields: [
            {
              id: 'setting',
              name: 'setting',
              displayName: 'Setting',
              type: 'options',
              required: true,
              options: [
                { name: 'Auto Add Hangouts', value: 'autoAddHangouts' },
                { name: 'Date Field Order', value: 'dateFieldOrder' },
                { name: 'Default Event Length', value: 'defaultEventLength' },
                { name: 'Format 24 Hour Time', value: 'format24HourTime' },
                { name: 'Hide Invitations', value: 'hideInvitations' },
                { name: 'Hide Weekends', value: 'hideWeekends' },
                { name: 'Locale', value: 'locale' },
                { name: 'Remind on Responded Events Only', value: 'remindOnRespondedEventsOnly' },
                { name: 'Show Declined Events', value: 'showDeclinedEvents' },
                { name: 'Timezone', value: 'timezone' },
                { name: 'Use Keyboard Shortcuts', value: 'useKeyboardShortcuts' },
                { name: 'Week Start', value: 'weekStart' },
              ],
            },
          ],
          optionalFields: [],
        },
        {
          id: 'list_settings',
          name: 'List Settings',
          value: 'getMany',
          description: 'List all calendar settings',
          action: 'List settings',
          fields: [],
          optionalFields: [],
        },
      ],
    },
  ],
};
