/**
 * Pinterest n8n-style Schema
 */

import { N8nAppSchema } from './types';

export const pinterestSchema: N8nAppSchema = {
  id: 'pinterest',
  name: 'Pinterest',
  description: 'Pinterest visual discovery platform',
  version: '1.0.0',
  color: '#BD081C',
  icon: 'pinterest',
  group: ['social', 'marketing'],
  
  credentials: [
    {
      name: 'pinterestOAuth2',
      displayName: 'Pinterest OAuth2',
      required: true,
      type: 'oauth2',
      properties: [
        { name: 'accessToken', displayName: 'Access Token', type: 'string', required: true, typeOptions: { password: true } },
      ],
    },
  ],
  
  resources: [
    {
      id: 'pin',
      name: 'Pin',
      value: 'pin',
      description: 'Pin operations',
      operations: [
        { id: 'create', name: 'Create', value: 'create', description: 'Create pin', action: 'Create pin',
          fields: [
            { id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true },
            { id: 'mediaSource', name: 'mediaSource', displayName: 'Media Source', type: 'options', required: true, options: [{ name: 'Image URL', value: 'image_url' }, { name: 'Image Base64', value: 'image_base64' }, { name: 'Video ID', value: 'video_id' }] },
          ],
          optionalFields: [
            { id: 'title', name: 'title', displayName: 'Title', type: 'string', required: false },
            { id: 'description', name: 'description', displayName: 'Description', type: 'string', required: false },
            { id: 'link', name: 'link', displayName: 'Link', type: 'string', required: false },
            { id: 'altText', name: 'altText', displayName: 'Alt Text', type: 'string', required: false },
            { id: 'boardSectionId', name: 'boardSectionId', displayName: 'Board Section ID', type: 'string', required: false },
          ],
        },
        { id: 'get', name: 'Get', value: 'get', description: 'Get pin', action: 'Get pin',
          fields: [{ id: 'pinId', name: 'pinId', displayName: 'Pin ID', type: 'string', required: true }],
          optionalFields: [],
        },
        { id: 'delete', name: 'Delete', value: 'delete', description: 'Delete pin', action: 'Delete pin',
          fields: [{ id: 'pinId', name: 'pinId', displayName: 'Pin ID', type: 'string', required: true }],
          optionalFields: [],
        },
        { id: 'list', name: 'List User Pins', value: 'list', description: 'List user pins', action: 'List pins',
          fields: [],
          optionalFields: [
            { id: 'pageSize', name: 'pageSize', displayName: 'Page Size', type: 'number', required: false, default: 25 },
            { id: 'bookmark', name: 'bookmark', displayName: 'Bookmark', type: 'string', required: false },
          ],
        },
        { id: 'save', name: 'Save Pin', value: 'save', description: 'Save pin to board', action: 'Save pin',
          fields: [
            { id: 'pinId', name: 'pinId', displayName: 'Pin ID', type: 'string', required: true },
            { id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true },
          ],
          optionalFields: [{ id: 'boardSectionId', name: 'boardSectionId', displayName: 'Board Section ID', type: 'string', required: false }],
        },
      ],
    },
    {
      id: 'board',
      name: 'Board',
      value: 'board',
      description: 'Board operations',
      operations: [
        { id: 'create', name: 'Create', value: 'create', description: 'Create board', action: 'Create board',
          fields: [{ id: 'name', name: 'name', displayName: 'Name', type: 'string', required: true }],
          optionalFields: [
            { id: 'description', name: 'description', displayName: 'Description', type: 'string', required: false },
            { id: 'privacy', name: 'privacy', displayName: 'Privacy', type: 'options', required: false, options: [{ name: 'Public', value: 'PUBLIC' }, { name: 'Protected', value: 'PROTECTED' }, { name: 'Secret', value: 'SECRET' }] },
          ],
        },
        { id: 'get', name: 'Get', value: 'get', description: 'Get board', action: 'Get board',
          fields: [{ id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true }],
          optionalFields: [],
        },
        { id: 'update', name: 'Update', value: 'update', description: 'Update board', action: 'Update board',
          fields: [{ id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true }],
          optionalFields: [
            { id: 'name', name: 'name', displayName: 'Name', type: 'string', required: false },
            { id: 'description', name: 'description', displayName: 'Description', type: 'string', required: false },
            { id: 'privacy', name: 'privacy', displayName: 'Privacy', type: 'options', required: false, options: [{ name: 'Public', value: 'PUBLIC' }, { name: 'Protected', value: 'PROTECTED' }, { name: 'Secret', value: 'SECRET' }] },
          ],
        },
        { id: 'delete', name: 'Delete', value: 'delete', description: 'Delete board', action: 'Delete board',
          fields: [{ id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true }],
          optionalFields: [],
        },
        { id: 'list', name: 'List', value: 'list', description: 'List boards', action: 'List boards',
          fields: [],
          optionalFields: [
            { id: 'privacy', name: 'privacy', displayName: 'Privacy Filter', type: 'options', required: false, options: [{ name: 'All', value: 'ALL' }, { name: 'Public', value: 'PUBLIC' }, { name: 'Protected', value: 'PROTECTED' }, { name: 'Secret', value: 'SECRET' }] },
            { id: 'pageSize', name: 'pageSize', displayName: 'Page Size', type: 'number', required: false, default: 25 },
          ],
        },
        { id: 'listPins', name: 'List Board Pins', value: 'listPins', description: 'List pins on board', action: 'List board pins',
          fields: [{ id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true }],
          optionalFields: [{ id: 'pageSize', name: 'pageSize', displayName: 'Page Size', type: 'number', required: false, default: 25 }],
        },
      ],
    },
    {
      id: 'boardSection',
      name: 'Board Section',
      value: 'boardSection',
      description: 'Board section operations',
      operations: [
        { id: 'create', name: 'Create', value: 'create', description: 'Create section', action: 'Create section',
          fields: [
            { id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true },
            { id: 'name', name: 'name', displayName: 'Name', type: 'string', required: true },
          ],
          optionalFields: [],
        },
        { id: 'list', name: 'List', value: 'list', description: 'List sections', action: 'List sections',
          fields: [{ id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true }],
          optionalFields: [{ id: 'pageSize', name: 'pageSize', displayName: 'Page Size', type: 'number', required: false, default: 25 }],
        },
        { id: 'update', name: 'Update', value: 'update', description: 'Update section', action: 'Update section',
          fields: [
            { id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true },
            { id: 'sectionId', name: 'sectionId', displayName: 'Section ID', type: 'string', required: true },
            { id: 'name', name: 'name', displayName: 'Name', type: 'string', required: true },
          ],
          optionalFields: [],
        },
        { id: 'delete', name: 'Delete', value: 'delete', description: 'Delete section', action: 'Delete section',
          fields: [
            { id: 'boardId', name: 'boardId', displayName: 'Board ID', type: 'string', required: true },
            { id: 'sectionId', name: 'sectionId', displayName: 'Section ID', type: 'string', required: true },
          ],
          optionalFields: [],
        },
      ],
    },
    {
      id: 'user',
      name: 'User Account',
      value: 'user',
      description: 'User account operations',
      operations: [
        { id: 'get', name: 'Get Account', value: 'get', description: 'Get account info', action: 'Get account',
          fields: [],
          optionalFields: [],
        },
        { id: 'getTopPins', name: 'Get Top Pins', value: 'getTopPins', description: 'Get top pins analytics', action: 'Get top pins',
          fields: [],
          optionalFields: [
            { id: 'startDate', name: 'startDate', displayName: 'Start Date', type: 'dateTime', required: false },
            { id: 'endDate', name: 'endDate', displayName: 'End Date', type: 'dateTime', required: false },
            { id: 'sortBy', name: 'sortBy', displayName: 'Sort By', type: 'options', required: false, options: [{ name: 'Engagement', value: 'ENGAGEMENT' }, { name: 'Impression', value: 'IMPRESSION' }, { name: 'Outbound Click', value: 'OUTBOUND_CLICK' }, { name: 'Pin Click', value: 'PIN_CLICK' }, { name: 'Save', value: 'SAVE' }] },
          ],
        },
      ],
    },
    {
      id: 'media',
      name: 'Media',
      value: 'media',
      description: 'Media upload operations',
      operations: [
        { id: 'registerUpload', name: 'Register Upload', value: 'registerUpload', description: 'Register media upload', action: 'Register upload',
          fields: [{ id: 'mediaType', name: 'mediaType', displayName: 'Media Type', type: 'options', required: true, options: [{ name: 'Video', value: 'video' }] }],
          optionalFields: [],
        },
        { id: 'getStatus', name: 'Get Upload Status', value: 'getStatus', description: 'Get upload status', action: 'Get status',
          fields: [{ id: 'mediaId', name: 'mediaId', displayName: 'Media ID', type: 'string', required: true }],
          optionalFields: [],
        },
      ],
    },
  ],
};
