/**
 * Pipedrive n8n-style Schema
 * 
 * Comprehensive Pipedrive CRM API operations
 */

import { N8nAppSchema } from './types';

export const pipedriveSchema: N8nAppSchema = {
  id: 'pipedrive',
  name: 'Pipedrive',
  description: 'Pipedrive sales CRM',
  version: '1.0.0',
  color: '#17A37D',
  icon: 'pipedrive',
  group: ['crm'],
  
  credentials: [
    {
      name: 'pipedriveApi',
      displayName: 'Pipedrive API Token',
      required: true,
      type: 'apiKey',
    },
  ],
  
  resources: [
    // ============================================
    // DEAL RESOURCE
    // ============================================
    {
      id: 'deal',
      name: 'Deal',
      value: 'deal',
      description: 'Sales deals/opportunities',
      operations: [
        {
          id: 'create_deal',
          name: 'Create Deal',
          value: 'create',
          description: 'Create a new deal',
          action: 'Create a new deal',
          fields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Deal Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'value',
              name: 'value',
              displayName: 'Value',
              type: 'number',
              required: false,
            },
            {
              id: 'currency',
              name: 'currency',
              displayName: 'Currency',
              type: 'string',
              required: false,
              default: 'USD',
            },
            {
              id: 'person_id',
              name: 'person_id',
              displayName: 'Person ID',
              type: 'number',
              required: false,
            },
            {
              id: 'org_id',
              name: 'org_id',
              displayName: 'Organization ID',
              type: 'number',
              required: false,
            },
            {
              id: 'stage_id',
              name: 'stage_id',
              displayName: 'Stage ID',
              type: 'number',
              required: false,
            },
            {
              id: 'pipeline_id',
              name: 'pipeline_id',
              displayName: 'Pipeline ID',
              type: 'number',
              required: false,
            },
            {
              id: 'user_id',
              name: 'user_id',
              displayName: 'Owner User ID',
              type: 'number',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'open',
              options: [
                { name: 'Open', value: 'open' },
                { name: 'Won', value: 'won' },
                { name: 'Lost', value: 'lost' },
                { name: 'Deleted', value: 'deleted' },
              ],
            },
            {
              id: 'expected_close_date',
              name: 'expected_close_date',
              displayName: 'Expected Close Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'probability',
              name: 'probability',
              displayName: 'Probability (%)',
              type: 'number',
              required: false,
            },
            {
              id: 'visible_to',
              name: 'visible_to',
              displayName: 'Visible To',
              type: 'options',
              required: false,
              options: [
                { name: 'Owner Only', value: '1' },
                { name: 'Owner\'s Visibility Group', value: '3' },
                { name: 'Entire Company', value: '5' },
              ],
            },
          ],
        },
        {
          id: 'get_deal',
          name: 'Get Deal',
          value: 'get',
          description: 'Get a deal by ID',
          action: 'Retrieve a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_deals',
          name: 'Get Deals',
          value: 'getMany',
          description: 'Get all deals',
          action: 'List all deals',
          fields: [],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'All (not deleted)', value: 'all_not_deleted' },
                { name: 'Open', value: 'open' },
                { name: 'Won', value: 'won' },
                { name: 'Lost', value: 'lost' },
                { name: 'Deleted', value: 'deleted' },
              ],
            },
            {
              id: 'stage_id',
              name: 'stage_id',
              displayName: 'Stage ID',
              type: 'number',
              required: false,
            },
            {
              id: 'pipeline_id',
              name: 'pipeline_id',
              displayName: 'Pipeline ID',
              type: 'number',
              required: false,
            },
            {
              id: 'user_id',
              name: 'user_id',
              displayName: 'User ID',
              type: 'number',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_deal',
          name: 'Update Deal',
          value: 'update',
          description: 'Update a deal',
          action: 'Update a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Deal Title',
              type: 'string',
              required: false,
            },
            {
              id: 'value',
              name: 'value',
              displayName: 'Value',
              type: 'number',
              required: false,
            },
            {
              id: 'stage_id',
              name: 'stage_id',
              displayName: 'Stage ID',
              type: 'number',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Open', value: 'open' },
                { name: 'Won', value: 'won' },
                { name: 'Lost', value: 'lost' },
              ],
            },
            {
              id: 'lost_reason',
              name: 'lost_reason',
              displayName: 'Lost Reason',
              type: 'string',
              required: false,
              displayOptions: {
                show: {
                  status: ['lost'],
                },
              },
            },
          ],
        },
        {
          id: 'delete_deal',
          name: 'Delete Deal',
          value: 'delete',
          description: 'Delete a deal',
          action: 'Delete a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'search_deals',
          name: 'Search Deals',
          value: 'search',
          description: 'Search for deals',
          action: 'Search deals',
          fields: [
            {
              id: 'term',
              name: 'term',
              displayName: 'Search Term',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'exact_match',
              name: 'exact_match',
              displayName: 'Exact Match',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // PERSON RESOURCE
    // ============================================
    {
      id: 'person',
      name: 'Person',
      value: 'person',
      description: 'Contact persons',
      operations: [
        {
          id: 'create_person',
          name: 'Create Person',
          value: 'create',
          description: 'Create a new person',
          action: 'Create a new contact person',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'org_id',
              name: 'org_id',
              displayName: 'Organization ID',
              type: 'number',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner User ID',
              type: 'number',
              required: false,
            },
            {
              id: 'visible_to',
              name: 'visible_to',
              displayName: 'Visible To',
              type: 'options',
              required: false,
              options: [
                { name: 'Owner Only', value: '1' },
                { name: 'Owner\'s Visibility Group', value: '3' },
                { name: 'Entire Company', value: '5' },
              ],
            },
            {
              id: 'label',
              name: 'label',
              displayName: 'Label ID',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_person',
          name: 'Get Person',
          value: 'get',
          description: 'Get a person by ID',
          action: 'Retrieve a person',
          fields: [
            {
              id: 'person_id',
              name: 'personId',
              displayName: 'Person ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_persons',
          name: 'Get Persons',
          value: 'getMany',
          description: 'Get all persons',
          action: 'List all persons',
          fields: [],
          optionalFields: [
            {
              id: 'org_id',
              name: 'org_id',
              displayName: 'Organization ID',
              type: 'number',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_person',
          name: 'Update Person',
          value: 'update',
          description: 'Update a person',
          action: 'Update a person',
          fields: [
            {
              id: 'person_id',
              name: 'personId',
              displayName: 'Person ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_person',
          name: 'Delete Person',
          value: 'delete',
          description: 'Delete a person',
          action: 'Delete a person',
          fields: [
            {
              id: 'person_id',
              name: 'personId',
              displayName: 'Person ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'search_persons',
          name: 'Search Persons',
          value: 'search',
          description: 'Search for persons',
          action: 'Search persons',
          fields: [
            {
              id: 'term',
              name: 'term',
              displayName: 'Search Term',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'search_by_email',
              name: 'search_by_email',
              displayName: 'Search by Email',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // ORGANIZATION RESOURCE
    // ============================================
    {
      id: 'organization',
      name: 'Organization',
      value: 'organization',
      description: 'Companies/organizations',
      operations: [
        {
          id: 'create_organization',
          name: 'Create Organization',
          value: 'create',
          description: 'Create a new organization',
          action: 'Create a new organization',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner User ID',
              type: 'number',
              required: false,
            },
            {
              id: 'visible_to',
              name: 'visible_to',
              displayName: 'Visible To',
              type: 'options',
              required: false,
              options: [
                { name: 'Owner Only', value: '1' },
                { name: 'Owner\'s Visibility Group', value: '3' },
                { name: 'Entire Company', value: '5' },
              ],
            },
            {
              id: 'label',
              name: 'label',
              displayName: 'Label ID',
              type: 'number',
              required: false,
            },
            {
              id: 'address',
              name: 'address',
              displayName: 'Address',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_organization',
          name: 'Get Organization',
          value: 'get',
          description: 'Get an organization by ID',
          action: 'Retrieve an organization',
          fields: [
            {
              id: 'org_id',
              name: 'orgId',
              displayName: 'Organization ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_organizations',
          name: 'Get Organizations',
          value: 'getMany',
          description: 'Get all organizations',
          action: 'List all organizations',
          fields: [],
          optionalFields: [
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_organization',
          name: 'Update Organization',
          value: 'update',
          description: 'Update an organization',
          action: 'Update an organization',
          fields: [
            {
              id: 'org_id',
              name: 'orgId',
              displayName: 'Organization ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'address',
              name: 'address',
              displayName: 'Address',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_organization',
          name: 'Delete Organization',
          value: 'delete',
          description: 'Delete an organization',
          action: 'Delete an organization',
          fields: [
            {
              id: 'org_id',
              name: 'orgId',
              displayName: 'Organization ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ACTIVITY RESOURCE
    // ============================================
    {
      id: 'activity',
      name: 'Activity',
      value: 'activity',
      description: 'Tasks and activities',
      operations: [
        {
          id: 'create_activity',
          name: 'Create Activity',
          value: 'create',
          description: 'Create a new activity',
          action: 'Create a new activity',
          fields: [
            {
              id: 'subject',
              name: 'subject',
              displayName: 'Subject',
              type: 'string',
              required: true,
            },
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: true,
              options: [
                { name: 'Call', value: 'call' },
                { name: 'Meeting', value: 'meeting' },
                { name: 'Task', value: 'task' },
                { name: 'Deadline', value: 'deadline' },
                { name: 'Email', value: 'email' },
                { name: 'Lunch', value: 'lunch' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'deal_id',
              name: 'deal_id',
              displayName: 'Deal ID',
              type: 'number',
              required: false,
            },
            {
              id: 'person_id',
              name: 'person_id',
              displayName: 'Person ID',
              type: 'number',
              required: false,
            },
            {
              id: 'org_id',
              name: 'org_id',
              displayName: 'Organization ID',
              type: 'number',
              required: false,
            },
            {
              id: 'due_date',
              name: 'due_date',
              displayName: 'Due Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'due_time',
              name: 'due_time',
              displayName: 'Due Time',
              type: 'string',
              required: false,
              placeholder: 'HH:MM',
            },
            {
              id: 'duration',
              name: 'duration',
              displayName: 'Duration',
              type: 'string',
              required: false,
              placeholder: 'HH:MM',
            },
            {
              id: 'note',
              name: 'note',
              displayName: 'Note',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'user_id',
              name: 'user_id',
              displayName: 'Assigned User ID',
              type: 'number',
              required: false,
            },
            {
              id: 'done',
              name: 'done',
              displayName: 'Mark as Done',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_activities',
          name: 'Get Activities',
          value: 'getMany',
          description: 'Get all activities',
          action: 'List all activities',
          fields: [],
          optionalFields: [
            {
              id: 'deal_id',
              name: 'deal_id',
              displayName: 'Deal ID',
              type: 'number',
              required: false,
            },
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'string',
              required: false,
            },
            {
              id: 'done',
              name: 'done',
              displayName: 'Done',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: '' },
                { name: 'Done', value: '1' },
                { name: 'Not Done', value: '0' },
              ],
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_activity',
          name: 'Update Activity',
          value: 'update',
          description: 'Update an activity',
          action: 'Update an activity',
          fields: [
            {
              id: 'activity_id',
              name: 'activityId',
              displayName: 'Activity ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'subject',
              name: 'subject',
              displayName: 'Subject',
              type: 'string',
              required: false,
            },
            {
              id: 'done',
              name: 'done',
              displayName: 'Mark as Done',
              type: 'boolean',
              required: false,
            },
            {
              id: 'due_date',
              name: 'due_date',
              displayName: 'Due Date',
              type: 'dateTime',
              required: false,
            },
          ],
        },
        {
          id: 'delete_activity',
          name: 'Delete Activity',
          value: 'delete',
          description: 'Delete an activity',
          action: 'Delete an activity',
          fields: [
            {
              id: 'activity_id',
              name: 'activityId',
              displayName: 'Activity ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // NOTE RESOURCE
    // ============================================
    {
      id: 'note',
      name: 'Note',
      value: 'note',
      description: 'Notes attached to deals/persons/organizations',
      operations: [
        {
          id: 'create_note',
          name: 'Create Note',
          value: 'create',
          description: 'Create a new note',
          action: 'Create a new note',
          fields: [
            {
              id: 'content',
              name: 'content',
              displayName: 'Content',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 5,
              },
            },
          ],
          optionalFields: [
            {
              id: 'deal_id',
              name: 'deal_id',
              displayName: 'Deal ID',
              type: 'number',
              required: false,
            },
            {
              id: 'person_id',
              name: 'person_id',
              displayName: 'Person ID',
              type: 'number',
              required: false,
            },
            {
              id: 'org_id',
              name: 'org_id',
              displayName: 'Organization ID',
              type: 'number',
              required: false,
            },
            {
              id: 'pinned',
              name: 'pinned_to_deal_flag',
              displayName: 'Pin to Deal',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_notes',
          name: 'Get Notes',
          value: 'getMany',
          description: 'Get all notes',
          action: 'List all notes',
          fields: [],
          optionalFields: [
            {
              id: 'deal_id',
              name: 'deal_id',
              displayName: 'Deal ID',
              type: 'number',
              required: false,
            },
            {
              id: 'person_id',
              name: 'person_id',
              displayName: 'Person ID',
              type: 'number',
              required: false,
            },
            {
              id: 'org_id',
              name: 'org_id',
              displayName: 'Organization ID',
              type: 'number',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_note',
          name: 'Update Note',
          value: 'update',
          description: 'Update a note',
          action: 'Update a note',
          fields: [
            {
              id: 'note_id',
              name: 'noteId',
              displayName: 'Note ID',
              type: 'number',
              required: true,
            },
            {
              id: 'content',
              name: 'content',
              displayName: 'Content',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 5,
              },
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_note',
          name: 'Delete Note',
          value: 'delete',
          description: 'Delete a note',
          action: 'Delete a note',
          fields: [
            {
              id: 'note_id',
              name: 'noteId',
              displayName: 'Note ID',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // LEAD RESOURCE
    // ============================================
    {
      id: 'lead',
      name: 'Lead',
      value: 'lead',
      description: 'Sales leads',
      operations: [
        {
          id: 'create_lead',
          name: 'Create Lead',
          value: 'create',
          description: 'Create a new lead',
          action: 'Create a new lead',
          fields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Lead Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'person_id',
              name: 'person_id',
              displayName: 'Person ID',
              type: 'number',
              required: false,
            },
            {
              id: 'org_id',
              name: 'organization_id',
              displayName: 'Organization ID',
              type: 'number',
              required: false,
            },
            {
              id: 'value',
              name: 'value',
              displayName: 'Value (JSON)',
              type: 'json',
              required: false,
              placeholder: '{"amount": 1000, "currency": "USD"}',
            },
            {
              id: 'expected_close_date',
              name: 'expected_close_date',
              displayName: 'Expected Close Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'label_ids',
              name: 'label_ids',
              displayName: 'Label IDs (comma-separated)',
              type: 'string',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'owner_id',
              displayName: 'Owner User ID',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_leads',
          name: 'Get Leads',
          value: 'getMany',
          description: 'Get all leads',
          action: 'List all leads',
          fields: [],
          optionalFields: [
            {
              id: 'archived',
              name: 'archived_status',
              displayName: 'Archived Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Not Archived', value: 'not_archived' },
                { name: 'Archived', value: 'archived' },
                { name: 'All', value: 'all' },
              ],
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_lead',
          name: 'Update Lead',
          value: 'update',
          description: 'Update a lead',
          action: 'Update a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Lead Title',
              type: 'string',
              required: false,
            },
            {
              id: 'is_archived',
              name: 'is_archived',
              displayName: 'Archive Lead',
              type: 'boolean',
              required: false,
            },
          ],
        },
        {
          id: 'delete_lead',
          name: 'Delete Lead',
          value: 'delete',
          description: 'Delete a lead',
          action: 'Delete a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
