/**
 * Razorpay n8n-style Schema
 * 
 * Comprehensive Razorpay payment operations (India)
 */

import { N8nAppSchema } from './types';

export const razorpaySchema: N8nAppSchema = {
  id: 'razorpay',
  name: 'Razorpay',
  description: 'Razorpay payment gateway for India',
  version: '1.0.0',
  color: '#0066FF',
  icon: 'razorpay',
  group: ['payments'],
  
  credentials: [
    {
      name: 'razorpayApi',
      displayName: 'Razorpay API',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'keyId',
          displayName: 'Key ID',
          type: 'string',
          required: true,
          placeholder: 'rzp_live_...',
        },
        {
          name: 'keySecret',
          displayName: 'Key Secret',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // ORDER RESOURCE
    // ============================================
    {
      id: 'order',
      name: 'Order',
      value: 'order',
      description: 'Payment orders',
      operations: [
        {
          id: 'create_order',
          name: 'Create Order',
          value: 'create',
          description: 'Create a new order',
          action: 'Create an order',
          fields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount (paise)',
              type: 'number',
              required: true,
              description: 'Amount in paise (100 paise = 1 INR)',
            },
            {
              id: 'currency',
              name: 'currency',
              displayName: 'Currency',
              type: 'options',
              required: true,
              default: 'INR',
              options: [
                { name: 'INR', value: 'INR' },
                { name: 'USD', value: 'USD' },
                { name: 'EUR', value: 'EUR' },
                { name: 'GBP', value: 'GBP' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'receipt',
              name: 'receipt',
              displayName: 'Receipt ID',
              type: 'string',
              required: false,
            },
            {
              id: 'notes',
              name: 'notes',
              displayName: 'Notes (JSON)',
              type: 'json',
              required: false,
              placeholder: '{"order_id": "123", "customer_name": "John"}',
            },
            {
              id: 'partial_payment',
              name: 'partial_payment',
              displayName: 'Allow Partial Payment',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'first_payment_min_amount',
              name: 'first_payment_min_amount',
              displayName: 'First Payment Min Amount',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'get_order',
          name: 'Get Order',
          value: 'get',
          description: 'Get an order by ID',
          action: 'Retrieve an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
              placeholder: 'order_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_orders',
          name: 'Get Orders',
          value: 'getMany',
          description: 'Get all orders',
          action: 'List all orders',
          fields: [],
          optionalFields: [
            {
              id: 'from',
              name: 'from',
              displayName: 'From (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'to',
              name: 'to',
              displayName: 'To (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'skip',
              name: 'skip',
              displayName: 'Skip',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'get_order_payments',
          name: 'Get Order Payments',
          value: 'getPayments',
          description: 'Get payments for an order',
          action: 'List order payments',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // PAYMENT RESOURCE
    // ============================================
    {
      id: 'payment',
      name: 'Payment',
      value: 'payment',
      description: 'Payments',
      operations: [
        {
          id: 'get_payment',
          name: 'Get Payment',
          value: 'get',
          description: 'Get a payment by ID',
          action: 'Retrieve a payment',
          fields: [
            {
              id: 'payment_id',
              name: 'paymentId',
              displayName: 'Payment ID',
              type: 'string',
              required: true,
              placeholder: 'pay_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_payments',
          name: 'Get Payments',
          value: 'getMany',
          description: 'Get all payments',
          action: 'List all payments',
          fields: [],
          optionalFields: [
            {
              id: 'from',
              name: 'from',
              displayName: 'From (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'to',
              name: 'to',
              displayName: 'To (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'skip',
              name: 'skip',
              displayName: 'Skip',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'capture_payment',
          name: 'Capture Payment',
          value: 'capture',
          description: 'Capture a payment',
          action: 'Capture a payment',
          fields: [
            {
              id: 'payment_id',
              name: 'paymentId',
              displayName: 'Payment ID',
              type: 'string',
              required: true,
            },
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount (paise)',
              type: 'number',
              required: true,
            },
            {
              id: 'currency',
              name: 'currency',
              displayName: 'Currency',
              type: 'options',
              required: true,
              default: 'INR',
              options: [
                { name: 'INR', value: 'INR' },
                { name: 'USD', value: 'USD' },
              ],
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_payment',
          name: 'Update Payment',
          value: 'update',
          description: 'Update payment notes',
          action: 'Update a payment',
          fields: [
            {
              id: 'payment_id',
              name: 'paymentId',
              displayName: 'Payment ID',
              type: 'string',
              required: true,
            },
            {
              id: 'notes',
              name: 'notes',
              displayName: 'Notes (JSON)',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // REFUND RESOURCE
    // ============================================
    {
      id: 'refund',
      name: 'Refund',
      value: 'refund',
      description: 'Payment refunds',
      operations: [
        {
          id: 'create_refund',
          name: 'Create Refund',
          value: 'create',
          description: 'Create a refund',
          action: 'Create a refund',
          fields: [
            {
              id: 'payment_id',
              name: 'paymentId',
              displayName: 'Payment ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount (paise)',
              type: 'number',
              required: false,
              description: 'Leave empty for full refund',
            },
            {
              id: 'speed',
              name: 'speed',
              displayName: 'Speed',
              type: 'options',
              required: false,
              default: 'normal',
              options: [
                { name: 'Normal', value: 'normal' },
                { name: 'Optimum (Instant if eligible)', value: 'optimum' },
              ],
            },
            {
              id: 'notes',
              name: 'notes',
              displayName: 'Notes (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'receipt',
              name: 'receipt',
              displayName: 'Receipt',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_refund',
          name: 'Get Refund',
          value: 'get',
          description: 'Get a refund by ID',
          action: 'Retrieve a refund',
          fields: [
            {
              id: 'refund_id',
              name: 'refundId',
              displayName: 'Refund ID',
              type: 'string',
              required: true,
              placeholder: 'rfnd_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_refunds',
          name: 'Get Refunds',
          value: 'getMany',
          description: 'Get all refunds',
          action: 'List all refunds',
          fields: [],
          optionalFields: [
            {
              id: 'from',
              name: 'from',
              displayName: 'From (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'to',
              name: 'to',
              displayName: 'To (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'skip',
              name: 'skip',
              displayName: 'Skip',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'get_payment_refunds',
          name: 'Get Payment Refunds',
          value: 'getByPayment',
          description: 'Get refunds for a payment',
          action: 'List payment refunds',
          fields: [
            {
              id: 'payment_id',
              name: 'paymentId',
              displayName: 'Payment ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CUSTOMER RESOURCE
    // ============================================
    {
      id: 'customer',
      name: 'Customer',
      value: 'customer',
      description: 'Customers',
      operations: [
        {
          id: 'create_customer',
          name: 'Create Customer',
          value: 'create',
          description: 'Create a customer',
          action: 'Create a customer',
          fields: [],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'contact',
              name: 'contact',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'gstin',
              name: 'gstin',
              displayName: 'GSTIN',
              type: 'string',
              required: false,
            },
            {
              id: 'notes',
              name: 'notes',
              displayName: 'Notes (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'fail_existing',
              name: 'fail_existing',
              displayName: 'Fail if Exists',
              type: 'options',
              required: false,
              default: '1',
              options: [
                { name: 'Yes (Return error if exists)', value: '1' },
                { name: 'No (Return existing customer)', value: '0' },
              ],
            },
          ],
        },
        {
          id: 'get_customer',
          name: 'Get Customer',
          value: 'get',
          description: 'Get a customer by ID',
          action: 'Retrieve a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
              placeholder: 'cust_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_customers',
          name: 'Get Customers',
          value: 'getMany',
          description: 'Get all customers',
          action: 'List all customers',
          fields: [],
          optionalFields: [
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'skip',
              name: 'skip',
              displayName: 'Skip',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'update_customer',
          name: 'Update Customer',
          value: 'update',
          description: 'Update a customer',
          action: 'Update a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'contact',
              name: 'contact',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // SUBSCRIPTION RESOURCE
    // ============================================
    {
      id: 'subscription',
      name: 'Subscription',
      value: 'subscription',
      description: 'Recurring subscriptions',
      operations: [
        {
          id: 'create_subscription',
          name: 'Create Subscription',
          value: 'create',
          description: 'Create a subscription',
          action: 'Create a subscription',
          fields: [
            {
              id: 'plan_id',
              name: 'plan_id',
              displayName: 'Plan ID',
              type: 'string',
              required: true,
              placeholder: 'plan_...',
            },
          ],
          optionalFields: [
            {
              id: 'total_count',
              name: 'total_count',
              displayName: 'Total Count',
              type: 'number',
              required: false,
              description: 'Total billing cycles',
            },
            {
              id: 'quantity',
              name: 'quantity',
              displayName: 'Quantity',
              type: 'number',
              required: false,
              default: 1,
            },
            {
              id: 'customer_notify',
              name: 'customer_notify',
              displayName: 'Notify Customer',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'start_at',
              name: 'start_at',
              displayName: 'Start At (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'expire_by',
              name: 'expire_by',
              displayName: 'Expire By (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'notes',
              name: 'notes',
              displayName: 'Notes (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_subscription',
          name: 'Get Subscription',
          value: 'get',
          description: 'Get a subscription',
          action: 'Retrieve a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
              placeholder: 'sub_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_subscriptions',
          name: 'Get Subscriptions',
          value: 'getMany',
          description: 'Get all subscriptions',
          action: 'List subscriptions',
          fields: [],
          optionalFields: [
            {
              id: 'plan_id',
              name: 'plan_id',
              displayName: 'Plan ID',
              type: 'string',
              required: false,
            },
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'skip',
              name: 'skip',
              displayName: 'Skip',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'update_subscription',
          name: 'Update Subscription',
          value: 'update',
          description: 'Update a subscription',
          action: 'Update a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'plan_id',
              name: 'plan_id',
              displayName: 'New Plan ID',
              type: 'string',
              required: false,
            },
            {
              id: 'quantity',
              name: 'quantity',
              displayName: 'Quantity',
              type: 'number',
              required: false,
            },
            {
              id: 'schedule_change_at',
              name: 'schedule_change_at',
              displayName: 'Schedule Change At',
              type: 'options',
              required: false,
              options: [
                { name: 'Now', value: 'now' },
                { name: 'Cycle End', value: 'cycle_end' },
              ],
            },
          ],
        },
        {
          id: 'cancel_subscription',
          name: 'Cancel Subscription',
          value: 'cancel',
          description: 'Cancel a subscription',
          action: 'Cancel a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'cancel_at_cycle_end',
              name: 'cancel_at_cycle_end',
              displayName: 'Cancel at Cycle End',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'pause_subscription',
          name: 'Pause Subscription',
          value: 'pause',
          description: 'Pause a subscription',
          action: 'Pause a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'pause_at',
              name: 'pause_at',
              displayName: 'Pause At',
              type: 'options',
              required: false,
              default: 'now',
              options: [
                { name: 'Now', value: 'now' },
                { name: 'Cycle End', value: 'cycle_end' },
              ],
            },
          ],
        },
        {
          id: 'resume_subscription',
          name: 'Resume Subscription',
          value: 'resume',
          description: 'Resume a paused subscription',
          action: 'Resume a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // INVOICE RESOURCE
    // ============================================
    {
      id: 'invoice',
      name: 'Invoice',
      value: 'invoice',
      description: 'Invoices',
      operations: [
        {
          id: 'create_invoice',
          name: 'Create Invoice',
          value: 'create',
          description: 'Create an invoice',
          action: 'Create an invoice',
          fields: [
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: true,
              default: 'invoice',
              options: [
                { name: 'Invoice', value: 'invoice' },
                { name: 'Link', value: 'link' },
              ],
            },
            {
              id: 'line_items',
              name: 'line_items',
              displayName: 'Line Items (JSON)',
              type: 'json',
              required: true,
              placeholder: '[{"name": "Product", "amount": 10000}]',
            },
          ],
          optionalFields: [
            {
              id: 'customer_id',
              name: 'customer_id',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer (JSON)',
              type: 'json',
              required: false,
              placeholder: '{"name": "John", "email": "john@example.com"}',
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'expire_by',
              name: 'expire_by',
              displayName: 'Expire By (Unix Timestamp)',
              type: 'number',
              required: false,
            },
            {
              id: 'sms_notify',
              name: 'sms_notify',
              displayName: 'SMS Notify',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'email_notify',
              name: 'email_notify',
              displayName: 'Email Notify',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'currency',
              name: 'currency',
              displayName: 'Currency',
              type: 'options',
              required: false,
              default: 'INR',
              options: [
                { name: 'INR', value: 'INR' },
                { name: 'USD', value: 'USD' },
              ],
            },
            {
              id: 'notes',
              name: 'notes',
              displayName: 'Notes (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_invoice',
          name: 'Get Invoice',
          value: 'get',
          description: 'Get an invoice',
          action: 'Retrieve an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
              placeholder: 'inv_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_invoices',
          name: 'Get Invoices',
          value: 'getMany',
          description: 'Get all invoices',
          action: 'List invoices',
          fields: [],
          optionalFields: [
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Invoice', value: 'invoice' },
                { name: 'Link', value: 'link' },
              ],
            },
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'skip',
              name: 'skip',
              displayName: 'Skip',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'cancel_invoice',
          name: 'Cancel Invoice',
          value: 'cancel',
          description: 'Cancel an invoice',
          action: 'Cancel an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'issue_invoice',
          name: 'Issue Invoice',
          value: 'issue',
          description: 'Issue a draft invoice',
          action: 'Issue an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // PLAN RESOURCE
    // ============================================
    {
      id: 'plan',
      name: 'Plan',
      value: 'plan',
      description: 'Subscription plans',
      operations: [
        {
          id: 'create_plan',
          name: 'Create Plan',
          value: 'create',
          description: 'Create a plan',
          action: 'Create a plan',
          fields: [
            {
              id: 'period',
              name: 'period',
              displayName: 'Period',
              type: 'options',
              required: true,
              options: [
                { name: 'Daily', value: 'daily' },
                { name: 'Weekly', value: 'weekly' },
                { name: 'Monthly', value: 'monthly' },
                { name: 'Yearly', value: 'yearly' },
              ],
            },
            {
              id: 'interval',
              name: 'interval',
              displayName: 'Interval',
              type: 'number',
              required: true,
              default: 1,
              description: 'Number of periods between billing',
            },
            {
              id: 'item',
              name: 'item',
              displayName: 'Item (JSON)',
              type: 'json',
              required: true,
              placeholder: '{"name": "Plan Name", "amount": 50000, "currency": "INR"}',
            },
          ],
          optionalFields: [
            {
              id: 'notes',
              name: 'notes',
              displayName: 'Notes (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_plan',
          name: 'Get Plan',
          value: 'get',
          description: 'Get a plan',
          action: 'Retrieve a plan',
          fields: [
            {
              id: 'plan_id',
              name: 'planId',
              displayName: 'Plan ID',
              type: 'string',
              required: true,
              placeholder: 'plan_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_plans',
          name: 'Get Plans',
          value: 'getMany',
          description: 'Get all plans',
          action: 'List plans',
          fields: [],
          optionalFields: [
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'skip',
              name: 'skip',
              displayName: 'Skip',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
      ],
    },
  ],
};
