/**
 * Redis n8n-style Schema
 * 
 * Comprehensive Redis in-memory data store operations
 */

import { N8nAppSchema } from './types';

export const redisSchema: N8nAppSchema = {
  id: 'redis',
  name: 'Redis',
  description: 'Redis in-memory data store',
  version: '1.0.0',
  color: '#DC382D',
  icon: 'redis',
  group: ['database'],
  
  credentials: [
    {
      name: 'redisConnection',
      displayName: 'Redis Connection',
      required: true,
      type: 'custom',
      properties: [
        {
          name: 'host',
          displayName: 'Host',
          type: 'string',
          required: true,
          default: 'localhost',
        },
        {
          name: 'port',
          displayName: 'Port',
          type: 'number',
          required: true,
          default: 6379,
        },
        {
          name: 'password',
          displayName: 'Password',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'database',
          displayName: 'Database Number',
          type: 'number',
          required: false,
          default: 0,
        },
        {
          name: 'tls',
          displayName: 'TLS/SSL',
          type: 'boolean',
          required: false,
          default: false,
        },
        {
          name: 'url',
          displayName: 'Redis URL',
          type: 'string',
          required: false,
          description: 'Overrides other settings (redis://...)',
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // STRING RESOURCE
    // ============================================
    {
      id: 'string',
      name: 'String',
      value: 'string',
      description: 'String data type operations',
      operations: [
        {
          id: 'set',
          name: 'Set',
          value: 'set',
          description: 'Set a key-value pair',
          action: 'Set value',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'value',
              name: 'value',
              displayName: 'Value',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'expire',
              name: 'expire',
              displayName: 'Expire (seconds)',
              type: 'number',
              required: false,
            },
            {
              id: 'px',
              name: 'px',
              displayName: 'Expire (milliseconds)',
              type: 'number',
              required: false,
            },
            {
              id: 'nx',
              name: 'nx',
              displayName: 'Only If Not Exists',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'xx',
              name: 'xx',
              displayName: 'Only If Exists',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get',
          name: 'Get',
          value: 'get',
          description: 'Get a value by key',
          action: 'Get value',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'mset',
          name: 'Multi Set',
          value: 'mset',
          description: 'Set multiple key-value pairs',
          action: 'Multi set values',
          fields: [
            {
              id: 'key_values',
              name: 'keyValues',
              displayName: 'Key-Value Pairs',
              type: 'json',
              required: true,
              description: 'Object with key-value pairs',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'mget',
          name: 'Multi Get',
          value: 'mget',
          description: 'Get multiple values',
          action: 'Multi get values',
          fields: [
            {
              id: 'keys',
              name: 'keys',
              displayName: 'Keys',
              type: 'string',
              required: true,
              description: 'Comma-separated keys',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'incr',
          name: 'Increment',
          value: 'incr',
          description: 'Increment integer value',
          action: 'Increment value',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount',
              type: 'number',
              required: false,
              default: 1,
            },
          ],
        },
        {
          id: 'decr',
          name: 'Decrement',
          value: 'decr',
          description: 'Decrement integer value',
          action: 'Decrement value',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount',
              type: 'number',
              required: false,
              default: 1,
            },
          ],
        },
        {
          id: 'append',
          name: 'Append',
          value: 'append',
          description: 'Append to string value',
          action: 'Append value',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'value',
              name: 'value',
              displayName: 'Value to Append',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // HASH RESOURCE
    // ============================================
    {
      id: 'hash',
      name: 'Hash',
      value: 'hash',
      description: 'Hash data type operations',
      operations: [
        {
          id: 'hset',
          name: 'Hash Set',
          value: 'hset',
          description: 'Set hash field',
          action: 'Set hash field',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'field',
              name: 'field',
              displayName: 'Field',
              type: 'string',
              required: true,
            },
            {
              id: 'value',
              name: 'value',
              displayName: 'Value',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'hmset',
          name: 'Hash Multi Set',
          value: 'hmset',
          description: 'Set multiple hash fields',
          action: 'Set multiple hash fields',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'fields',
              name: 'fields',
              displayName: 'Fields',
              type: 'json',
              required: true,
              description: 'Object with field-value pairs',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'hget',
          name: 'Hash Get',
          value: 'hget',
          description: 'Get hash field',
          action: 'Get hash field',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'field',
              name: 'field',
              displayName: 'Field',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'hgetall',
          name: 'Hash Get All',
          value: 'hgetall',
          description: 'Get all hash fields',
          action: 'Get all hash fields',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'hdel',
          name: 'Hash Delete',
          value: 'hdel',
          description: 'Delete hash field',
          action: 'Delete hash field',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'fields',
              name: 'fields',
              displayName: 'Fields',
              type: 'string',
              required: true,
              description: 'Comma-separated field names',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'hincrby',
          name: 'Hash Increment',
          value: 'hincrby',
          description: 'Increment hash field',
          action: 'Increment hash field',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'field',
              name: 'field',
              displayName: 'Field',
              type: 'string',
              required: true,
            },
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'hexists',
          name: 'Hash Exists',
          value: 'hexists',
          description: 'Check if hash field exists',
          action: 'Check hash field exists',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'field',
              name: 'field',
              displayName: 'Field',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // LIST RESOURCE
    // ============================================
    {
      id: 'list',
      name: 'List',
      value: 'list',
      description: 'List data type operations',
      operations: [
        {
          id: 'lpush',
          name: 'Left Push',
          value: 'lpush',
          description: 'Push to left of list',
          action: 'Push to left',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'values',
              name: 'values',
              displayName: 'Values',
              type: 'string',
              required: true,
              description: 'Comma-separated values',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'rpush',
          name: 'Right Push',
          value: 'rpush',
          description: 'Push to right of list',
          action: 'Push to right',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'values',
              name: 'values',
              displayName: 'Values',
              type: 'string',
              required: true,
              description: 'Comma-separated values',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'lpop',
          name: 'Left Pop',
          value: 'lpop',
          description: 'Pop from left of list',
          action: 'Pop from left',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 1,
            },
          ],
        },
        {
          id: 'rpop',
          name: 'Right Pop',
          value: 'rpop',
          description: 'Pop from right of list',
          action: 'Pop from right',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 1,
            },
          ],
        },
        {
          id: 'lrange',
          name: 'List Range',
          value: 'lrange',
          description: 'Get list range',
          action: 'Get list range',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'start',
              name: 'start',
              displayName: 'Start Index',
              type: 'number',
              required: true,
              default: 0,
            },
            {
              id: 'stop',
              name: 'stop',
              displayName: 'Stop Index',
              type: 'number',
              required: true,
              default: -1,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'llen',
          name: 'List Length',
          value: 'llen',
          description: 'Get list length',
          action: 'Get list length',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'lindex',
          name: 'List Index',
          value: 'lindex',
          description: 'Get element by index',
          action: 'Get by index',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'index',
              name: 'index',
              displayName: 'Index',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'lrem',
          name: 'List Remove',
          value: 'lrem',
          description: 'Remove elements from list',
          action: 'Remove from list',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: true,
              description: '0=all, >0=from head, <0=from tail',
            },
            {
              id: 'value',
              name: 'value',
              displayName: 'Value',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // SET RESOURCE
    // ============================================
    {
      id: 'set',
      name: 'Set',
      value: 'set',
      description: 'Set data type operations',
      operations: [
        {
          id: 'sadd',
          name: 'Set Add',
          value: 'sadd',
          description: 'Add members to set',
          action: 'Add to set',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'members',
              name: 'members',
              displayName: 'Members',
              type: 'string',
              required: true,
              description: 'Comma-separated members',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'srem',
          name: 'Set Remove',
          value: 'srem',
          description: 'Remove members from set',
          action: 'Remove from set',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'members',
              name: 'members',
              displayName: 'Members',
              type: 'string',
              required: true,
              description: 'Comma-separated members',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'smembers',
          name: 'Set Members',
          value: 'smembers',
          description: 'Get all set members',
          action: 'Get set members',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'sismember',
          name: 'Set Is Member',
          value: 'sismember',
          description: 'Check if member exists',
          action: 'Check membership',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'member',
              name: 'member',
              displayName: 'Member',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'scard',
          name: 'Set Cardinality',
          value: 'scard',
          description: 'Get set size',
          action: 'Get set size',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'sunion',
          name: 'Set Union',
          value: 'sunion',
          description: 'Union of sets',
          action: 'Union sets',
          fields: [
            {
              id: 'keys',
              name: 'keys',
              displayName: 'Keys',
              type: 'string',
              required: true,
              description: 'Comma-separated keys',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'sinter',
          name: 'Set Intersection',
          value: 'sinter',
          description: 'Intersection of sets',
          action: 'Intersect sets',
          fields: [
            {
              id: 'keys',
              name: 'keys',
              displayName: 'Keys',
              type: 'string',
              required: true,
              description: 'Comma-separated keys',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'sdiff',
          name: 'Set Difference',
          value: 'sdiff',
          description: 'Difference of sets',
          action: 'Difference of sets',
          fields: [
            {
              id: 'keys',
              name: 'keys',
              displayName: 'Keys',
              type: 'string',
              required: true,
              description: 'Comma-separated keys',
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // SORTED SET RESOURCE
    // ============================================
    {
      id: 'sortedSet',
      name: 'Sorted Set',
      value: 'sortedSet',
      description: 'Sorted set data type operations',
      operations: [
        {
          id: 'zadd',
          name: 'Sorted Set Add',
          value: 'zadd',
          description: 'Add member with score',
          action: 'Add to sorted set',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'score',
              name: 'score',
              displayName: 'Score',
              type: 'number',
              required: true,
            },
            {
              id: 'member',
              name: 'member',
              displayName: 'Member',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'nx',
              name: 'nx',
              displayName: 'Only Add New',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'xx',
              name: 'xx',
              displayName: 'Only Update',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'zrange',
          name: 'Sorted Set Range',
          value: 'zrange',
          description: 'Get range by index',
          action: 'Get sorted set range',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'start',
              name: 'start',
              displayName: 'Start Index',
              type: 'number',
              required: true,
              default: 0,
            },
            {
              id: 'stop',
              name: 'stop',
              displayName: 'Stop Index',
              type: 'number',
              required: true,
              default: -1,
            },
          ],
          optionalFields: [
            {
              id: 'withscores',
              name: 'withscores',
              displayName: 'With Scores',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'rev',
              name: 'rev',
              displayName: 'Reverse',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'zrangebyscore',
          name: 'Range By Score',
          value: 'zrangebyscore',
          description: 'Get range by score',
          action: 'Get by score range',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'min',
              name: 'min',
              displayName: 'Min Score',
              type: 'string',
              required: true,
              default: '-inf',
            },
            {
              id: 'max',
              name: 'max',
              displayName: 'Max Score',
              type: 'string',
              required: true,
              default: '+inf',
            },
          ],
          optionalFields: [
            {
              id: 'withscores',
              name: 'withscores',
              displayName: 'With Scores',
              type: 'boolean',
              required: false,
            },
            {
              id: 'limit_offset',
              name: 'limitOffset',
              displayName: 'Offset',
              type: 'number',
              required: false,
            },
            {
              id: 'limit_count',
              name: 'limitCount',
              displayName: 'Count',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'zscore',
          name: 'Get Score',
          value: 'zscore',
          description: 'Get member score',
          action: 'Get score',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'member',
              name: 'member',
              displayName: 'Member',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'zrank',
          name: 'Get Rank',
          value: 'zrank',
          description: 'Get member rank',
          action: 'Get rank',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'member',
              name: 'member',
              displayName: 'Member',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'zrem',
          name: 'Sorted Set Remove',
          value: 'zrem',
          description: 'Remove members',
          action: 'Remove from sorted set',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'members',
              name: 'members',
              displayName: 'Members',
              type: 'string',
              required: true,
              description: 'Comma-separated members',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'zcard',
          name: 'Sorted Set Count',
          value: 'zcard',
          description: 'Get sorted set size',
          action: 'Get sorted set size',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // KEY RESOURCE
    // ============================================
    {
      id: 'key',
      name: 'Key',
      value: 'key',
      description: 'Key management operations',
      operations: [
        {
          id: 'del',
          name: 'Delete',
          value: 'del',
          description: 'Delete keys',
          action: 'Delete keys',
          fields: [
            {
              id: 'keys',
              name: 'keys',
              displayName: 'Keys',
              type: 'string',
              required: true,
              description: 'Comma-separated keys',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'exists',
          name: 'Exists',
          value: 'exists',
          description: 'Check if key exists',
          action: 'Check key exists',
          fields: [
            {
              id: 'keys',
              name: 'keys',
              displayName: 'Keys',
              type: 'string',
              required: true,
              description: 'Comma-separated keys',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'expire',
          name: 'Set Expiry',
          value: 'expire',
          description: 'Set key expiration',
          action: 'Set expiry',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'seconds',
              name: 'seconds',
              displayName: 'Seconds',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'ttl',
          name: 'Get TTL',
          value: 'ttl',
          description: 'Get time to live',
          action: 'Get TTL',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'persist',
          name: 'Persist',
          value: 'persist',
          description: 'Remove expiration',
          action: 'Remove expiration',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'keys',
          name: 'Keys Pattern',
          value: 'keys',
          description: 'Find keys by pattern',
          action: 'Find keys',
          fields: [
            {
              id: 'pattern',
              name: 'pattern',
              displayName: 'Pattern',
              type: 'string',
              required: true,
              default: '*',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'scan',
          name: 'Scan',
          value: 'scan',
          description: 'Incrementally iterate keys',
          action: 'Scan keys',
          fields: [
            {
              id: 'cursor',
              name: 'cursor',
              displayName: 'Cursor',
              type: 'string',
              required: true,
              default: '0',
            },
          ],
          optionalFields: [
            {
              id: 'match',
              name: 'match',
              displayName: 'Match Pattern',
              type: 'string',
              required: false,
            },
            {
              id: 'count',
              name: 'count',
              displayName: 'Count',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'type',
          name: 'Type',
          value: 'type',
          description: 'Get key type',
          action: 'Get key type',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'rename',
          name: 'Rename',
          value: 'rename',
          description: 'Rename a key',
          action: 'Rename key',
          fields: [
            {
              id: 'key',
              name: 'key',
              displayName: 'Key',
              type: 'string',
              required: true,
            },
            {
              id: 'new_key',
              name: 'newKey',
              displayName: 'New Key',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // PUB/SUB RESOURCE
    // ============================================
    {
      id: 'pubsub',
      name: 'Pub/Sub',
      value: 'pubsub',
      description: 'Publish/Subscribe operations',
      operations: [
        {
          id: 'publish',
          name: 'Publish',
          value: 'publish',
          description: 'Publish message to channel',
          action: 'Publish message',
          fields: [
            {
              id: 'channel',
              name: 'channel',
              displayName: 'Channel',
              type: 'string',
              required: true,
            },
            {
              id: 'message',
              name: 'message',
              displayName: 'Message',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // SERVER RESOURCE
    // ============================================
    {
      id: 'server',
      name: 'Server',
      value: 'server',
      description: 'Server operations',
      operations: [
        {
          id: 'info',
          name: 'Info',
          value: 'info',
          description: 'Get server information',
          action: 'Get server info',
          fields: [],
          optionalFields: [
            {
              id: 'section',
              name: 'section',
              displayName: 'Section',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: '' },
                { name: 'Server', value: 'server' },
                { name: 'Clients', value: 'clients' },
                { name: 'Memory', value: 'memory' },
                { name: 'Persistence', value: 'persistence' },
                { name: 'Stats', value: 'stats' },
                { name: 'Replication', value: 'replication' },
                { name: 'CPU', value: 'cpu' },
                { name: 'Keyspace', value: 'keyspace' },
              ],
            },
          ],
        },
        {
          id: 'dbsize',
          name: 'Database Size',
          value: 'dbsize',
          description: 'Get number of keys',
          action: 'Get database size',
          fields: [],
          optionalFields: [],
        },
        {
          id: 'flushdb',
          name: 'Flush Database',
          value: 'flushdb',
          description: 'Flush current database',
          action: 'Flush database',
          fields: [],
          optionalFields: [
            {
              id: 'async',
              name: 'async',
              displayName: 'Async',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'ping',
          name: 'Ping',
          value: 'ping',
          description: 'Ping the server',
          action: 'Ping server',
          fields: [],
          optionalFields: [],
        },
      ],
    },
  ],
};
