/**
 * REST API n8n-style Schema
 * 
 * Generic REST API / HTTP Request operations
 */

import { N8nAppSchema } from './types';

export const restApiSchema: N8nAppSchema = {
  id: 'rest-api',
  name: 'REST API',
  description: 'HTTP Request / REST API client',
  version: '1.0.0',
  color: '#2200DD',
  icon: 'http',
  group: ['developer'],
  
  credentials: [
    {
      name: 'httpAuth',
      displayName: 'HTTP Authentication',
      required: false,
      type: 'custom',
      properties: [
        {
          name: 'authType',
          displayName: 'Authentication Type',
          type: 'options',
          required: true,
          default: 'none',
          options: [
            { name: 'None', value: 'none' },
            { name: 'Basic Auth', value: 'basicAuth' },
            { name: 'Bearer Token', value: 'bearer' },
            { name: 'API Key', value: 'apiKey' },
            { name: 'OAuth2', value: 'oauth2' },
            { name: 'Digest Auth', value: 'digest' },
          ],
        },
        {
          name: 'username',
          displayName: 'Username',
          type: 'string',
          required: false,
        },
        {
          name: 'password',
          displayName: 'Password',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'token',
          displayName: 'Token',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'apiKeyName',
          displayName: 'API Key Name',
          type: 'string',
          required: false,
        },
        {
          name: 'apiKeyValue',
          displayName: 'API Key Value',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'apiKeyLocation',
          displayName: 'API Key Location',
          type: 'options',
          required: false,
          options: [
            { name: 'Header', value: 'header' },
            { name: 'Query Parameter', value: 'query' },
          ],
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // REQUEST RESOURCE
    // ============================================
    {
      id: 'request',
      name: 'HTTP Request',
      value: 'request',
      description: 'Make HTTP requests',
      operations: [
        {
          id: 'get',
          name: 'GET',
          value: 'GET',
          description: 'Make GET request',
          action: 'GET request',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
              placeholder: 'https://api.example.com/resource',
            },
          ],
          optionalFields: [
            {
              id: 'query_parameters',
              name: 'queryParameters',
              displayName: 'Query Parameters',
              type: 'json',
              required: false,
              description: 'URL query parameters as JSON object',
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
            {
              id: 'authentication',
              name: 'authentication',
              displayName: 'Authentication',
              type: 'options',
              required: false,
              options: [
                { name: 'None', value: 'none' },
                { name: 'Predefined Credential', value: 'predefined' },
                { name: 'Generic Credential', value: 'generic' },
              ],
            },
            {
              id: 'timeout',
              name: 'timeout',
              displayName: 'Timeout (ms)',
              type: 'number',
              required: false,
              default: 30000,
            },
            {
              id: 'follow_redirects',
              name: 'followRedirects',
              displayName: 'Follow Redirects',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'max_redirects',
              name: 'maxRedirects',
              displayName: 'Max Redirects',
              type: 'number',
              required: false,
              default: 5,
            },
            {
              id: 'ignore_ssl',
              name: 'ignoreSsl',
              displayName: 'Ignore SSL Issues',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'response_format',
              name: 'responseFormat',
              displayName: 'Response Format',
              type: 'options',
              required: false,
              default: 'autodetect',
              options: [
                { name: 'Autodetect', value: 'autodetect' },
                { name: 'JSON', value: 'json' },
                { name: 'Text', value: 'text' },
                { name: 'Binary', value: 'binary' },
              ],
            },
            {
              id: 'proxy',
              name: 'proxy',
              displayName: 'Proxy URL',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'post',
          name: 'POST',
          value: 'POST',
          description: 'Make POST request',
          action: 'POST request',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'body_content_type',
              name: 'bodyContentType',
              displayName: 'Body Content Type',
              type: 'options',
              required: false,
              default: 'json',
              options: [
                { name: 'JSON', value: 'json' },
                { name: 'Form Data', value: 'multipart-form-data' },
                { name: 'Form URL Encoded', value: 'form-urlencoded' },
                { name: 'Raw', value: 'raw' },
                { name: 'Binary', value: 'binary' },
                { name: 'None', value: 'none' },
              ],
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'json',
              required: false,
            },
            {
              id: 'raw_body',
              name: 'rawBody',
              displayName: 'Raw Body',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'query_parameters',
              name: 'queryParameters',
              displayName: 'Query Parameters',
              type: 'json',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
            {
              id: 'authentication',
              name: 'authentication',
              displayName: 'Authentication',
              type: 'options',
              required: false,
              options: [
                { name: 'None', value: 'none' },
                { name: 'Predefined Credential', value: 'predefined' },
                { name: 'Generic Credential', value: 'generic' },
              ],
            },
            {
              id: 'timeout',
              name: 'timeout',
              displayName: 'Timeout (ms)',
              type: 'number',
              required: false,
              default: 30000,
            },
            {
              id: 'ignore_ssl',
              name: 'ignoreSsl',
              displayName: 'Ignore SSL Issues',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'response_format',
              name: 'responseFormat',
              displayName: 'Response Format',
              type: 'options',
              required: false,
              default: 'autodetect',
              options: [
                { name: 'Autodetect', value: 'autodetect' },
                { name: 'JSON', value: 'json' },
                { name: 'Text', value: 'text' },
                { name: 'Binary', value: 'binary' },
              ],
            },
          ],
        },
        {
          id: 'put',
          name: 'PUT',
          value: 'PUT',
          description: 'Make PUT request',
          action: 'PUT request',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'body_content_type',
              name: 'bodyContentType',
              displayName: 'Body Content Type',
              type: 'options',
              required: false,
              default: 'json',
              options: [
                { name: 'JSON', value: 'json' },
                { name: 'Form Data', value: 'multipart-form-data' },
                { name: 'Form URL Encoded', value: 'form-urlencoded' },
                { name: 'Raw', value: 'raw' },
              ],
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'json',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
            {
              id: 'timeout',
              name: 'timeout',
              displayName: 'Timeout (ms)',
              type: 'number',
              required: false,
              default: 30000,
            },
          ],
        },
        {
          id: 'patch',
          name: 'PATCH',
          value: 'PATCH',
          description: 'Make PATCH request',
          action: 'PATCH request',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'body_content_type',
              name: 'bodyContentType',
              displayName: 'Body Content Type',
              type: 'options',
              required: false,
              default: 'json',
              options: [
                { name: 'JSON', value: 'json' },
                { name: 'Form Data', value: 'multipart-form-data' },
                { name: 'Form URL Encoded', value: 'form-urlencoded' },
                { name: 'Raw', value: 'raw' },
              ],
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'json',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
            {
              id: 'timeout',
              name: 'timeout',
              displayName: 'Timeout (ms)',
              type: 'number',
              required: false,
              default: 30000,
            },
          ],
        },
        {
          id: 'delete',
          name: 'DELETE',
          value: 'DELETE',
          description: 'Make DELETE request',
          action: 'DELETE request',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'query_parameters',
              name: 'queryParameters',
              displayName: 'Query Parameters',
              type: 'json',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
            {
              id: 'body',
              name: 'body',
              displayName: 'Body',
              type: 'json',
              required: false,
            },
            {
              id: 'timeout',
              name: 'timeout',
              displayName: 'Timeout (ms)',
              type: 'number',
              required: false,
              default: 30000,
            },
          ],
        },
        {
          id: 'head',
          name: 'HEAD',
          value: 'HEAD',
          description: 'Make HEAD request',
          action: 'HEAD request',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
            {
              id: 'timeout',
              name: 'timeout',
              displayName: 'Timeout (ms)',
              type: 'number',
              required: false,
              default: 30000,
            },
          ],
        },
        {
          id: 'options',
          name: 'OPTIONS',
          value: 'OPTIONS',
          description: 'Make OPTIONS request',
          action: 'OPTIONS request',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // PAGINATION RESOURCE
    // ============================================
    {
      id: 'pagination',
      name: 'Paginated Request',
      value: 'pagination',
      description: 'Handle paginated APIs',
      operations: [
        {
          id: 'cursor',
          name: 'Cursor Pagination',
          value: 'cursor',
          description: 'Cursor-based pagination',
          action: 'Cursor pagination',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
            {
              id: 'cursor_path',
              name: 'cursorPath',
              displayName: 'Cursor Path in Response',
              type: 'string',
              required: true,
              placeholder: 'meta.next_cursor',
            },
            {
              id: 'cursor_param',
              name: 'cursorParam',
              displayName: 'Cursor Parameter Name',
              type: 'string',
              required: true,
              default: 'cursor',
            },
          ],
          optionalFields: [
            {
              id: 'data_path',
              name: 'dataPath',
              displayName: 'Data Path',
              type: 'string',
              required: false,
              placeholder: 'data',
            },
            {
              id: 'max_pages',
              name: 'maxPages',
              displayName: 'Max Pages',
              type: 'number',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'offset',
          name: 'Offset Pagination',
          value: 'offset',
          description: 'Offset-based pagination',
          action: 'Offset pagination',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Page Size (Limit)',
              type: 'number',
              required: true,
              default: 100,
            },
          ],
          optionalFields: [
            {
              id: 'limit_param',
              name: 'limitParam',
              displayName: 'Limit Parameter Name',
              type: 'string',
              required: false,
              default: 'limit',
            },
            {
              id: 'offset_param',
              name: 'offsetParam',
              displayName: 'Offset Parameter Name',
              type: 'string',
              required: false,
              default: 'offset',
            },
            {
              id: 'data_path',
              name: 'dataPath',
              displayName: 'Data Path',
              type: 'string',
              required: false,
            },
            {
              id: 'total_path',
              name: 'totalPath',
              displayName: 'Total Count Path',
              type: 'string',
              required: false,
            },
            {
              id: 'max_items',
              name: 'maxItems',
              displayName: 'Max Items',
              type: 'number',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'page_number',
          name: 'Page Number Pagination',
          value: 'pageNumber',
          description: 'Page number-based pagination',
          action: 'Page number pagination',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
            {
              id: 'page_size',
              name: 'pageSize',
              displayName: 'Page Size',
              type: 'number',
              required: true,
              default: 100,
            },
          ],
          optionalFields: [
            {
              id: 'page_param',
              name: 'pageParam',
              displayName: 'Page Parameter Name',
              type: 'string',
              required: false,
              default: 'page',
            },
            {
              id: 'size_param',
              name: 'sizeParam',
              displayName: 'Size Parameter Name',
              type: 'string',
              required: false,
              default: 'per_page',
            },
            {
              id: 'start_page',
              name: 'startPage',
              displayName: 'Start Page',
              type: 'number',
              required: false,
              default: 1,
            },
            {
              id: 'data_path',
              name: 'dataPath',
              displayName: 'Data Path',
              type: 'string',
              required: false,
            },
            {
              id: 'total_pages_path',
              name: 'totalPagesPath',
              displayName: 'Total Pages Path',
              type: 'string',
              required: false,
            },
            {
              id: 'max_pages',
              name: 'maxPages',
              displayName: 'Max Pages',
              type: 'number',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'link_header',
          name: 'Link Header Pagination',
          value: 'linkHeader',
          description: 'Link header-based pagination (RFC 5988)',
          action: 'Link header pagination',
          fields: [
            {
              id: 'url',
              name: 'url',
              displayName: 'URL',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'data_path',
              name: 'dataPath',
              displayName: 'Data Path',
              type: 'string',
              required: false,
            },
            {
              id: 'max_pages',
              name: 'maxPages',
              displayName: 'Max Pages',
              type: 'number',
              required: false,
            },
            {
              id: 'headers',
              name: 'headers',
              displayName: 'Headers',
              type: 'json',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // BATCH RESOURCE
    // ============================================
    {
      id: 'batch',
      name: 'Batch Request',
      value: 'batch',
      description: 'Batch multiple requests',
      operations: [
        {
          id: 'sequential',
          name: 'Sequential Batch',
          value: 'sequential',
          description: 'Execute requests sequentially',
          action: 'Sequential batch',
          fields: [
            {
              id: 'requests',
              name: 'requests',
              displayName: 'Requests',
              type: 'json',
              required: true,
              description: 'Array of request objects',
            },
          ],
          optionalFields: [
            {
              id: 'stop_on_error',
              name: 'stopOnError',
              displayName: 'Stop on Error',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'delay_between',
              name: 'delayBetween',
              displayName: 'Delay Between Requests (ms)',
              type: 'number',
              required: false,
              default: 0,
            },
          ],
        },
        {
          id: 'parallel',
          name: 'Parallel Batch',
          value: 'parallel',
          description: 'Execute requests in parallel',
          action: 'Parallel batch',
          fields: [
            {
              id: 'requests',
              name: 'requests',
              displayName: 'Requests',
              type: 'json',
              required: true,
              description: 'Array of request objects',
            },
          ],
          optionalFields: [
            {
              id: 'max_concurrent',
              name: 'maxConcurrent',
              displayName: 'Max Concurrent',
              type: 'number',
              required: false,
              default: 5,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // RETRY RESOURCE
    // ============================================
    {
      id: 'retry',
      name: 'Retry Configuration',
      value: 'retry',
      description: 'Retry failed requests',
      operations: [
        {
          id: 'configure',
          name: 'Configure Retry',
          value: 'configure',
          description: 'Configure retry behavior',
          action: 'Configure retry',
          fields: [
            {
              id: 'max_retries',
              name: 'maxRetries',
              displayName: 'Max Retries',
              type: 'number',
              required: true,
              default: 3,
            },
          ],
          optionalFields: [
            {
              id: 'retry_on',
              name: 'retryOn',
              displayName: 'Retry On Status Codes',
              type: 'string',
              required: false,
              default: '408,429,500,502,503,504',
              description: 'Comma-separated status codes',
            },
            {
              id: 'retry_delay',
              name: 'retryDelay',
              displayName: 'Retry Delay (ms)',
              type: 'number',
              required: false,
              default: 1000,
            },
            {
              id: 'exponential_backoff',
              name: 'exponentialBackoff',
              displayName: 'Exponential Backoff',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'max_delay',
              name: 'maxDelay',
              displayName: 'Max Delay (ms)',
              type: 'number',
              required: false,
              default: 30000,
            },
          ],
        },
      ],
    },
  ],
};
