/**
 * Salesforce n8n-style Schema
 * 
 * Comprehensive Salesforce CRM API operations
 */

import { N8nAppSchema } from './types';

export const salesforceSchema: N8nAppSchema = {
  id: 'salesforce',
  name: 'Salesforce',
  description: 'Salesforce CRM automation',
  version: '1.0.0',
  color: '#00A1E0',
  icon: 'salesforce',
  group: ['crm'],
  
  credentials: [
    {
      name: 'salesforceOAuth2',
      displayName: 'Salesforce OAuth2',
      required: true,
      type: 'oauth2',
    },
  ],
  
  resources: [
    // ============================================
    // LEAD RESOURCE
    // ============================================
    {
      id: 'lead',
      name: 'Lead',
      value: 'lead',
      description: 'Sales leads',
      operations: [
        {
          id: 'create_lead',
          name: 'Create Lead',
          value: 'create',
          description: 'Create a new lead',
          action: 'Create a new lead',
          fields: [
            {
              id: 'company',
              name: 'Company',
              displayName: 'Company',
              type: 'string',
              required: true,
            },
            {
              id: 'last_name',
              name: 'LastName',
              displayName: 'Last Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'FirstName',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'mobile',
              name: 'MobilePhone',
              displayName: 'Mobile Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'title',
              name: 'Title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'website',
              name: 'Website',
              displayName: 'Website',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'Status',
              displayName: 'Lead Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Open - Not Contacted', value: 'Open - Not Contacted' },
                { name: 'Working - Contacted', value: 'Working - Contacted' },
                { name: 'Closed - Converted', value: 'Closed - Converted' },
                { name: 'Closed - Not Converted', value: 'Closed - Not Converted' },
              ],
            },
            {
              id: 'lead_source',
              name: 'LeadSource',
              displayName: 'Lead Source',
              type: 'options',
              required: false,
              options: [
                { name: 'Web', value: 'Web' },
                { name: 'Phone Inquiry', value: 'Phone Inquiry' },
                { name: 'Partner Referral', value: 'Partner Referral' },
                { name: 'Purchased List', value: 'Purchased List' },
                { name: 'Other', value: 'Other' },
              ],
            },
            {
              id: 'industry',
              name: 'Industry',
              displayName: 'Industry',
              type: 'string',
              required: false,
            },
            {
              id: 'annual_revenue',
              name: 'AnnualRevenue',
              displayName: 'Annual Revenue',
              type: 'number',
              required: false,
            },
            {
              id: 'num_employees',
              name: 'NumberOfEmployees',
              displayName: 'Number of Employees',
              type: 'number',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'street',
              name: 'Street',
              displayName: 'Street',
              type: 'string',
              required: false,
            },
            {
              id: 'city',
              name: 'City',
              displayName: 'City',
              type: 'string',
              required: false,
            },
            {
              id: 'state',
              name: 'State',
              displayName: 'State/Province',
              type: 'string',
              required: false,
            },
            {
              id: 'postal_code',
              name: 'PostalCode',
              displayName: 'Postal Code',
              type: 'string',
              required: false,
            },
            {
              id: 'country',
              name: 'Country',
              displayName: 'Country',
              type: 'string',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'OwnerId',
              displayName: 'Owner ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_lead',
          name: 'Get Lead',
          value: 'get',
          description: 'Get a lead by ID',
          action: 'Retrieve a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_leads',
          name: 'Get Leads',
          value: 'getMany',
          description: 'Get all leads',
          action: 'List all leads',
          fields: [],
          optionalFields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'SOQL Query',
              type: 'string',
              required: false,
              placeholder: "SELECT Id, Name, Email FROM Lead WHERE Status = 'Open - Not Contacted'",
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_lead',
          name: 'Update Lead',
          value: 'update',
          description: 'Update a lead',
          action: 'Update a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'FirstName',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'LastName',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'Status',
              displayName: 'Lead Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Open - Not Contacted', value: 'Open - Not Contacted' },
                { name: 'Working - Contacted', value: 'Working - Contacted' },
                { name: 'Closed - Converted', value: 'Closed - Converted' },
                { name: 'Closed - Not Converted', value: 'Closed - Not Converted' },
              ],
            },
          ],
        },
        {
          id: 'delete_lead',
          name: 'Delete Lead',
          value: 'delete',
          description: 'Delete a lead',
          action: 'Delete a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'convert_lead',
          name: 'Convert Lead',
          value: 'convert',
          description: 'Convert lead to account/contact/opportunity',
          action: 'Convert a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Existing Account ID',
              type: 'string',
              required: false,
              description: 'Merge with existing account',
            },
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Existing Contact ID',
              type: 'string',
              required: false,
            },
            {
              id: 'create_opportunity',
              name: 'createOpportunity',
              displayName: 'Create Opportunity',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'opportunity_name',
              name: 'opportunityName',
              displayName: 'Opportunity Name',
              type: 'string',
              required: false,
            },
            {
              id: 'owner_id',
              name: 'ownerId',
              displayName: 'New Owner ID',
              type: 'string',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // CONTACT RESOURCE
    // ============================================
    {
      id: 'contact',
      name: 'Contact',
      value: 'contact',
      description: 'Contact records',
      operations: [
        {
          id: 'create_contact',
          name: 'Create Contact',
          value: 'create',
          description: 'Create a new contact',
          action: 'Create a new contact',
          fields: [
            {
              id: 'last_name',
              name: 'LastName',
              displayName: 'Last Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'FirstName',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'account_id',
              name: 'AccountId',
              displayName: 'Account ID',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'mobile',
              name: 'MobilePhone',
              displayName: 'Mobile Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'title',
              name: 'Title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'department',
              name: 'Department',
              displayName: 'Department',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_street',
              name: 'MailingStreet',
              displayName: 'Mailing Street',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_city',
              name: 'MailingCity',
              displayName: 'Mailing City',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_state',
              name: 'MailingState',
              displayName: 'Mailing State',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_postal_code',
              name: 'MailingPostalCode',
              displayName: 'Mailing Postal Code',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_country',
              name: 'MailingCountry',
              displayName: 'Mailing Country',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
          ],
        },
        {
          id: 'get_contact',
          name: 'Get Contact',
          value: 'get',
          description: 'Get a contact by ID',
          action: 'Retrieve a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_contacts',
          name: 'Get Contacts',
          value: 'getMany',
          description: 'Get all contacts',
          action: 'List all contacts',
          fields: [],
          optionalFields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: false,
              description: 'Filter by account',
            },
            {
              id: 'query',
              name: 'query',
              displayName: 'SOQL Query',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_contact',
          name: 'Update Contact',
          value: 'update',
          description: 'Update a contact',
          action: 'Update a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'FirstName',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'LastName',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_contact',
          name: 'Delete Contact',
          value: 'delete',
          description: 'Delete a contact',
          action: 'Delete a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ACCOUNT RESOURCE
    // ============================================
    {
      id: 'account',
      name: 'Account',
      value: 'account',
      description: 'Account/company records',
      operations: [
        {
          id: 'create_account',
          name: 'Create Account',
          value: 'create',
          description: 'Create a new account',
          action: 'Create a new account',
          fields: [
            {
              id: 'name',
              name: 'Name',
              displayName: 'Account Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'type',
              name: 'Type',
              displayName: 'Account Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Prospect', value: 'Prospect' },
                { name: 'Customer - Direct', value: 'Customer - Direct' },
                { name: 'Customer - Channel', value: 'Customer - Channel' },
                { name: 'Channel Partner / Reseller', value: 'Channel Partner / Reseller' },
                { name: 'Installation Partner', value: 'Installation Partner' },
                { name: 'Technology Partner', value: 'Technology Partner' },
                { name: 'Other', value: 'Other' },
              ],
            },
            {
              id: 'industry',
              name: 'Industry',
              displayName: 'Industry',
              type: 'string',
              required: false,
            },
            {
              id: 'website',
              name: 'Website',
              displayName: 'Website',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'annual_revenue',
              name: 'AnnualRevenue',
              displayName: 'Annual Revenue',
              type: 'number',
              required: false,
            },
            {
              id: 'num_employees',
              name: 'NumberOfEmployees',
              displayName: 'Number of Employees',
              type: 'number',
              required: false,
            },
            {
              id: 'billing_street',
              name: 'BillingStreet',
              displayName: 'Billing Street',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_city',
              name: 'BillingCity',
              displayName: 'Billing City',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_state',
              name: 'BillingState',
              displayName: 'Billing State',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_postal_code',
              name: 'BillingPostalCode',
              displayName: 'Billing Postal Code',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_country',
              name: 'BillingCountry',
              displayName: 'Billing Country',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'owner_id',
              name: 'OwnerId',
              displayName: 'Owner ID',
              type: 'string',
              required: false,
            },
            {
              id: 'parent_id',
              name: 'ParentId',
              displayName: 'Parent Account ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_account',
          name: 'Get Account',
          value: 'get',
          description: 'Get an account by ID',
          action: 'Retrieve an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_accounts',
          name: 'Get Accounts',
          value: 'getMany',
          description: 'Get all accounts',
          action: 'List all accounts',
          fields: [],
          optionalFields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'SOQL Query',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_account',
          name: 'Update Account',
          value: 'update',
          description: 'Update an account',
          action: 'Update an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'Name',
              displayName: 'Account Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'website',
              name: 'Website',
              displayName: 'Website',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_account',
          name: 'Delete Account',
          value: 'delete',
          description: 'Delete an account',
          action: 'Delete an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // OPPORTUNITY RESOURCE
    // ============================================
    {
      id: 'opportunity',
      name: 'Opportunity',
      value: 'opportunity',
      description: 'Sales opportunities',
      operations: [
        {
          id: 'create_opportunity',
          name: 'Create Opportunity',
          value: 'create',
          description: 'Create a new opportunity',
          action: 'Create a new opportunity',
          fields: [
            {
              id: 'name',
              name: 'Name',
              displayName: 'Opportunity Name',
              type: 'string',
              required: true,
            },
            {
              id: 'stage_name',
              name: 'StageName',
              displayName: 'Stage',
              type: 'options',
              required: true,
              options: [
                { name: 'Prospecting', value: 'Prospecting' },
                { name: 'Qualification', value: 'Qualification' },
                { name: 'Needs Analysis', value: 'Needs Analysis' },
                { name: 'Value Proposition', value: 'Value Proposition' },
                { name: 'Id. Decision Makers', value: 'Id. Decision Makers' },
                { name: 'Perception Analysis', value: 'Perception Analysis' },
                { name: 'Proposal/Price Quote', value: 'Proposal/Price Quote' },
                { name: 'Negotiation/Review', value: 'Negotiation/Review' },
                { name: 'Closed Won', value: 'Closed Won' },
                { name: 'Closed Lost', value: 'Closed Lost' },
              ],
            },
            {
              id: 'close_date',
              name: 'CloseDate',
              displayName: 'Close Date',
              type: 'dateTime',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'account_id',
              name: 'AccountId',
              displayName: 'Account ID',
              type: 'string',
              required: false,
            },
            {
              id: 'amount',
              name: 'Amount',
              displayName: 'Amount',
              type: 'number',
              required: false,
            },
            {
              id: 'probability',
              name: 'Probability',
              displayName: 'Probability (%)',
              type: 'number',
              required: false,
            },
            {
              id: 'type',
              name: 'Type',
              displayName: 'Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Existing Customer - Upgrade', value: 'Existing Customer - Upgrade' },
                { name: 'Existing Customer - Replacement', value: 'Existing Customer - Replacement' },
                { name: 'Existing Customer - Downgrade', value: 'Existing Customer - Downgrade' },
                { name: 'New Customer', value: 'New Customer' },
              ],
            },
            {
              id: 'lead_source',
              name: 'LeadSource',
              displayName: 'Lead Source',
              type: 'options',
              required: false,
              options: [
                { name: 'Web', value: 'Web' },
                { name: 'Phone Inquiry', value: 'Phone Inquiry' },
                { name: 'Partner Referral', value: 'Partner Referral' },
                { name: 'Purchased List', value: 'Purchased List' },
                { name: 'Other', value: 'Other' },
              ],
            },
            {
              id: 'next_step',
              name: 'NextStep',
              displayName: 'Next Step',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'owner_id',
              name: 'OwnerId',
              displayName: 'Owner ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_opportunity',
          name: 'Get Opportunity',
          value: 'get',
          description: 'Get an opportunity by ID',
          action: 'Retrieve an opportunity',
          fields: [
            {
              id: 'opportunity_id',
              name: 'opportunityId',
              displayName: 'Opportunity ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_opportunities',
          name: 'Get Opportunities',
          value: 'getMany',
          description: 'Get all opportunities',
          action: 'List all opportunities',
          fields: [],
          optionalFields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: false,
            },
            {
              id: 'stage',
              name: 'stageName',
              displayName: 'Stage',
              type: 'string',
              required: false,
            },
            {
              id: 'query',
              name: 'query',
              displayName: 'SOQL Query',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_opportunity',
          name: 'Update Opportunity',
          value: 'update',
          description: 'Update an opportunity',
          action: 'Update an opportunity',
          fields: [
            {
              id: 'opportunity_id',
              name: 'opportunityId',
              displayName: 'Opportunity ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'Name',
              displayName: 'Opportunity Name',
              type: 'string',
              required: false,
            },
            {
              id: 'stage_name',
              name: 'StageName',
              displayName: 'Stage',
              type: 'options',
              required: false,
              options: [
                { name: 'Prospecting', value: 'Prospecting' },
                { name: 'Qualification', value: 'Qualification' },
                { name: 'Closed Won', value: 'Closed Won' },
                { name: 'Closed Lost', value: 'Closed Lost' },
              ],
            },
            {
              id: 'amount',
              name: 'Amount',
              displayName: 'Amount',
              type: 'number',
              required: false,
            },
            {
              id: 'close_date',
              name: 'CloseDate',
              displayName: 'Close Date',
              type: 'dateTime',
              required: false,
            },
          ],
        },
        {
          id: 'delete_opportunity',
          name: 'Delete Opportunity',
          value: 'delete',
          description: 'Delete an opportunity',
          action: 'Delete an opportunity',
          fields: [
            {
              id: 'opportunity_id',
              name: 'opportunityId',
              displayName: 'Opportunity ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // TASK RESOURCE
    // ============================================
    {
      id: 'task',
      name: 'Task',
      value: 'task',
      description: 'Tasks and activities',
      operations: [
        {
          id: 'create_task',
          name: 'Create Task',
          value: 'create',
          description: 'Create a new task',
          action: 'Create a new task',
          fields: [
            {
              id: 'subject',
              name: 'Subject',
              displayName: 'Subject',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'what_id',
              name: 'WhatId',
              displayName: 'Related To (ID)',
              type: 'string',
              required: false,
              description: 'Account, Opportunity, or other record',
            },
            {
              id: 'who_id',
              name: 'WhoId',
              displayName: 'Name (Contact/Lead ID)',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'Status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'Not Started',
              options: [
                { name: 'Not Started', value: 'Not Started' },
                { name: 'In Progress', value: 'In Progress' },
                { name: 'Completed', value: 'Completed' },
                { name: 'Waiting on someone else', value: 'Waiting on someone else' },
                { name: 'Deferred', value: 'Deferred' },
              ],
            },
            {
              id: 'priority',
              name: 'Priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              default: 'Normal',
              options: [
                { name: 'High', value: 'High' },
                { name: 'Normal', value: 'Normal' },
                { name: 'Low', value: 'Low' },
              ],
            },
            {
              id: 'activity_date',
              name: 'ActivityDate',
              displayName: 'Due Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'owner_id',
              name: 'OwnerId',
              displayName: 'Owner ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_tasks',
          name: 'Get Tasks',
          value: 'getMany',
          description: 'Get all tasks',
          action: 'List all tasks',
          fields: [],
          optionalFields: [
            {
              id: 'what_id',
              name: 'whatId',
              displayName: 'Related To (ID)',
              type: 'string',
              required: false,
            },
            {
              id: 'who_id',
              name: 'whoId',
              displayName: 'Contact/Lead ID',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_task',
          name: 'Update Task',
          value: 'update',
          description: 'Update a task',
          action: 'Update a task',
          fields: [
            {
              id: 'task_id',
              name: 'taskId',
              displayName: 'Task ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'subject',
              name: 'Subject',
              displayName: 'Subject',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'Status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Not Started', value: 'Not Started' },
                { name: 'In Progress', value: 'In Progress' },
                { name: 'Completed', value: 'Completed' },
              ],
            },
            {
              id: 'priority',
              name: 'Priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              options: [
                { name: 'High', value: 'High' },
                { name: 'Normal', value: 'Normal' },
                { name: 'Low', value: 'Low' },
              ],
            },
          ],
        },
        {
          id: 'delete_task',
          name: 'Delete Task',
          value: 'delete',
          description: 'Delete a task',
          action: 'Delete a task',
          fields: [
            {
              id: 'task_id',
              name: 'taskId',
              displayName: 'Task ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CASE RESOURCE
    // ============================================
    {
      id: 'case',
      name: 'Case',
      value: 'case',
      description: 'Support cases',
      operations: [
        {
          id: 'create_case',
          name: 'Create Case',
          value: 'create',
          description: 'Create a support case',
          action: 'Create a new case',
          fields: [
            {
              id: 'subject',
              name: 'Subject',
              displayName: 'Subject',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'account_id',
              name: 'AccountId',
              displayName: 'Account ID',
              type: 'string',
              required: false,
            },
            {
              id: 'contact_id',
              name: 'ContactId',
              displayName: 'Contact ID',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'Status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'New',
              options: [
                { name: 'New', value: 'New' },
                { name: 'Working', value: 'Working' },
                { name: 'Escalated', value: 'Escalated' },
                { name: 'Closed', value: 'Closed' },
              ],
            },
            {
              id: 'priority',
              name: 'Priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              default: 'Medium',
              options: [
                { name: 'High', value: 'High' },
                { name: 'Medium', value: 'Medium' },
                { name: 'Low', value: 'Low' },
              ],
            },
            {
              id: 'origin',
              name: 'Origin',
              displayName: 'Case Origin',
              type: 'options',
              required: false,
              options: [
                { name: 'Phone', value: 'Phone' },
                { name: 'Email', value: 'Email' },
                { name: 'Web', value: 'Web' },
              ],
            },
            {
              id: 'type',
              name: 'Type',
              displayName: 'Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Problem', value: 'Problem' },
                { name: 'Feature Request', value: 'Feature Request' },
                { name: 'Question', value: 'Question' },
              ],
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
          ],
        },
        {
          id: 'get_cases',
          name: 'Get Cases',
          value: 'getMany',
          description: 'Get all cases',
          action: 'List all cases',
          fields: [],
          optionalFields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'string',
              required: false,
            },
            {
              id: 'query',
              name: 'query',
              displayName: 'SOQL Query',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_case',
          name: 'Update Case',
          value: 'update',
          description: 'Update a case',
          action: 'Update a case',
          fields: [
            {
              id: 'case_id',
              name: 'caseId',
              displayName: 'Case ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'status',
              name: 'Status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'New', value: 'New' },
                { name: 'Working', value: 'Working' },
                { name: 'Escalated', value: 'Escalated' },
                { name: 'Closed', value: 'Closed' },
              ],
            },
            {
              id: 'priority',
              name: 'Priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              options: [
                { name: 'High', value: 'High' },
                { name: 'Medium', value: 'Medium' },
                { name: 'Low', value: 'Low' },
              ],
            },
          ],
        },
      ],
    },
    
    // ============================================
    // CUSTOM OBJECT RESOURCE
    // ============================================
    {
      id: 'custom',
      name: 'Custom Object',
      value: 'custom',
      description: 'Custom Salesforce objects',
      operations: [
        {
          id: 'query',
          name: 'SOQL Query',
          value: 'query',
          description: 'Execute a SOQL query',
          action: 'Execute a custom SOQL query',
          fields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'SOQL Query',
              type: 'string',
              required: true,
              placeholder: 'SELECT Id, Name FROM Account WHERE Industry = \'Technology\'',
              typeOptions: {
                rows: 3,
              },
            },
          ],
          optionalFields: [],
        },
        {
          id: 'create_record',
          name: 'Create Record',
          value: 'create',
          description: 'Create a custom object record',
          action: 'Create a record in any object',
          fields: [
            {
              id: 'object_name',
              name: 'objectName',
              displayName: 'Object API Name',
              type: 'string',
              required: true,
              placeholder: 'Custom_Object__c',
            },
            {
              id: 'fields',
              name: 'fields',
              displayName: 'Field Values (JSON)',
              type: 'json',
              required: true,
              placeholder: '{"Name": "Test", "Custom_Field__c": "Value"}',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_record',
          name: 'Update Record',
          value: 'update',
          description: 'Update a custom object record',
          action: 'Update a record in any object',
          fields: [
            {
              id: 'object_name',
              name: 'objectName',
              displayName: 'Object API Name',
              type: 'string',
              required: true,
            },
            {
              id: 'record_id',
              name: 'recordId',
              displayName: 'Record ID',
              type: 'string',
              required: true,
            },
            {
              id: 'fields',
              name: 'fields',
              displayName: 'Field Values (JSON)',
              type: 'json',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'delete_record',
          name: 'Delete Record',
          value: 'delete',
          description: 'Delete a custom object record',
          action: 'Delete a record from any object',
          fields: [
            {
              id: 'object_name',
              name: 'objectName',
              displayName: 'Object API Name',
              type: 'string',
              required: true,
            },
            {
              id: 'record_id',
              name: 'recordId',
              displayName: 'Record ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
