/**
 * Shopify n8n-style Schema
 * 
 * Comprehensive Shopify e-commerce API operations
 */

import { N8nAppSchema } from './types';

export const shopifySchema: N8nAppSchema = {
  id: 'shopify',
  name: 'Shopify',
  description: 'Shopify e-commerce platform',
  version: '1.0.0',
  color: '#96BF48',
  icon: 'shopify',
  group: ['ecommerce'],
  
  credentials: [
    {
      name: 'shopifyApi',
      displayName: 'Shopify API',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'shopName',
          displayName: 'Shop Name',
          type: 'string',
          required: true,
          placeholder: 'mystore',
        },
        {
          name: 'apiKey',
          displayName: 'API Key',
          type: 'string',
          required: true,
        },
        {
          name: 'password',
          displayName: 'Password/Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // PRODUCT RESOURCE
    // ============================================
    {
      id: 'product',
      name: 'Product',
      value: 'product',
      description: 'Products in your store',
      operations: [
        {
          id: 'create_product',
          name: 'Create Product',
          value: 'create',
          description: 'Create a new product',
          action: 'Create a new product',
          fields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'body_html',
              name: 'body_html',
              displayName: 'Description (HTML)',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'vendor',
              name: 'vendor',
              displayName: 'Vendor',
              type: 'string',
              required: false,
            },
            {
              id: 'product_type',
              name: 'product_type',
              displayName: 'Product Type',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'active',
              options: [
                { name: 'Active', value: 'active' },
                { name: 'Archived', value: 'archived' },
                { name: 'Draft', value: 'draft' },
              ],
            },
            {
              id: 'tags',
              name: 'tags',
              displayName: 'Tags',
              type: 'string',
              required: false,
              description: 'Comma-separated tags',
            },
            {
              id: 'template_suffix',
              name: 'template_suffix',
              displayName: 'Template Suffix',
              type: 'string',
              required: false,
            },
            {
              id: 'published_scope',
              name: 'published_scope',
              displayName: 'Published Scope',
              type: 'options',
              required: false,
              default: 'web',
              options: [
                { name: 'Web Only', value: 'web' },
                { name: 'Global (Web + POS)', value: 'global' },
              ],
            },
            {
              id: 'variants',
              name: 'variants',
              displayName: 'Variants (JSON)',
              type: 'json',
              required: false,
              placeholder: '[{"price": "10.00", "sku": "SKU001"}]',
            },
            {
              id: 'images',
              name: 'images',
              displayName: 'Images (JSON)',
              type: 'json',
              required: false,
              placeholder: '[{"src": "https://example.com/image.jpg"}]',
            },
            {
              id: 'options',
              name: 'options',
              displayName: 'Options (JSON)',
              type: 'json',
              required: false,
              placeholder: '[{"name": "Size", "values": ["S", "M", "L"]}]',
            },
          ],
        },
        {
          id: 'get_product',
          name: 'Get Product',
          value: 'get',
          description: 'Get a product by ID',
          action: 'Retrieve a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_products',
          name: 'Get Products',
          value: 'getMany',
          description: 'Get all products',
          action: 'List all products',
          fields: [],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: 'any' },
                { name: 'Active', value: 'active' },
                { name: 'Archived', value: 'archived' },
                { name: 'Draft', value: 'draft' },
              ],
            },
            {
              id: 'collection_id',
              name: 'collection_id',
              displayName: 'Collection ID',
              type: 'string',
              required: false,
            },
            {
              id: 'vendor',
              name: 'vendor',
              displayName: 'Vendor',
              type: 'string',
              required: false,
            },
            {
              id: 'product_type',
              name: 'product_type',
              displayName: 'Product Type',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_product',
          name: 'Update Product',
          value: 'update',
          description: 'Update a product',
          action: 'Update a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'title',
              name: 'title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'body_html',
              name: 'body_html',
              displayName: 'Description (HTML)',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Active', value: 'active' },
                { name: 'Archived', value: 'archived' },
                { name: 'Draft', value: 'draft' },
              ],
            },
            {
              id: 'tags',
              name: 'tags',
              displayName: 'Tags',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_product',
          name: 'Delete Product',
          value: 'delete',
          description: 'Delete a product',
          action: 'Delete a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ORDER RESOURCE
    // ============================================
    {
      id: 'order',
      name: 'Order',
      value: 'order',
      description: 'Customer orders',
      operations: [
        {
          id: 'create_order',
          name: 'Create Order',
          value: 'create',
          description: 'Create a new order',
          action: 'Create a new order',
          fields: [
            {
              id: 'line_items',
              name: 'line_items',
              displayName: 'Line Items (JSON)',
              type: 'json',
              required: true,
              placeholder: '[{"variant_id": 123, "quantity": 1}]',
            },
          ],
          optionalFields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer (JSON)',
              type: 'json',
              required: false,
              placeholder: '{"id": 123} or {"email": "customer@example.com"}',
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'shipping_address',
              name: 'shipping_address',
              displayName: 'Shipping Address (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'billing_address',
              name: 'billing_address',
              displayName: 'Billing Address (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'financial_status',
              name: 'financial_status',
              displayName: 'Financial Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Pending', value: 'pending' },
                { name: 'Authorized', value: 'authorized' },
                { name: 'Partially Paid', value: 'partially_paid' },
                { name: 'Paid', value: 'paid' },
                { name: 'Partially Refunded', value: 'partially_refunded' },
                { name: 'Refunded', value: 'refunded' },
                { name: 'Voided', value: 'voided' },
              ],
            },
            {
              id: 'send_receipt',
              name: 'send_receipt',
              displayName: 'Send Receipt',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'send_fulfillment_receipt',
              name: 'send_fulfillment_receipt',
              displayName: 'Send Fulfillment Receipt',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'tags',
              name: 'tags',
              displayName: 'Tags',
              type: 'string',
              required: false,
            },
            {
              id: 'note',
              name: 'note',
              displayName: 'Note',
              type: 'string',
              required: false,
            },
            {
              id: 'discount_codes',
              name: 'discount_codes',
              displayName: 'Discount Codes (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_order',
          name: 'Get Order',
          value: 'get',
          description: 'Get an order by ID',
          action: 'Retrieve an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_orders',
          name: 'Get Orders',
          value: 'getMany',
          description: 'Get all orders',
          action: 'List all orders',
          fields: [],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'any',
              options: [
                { name: 'Any', value: 'any' },
                { name: 'Open', value: 'open' },
                { name: 'Closed', value: 'closed' },
                { name: 'Cancelled', value: 'cancelled' },
              ],
            },
            {
              id: 'financial_status',
              name: 'financial_status',
              displayName: 'Financial Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Any', value: 'any' },
                { name: 'Pending', value: 'pending' },
                { name: 'Authorized', value: 'authorized' },
                { name: 'Paid', value: 'paid' },
                { name: 'Refunded', value: 'refunded' },
              ],
            },
            {
              id: 'fulfillment_status',
              name: 'fulfillment_status',
              displayName: 'Fulfillment Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Any', value: 'any' },
                { name: 'Shipped', value: 'shipped' },
                { name: 'Partial', value: 'partial' },
                { name: 'Unshipped', value: 'unshipped' },
                { name: 'Unfulfilled', value: 'unfulfilled' },
              ],
            },
            {
              id: 'created_at_min',
              name: 'created_at_min',
              displayName: 'Created After',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'created_at_max',
              name: 'created_at_max',
              displayName: 'Created Before',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_order',
          name: 'Update Order',
          value: 'update',
          description: 'Update an order',
          action: 'Update an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'note',
              name: 'note',
              displayName: 'Note',
              type: 'string',
              required: false,
            },
            {
              id: 'tags',
              name: 'tags',
              displayName: 'Tags',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'shipping_address',
              name: 'shipping_address',
              displayName: 'Shipping Address (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'cancel_order',
          name: 'Cancel Order',
          value: 'cancel',
          description: 'Cancel an order',
          action: 'Cancel an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'reason',
              name: 'reason',
              displayName: 'Reason',
              type: 'options',
              required: false,
              options: [
                { name: 'Customer', value: 'customer' },
                { name: 'Declined', value: 'declined' },
                { name: 'Fraud', value: 'fraud' },
                { name: 'Inventory', value: 'inventory' },
                { name: 'Other', value: 'other' },
              ],
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Send Email',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'restock',
              name: 'restock',
              displayName: 'Restock Items',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'close_order',
          name: 'Close Order',
          value: 'close',
          description: 'Close an order',
          action: 'Close an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CUSTOMER RESOURCE
    // ============================================
    {
      id: 'customer',
      name: 'Customer',
      value: 'customer',
      description: 'Store customers',
      operations: [
        {
          id: 'create_customer',
          name: 'Create Customer',
          value: 'create',
          description: 'Create a new customer',
          action: 'Create a new customer',
          fields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'verified_email',
              name: 'verified_email',
              displayName: 'Verified Email',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'send_email_invite',
              name: 'send_email_invite',
              displayName: 'Send Email Invite',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'tags',
              name: 'tags',
              displayName: 'Tags',
              type: 'string',
              required: false,
            },
            {
              id: 'note',
              name: 'note',
              displayName: 'Note',
              type: 'string',
              required: false,
            },
            {
              id: 'accepts_marketing',
              name: 'accepts_marketing',
              displayName: 'Accepts Marketing',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'addresses',
              name: 'addresses',
              displayName: 'Addresses (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_customer',
          name: 'Get Customer',
          value: 'get',
          description: 'Get a customer by ID',
          action: 'Retrieve a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_customers',
          name: 'Get Customers',
          value: 'getMany',
          description: 'Get all customers',
          action: 'List all customers',
          fields: [],
          optionalFields: [
            {
              id: 'created_at_min',
              name: 'created_at_min',
              displayName: 'Created After',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'updated_at_min',
              name: 'updated_at_min',
              displayName: 'Updated After',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'update_customer',
          name: 'Update Customer',
          value: 'update',
          description: 'Update a customer',
          action: 'Update a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'tags',
              name: 'tags',
              displayName: 'Tags',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_customer',
          name: 'Delete Customer',
          value: 'delete',
          description: 'Delete a customer',
          action: 'Delete a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'search_customers',
          name: 'Search Customers',
          value: 'search',
          description: 'Search for customers',
          action: 'Search customers',
          fields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Search Query',
              type: 'string',
              required: true,
              placeholder: 'email:test@example.com',
            },
          ],
          optionalFields: [
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // INVENTORY RESOURCE
    // ============================================
    {
      id: 'inventory',
      name: 'Inventory',
      value: 'inventory',
      description: 'Inventory levels',
      operations: [
        {
          id: 'get_inventory_levels',
          name: 'Get Inventory Levels',
          value: 'getMany',
          description: 'Get inventory levels',
          action: 'List inventory levels',
          fields: [],
          optionalFields: [
            {
              id: 'inventory_item_ids',
              name: 'inventory_item_ids',
              displayName: 'Inventory Item IDs',
              type: 'string',
              required: false,
              description: 'Comma-separated IDs',
            },
            {
              id: 'location_ids',
              name: 'location_ids',
              displayName: 'Location IDs',
              type: 'string',
              required: false,
              description: 'Comma-separated IDs',
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'adjust_inventory',
          name: 'Adjust Inventory',
          value: 'adjust',
          description: 'Adjust inventory level',
          action: 'Adjust inventory quantity',
          fields: [
            {
              id: 'inventory_item_id',
              name: 'inventory_item_id',
              displayName: 'Inventory Item ID',
              type: 'string',
              required: true,
            },
            {
              id: 'location_id',
              name: 'location_id',
              displayName: 'Location ID',
              type: 'string',
              required: true,
            },
            {
              id: 'adjustment',
              name: 'available_adjustment',
              displayName: 'Adjustment',
              type: 'number',
              required: true,
              description: 'Positive to add, negative to subtract',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'set_inventory',
          name: 'Set Inventory',
          value: 'set',
          description: 'Set inventory level',
          action: 'Set inventory quantity',
          fields: [
            {
              id: 'inventory_item_id',
              name: 'inventory_item_id',
              displayName: 'Inventory Item ID',
              type: 'string',
              required: true,
            },
            {
              id: 'location_id',
              name: 'location_id',
              displayName: 'Location ID',
              type: 'string',
              required: true,
            },
            {
              id: 'available',
              name: 'available',
              displayName: 'Available Quantity',
              type: 'number',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // FULFILLMENT RESOURCE
    // ============================================
    {
      id: 'fulfillment',
      name: 'Fulfillment',
      value: 'fulfillment',
      description: 'Order fulfillments',
      operations: [
        {
          id: 'create_fulfillment',
          name: 'Create Fulfillment',
          value: 'create',
          description: 'Create a fulfillment',
          action: 'Fulfill an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'location_id',
              name: 'location_id',
              displayName: 'Location ID',
              type: 'string',
              required: false,
            },
            {
              id: 'tracking_number',
              name: 'tracking_number',
              displayName: 'Tracking Number',
              type: 'string',
              required: false,
            },
            {
              id: 'tracking_company',
              name: 'tracking_company',
              displayName: 'Tracking Company',
              type: 'string',
              required: false,
            },
            {
              id: 'tracking_url',
              name: 'tracking_url',
              displayName: 'Tracking URL',
              type: 'string',
              required: false,
            },
            {
              id: 'notify_customer',
              name: 'notify_customer',
              displayName: 'Notify Customer',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'line_items',
              name: 'line_items',
              displayName: 'Line Items (JSON)',
              type: 'json',
              required: false,
              description: 'Partial fulfillment items',
            },
          ],
        },
        {
          id: 'get_fulfillments',
          name: 'Get Fulfillments',
          value: 'getMany',
          description: 'Get fulfillments for an order',
          action: 'List fulfillments',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_tracking',
          name: 'Update Tracking',
          value: 'updateTracking',
          description: 'Update tracking info',
          action: 'Update fulfillment tracking',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
            {
              id: 'fulfillment_id',
              name: 'fulfillmentId',
              displayName: 'Fulfillment ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'tracking_number',
              name: 'tracking_number',
              displayName: 'Tracking Number',
              type: 'string',
              required: false,
            },
            {
              id: 'tracking_company',
              name: 'tracking_company',
              displayName: 'Tracking Company',
              type: 'string',
              required: false,
            },
            {
              id: 'tracking_url',
              name: 'tracking_url',
              displayName: 'Tracking URL',
              type: 'string',
              required: false,
            },
            {
              id: 'notify_customer',
              name: 'notify_customer',
              displayName: 'Notify Customer',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'cancel_fulfillment',
          name: 'Cancel Fulfillment',
          value: 'cancel',
          description: 'Cancel a fulfillment',
          action: 'Cancel a fulfillment',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
            {
              id: 'fulfillment_id',
              name: 'fulfillmentId',
              displayName: 'Fulfillment ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // COLLECTION RESOURCE
    // ============================================
    {
      id: 'collection',
      name: 'Collection',
      value: 'collection',
      description: 'Product collections',
      operations: [
        {
          id: 'get_collections',
          name: 'Get Collections',
          value: 'getMany',
          description: 'Get all collections',
          action: 'List all collections',
          fields: [],
          optionalFields: [
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
        {
          id: 'get_collection',
          name: 'Get Collection',
          value: 'get',
          description: 'Get a collection by ID',
          action: 'Retrieve a collection',
          fields: [
            {
              id: 'collection_id',
              name: 'collectionId',
              displayName: 'Collection ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_collection_products',
          name: 'Get Collection Products',
          value: 'getProducts',
          description: 'Get products in a collection',
          action: 'List products in a collection',
          fields: [
            {
              id: 'collection_id',
              name: 'collectionId',
              displayName: 'Collection ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 50,
            },
          ],
        },
      ],
    },
  ],
};
