/**
 * Stripe n8n-style Schema
 * 
 * Comprehensive Stripe payment processing operations
 */

import { N8nAppSchema } from './types';

export const stripeSchema: N8nAppSchema = {
  id: 'stripe',
  name: 'Stripe',
  description: 'Stripe payment processing platform',
  version: '1.0.0',
  color: '#635BFF',
  icon: 'stripe',
  group: ['payments'],
  
  credentials: [
    {
      name: 'stripeApi',
      displayName: 'Stripe API',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'secretKey',
          displayName: 'Secret Key',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
          placeholder: 'sk_live_...',
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // CUSTOMER RESOURCE
    // ============================================
    {
      id: 'customer',
      name: 'Customer',
      value: 'customer',
      description: 'Stripe customers',
      operations: [
        {
          id: 'create_customer',
          name: 'Create Customer',
          value: 'create',
          description: 'Create a new customer',
          action: 'Create a new customer',
          fields: [],
          optionalFields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'address',
              name: 'address',
              displayName: 'Address (JSON)',
              type: 'json',
              required: false,
              placeholder: '{"line1": "123 Main St", "city": "NYC", "postal_code": "10001", "country": "US"}',
            },
            {
              id: 'shipping',
              name: 'shipping',
              displayName: 'Shipping (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'payment_method',
              name: 'payment_method',
              displayName: 'Payment Method ID',
              type: 'string',
              required: false,
            },
            {
              id: 'invoice_settings',
              name: 'invoice_settings',
              displayName: 'Invoice Settings (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_customer',
          name: 'Get Customer',
          value: 'get',
          description: 'Get a customer by ID',
          action: 'Retrieve a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
              placeholder: 'cus_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_customers',
          name: 'Get Customers',
          value: 'getMany',
          description: 'Get all customers',
          action: 'List all customers',
          fields: [],
          optionalFields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'created_after',
              name: 'created[gte]',
              displayName: 'Created After',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'created_before',
              name: 'created[lte]',
              displayName: 'Created Before',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_customer',
          name: 'Update Customer',
          value: 'update',
          description: 'Update a customer',
          action: 'Update a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'delete_customer',
          name: 'Delete Customer',
          value: 'delete',
          description: 'Delete a customer',
          action: 'Delete a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CHARGE RESOURCE
    // ============================================
    {
      id: 'charge',
      name: 'Charge',
      value: 'charge',
      description: 'Payment charges',
      operations: [
        {
          id: 'create_charge',
          name: 'Create Charge',
          value: 'create',
          description: 'Create a new charge',
          action: 'Create a charge',
          fields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount (cents)',
              type: 'number',
              required: true,
              description: 'Amount in smallest currency unit (cents for USD)',
            },
            {
              id: 'currency',
              name: 'currency',
              displayName: 'Currency',
              type: 'options',
              required: true,
              default: 'usd',
              options: [
                { name: 'USD', value: 'usd' },
                { name: 'EUR', value: 'eur' },
                { name: 'GBP', value: 'gbp' },
                { name: 'INR', value: 'inr' },
                { name: 'JPY', value: 'jpy' },
                { name: 'AUD', value: 'aud' },
                { name: 'CAD', value: 'cad' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'source',
              name: 'source',
              displayName: 'Source/Token',
              type: 'string',
              required: false,
              placeholder: 'tok_...',
            },
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
              placeholder: 'cus_...',
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'receipt_email',
              name: 'receipt_email',
              displayName: 'Receipt Email',
              type: 'string',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'capture',
              name: 'capture',
              displayName: 'Capture Immediately',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'get_charge',
          name: 'Get Charge',
          value: 'get',
          description: 'Get a charge by ID',
          action: 'Retrieve a charge',
          fields: [
            {
              id: 'charge_id',
              name: 'chargeId',
              displayName: 'Charge ID',
              type: 'string',
              required: true,
              placeholder: 'ch_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_charges',
          name: 'Get Charges',
          value: 'getMany',
          description: 'Get all charges',
          action: 'List all charges',
          fields: [],
          optionalFields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'payment_intent',
              name: 'payment_intent',
              displayName: 'Payment Intent ID',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'capture_charge',
          name: 'Capture Charge',
          value: 'capture',
          description: 'Capture a pending charge',
          action: 'Capture a charge',
          fields: [
            {
              id: 'charge_id',
              name: 'chargeId',
              displayName: 'Charge ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount (cents)',
              type: 'number',
              required: false,
              description: 'Leave empty to capture full amount',
            },
          ],
        },
        {
          id: 'update_charge',
          name: 'Update Charge',
          value: 'update',
          description: 'Update a charge',
          action: 'Update a charge',
          fields: [
            {
              id: 'charge_id',
              name: 'chargeId',
              displayName: 'Charge ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // PAYMENT INTENT RESOURCE
    // ============================================
    {
      id: 'paymentIntent',
      name: 'Payment Intent',
      value: 'paymentIntent',
      description: 'Payment intents',
      operations: [
        {
          id: 'create_payment_intent',
          name: 'Create Payment Intent',
          value: 'create',
          description: 'Create a payment intent',
          action: 'Create a payment intent',
          fields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount (cents)',
              type: 'number',
              required: true,
            },
            {
              id: 'currency',
              name: 'currency',
              displayName: 'Currency',
              type: 'options',
              required: true,
              default: 'usd',
              options: [
                { name: 'USD', value: 'usd' },
                { name: 'EUR', value: 'eur' },
                { name: 'GBP', value: 'gbp' },
                { name: 'INR', value: 'inr' },
                { name: 'JPY', value: 'jpy' },
                { name: 'AUD', value: 'aud' },
                { name: 'CAD', value: 'cad' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'payment_method',
              name: 'payment_method',
              displayName: 'Payment Method ID',
              type: 'string',
              required: false,
            },
            {
              id: 'payment_method_types',
              name: 'payment_method_types',
              displayName: 'Payment Method Types',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Card', value: 'card' },
                { name: 'Bank Transfer', value: 'us_bank_account' },
                { name: 'SEPA Debit', value: 'sepa_debit' },
                { name: 'iDEAL', value: 'ideal' },
                { name: 'Bancontact', value: 'bancontact' },
              ],
            },
            {
              id: 'confirm',
              name: 'confirm',
              displayName: 'Confirm Immediately',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'capture_method',
              name: 'capture_method',
              displayName: 'Capture Method',
              type: 'options',
              required: false,
              default: 'automatic',
              options: [
                { name: 'Automatic', value: 'automatic' },
                { name: 'Manual', value: 'manual' },
              ],
            },
            {
              id: 'receipt_email',
              name: 'receipt_email',
              displayName: 'Receipt Email',
              type: 'string',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_payment_intent',
          name: 'Get Payment Intent',
          value: 'get',
          description: 'Get a payment intent',
          action: 'Retrieve a payment intent',
          fields: [
            {
              id: 'payment_intent_id',
              name: 'paymentIntentId',
              displayName: 'Payment Intent ID',
              type: 'string',
              required: true,
              placeholder: 'pi_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_payment_intents',
          name: 'Get Payment Intents',
          value: 'getMany',
          description: 'Get all payment intents',
          action: 'List payment intents',
          fields: [],
          optionalFields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'confirm_payment_intent',
          name: 'Confirm Payment Intent',
          value: 'confirm',
          description: 'Confirm a payment intent',
          action: 'Confirm a payment intent',
          fields: [
            {
              id: 'payment_intent_id',
              name: 'paymentIntentId',
              displayName: 'Payment Intent ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'payment_method',
              name: 'payment_method',
              displayName: 'Payment Method ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'capture_payment_intent',
          name: 'Capture Payment Intent',
          value: 'capture',
          description: 'Capture a payment intent',
          action: 'Capture a payment intent',
          fields: [
            {
              id: 'payment_intent_id',
              name: 'paymentIntentId',
              displayName: 'Payment Intent ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'amount_to_capture',
              name: 'amount_to_capture',
              displayName: 'Amount to Capture',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'cancel_payment_intent',
          name: 'Cancel Payment Intent',
          value: 'cancel',
          description: 'Cancel a payment intent',
          action: 'Cancel a payment intent',
          fields: [
            {
              id: 'payment_intent_id',
              name: 'paymentIntentId',
              displayName: 'Payment Intent ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'cancellation_reason',
              name: 'cancellation_reason',
              displayName: 'Cancellation Reason',
              type: 'options',
              required: false,
              options: [
                { name: 'Duplicate', value: 'duplicate' },
                { name: 'Fraudulent', value: 'fraudulent' },
                { name: 'Requested by Customer', value: 'requested_by_customer' },
                { name: 'Abandoned', value: 'abandoned' },
              ],
            },
          ],
        },
      ],
    },
    
    // ============================================
    // SUBSCRIPTION RESOURCE
    // ============================================
    {
      id: 'subscription',
      name: 'Subscription',
      value: 'subscription',
      description: 'Recurring subscriptions',
      operations: [
        {
          id: 'create_subscription',
          name: 'Create Subscription',
          value: 'create',
          description: 'Create a subscription',
          action: 'Create a subscription',
          fields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
              placeholder: 'cus_...',
            },
            {
              id: 'items',
              name: 'items',
              displayName: 'Items (JSON)',
              type: 'json',
              required: true,
              placeholder: '[{"price": "price_..."}]',
            },
          ],
          optionalFields: [
            {
              id: 'default_payment_method',
              name: 'default_payment_method',
              displayName: 'Default Payment Method',
              type: 'string',
              required: false,
            },
            {
              id: 'trial_period_days',
              name: 'trial_period_days',
              displayName: 'Trial Period (Days)',
              type: 'number',
              required: false,
            },
            {
              id: 'billing_cycle_anchor',
              name: 'billing_cycle_anchor',
              displayName: 'Billing Cycle Anchor',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'cancel_at_period_end',
              name: 'cancel_at_period_end',
              displayName: 'Cancel at Period End',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'coupon',
              name: 'coupon',
              displayName: 'Coupon Code',
              type: 'string',
              required: false,
            },
            {
              id: 'collection_method',
              name: 'collection_method',
              displayName: 'Collection Method',
              type: 'options',
              required: false,
              default: 'charge_automatically',
              options: [
                { name: 'Charge Automatically', value: 'charge_automatically' },
                { name: 'Send Invoice', value: 'send_invoice' },
              ],
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_subscription',
          name: 'Get Subscription',
          value: 'get',
          description: 'Get a subscription',
          action: 'Retrieve a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
              placeholder: 'sub_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_subscriptions',
          name: 'Get Subscriptions',
          value: 'getMany',
          description: 'Get all subscriptions',
          action: 'List subscriptions',
          fields: [],
          optionalFields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: 'all' },
                { name: 'Active', value: 'active' },
                { name: 'Past Due', value: 'past_due' },
                { name: 'Unpaid', value: 'unpaid' },
                { name: 'Canceled', value: 'canceled' },
                { name: 'Trialing', value: 'trialing' },
                { name: 'Incomplete', value: 'incomplete' },
              ],
            },
            {
              id: 'price',
              name: 'price',
              displayName: 'Price ID',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_subscription',
          name: 'Update Subscription',
          value: 'update',
          description: 'Update a subscription',
          action: 'Update a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'items',
              name: 'items',
              displayName: 'Items (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'proration_behavior',
              name: 'proration_behavior',
              displayName: 'Proration Behavior',
              type: 'options',
              required: false,
              default: 'create_prorations',
              options: [
                { name: 'Create Prorations', value: 'create_prorations' },
                { name: 'None', value: 'none' },
                { name: 'Always Invoice', value: 'always_invoice' },
              ],
            },
            {
              id: 'cancel_at_period_end',
              name: 'cancel_at_period_end',
              displayName: 'Cancel at Period End',
              type: 'boolean',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'cancel_subscription',
          name: 'Cancel Subscription',
          value: 'cancel',
          description: 'Cancel a subscription',
          action: 'Cancel a subscription',
          fields: [
            {
              id: 'subscription_id',
              name: 'subscriptionId',
              displayName: 'Subscription ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'invoice_now',
              name: 'invoice_now',
              displayName: 'Invoice Now',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'prorate',
              name: 'prorate',
              displayName: 'Prorate',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // INVOICE RESOURCE
    // ============================================
    {
      id: 'invoice',
      name: 'Invoice',
      value: 'invoice',
      description: 'Invoices',
      operations: [
        {
          id: 'create_invoice',
          name: 'Create Invoice',
          value: 'create',
          description: 'Create an invoice',
          action: 'Create an invoice',
          fields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'auto_advance',
              name: 'auto_advance',
              displayName: 'Auto Advance',
              type: 'boolean',
              required: false,
              default: true,
              description: 'Automatically finalize and collect',
            },
            {
              id: 'collection_method',
              name: 'collection_method',
              displayName: 'Collection Method',
              type: 'options',
              required: false,
              default: 'charge_automatically',
              options: [
                { name: 'Charge Automatically', value: 'charge_automatically' },
                { name: 'Send Invoice', value: 'send_invoice' },
              ],
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'due_date',
              name: 'due_date',
              displayName: 'Due Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_invoice',
          name: 'Get Invoice',
          value: 'get',
          description: 'Get an invoice',
          action: 'Retrieve an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
              placeholder: 'in_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_invoices',
          name: 'Get Invoices',
          value: 'getMany',
          description: 'Get all invoices',
          action: 'List invoices',
          fields: [],
          optionalFields: [
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Draft', value: 'draft' },
                { name: 'Open', value: 'open' },
                { name: 'Paid', value: 'paid' },
                { name: 'Uncollectible', value: 'uncollectible' },
                { name: 'Void', value: 'void' },
              ],
            },
            {
              id: 'subscription',
              name: 'subscription',
              displayName: 'Subscription ID',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'finalize_invoice',
          name: 'Finalize Invoice',
          value: 'finalize',
          description: 'Finalize a draft invoice',
          action: 'Finalize an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'auto_advance',
              name: 'auto_advance',
              displayName: 'Auto Advance',
              type: 'boolean',
              required: false,
              default: true,
            },
          ],
        },
        {
          id: 'pay_invoice',
          name: 'Pay Invoice',
          value: 'pay',
          description: 'Pay an invoice',
          action: 'Pay an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'payment_method',
              name: 'payment_method',
              displayName: 'Payment Method ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'void_invoice',
          name: 'Void Invoice',
          value: 'void',
          description: 'Void an invoice',
          action: 'Void an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'send_invoice',
          name: 'Send Invoice',
          value: 'send',
          description: 'Send an invoice email',
          action: 'Send an invoice',
          fields: [
            {
              id: 'invoice_id',
              name: 'invoiceId',
              displayName: 'Invoice ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // REFUND RESOURCE
    // ============================================
    {
      id: 'refund',
      name: 'Refund',
      value: 'refund',
      description: 'Payment refunds',
      operations: [
        {
          id: 'create_refund',
          name: 'Create Refund',
          value: 'create',
          description: 'Create a refund',
          action: 'Create a refund',
          fields: [],
          optionalFields: [
            {
              id: 'charge',
              name: 'charge',
              displayName: 'Charge ID',
              type: 'string',
              required: false,
              placeholder: 'ch_...',
            },
            {
              id: 'payment_intent',
              name: 'payment_intent',
              displayName: 'Payment Intent ID',
              type: 'string',
              required: false,
              placeholder: 'pi_...',
            },
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount (cents)',
              type: 'number',
              required: false,
              description: 'Leave empty for full refund',
            },
            {
              id: 'reason',
              name: 'reason',
              displayName: 'Reason',
              type: 'options',
              required: false,
              options: [
                { name: 'Duplicate', value: 'duplicate' },
                { name: 'Fraudulent', value: 'fraudulent' },
                { name: 'Requested by Customer', value: 'requested_by_customer' },
              ],
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_refund',
          name: 'Get Refund',
          value: 'get',
          description: 'Get a refund',
          action: 'Retrieve a refund',
          fields: [
            {
              id: 'refund_id',
              name: 'refundId',
              displayName: 'Refund ID',
              type: 'string',
              required: true,
              placeholder: 're_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_refunds',
          name: 'Get Refunds',
          value: 'getMany',
          description: 'Get all refunds',
          action: 'List refunds',
          fields: [],
          optionalFields: [
            {
              id: 'charge',
              name: 'charge',
              displayName: 'Charge ID',
              type: 'string',
              required: false,
            },
            {
              id: 'payment_intent',
              name: 'payment_intent',
              displayName: 'Payment Intent ID',
              type: 'string',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // PRODUCT RESOURCE
    // ============================================
    {
      id: 'product',
      name: 'Product',
      value: 'product',
      description: 'Products for billing',
      operations: [
        {
          id: 'create_product',
          name: 'Create Product',
          value: 'create',
          description: 'Create a product',
          action: 'Create a product',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'active',
              name: 'active',
              displayName: 'Active',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'images',
              name: 'images',
              displayName: 'Images (JSON Array)',
              type: 'json',
              required: false,
              placeholder: '["https://example.com/image.png"]',
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_product',
          name: 'Get Product',
          value: 'get',
          description: 'Get a product',
          action: 'Retrieve a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
              placeholder: 'prod_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_products',
          name: 'Get Products',
          value: 'getMany',
          description: 'Get all products',
          action: 'List products',
          fields: [],
          optionalFields: [
            {
              id: 'active',
              name: 'active',
              displayName: 'Active Only',
              type: 'boolean',
              required: false,
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_product',
          name: 'Update Product',
          value: 'update',
          description: 'Update a product',
          action: 'Update a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'active',
              name: 'active',
              displayName: 'Active',
              type: 'boolean',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'delete_product',
          name: 'Delete Product',
          value: 'delete',
          description: 'Delete a product',
          action: 'Delete a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // PRICE RESOURCE
    // ============================================
    {
      id: 'price',
      name: 'Price',
      value: 'price',
      description: 'Prices for products',
      operations: [
        {
          id: 'create_price',
          name: 'Create Price',
          value: 'create',
          description: 'Create a price',
          action: 'Create a price',
          fields: [
            {
              id: 'product',
              name: 'product',
              displayName: 'Product ID',
              type: 'string',
              required: true,
              placeholder: 'prod_...',
            },
            {
              id: 'unit_amount',
              name: 'unit_amount',
              displayName: 'Unit Amount (cents)',
              type: 'number',
              required: true,
            },
            {
              id: 'currency',
              name: 'currency',
              displayName: 'Currency',
              type: 'options',
              required: true,
              default: 'usd',
              options: [
                { name: 'USD', value: 'usd' },
                { name: 'EUR', value: 'eur' },
                { name: 'GBP', value: 'gbp' },
                { name: 'INR', value: 'inr' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'recurring',
              name: 'recurring',
              displayName: 'Recurring (JSON)',
              type: 'json',
              required: false,
              placeholder: '{"interval": "month", "interval_count": 1}',
            },
            {
              id: 'billing_scheme',
              name: 'billing_scheme',
              displayName: 'Billing Scheme',
              type: 'options',
              required: false,
              default: 'per_unit',
              options: [
                { name: 'Per Unit', value: 'per_unit' },
                { name: 'Tiered', value: 'tiered' },
              ],
            },
            {
              id: 'active',
              name: 'active',
              displayName: 'Active',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'nickname',
              name: 'nickname',
              displayName: 'Nickname',
              type: 'string',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_price',
          name: 'Get Price',
          value: 'get',
          description: 'Get a price',
          action: 'Retrieve a price',
          fields: [
            {
              id: 'price_id',
              name: 'priceId',
              displayName: 'Price ID',
              type: 'string',
              required: true,
              placeholder: 'price_...',
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_prices',
          name: 'Get Prices',
          value: 'getMany',
          description: 'Get all prices',
          action: 'List prices',
          fields: [],
          optionalFields: [
            {
              id: 'product',
              name: 'product',
              displayName: 'Product ID',
              type: 'string',
              required: false,
            },
            {
              id: 'active',
              name: 'active',
              displayName: 'Active Only',
              type: 'boolean',
              required: false,
            },
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: false,
              options: [
                { name: 'One-Time', value: 'one_time' },
                { name: 'Recurring', value: 'recurring' },
              ],
            },
            {
              id: 'limit',
              name: 'limit',
              displayName: 'Limit',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_price',
          name: 'Update Price',
          value: 'update',
          description: 'Update a price',
          action: 'Update a price',
          fields: [
            {
              id: 'price_id',
              name: 'priceId',
              displayName: 'Price ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'active',
              name: 'active',
              displayName: 'Active',
              type: 'boolean',
              required: false,
            },
            {
              id: 'nickname',
              name: 'nickname',
              displayName: 'Nickname',
              type: 'string',
              required: false,
            },
            {
              id: 'metadata',
              name: 'metadata',
              displayName: 'Metadata (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
      ],
    },
  ],
};
