/**
 * Twitter (X) n8n-style Schema
 * 
 * Comprehensive Twitter/X API v2 operations
 */

import { N8nAppSchema } from './types';

export const twitterSchema: N8nAppSchema = {
  id: 'twitter',
  name: 'Twitter (X)',
  description: 'Twitter/X social media platform',
  version: '1.0.0',
  color: '#000000',
  icon: 'twitter',
  group: ['social', 'marketing'],
  
  credentials: [
    {
      name: 'twitterOAuth2',
      displayName: 'Twitter OAuth2',
      required: true,
      type: 'oauth2',
      properties: [
        {
          name: 'accessToken',
          displayName: 'Access Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
        {
          name: 'refreshToken',
          displayName: 'Refresh Token',
          type: 'string',
          required: false,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
    {
      name: 'twitterApi',
      displayName: 'Twitter API (Bearer Token)',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'bearerToken',
          displayName: 'Bearer Token',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // TWEET RESOURCE
    // ============================================
    {
      id: 'tweet',
      name: 'Tweet',
      value: 'tweet',
      description: 'Tweet operations',
      operations: [
        {
          id: 'create_tweet',
          name: 'Create Tweet',
          value: 'create',
          description: 'Post a new tweet',
          action: 'Create tweet',
          fields: [
            {
              id: 'text',
              name: 'text',
              displayName: 'Text',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 3,
              },
              description: 'Max 280 characters',
            },
          ],
          optionalFields: [
            {
              id: 'reply_to',
              name: 'replyTo',
              displayName: 'Reply To Tweet ID',
              type: 'string',
              required: false,
            },
            {
              id: 'quote_tweet_id',
              name: 'quoteTweetId',
              displayName: 'Quote Tweet ID',
              type: 'string',
              required: false,
            },
            {
              id: 'media_ids',
              name: 'mediaIds',
              displayName: 'Media IDs',
              type: 'string',
              required: false,
              description: 'Comma-separated media IDs',
            },
            {
              id: 'poll_options',
              name: 'pollOptions',
              displayName: 'Poll Options',
              type: 'string',
              required: false,
              description: 'Comma-separated options (2-4)',
            },
            {
              id: 'poll_duration_minutes',
              name: 'pollDurationMinutes',
              displayName: 'Poll Duration (minutes)',
              type: 'number',
              required: false,
              default: 1440,
              description: '5 to 10080 minutes',
            },
            {
              id: 'reply_settings',
              name: 'replySettings',
              displayName: 'Reply Settings',
              type: 'options',
              required: false,
              options: [
                { name: 'Everyone', value: 'everyone' },
                { name: 'Following', value: 'following' },
                { name: 'Mentioned Users', value: 'mentionedUsers' },
              ],
            },
            {
              id: 'for_super_followers_only',
              name: 'forSuperFollowersOnly',
              displayName: 'Super Followers Only',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'geo_place_id',
              name: 'geoPlaceId',
              displayName: 'Geo Place ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_tweet',
          name: 'Get Tweet',
          value: 'get',
          description: 'Get a tweet by ID',
          action: 'Get tweet',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'expansions',
              name: 'expansions',
              displayName: 'Expansions',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Author ID', value: 'author_id' },
                { name: 'Referenced Tweets', value: 'referenced_tweets.id' },
                { name: 'In Reply To User', value: 'in_reply_to_user_id' },
                { name: 'Media Keys', value: 'attachments.media_keys' },
                { name: 'Poll IDs', value: 'attachments.poll_ids' },
                { name: 'Place ID', value: 'geo.place_id' },
                { name: 'Entities Mentions', value: 'entities.mentions.username' },
              ],
            },
            {
              id: 'tweet_fields',
              name: 'tweetFields',
              displayName: 'Tweet Fields',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Attachments', value: 'attachments' },
                { name: 'Author ID', value: 'author_id' },
                { name: 'Context Annotations', value: 'context_annotations' },
                { name: 'Conversation ID', value: 'conversation_id' },
                { name: 'Created At', value: 'created_at' },
                { name: 'Entities', value: 'entities' },
                { name: 'Geo', value: 'geo' },
                { name: 'ID', value: 'id' },
                { name: 'In Reply To User ID', value: 'in_reply_to_user_id' },
                { name: 'Language', value: 'lang' },
                { name: 'Public Metrics', value: 'public_metrics' },
                { name: 'Reply Settings', value: 'reply_settings' },
                { name: 'Source', value: 'source' },
                { name: 'Text', value: 'text' },
              ],
            },
          ],
        },
        {
          id: 'delete_tweet',
          name: 'Delete Tweet',
          value: 'delete',
          description: 'Delete a tweet',
          action: 'Delete tweet',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'search_tweets',
          name: 'Search Tweets',
          value: 'search',
          description: 'Search for tweets',
          action: 'Search tweets',
          fields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'string',
              required: true,
              description: 'Search query (operators supported)',
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 10,
              description: '10 to 100',
            },
            {
              id: 'start_time',
              name: 'startTime',
              displayName: 'Start Time',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'end_time',
              name: 'endTime',
              displayName: 'End Time',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'since_id',
              name: 'sinceId',
              displayName: 'Since ID',
              type: 'string',
              required: false,
            },
            {
              id: 'until_id',
              name: 'untilId',
              displayName: 'Until ID',
              type: 'string',
              required: false,
            },
            {
              id: 'sort_order',
              name: 'sortOrder',
              displayName: 'Sort Order',
              type: 'options',
              required: false,
              options: [
                { name: 'Recency', value: 'recency' },
                { name: 'Relevancy', value: 'relevancy' },
              ],
            },
            {
              id: 'expansions',
              name: 'expansions',
              displayName: 'Expansions',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Author ID', value: 'author_id' },
                { name: 'Referenced Tweets', value: 'referenced_tweets.id' },
                { name: 'Media Keys', value: 'attachments.media_keys' },
              ],
            },
          ],
        },
        {
          id: 'get_tweet_counts',
          name: 'Get Tweet Counts',
          value: 'counts',
          description: 'Get tweet counts for a query',
          action: 'Get tweet counts',
          fields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'granularity',
              name: 'granularity',
              displayName: 'Granularity',
              type: 'options',
              required: false,
              options: [
                { name: 'Minute', value: 'minute' },
                { name: 'Hour', value: 'hour' },
                { name: 'Day', value: 'day' },
              ],
              default: 'hour',
            },
            {
              id: 'start_time',
              name: 'startTime',
              displayName: 'Start Time',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'end_time',
              name: 'endTime',
              displayName: 'End Time',
              type: 'dateTime',
              required: false,
            },
          ],
        },
        {
          id: 'like_tweet',
          name: 'Like Tweet',
          value: 'like',
          description: 'Like a tweet',
          action: 'Like tweet',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'unlike_tweet',
          name: 'Unlike Tweet',
          value: 'unlike',
          description: 'Remove like from a tweet',
          action: 'Unlike tweet',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'retweet',
          name: 'Retweet',
          value: 'retweet',
          description: 'Retweet a tweet',
          action: 'Retweet',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'undo_retweet',
          name: 'Undo Retweet',
          value: 'undoRetweet',
          description: 'Remove retweet',
          action: 'Undo retweet',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'bookmark_tweet',
          name: 'Bookmark Tweet',
          value: 'bookmark',
          description: 'Bookmark a tweet',
          action: 'Bookmark tweet',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'remove_bookmark',
          name: 'Remove Bookmark',
          value: 'removeBookmark',
          description: 'Remove bookmark from tweet',
          action: 'Remove bookmark',
          fields: [
            {
              id: 'tweet_id',
              name: 'tweetId',
              displayName: 'Tweet ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // USER RESOURCE
    // ============================================
    {
      id: 'user',
      name: 'User',
      value: 'user',
      description: 'User operations',
      operations: [
        {
          id: 'get_user',
          name: 'Get User',
          value: 'get',
          description: 'Get user by ID or username',
          action: 'Get user',
          fields: [
            {
              id: 'lookup_by',
              name: 'lookupBy',
              displayName: 'Lookup By',
              type: 'options',
              required: true,
              options: [
                { name: 'User ID', value: 'id' },
                { name: 'Username', value: 'username' },
              ],
            },
            {
              id: 'user_identifier',
              name: 'userIdentifier',
              displayName: 'User ID or Username',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'user_fields',
              name: 'userFields',
              displayName: 'User Fields',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Created At', value: 'created_at' },
                { name: 'Description', value: 'description' },
                { name: 'Entities', value: 'entities' },
                { name: 'ID', value: 'id' },
                { name: 'Location', value: 'location' },
                { name: 'Name', value: 'name' },
                { name: 'Pinned Tweet ID', value: 'pinned_tweet_id' },
                { name: 'Profile Image URL', value: 'profile_image_url' },
                { name: 'Protected', value: 'protected' },
                { name: 'Public Metrics', value: 'public_metrics' },
                { name: 'URL', value: 'url' },
                { name: 'Username', value: 'username' },
                { name: 'Verified', value: 'verified' },
                { name: 'Verified Type', value: 'verified_type' },
              ],
            },
          ],
        },
        {
          id: 'get_me',
          name: 'Get Me',
          value: 'getMe',
          description: 'Get authenticated user',
          action: 'Get me',
          fields: [],
          optionalFields: [
            {
              id: 'user_fields',
              name: 'userFields',
              displayName: 'User Fields',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Created At', value: 'created_at' },
                { name: 'Description', value: 'description' },
                { name: 'Public Metrics', value: 'public_metrics' },
                { name: 'Profile Image URL', value: 'profile_image_url' },
                { name: 'Verified', value: 'verified' },
              ],
            },
          ],
        },
        {
          id: 'get_followers',
          name: 'Get Followers',
          value: 'getFollowers',
          description: 'Get user followers',
          action: 'Get followers',
          fields: [
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
              description: '1 to 1000',
            },
            {
              id: 'user_fields',
              name: 'userFields',
              displayName: 'User Fields',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Created At', value: 'created_at' },
                { name: 'Description', value: 'description' },
                { name: 'Public Metrics', value: 'public_metrics' },
                { name: 'Profile Image URL', value: 'profile_image_url' },
              ],
            },
          ],
        },
        {
          id: 'get_following',
          name: 'Get Following',
          value: 'getFollowing',
          description: 'Get users that user follows',
          action: 'Get following',
          fields: [
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
            {
              id: 'user_fields',
              name: 'userFields',
              displayName: 'User Fields',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Created At', value: 'created_at' },
                { name: 'Description', value: 'description' },
                { name: 'Public Metrics', value: 'public_metrics' },
              ],
            },
          ],
        },
        {
          id: 'follow_user',
          name: 'Follow User',
          value: 'follow',
          description: 'Follow a user',
          action: 'Follow user',
          fields: [
            {
              id: 'target_user_id',
              name: 'targetUserId',
              displayName: 'Target User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'unfollow_user',
          name: 'Unfollow User',
          value: 'unfollow',
          description: 'Unfollow a user',
          action: 'Unfollow user',
          fields: [
            {
              id: 'target_user_id',
              name: 'targetUserId',
              displayName: 'Target User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'block_user',
          name: 'Block User',
          value: 'block',
          description: 'Block a user',
          action: 'Block user',
          fields: [
            {
              id: 'target_user_id',
              name: 'targetUserId',
              displayName: 'Target User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'unblock_user',
          name: 'Unblock User',
          value: 'unblock',
          description: 'Unblock a user',
          action: 'Unblock user',
          fields: [
            {
              id: 'target_user_id',
              name: 'targetUserId',
              displayName: 'Target User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'mute_user',
          name: 'Mute User',
          value: 'mute',
          description: 'Mute a user',
          action: 'Mute user',
          fields: [
            {
              id: 'target_user_id',
              name: 'targetUserId',
              displayName: 'Target User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'unmute_user',
          name: 'Unmute User',
          value: 'unmute',
          description: 'Unmute a user',
          action: 'Unmute user',
          fields: [
            {
              id: 'target_user_id',
              name: 'targetUserId',
              displayName: 'Target User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_user_tweets',
          name: 'Get User Tweets',
          value: 'getTweets',
          description: 'Get tweets by user',
          action: 'Get user tweets',
          fields: [
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 10,
              description: '5 to 100',
            },
            {
              id: 'exclude',
              name: 'exclude',
              displayName: 'Exclude',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Retweets', value: 'retweets' },
                { name: 'Replies', value: 'replies' },
              ],
            },
            {
              id: 'start_time',
              name: 'startTime',
              displayName: 'Start Time',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'end_time',
              name: 'endTime',
              displayName: 'End Time',
              type: 'dateTime',
              required: false,
            },
          ],
        },
        {
          id: 'get_user_mentions',
          name: 'Get User Mentions',
          value: 'getMentions',
          description: 'Get tweets mentioning user',
          action: 'Get user mentions',
          fields: [
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 10,
            },
            {
              id: 'start_time',
              name: 'startTime',
              displayName: 'Start Time',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'end_time',
              name: 'endTime',
              displayName: 'End Time',
              type: 'dateTime',
              required: false,
            },
          ],
        },
        {
          id: 'get_liked_tweets',
          name: 'Get Liked Tweets',
          value: 'getLikedTweets',
          description: 'Get tweets liked by user',
          action: 'Get liked tweets',
          fields: [
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'get_bookmarks',
          name: 'Get Bookmarks',
          value: 'getBookmarks',
          description: 'Get user bookmarks',
          action: 'Get bookmarks',
          fields: [],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // LIST RESOURCE
    // ============================================
    {
      id: 'list',
      name: 'List',
      value: 'list',
      description: 'List operations',
      operations: [
        {
          id: 'create_list',
          name: 'Create List',
          value: 'create',
          description: 'Create a new list',
          action: 'Create list',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: true,
              description: 'Max 25 characters',
            },
          ],
          optionalFields: [
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
              description: 'Max 100 characters',
            },
            {
              id: 'private',
              name: 'private',
              displayName: 'Private',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'get_list',
          name: 'Get List',
          value: 'get',
          description: 'Get list by ID',
          action: 'Get list',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'update_list',
          name: 'Update List',
          value: 'update',
          description: 'Update a list',
          action: 'Update list',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'private',
              name: 'private',
              displayName: 'Private',
              type: 'boolean',
              required: false,
            },
          ],
        },
        {
          id: 'delete_list',
          name: 'Delete List',
          value: 'delete',
          description: 'Delete a list',
          action: 'Delete list',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_user_lists',
          name: 'Get User Lists',
          value: 'getUserLists',
          description: 'Get lists owned by user',
          action: 'Get user lists',
          fields: [
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
          ],
        },
        {
          id: 'get_list_members',
          name: 'Get List Members',
          value: 'getMembers',
          description: 'Get members of a list',
          action: 'Get list members',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
          ],
        },
        {
          id: 'add_list_member',
          name: 'Add List Member',
          value: 'addMember',
          description: 'Add a member to a list',
          action: 'Add list member',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'remove_list_member',
          name: 'Remove List Member',
          value: 'removeMember',
          description: 'Remove a member from a list',
          action: 'Remove list member',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
            {
              id: 'user_id',
              name: 'userId',
              displayName: 'User ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'follow_list',
          name: 'Follow List',
          value: 'follow',
          description: 'Follow a list',
          action: 'Follow list',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'unfollow_list',
          name: 'Unfollow List',
          value: 'unfollow',
          description: 'Unfollow a list',
          action: 'Unfollow list',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_list_tweets',
          name: 'Get List Tweets',
          value: 'getTweets',
          description: 'Get tweets from a list',
          action: 'Get list tweets',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
          ],
        },
        {
          id: 'pin_list',
          name: 'Pin List',
          value: 'pin',
          description: 'Pin a list',
          action: 'Pin list',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'unpin_list',
          name: 'Unpin List',
          value: 'unpin',
          description: 'Unpin a list',
          action: 'Unpin list',
          fields: [
            {
              id: 'list_id',
              name: 'listId',
              displayName: 'List ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // DIRECT MESSAGE RESOURCE
    // ============================================
    {
      id: 'directMessage',
      name: 'Direct Message',
      value: 'directMessage',
      description: 'Direct message operations',
      operations: [
        {
          id: 'send_dm',
          name: 'Send Direct Message',
          value: 'send',
          description: 'Send a direct message',
          action: 'Send direct message',
          fields: [
            {
              id: 'participant_id',
              name: 'participantId',
              displayName: 'Participant User ID',
              type: 'string',
              required: true,
            },
            {
              id: 'text',
              name: 'text',
              displayName: 'Text',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 3,
              },
            },
          ],
          optionalFields: [
            {
              id: 'media_id',
              name: 'mediaId',
              displayName: 'Media ID',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_dm_conversations',
          name: 'Get DM Conversations',
          value: 'getConversations',
          description: 'Get direct message conversations',
          action: 'Get DM conversations',
          fields: [],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
            {
              id: 'dm_event_fields',
              name: 'dmEventFields',
              displayName: 'DM Event Fields',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'ID', value: 'id' },
                { name: 'Text', value: 'text' },
                { name: 'Event Type', value: 'event_type' },
                { name: 'Created At', value: 'created_at' },
                { name: 'Sender ID', value: 'sender_id' },
                { name: 'DM Conversation ID', value: 'dm_conversation_id' },
              ],
            },
          ],
        },
        {
          id: 'get_dm_events',
          name: 'Get DM Events',
          value: 'getEvents',
          description: 'Get direct message events in conversation',
          action: 'Get DM events',
          fields: [
            {
              id: 'dm_conversation_id',
              name: 'dmConversationId',
              displayName: 'DM Conversation ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // MEDIA RESOURCE
    // ============================================
    {
      id: 'media',
      name: 'Media',
      value: 'media',
      description: 'Media upload operations',
      operations: [
        {
          id: 'upload_media',
          name: 'Upload Media',
          value: 'upload',
          description: 'Upload media for tweets',
          action: 'Upload media',
          fields: [
            {
              id: 'media_data',
              name: 'mediaData',
              displayName: 'Media Data (Base64)',
              type: 'string',
              required: true,
            },
            {
              id: 'media_type',
              name: 'mediaType',
              displayName: 'Media Type',
              type: 'options',
              required: true,
              options: [
                { name: 'Image (PNG)', value: 'image/png' },
                { name: 'Image (JPEG)', value: 'image/jpeg' },
                { name: 'Image (GIF)', value: 'image/gif' },
                { name: 'Image (WebP)', value: 'image/webp' },
                { name: 'Video (MP4)', value: 'video/mp4' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'alt_text',
              name: 'altText',
              displayName: 'Alt Text',
              type: 'string',
              required: false,
              description: 'Accessibility text for media',
            },
          ],
        },
        {
          id: 'get_media_status',
          name: 'Get Media Status',
          value: 'getStatus',
          description: 'Get upload status for media',
          action: 'Get media status',
          fields: [
            {
              id: 'media_id',
              name: 'mediaId',
              displayName: 'Media ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // SPACES RESOURCE
    // ============================================
    {
      id: 'spaces',
      name: 'Spaces',
      value: 'spaces',
      description: 'Twitter Spaces operations',
      operations: [
        {
          id: 'get_space',
          name: 'Get Space',
          value: 'get',
          description: 'Get space by ID',
          action: 'Get space',
          fields: [
            {
              id: 'space_id',
              name: 'spaceId',
              displayName: 'Space ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'space_fields',
              name: 'spaceFields',
              displayName: 'Space Fields',
              type: 'multiOptions',
              required: false,
              options: [
                { name: 'Host IDs', value: 'host_ids' },
                { name: 'Created At', value: 'created_at' },
                { name: 'Creator ID', value: 'creator_id' },
                { name: 'ID', value: 'id' },
                { name: 'Language', value: 'lang' },
                { name: 'Is Ticketed', value: 'is_ticketed' },
                { name: 'Invited User IDs', value: 'invited_user_ids' },
                { name: 'Participant Count', value: 'participant_count' },
                { name: 'Scheduled Start', value: 'scheduled_start' },
                { name: 'Speaker IDs', value: 'speaker_ids' },
                { name: 'Started At', value: 'started_at' },
                { name: 'State', value: 'state' },
                { name: 'Title', value: 'title' },
                { name: 'Updated At', value: 'updated_at' },
              ],
            },
          ],
        },
        {
          id: 'search_spaces',
          name: 'Search Spaces',
          value: 'search',
          description: 'Search for spaces',
          action: 'Search spaces',
          fields: [
            {
              id: 'query',
              name: 'query',
              displayName: 'Query',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'state',
              name: 'state',
              displayName: 'State',
              type: 'options',
              required: false,
              options: [
                { name: 'All', value: 'all' },
                { name: 'Live', value: 'live' },
                { name: 'Scheduled', value: 'scheduled' },
              ],
              default: 'all',
            },
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
          ],
        },
        {
          id: 'get_space_buyers',
          name: 'Get Space Buyers',
          value: 'getBuyers',
          description: 'Get buyers of a ticketed space',
          action: 'Get space buyers',
          fields: [
            {
              id: 'space_id',
              name: 'spaceId',
              displayName: 'Space ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_space_tweets',
          name: 'Get Space Tweets',
          value: 'getTweets',
          description: 'Get tweets shared in a space',
          action: 'Get space tweets',
          fields: [
            {
              id: 'space_id',
              name: 'spaceId',
              displayName: 'Space ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'max_results',
              name: 'maxResults',
              displayName: 'Max Results',
              type: 'number',
              required: false,
              default: 100,
            },
          ],
        },
      ],
    },
  ],
};
