/**
 * WooCommerce n8n-style Schema
 * 
 * Comprehensive WooCommerce e-commerce operations
 */

import { N8nAppSchema } from './types';

export const woocommerceSchema: N8nAppSchema = {
  id: 'woocommerce',
  name: 'WooCommerce',
  description: 'WooCommerce e-commerce platform for WordPress',
  version: '1.0.0',
  color: '#96588A',
  icon: 'woocommerce',
  group: ['ecommerce'],
  
  credentials: [
    {
      name: 'woocommerceApi',
      displayName: 'WooCommerce API',
      required: true,
      type: 'apiKey',
      properties: [
        {
          name: 'siteUrl',
          displayName: 'Site URL',
          type: 'string',
          required: true,
          placeholder: 'https://mystore.com',
        },
        {
          name: 'consumerKey',
          displayName: 'Consumer Key',
          type: 'string',
          required: true,
          placeholder: 'ck_...',
        },
        {
          name: 'consumerSecret',
          displayName: 'Consumer Secret',
          type: 'string',
          required: true,
          typeOptions: {
            password: true,
          },
          placeholder: 'cs_...',
        },
      ],
    },
  ],
  
  resources: [
    // ============================================
    // PRODUCT RESOURCE
    // ============================================
    {
      id: 'product',
      name: 'Product',
      value: 'product',
      description: 'Store products',
      operations: [
        {
          id: 'create_product',
          name: 'Create Product',
          value: 'create',
          description: 'Create a new product',
          action: 'Create a product',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: false,
              default: 'simple',
              options: [
                { name: 'Simple', value: 'simple' },
                { name: 'Grouped', value: 'grouped' },
                { name: 'External', value: 'external' },
                { name: 'Variable', value: 'variable' },
              ],
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'publish',
              options: [
                { name: 'Draft', value: 'draft' },
                { name: 'Pending', value: 'pending' },
                { name: 'Private', value: 'private' },
                { name: 'Publish', value: 'publish' },
              ],
            },
            {
              id: 'regular_price',
              name: 'regular_price',
              displayName: 'Regular Price',
              type: 'string',
              required: false,
            },
            {
              id: 'sale_price',
              name: 'sale_price',
              displayName: 'Sale Price',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'short_description',
              name: 'short_description',
              displayName: 'Short Description',
              type: 'string',
              required: false,
            },
            {
              id: 'sku',
              name: 'sku',
              displayName: 'SKU',
              type: 'string',
              required: false,
            },
            {
              id: 'manage_stock',
              name: 'manage_stock',
              displayName: 'Manage Stock',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'stock_quantity',
              name: 'stock_quantity',
              displayName: 'Stock Quantity',
              type: 'number',
              required: false,
            },
            {
              id: 'categories',
              name: 'categories',
              displayName: 'Categories (JSON)',
              type: 'json',
              required: false,
              placeholder: '[{"id": 1}]',
            },
            {
              id: 'images',
              name: 'images',
              displayName: 'Images (JSON)',
              type: 'json',
              required: false,
              placeholder: '[{"src": "https://example.com/image.jpg"}]',
            },
            {
              id: 'attributes',
              name: 'attributes',
              displayName: 'Attributes (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_product',
          name: 'Get Product',
          value: 'get',
          description: 'Get a product by ID',
          action: 'Retrieve a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_products',
          name: 'Get Products',
          value: 'getMany',
          description: 'Get all products',
          action: 'List all products',
          fields: [],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Any', value: 'any' },
                { name: 'Draft', value: 'draft' },
                { name: 'Pending', value: 'pending' },
                { name: 'Private', value: 'private' },
                { name: 'Publish', value: 'publish' },
              ],
            },
            {
              id: 'type',
              name: 'type',
              displayName: 'Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Simple', value: 'simple' },
                { name: 'Grouped', value: 'grouped' },
                { name: 'External', value: 'external' },
                { name: 'Variable', value: 'variable' },
              ],
            },
            {
              id: 'category',
              name: 'category',
              displayName: 'Category ID',
              type: 'string',
              required: false,
            },
            {
              id: 'search',
              name: 'search',
              displayName: 'Search',
              type: 'string',
              required: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_product',
          name: 'Update Product',
          value: 'update',
          description: 'Update a product',
          action: 'Update a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Draft', value: 'draft' },
                { name: 'Pending', value: 'pending' },
                { name: 'Private', value: 'private' },
                { name: 'Publish', value: 'publish' },
              ],
            },
            {
              id: 'regular_price',
              name: 'regular_price',
              displayName: 'Regular Price',
              type: 'string',
              required: false,
            },
            {
              id: 'sale_price',
              name: 'sale_price',
              displayName: 'Sale Price',
              type: 'string',
              required: false,
            },
            {
              id: 'stock_quantity',
              name: 'stock_quantity',
              displayName: 'Stock Quantity',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'delete_product',
          name: 'Delete Product',
          value: 'delete',
          description: 'Delete a product',
          action: 'Delete a product',
          fields: [
            {
              id: 'product_id',
              name: 'productId',
              displayName: 'Product ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'force',
              name: 'force',
              displayName: 'Force Delete',
              type: 'boolean',
              required: false,
              default: false,
              description: 'Bypass trash and permanently delete',
            },
          ],
        },
      ],
    },
    
    // ============================================
    // ORDER RESOURCE
    // ============================================
    {
      id: 'order',
      name: 'Order',
      value: 'order',
      description: 'Customer orders',
      operations: [
        {
          id: 'create_order',
          name: 'Create Order',
          value: 'create',
          description: 'Create a new order',
          action: 'Create an order',
          fields: [],
          optionalFields: [
            {
              id: 'customer_id',
              name: 'customer_id',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'pending',
              options: [
                { name: 'Pending', value: 'pending' },
                { name: 'Processing', value: 'processing' },
                { name: 'On Hold', value: 'on-hold' },
                { name: 'Completed', value: 'completed' },
                { name: 'Cancelled', value: 'cancelled' },
                { name: 'Refunded', value: 'refunded' },
                { name: 'Failed', value: 'failed' },
              ],
            },
            {
              id: 'line_items',
              name: 'line_items',
              displayName: 'Line Items (JSON)',
              type: 'json',
              required: false,
              placeholder: '[{"product_id": 1, "quantity": 2}]',
            },
            {
              id: 'billing',
              name: 'billing',
              displayName: 'Billing Address (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'shipping',
              name: 'shipping',
              displayName: 'Shipping Address (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'payment_method',
              name: 'payment_method',
              displayName: 'Payment Method',
              type: 'string',
              required: false,
            },
            {
              id: 'payment_method_title',
              name: 'payment_method_title',
              displayName: 'Payment Method Title',
              type: 'string',
              required: false,
            },
            {
              id: 'set_paid',
              name: 'set_paid',
              displayName: 'Set as Paid',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'coupon_lines',
              name: 'coupon_lines',
              displayName: 'Coupons (JSON)',
              type: 'json',
              required: false,
              placeholder: '[{"code": "DISCOUNT10"}]',
            },
          ],
        },
        {
          id: 'get_order',
          name: 'Get Order',
          value: 'get',
          description: 'Get an order by ID',
          action: 'Retrieve an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_orders',
          name: 'Get Orders',
          value: 'getMany',
          description: 'Get all orders',
          action: 'List all orders',
          fields: [],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Any', value: 'any' },
                { name: 'Pending', value: 'pending' },
                { name: 'Processing', value: 'processing' },
                { name: 'On Hold', value: 'on-hold' },
                { name: 'Completed', value: 'completed' },
                { name: 'Cancelled', value: 'cancelled' },
                { name: 'Refunded', value: 'refunded' },
                { name: 'Failed', value: 'failed' },
              ],
            },
            {
              id: 'customer',
              name: 'customer',
              displayName: 'Customer ID',
              type: 'string',
              required: false,
            },
            {
              id: 'after',
              name: 'after',
              displayName: 'After Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'before',
              name: 'before',
              displayName: 'Before Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_order',
          name: 'Update Order',
          value: 'update',
          description: 'Update an order',
          action: 'Update an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'status',
              name: 'status',
              displayName: 'Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Pending', value: 'pending' },
                { name: 'Processing', value: 'processing' },
                { name: 'On Hold', value: 'on-hold' },
                { name: 'Completed', value: 'completed' },
                { name: 'Cancelled', value: 'cancelled' },
                { name: 'Refunded', value: 'refunded' },
                { name: 'Failed', value: 'failed' },
              ],
            },
            {
              id: 'customer_note',
              name: 'customer_note',
              displayName: 'Customer Note',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_order',
          name: 'Delete Order',
          value: 'delete',
          description: 'Delete an order',
          action: 'Delete an order',
          fields: [
            {
              id: 'order_id',
              name: 'orderId',
              displayName: 'Order ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'force',
              name: 'force',
              displayName: 'Force Delete',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // CUSTOMER RESOURCE
    // ============================================
    {
      id: 'customer',
      name: 'Customer',
      value: 'customer',
      description: 'Store customers',
      operations: [
        {
          id: 'create_customer',
          name: 'Create Customer',
          value: 'create',
          description: 'Create a new customer',
          action: 'Create a customer',
          fields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'username',
              name: 'username',
              displayName: 'Username',
              type: 'string',
              required: false,
            },
            {
              id: 'password',
              name: 'password',
              displayName: 'Password',
              type: 'string',
              required: false,
              typeOptions: {
                password: true,
              },
            },
            {
              id: 'billing',
              name: 'billing',
              displayName: 'Billing Address (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'shipping',
              name: 'shipping',
              displayName: 'Shipping Address (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'get_customer',
          name: 'Get Customer',
          value: 'get',
          description: 'Get a customer by ID',
          action: 'Retrieve a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_customers',
          name: 'Get Customers',
          value: 'getMany',
          description: 'Get all customers',
          action: 'List all customers',
          fields: [],
          optionalFields: [
            {
              id: 'search',
              name: 'search',
              displayName: 'Search',
              type: 'string',
              required: false,
            },
            {
              id: 'role',
              name: 'role',
              displayName: 'Role',
              type: 'options',
              required: false,
              default: 'customer',
              options: [
                { name: 'All', value: 'all' },
                { name: 'Customer', value: 'customer' },
                { name: 'Subscriber', value: 'subscriber' },
              ],
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_customer',
          name: 'Update Customer',
          value: 'update',
          description: 'Update a customer',
          action: 'Update a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'email',
              name: 'email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'first_name',
              name: 'first_name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'last_name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'billing',
              name: 'billing',
              displayName: 'Billing Address (JSON)',
              type: 'json',
              required: false,
            },
            {
              id: 'shipping',
              name: 'shipping',
              displayName: 'Shipping Address (JSON)',
              type: 'json',
              required: false,
            },
          ],
        },
        {
          id: 'delete_customer',
          name: 'Delete Customer',
          value: 'delete',
          description: 'Delete a customer',
          action: 'Delete a customer',
          fields: [
            {
              id: 'customer_id',
              name: 'customerId',
              displayName: 'Customer ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'force',
              name: 'force',
              displayName: 'Force Delete',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // COUPON RESOURCE
    // ============================================
    {
      id: 'coupon',
      name: 'Coupon',
      value: 'coupon',
      description: 'Discount coupons',
      operations: [
        {
          id: 'create_coupon',
          name: 'Create Coupon',
          value: 'create',
          description: 'Create a coupon',
          action: 'Create a coupon',
          fields: [
            {
              id: 'code',
              name: 'code',
              displayName: 'Coupon Code',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'discount_type',
              name: 'discount_type',
              displayName: 'Discount Type',
              type: 'options',
              required: false,
              default: 'percent',
              options: [
                { name: 'Percentage', value: 'percent' },
                { name: 'Fixed Cart', value: 'fixed_cart' },
                { name: 'Fixed Product', value: 'fixed_product' },
              ],
            },
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'date_expires',
              name: 'date_expires',
              displayName: 'Expiry Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'individual_use',
              name: 'individual_use',
              displayName: 'Individual Use Only',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'usage_limit',
              name: 'usage_limit',
              displayName: 'Usage Limit',
              type: 'number',
              required: false,
            },
            {
              id: 'usage_limit_per_user',
              name: 'usage_limit_per_user',
              displayName: 'Limit Per User',
              type: 'number',
              required: false,
            },
            {
              id: 'free_shipping',
              name: 'free_shipping',
              displayName: 'Free Shipping',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'minimum_amount',
              name: 'minimum_amount',
              displayName: 'Minimum Spend',
              type: 'string',
              required: false,
            },
            {
              id: 'maximum_amount',
              name: 'maximum_amount',
              displayName: 'Maximum Spend',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_coupon',
          name: 'Get Coupon',
          value: 'get',
          description: 'Get a coupon by ID',
          action: 'Retrieve a coupon',
          fields: [
            {
              id: 'coupon_id',
              name: 'couponId',
              displayName: 'Coupon ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_coupons',
          name: 'Get Coupons',
          value: 'getMany',
          description: 'Get all coupons',
          action: 'List all coupons',
          fields: [],
          optionalFields: [
            {
              id: 'search',
              name: 'search',
              displayName: 'Search',
              type: 'string',
              required: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_coupon',
          name: 'Update Coupon',
          value: 'update',
          description: 'Update a coupon',
          action: 'Update a coupon',
          fields: [
            {
              id: 'coupon_id',
              name: 'couponId',
              displayName: 'Coupon ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'amount',
              name: 'amount',
              displayName: 'Amount',
              type: 'string',
              required: false,
            },
            {
              id: 'date_expires',
              name: 'date_expires',
              displayName: 'Expiry Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'usage_limit',
              name: 'usage_limit',
              displayName: 'Usage Limit',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'delete_coupon',
          name: 'Delete Coupon',
          value: 'delete',
          description: 'Delete a coupon',
          action: 'Delete a coupon',
          fields: [
            {
              id: 'coupon_id',
              name: 'couponId',
              displayName: 'Coupon ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'force',
              name: 'force',
              displayName: 'Force Delete',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
      ],
    },
    
    // ============================================
    // CATEGORY RESOURCE
    // ============================================
    {
      id: 'category',
      name: 'Product Category',
      value: 'category',
      description: 'Product categories',
      operations: [
        {
          id: 'create_category',
          name: 'Create Category',
          value: 'create',
          description: 'Create a category',
          action: 'Create a category',
          fields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'slug',
              name: 'slug',
              displayName: 'Slug',
              type: 'string',
              required: false,
            },
            {
              id: 'parent',
              name: 'parent',
              displayName: 'Parent Category ID',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
            {
              id: 'image',
              name: 'image',
              displayName: 'Image (JSON)',
              type: 'json',
              required: false,
              placeholder: '{"src": "https://example.com/image.jpg"}',
            },
          ],
        },
        {
          id: 'get_category',
          name: 'Get Category',
          value: 'get',
          description: 'Get a category by ID',
          action: 'Retrieve a category',
          fields: [
            {
              id: 'category_id',
              name: 'categoryId',
              displayName: 'Category ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_categories',
          name: 'Get Categories',
          value: 'getMany',
          description: 'Get all categories',
          action: 'List all categories',
          fields: [],
          optionalFields: [
            {
              id: 'parent',
              name: 'parent',
              displayName: 'Parent ID',
              type: 'string',
              required: false,
            },
            {
              id: 'hide_empty',
              name: 'hide_empty',
              displayName: 'Hide Empty',
              type: 'boolean',
              required: false,
              default: false,
            },
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 10,
            },
          ],
        },
        {
          id: 'update_category',
          name: 'Update Category',
          value: 'update',
          description: 'Update a category',
          action: 'Update a category',
          fields: [
            {
              id: 'category_id',
              name: 'categoryId',
              displayName: 'Category ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'name',
              name: 'name',
              displayName: 'Name',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'description',
              displayName: 'Description',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_category',
          name: 'Delete Category',
          value: 'delete',
          description: 'Delete a category',
          action: 'Delete a category',
          fields: [
            {
              id: 'category_id',
              name: 'categoryId',
              displayName: 'Category ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'force',
              name: 'force',
              displayName: 'Force Delete',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
      ],
    },
  ],
};
