/**
 * Zoho CRM n8n-style Schema
 * 
 * Comprehensive Zoho CRM API operations
 */

import { N8nAppSchema } from './types';

export const zohoSchema: N8nAppSchema = {
  id: 'zoho',
  name: 'Zoho CRM',
  description: 'Zoho CRM automation',
  version: '1.0.0',
  color: '#E42527',
  icon: 'zoho',
  group: ['crm'],
  
  credentials: [
    {
      name: 'zohoOAuth2',
      displayName: 'Zoho OAuth2',
      required: true,
      type: 'oauth2',
    },
  ],
  
  resources: [
    // ============================================
    // LEAD RESOURCE
    // ============================================
    {
      id: 'lead',
      name: 'Lead',
      value: 'lead',
      description: 'Sales leads',
      operations: [
        {
          id: 'create_lead',
          name: 'Create Lead',
          value: 'create',
          description: 'Create a new lead',
          action: 'Create a new lead',
          fields: [
            {
              id: 'last_name',
              name: 'Last_Name',
              displayName: 'Last Name',
              type: 'string',
              required: true,
            },
            {
              id: 'company',
              name: 'Company',
              displayName: 'Company',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'First_Name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'mobile',
              name: 'Mobile',
              displayName: 'Mobile',
              type: 'string',
              required: false,
            },
            {
              id: 'title',
              name: 'Designation',
              displayName: 'Title/Designation',
              type: 'string',
              required: false,
            },
            {
              id: 'website',
              name: 'Website',
              displayName: 'Website',
              type: 'string',
              required: false,
            },
            {
              id: 'lead_source',
              name: 'Lead_Source',
              displayName: 'Lead Source',
              type: 'options',
              required: false,
              options: [
                { name: 'Advertisement', value: 'Advertisement' },
                { name: 'Cold Call', value: 'Cold Call' },
                { name: 'Employee Referral', value: 'Employee Referral' },
                { name: 'External Referral', value: 'External Referral' },
                { name: 'Online Store', value: 'Online Store' },
                { name: 'Partner', value: 'Partner' },
                { name: 'Public Relations', value: 'Public Relations' },
                { name: 'Trade Show', value: 'Trade Show' },
                { name: 'Web Form', value: 'Web Form' },
                { name: 'Web Research', value: 'Web Research' },
                { name: 'Chat', value: 'Chat' },
              ],
            },
            {
              id: 'lead_status',
              name: 'Lead_Status',
              displayName: 'Lead Status',
              type: 'options',
              required: false,
              options: [
                { name: 'Attempted to Contact', value: 'Attempted to Contact' },
                { name: 'Contact in Future', value: 'Contact in Future' },
                { name: 'Contacted', value: 'Contacted' },
                { name: 'Junk Lead', value: 'Junk Lead' },
                { name: 'Lost Lead', value: 'Lost Lead' },
                { name: 'Not Contacted', value: 'Not Contacted' },
                { name: 'Pre-Qualified', value: 'Pre-Qualified' },
                { name: 'Not Qualified', value: 'Not Qualified' },
              ],
            },
            {
              id: 'industry',
              name: 'Industry',
              displayName: 'Industry',
              type: 'string',
              required: false,
            },
            {
              id: 'annual_revenue',
              name: 'Annual_Revenue',
              displayName: 'Annual Revenue',
              type: 'number',
              required: false,
            },
            {
              id: 'no_of_employees',
              name: 'No_of_Employees',
              displayName: 'Number of Employees',
              type: 'number',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'street',
              name: 'Street',
              displayName: 'Street',
              type: 'string',
              required: false,
            },
            {
              id: 'city',
              name: 'City',
              displayName: 'City',
              type: 'string',
              required: false,
            },
            {
              id: 'state',
              name: 'State',
              displayName: 'State',
              type: 'string',
              required: false,
            },
            {
              id: 'zip_code',
              name: 'Zip_Code',
              displayName: 'Zip Code',
              type: 'string',
              required: false,
            },
            {
              id: 'country',
              name: 'Country',
              displayName: 'Country',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_lead',
          name: 'Get Lead',
          value: 'get',
          description: 'Get a lead by ID',
          action: 'Retrieve a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_leads',
          name: 'Get Leads',
          value: 'getMany',
          description: 'Get all leads',
          action: 'List all leads',
          fields: [],
          optionalFields: [
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 200,
            },
          ],
        },
        {
          id: 'update_lead',
          name: 'Update Lead',
          value: 'update',
          description: 'Update a lead',
          action: 'Update a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'First_Name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'Last_Name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'lead_status',
              name: 'Lead_Status',
              displayName: 'Lead Status',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_lead',
          name: 'Delete Lead',
          value: 'delete',
          description: 'Delete a lead',
          action: 'Delete a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'convert_lead',
          name: 'Convert Lead',
          value: 'convert',
          description: 'Convert lead to contact/account/deal',
          action: 'Convert a lead',
          fields: [
            {
              id: 'lead_id',
              name: 'leadId',
              displayName: 'Lead ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'create_deal',
              name: 'Deals',
              displayName: 'Create Deal',
              type: 'boolean',
              required: false,
              default: true,
            },
            {
              id: 'deal_name',
              name: 'Deal_Name',
              displayName: 'Deal Name',
              type: 'string',
              required: false,
            },
            {
              id: 'overwrite',
              name: 'overwrite',
              displayName: 'Overwrite Existing',
              type: 'boolean',
              required: false,
              default: false,
            },
          ],
        },
        {
          id: 'search_leads',
          name: 'Search Leads',
          value: 'search',
          description: 'Search for leads',
          action: 'Search leads',
          fields: [
            {
              id: 'criteria',
              name: 'criteria',
              displayName: 'Search Criteria',
              type: 'string',
              required: true,
              placeholder: '(Email:equals:user@example.com)',
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // CONTACT RESOURCE
    // ============================================
    {
      id: 'contact',
      name: 'Contact',
      value: 'contact',
      description: 'Contacts',
      operations: [
        {
          id: 'create_contact',
          name: 'Create Contact',
          value: 'create',
          description: 'Create a new contact',
          action: 'Create a new contact',
          fields: [
            {
              id: 'last_name',
              name: 'Last_Name',
              displayName: 'Last Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'First_Name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'account_id',
              name: 'Account_Name',
              displayName: 'Account ID',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'mobile',
              name: 'Mobile',
              displayName: 'Mobile',
              type: 'string',
              required: false,
            },
            {
              id: 'title',
              name: 'Title',
              displayName: 'Title',
              type: 'string',
              required: false,
            },
            {
              id: 'department',
              name: 'Department',
              displayName: 'Department',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_street',
              name: 'Mailing_Street',
              displayName: 'Mailing Street',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_city',
              name: 'Mailing_City',
              displayName: 'Mailing City',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_state',
              name: 'Mailing_State',
              displayName: 'Mailing State',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_zip',
              name: 'Mailing_Zip',
              displayName: 'Mailing Zip',
              type: 'string',
              required: false,
            },
            {
              id: 'mailing_country',
              name: 'Mailing_Country',
              displayName: 'Mailing Country',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'get_contact',
          name: 'Get Contact',
          value: 'get',
          description: 'Get a contact by ID',
          action: 'Retrieve a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_contacts',
          name: 'Get Contacts',
          value: 'getMany',
          description: 'Get all contacts',
          action: 'List all contacts',
          fields: [],
          optionalFields: [
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 200,
            },
          ],
        },
        {
          id: 'update_contact',
          name: 'Update Contact',
          value: 'update',
          description: 'Update a contact',
          action: 'Update a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'first_name',
              name: 'First_Name',
              displayName: 'First Name',
              type: 'string',
              required: false,
            },
            {
              id: 'last_name',
              name: 'Last_Name',
              displayName: 'Last Name',
              type: 'string',
              required: false,
            },
            {
              id: 'email',
              name: 'Email',
              displayName: 'Email',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_contact',
          name: 'Delete Contact',
          value: 'delete',
          description: 'Delete a contact',
          action: 'Delete a contact',
          fields: [
            {
              id: 'contact_id',
              name: 'contactId',
              displayName: 'Contact ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // ACCOUNT RESOURCE
    // ============================================
    {
      id: 'account',
      name: 'Account',
      value: 'account',
      description: 'Company accounts',
      operations: [
        {
          id: 'create_account',
          name: 'Create Account',
          value: 'create',
          description: 'Create a new account',
          action: 'Create a new account',
          fields: [
            {
              id: 'account_name',
              name: 'Account_Name',
              displayName: 'Account Name',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'website',
              name: 'Website',
              displayName: 'Website',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
            {
              id: 'account_type',
              name: 'Account_Type',
              displayName: 'Account Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Analyst', value: 'Analyst' },
                { name: 'Competitor', value: 'Competitor' },
                { name: 'Customer', value: 'Customer' },
                { name: 'Integrator', value: 'Integrator' },
                { name: 'Investor', value: 'Investor' },
                { name: 'Partner', value: 'Partner' },
                { name: 'Press', value: 'Press' },
                { name: 'Prospect', value: 'Prospect' },
                { name: 'Reseller', value: 'Reseller' },
                { name: 'Vendor', value: 'Vendor' },
                { name: 'Other', value: 'Other' },
              ],
            },
            {
              id: 'industry',
              name: 'Industry',
              displayName: 'Industry',
              type: 'string',
              required: false,
            },
            {
              id: 'annual_revenue',
              name: 'Annual_Revenue',
              displayName: 'Annual Revenue',
              type: 'number',
              required: false,
            },
            {
              id: 'employees',
              name: 'Employees',
              displayName: 'Employees',
              type: 'number',
              required: false,
            },
            {
              id: 'billing_street',
              name: 'Billing_Street',
              displayName: 'Billing Street',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_city',
              name: 'Billing_City',
              displayName: 'Billing City',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_state',
              name: 'Billing_State',
              displayName: 'Billing State',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_code',
              name: 'Billing_Code',
              displayName: 'Billing Zip/Postal Code',
              type: 'string',
              required: false,
            },
            {
              id: 'billing_country',
              name: 'Billing_Country',
              displayName: 'Billing Country',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
          ],
        },
        {
          id: 'get_account',
          name: 'Get Account',
          value: 'get',
          description: 'Get an account by ID',
          action: 'Retrieve an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_accounts',
          name: 'Get Accounts',
          value: 'getMany',
          description: 'Get all accounts',
          action: 'List all accounts',
          fields: [],
          optionalFields: [
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 200,
            },
          ],
        },
        {
          id: 'update_account',
          name: 'Update Account',
          value: 'update',
          description: 'Update an account',
          action: 'Update an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'account_name',
              name: 'Account_Name',
              displayName: 'Account Name',
              type: 'string',
              required: false,
            },
            {
              id: 'phone',
              name: 'Phone',
              displayName: 'Phone',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_account',
          name: 'Delete Account',
          value: 'delete',
          description: 'Delete an account',
          action: 'Delete an account',
          fields: [
            {
              id: 'account_id',
              name: 'accountId',
              displayName: 'Account ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // DEAL RESOURCE
    // ============================================
    {
      id: 'deal',
      name: 'Deal',
      value: 'deal',
      description: 'Sales opportunities/deals',
      operations: [
        {
          id: 'create_deal',
          name: 'Create Deal',
          value: 'create',
          description: 'Create a new deal',
          action: 'Create a new deal',
          fields: [
            {
              id: 'deal_name',
              name: 'Deal_Name',
              displayName: 'Deal Name',
              type: 'string',
              required: true,
            },
            {
              id: 'stage',
              name: 'Stage',
              displayName: 'Stage',
              type: 'options',
              required: true,
              options: [
                { name: 'Qualification', value: 'Qualification' },
                { name: 'Needs Analysis', value: 'Needs Analysis' },
                { name: 'Value Proposition', value: 'Value Proposition' },
                { name: 'Identify Decision Makers', value: 'Identify Decision Makers' },
                { name: 'Proposal/Price Quote', value: 'Proposal/Price Quote' },
                { name: 'Negotiation/Review', value: 'Negotiation/Review' },
                { name: 'Closed Won', value: 'Closed Won' },
                { name: 'Closed Lost', value: 'Closed Lost' },
              ],
            },
          ],
          optionalFields: [
            {
              id: 'account_id',
              name: 'Account_Name',
              displayName: 'Account ID',
              type: 'string',
              required: false,
            },
            {
              id: 'contact_id',
              name: 'Contact_Name',
              displayName: 'Contact ID',
              type: 'string',
              required: false,
            },
            {
              id: 'amount',
              name: 'Amount',
              displayName: 'Amount',
              type: 'number',
              required: false,
            },
            {
              id: 'closing_date',
              name: 'Closing_Date',
              displayName: 'Closing Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'probability',
              name: 'Probability',
              displayName: 'Probability (%)',
              type: 'number',
              required: false,
            },
            {
              id: 'type',
              name: 'Type',
              displayName: 'Type',
              type: 'options',
              required: false,
              options: [
                { name: 'Existing Business', value: 'Existing Business' },
                { name: 'New Business', value: 'New Business' },
              ],
            },
            {
              id: 'lead_source',
              name: 'Lead_Source',
              displayName: 'Lead Source',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
          ],
        },
        {
          id: 'get_deal',
          name: 'Get Deal',
          value: 'get',
          description: 'Get a deal by ID',
          action: 'Retrieve a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_deals',
          name: 'Get Deals',
          value: 'getMany',
          description: 'Get all deals',
          action: 'List all deals',
          fields: [],
          optionalFields: [
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 200,
            },
          ],
        },
        {
          id: 'update_deal',
          name: 'Update Deal',
          value: 'update',
          description: 'Update a deal',
          action: 'Update a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'deal_name',
              name: 'Deal_Name',
              displayName: 'Deal Name',
              type: 'string',
              required: false,
            },
            {
              id: 'stage',
              name: 'Stage',
              displayName: 'Stage',
              type: 'string',
              required: false,
            },
            {
              id: 'amount',
              name: 'Amount',
              displayName: 'Amount',
              type: 'number',
              required: false,
            },
          ],
        },
        {
          id: 'delete_deal',
          name: 'Delete Deal',
          value: 'delete',
          description: 'Delete a deal',
          action: 'Delete a deal',
          fields: [
            {
              id: 'deal_id',
              name: 'dealId',
              displayName: 'Deal ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // TASK RESOURCE
    // ============================================
    {
      id: 'task',
      name: 'Task',
      value: 'task',
      description: 'Tasks and activities',
      operations: [
        {
          id: 'create_task',
          name: 'Create Task',
          value: 'create',
          description: 'Create a new task',
          action: 'Create a new task',
          fields: [
            {
              id: 'subject',
              name: 'Subject',
              displayName: 'Subject',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'due_date',
              name: 'Due_Date',
              displayName: 'Due Date',
              type: 'dateTime',
              required: false,
            },
            {
              id: 'status',
              name: 'Status',
              displayName: 'Status',
              type: 'options',
              required: false,
              default: 'Not Started',
              options: [
                { name: 'Not Started', value: 'Not Started' },
                { name: 'Deferred', value: 'Deferred' },
                { name: 'In Progress', value: 'In Progress' },
                { name: 'Completed', value: 'Completed' },
                { name: 'Waiting for input', value: 'Waiting for input' },
              ],
            },
            {
              id: 'priority',
              name: 'Priority',
              displayName: 'Priority',
              type: 'options',
              required: false,
              default: 'Normal',
              options: [
                { name: 'High', value: 'High' },
                { name: 'Highest', value: 'Highest' },
                { name: 'Low', value: 'Low' },
                { name: 'Lowest', value: 'Lowest' },
                { name: 'Normal', value: 'Normal' },
              ],
            },
            {
              id: 'what_id',
              name: 'What_Id',
              displayName: 'Related To (ID)',
              type: 'string',
              required: false,
            },
            {
              id: 'who_id',
              name: 'Who_Id',
              displayName: 'Contact/Lead ID',
              type: 'string',
              required: false,
            },
            {
              id: 'description',
              name: 'Description',
              displayName: 'Description',
              type: 'string',
              required: false,
              typeOptions: {
                rows: 3,
              },
            },
            {
              id: 'remind_at',
              name: 'Remind_At',
              displayName: 'Reminder',
              type: 'dateTime',
              required: false,
            },
          ],
        },
        {
          id: 'get_tasks',
          name: 'Get Tasks',
          value: 'getMany',
          description: 'Get all tasks',
          action: 'List all tasks',
          fields: [],
          optionalFields: [
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 200,
            },
          ],
        },
        {
          id: 'update_task',
          name: 'Update Task',
          value: 'update',
          description: 'Update a task',
          action: 'Update a task',
          fields: [
            {
              id: 'task_id',
              name: 'taskId',
              displayName: 'Task ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [
            {
              id: 'subject',
              name: 'Subject',
              displayName: 'Subject',
              type: 'string',
              required: false,
            },
            {
              id: 'status',
              name: 'Status',
              displayName: 'Status',
              type: 'string',
              required: false,
            },
          ],
        },
        {
          id: 'delete_task',
          name: 'Delete Task',
          value: 'delete',
          description: 'Delete a task',
          action: 'Delete a task',
          fields: [
            {
              id: 'task_id',
              name: 'taskId',
              displayName: 'Task ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
    
    // ============================================
    // NOTE RESOURCE
    // ============================================
    {
      id: 'note',
      name: 'Note',
      value: 'note',
      description: 'Notes attached to records',
      operations: [
        {
          id: 'create_note',
          name: 'Create Note',
          value: 'create',
          description: 'Create a new note',
          action: 'Create a new note',
          fields: [
            {
              id: 'note_title',
              name: 'Note_Title',
              displayName: 'Note Title',
              type: 'string',
              required: true,
            },
            {
              id: 'note_content',
              name: 'Note_Content',
              displayName: 'Note Content',
              type: 'string',
              required: true,
              typeOptions: {
                rows: 5,
              },
            },
            {
              id: 'parent_id',
              name: 'Parent_Id',
              displayName: 'Parent Record ID',
              type: 'string',
              required: true,
            },
            {
              id: 'se_module',
              name: 'se_module',
              displayName: 'Parent Module',
              type: 'options',
              required: true,
              options: [
                { name: 'Leads', value: 'Leads' },
                { name: 'Contacts', value: 'Contacts' },
                { name: 'Accounts', value: 'Accounts' },
                { name: 'Deals', value: 'Deals' },
              ],
            },
          ],
          optionalFields: [],
        },
        {
          id: 'get_notes',
          name: 'Get Notes',
          value: 'getMany',
          description: 'Get all notes',
          action: 'List all notes',
          fields: [],
          optionalFields: [
            {
              id: 'per_page',
              name: 'per_page',
              displayName: 'Per Page',
              type: 'number',
              required: false,
              default: 200,
            },
          ],
        },
        {
          id: 'delete_note',
          name: 'Delete Note',
          value: 'delete',
          description: 'Delete a note',
          action: 'Delete a note',
          fields: [
            {
              id: 'note_id',
              name: 'noteId',
              displayName: 'Note ID',
              type: 'string',
              required: true,
            },
          ],
          optionalFields: [],
        },
      ],
    },
  ],
};
